dotnet/linker

- .gitmodules
- linker/Mono.Linker.csproj
Fix Mono.Linker.csproj to point to the new location of cecil.
Change a call to XmlWriter.Dispose() (it's declared private on desktop .NET).
> Add cecil as a submodule.

- linker/Mono.Linker.Steps/MarkStep.cs
- linker/Mono.Linker.Steps/ResolveFromXmlStep.cs
- linker/Mono.Linker.Steps/SweepStep.cs
- linker/Mono.Linker.csproj
The changes in MarkStep.cs and SweepStep.cs are mostly from https://github.com/xamarin/xamarin-macios/blob/master/tools/linker/MobileMarkStep.cs#L33 and https://github.com/xamarin/xamarin-macios/blob/master/tools/linker/MobileSweepStep.cs#L45 . One additional line
Annotations.Mark (assembly.MainModule);
was added to MarkStep.Process().
The changes in ResolveFromXmlStep.cs are new and allow type forwarders to be specified in xml descriptors.
The change in Mono.Linker.csproj allows opt-out from embedding the default xml descriptors.
> Fixes for type forwarders.

- linker/Mono.Linker.Steps/MarkStep.cs
The linker should mark exported nested types if they resolve to
marked types. IsForwarder property is only set on the outermost
enclosing type so nested types weren't marked.
> Fix marking of exported nested types.

- netci.groovy
The \ wasn't escaped, causing strange behavior with jobs not showing up.
This also fixes build failures due to the submodule for Mono.Cecil not being initialized.
> Fix generated jobs by removing \b from job steps, and update submodules in netci.groovy

- linker/Mono.Linker.Steps/MarkStep.cs
The existing code for marking custom attributes was only marking the type
and the lowest element type, i.e. marking (1) would also mark (3) but
would miss (2).
1. [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>[][]))]
2. [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>[]))]
3. [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
That's generally not an issue since the type is marked (elsewhere).
However, in the case of custom attributes, we need to update the Scope
to what was resolved (and that was missed).
That lack of updated Scope means that a PCL assembly would still keep
references to System.Runtime, which is …
> Fix marking types inside custom attributes. Fixes #47064

- linker/Mono.Linker.Steps/OutputStep.cs
The file name of an output assembly of the linker should match the file name of the corresponding input assembly.
Before this fix, OutputStep.GetAssemblyFileName inferred the name of the output file from assembly name and the main module kind.
The name of the input assembly doesn't have to be the same as the name of the corresponding file;
moreover, a Windows or Console main module can live in a dll file instead of an exe file.
> Fix the names of output assembly files

- linker/Mono.Linker.Steps/SweepStep.cs
Older Cecil (0.9) were saving the scope of the actual type. This changed
with Cecil 0.10 where the ExportedType.Scope is saved, which could lead
to invalid assemblies being saved with the current linker code (which
could not update the scope without the cecil bump)
reference:
https://bugzilla.xamarin.com/show_bug.cgi?id=51805
> Bump cecil and use the new setter for ExportedType.Scope. Fixes #51805

- linker/Mono.Linker.Steps/SweepStep.cs
Debug information sweep was missing completely causing problems with pdbs which can
contain type references in scopes referenced by method debug information.
Good example is C# type alias
```csharp
using X = System.DateTime;
```
Without the sweep the debug symbols cannot be written back if `System.DateTime` is linked out.
cc @jbevain
> Debug Information sweep

- linker/Mono.Linker.Steps/MarkStep.cs
- linker/Mono.Linker.Steps/ResolveFromAssemblyStep.cs
- linker/Mono.Linker.Steps/SweepStep.cs
- linker/Mono.Linker/Driver.cs
- linker/Mono.Linker/LinkContext.cs
The linker had an optimization that removed assemblies that had only type forwarders referenced.
https://github.com/mono/linker/pull/2 broke that optimization by adding a line that
marked assembly.MainModule whenever a type forwarder was marked.
This change introduces a new switch -t that controls this optimization. The optimization is on
by default; if -t is specified, the optimization is disabled and assemblies with referenced type
forwarders are kept.
Additionally, this includes a change that marks all type forwarders in assemblies specified with -a.
> Option to keep assemblies that have only type forwarders referenced.

- linker/Mono.Linker.Steps/LoadReferencesStep.cs
- linker/Mono.Linker.Steps/MarkStep.cs
- linker/Mono.Linker.Steps/ResolveFromAssemblyStep.cs
- linker/Mono.Linker.Steps/ResolveFromXmlStep.cs
- linker/Mono.Linker.Steps/SweepStep.cs
This change modifies the linker to ignore unresolved type forwarders and assembly references.
This is needed to support .NET Core 2.0 scenarios where mscorlib.dll (and possibly other assemblies) will
contain type forwarders that point to assemblies that may not always be resolved.
> Ignore unresolved type forwarders and assembly references.

- linker/Mono.Linker/AssemblyResolver.cs
AssemblyDefinition caching should use string-insensitive string comparisons
so that only a single AssemblyDefinition is created when assembly name is specified
with a different case (e.g., in -a, in -x file, reference in metadata, etc.).
> Fix AssemblyDefinition caching in AssemblyResolver.

- linker/Mono.Linker.csproj
- linker/Mono.Linker/Driver.cs
- linker/NetCore.props
The .NET core linker is being renamed to "illink". The usage info is changed correspondingly:
```
IL Linker
Error: No parameters specified
illink [options] -x|-a|-i file
--about     About the IL Linker
--version   Print the version number of the IL Linker
-out        Specify the output directory, default to `output'
-c          Action on the core assemblies, skip, copy or link, default to skip
-p          Action per assembly
-s          Add a new step to the pipeline.
-t          Keep assemblies in which only type forwarders are referenced.
-d          Add a directory where the linker will look for assemblies
-b          Generate debug symbols for each linked module (true or false)
-g          Generate a new unique guid for each linked module (true or false)
-l          List of i18n …
```
> Rename .NET core build of linker to illink

- linker/Mono.Linker.Steps/ResolveFromAssemblyStep.cs
We compile the linker with warnings as errors which led us to this unused variable
> Remove unused variable to fix warn as error

- linker/Mono.Linker/DirectoryAssemblyResolver.cs
DirectoryAssemblyResolver shouldn't add the directory containing the core assembly
for the linker itself to the list of search directories. That core assembly is not necessarily
used by the app being linked so a wrong assembly may be found.
> Fix DirectoryAssemblyResolver.

- linker/Mono.Linker.Steps/MarkStep.cs
My PR  https://github.com/mono/linker/pull/27 yesterday
had a bug that resulted in default constructors of by-ref interop method
parameter types not getting marked. This change fixes the bug.
> Fix ProcessInteropMethod.

- linker/Mono.Linker.Steps/SweepStep.cs
- linker/Mono.Linker/Annotations.cs
- linker/Mono.Linker/LinkContext.cs
Sweep all of the assemblies that were linked, not all of the assemblies that were resolved.  There may be some assemblies that are resolved, but are not linked.  We ran into this problem with the WinRT support in the UnityLinker.
> Sweep assemblies fix

- linker/Mono.Linker.Steps/ResolveStep.cs
We've made a number of changes to ResolveFromXmlStep.  It will take some
time to upstream them,
until then we are going to maintain our copy and in order to do that we
need to be able to derive from ResolveStep in our linker project.
> Make ResolveStep  ctr protected so that we can derive

- linker/Mono.Linker/LinkContext.cs
Unity linker has it's own reader parameters that we want to pass in & need access to later on during some of our steps.
> Allow pass in of reader params

- linker/Mono.Linker.Steps/MarkStep.cs
In the UnityLinker, we don't error on unresolved types/method.  Instead we have a custom step that stubs in these missing types/methods.  Introducing ContinueWith gives us the extension point that we need to customize the behavior of the MarkStep.
There's no behavior change here.
> Mark step continue with

- linker/Mono.Linker.Steps/LoadI18nAssemblies.cs
- linker/Mono.Linker.Steps/ResolveFromAssemblyStep.cs
- linker/Mono.Linker/Driver.cs
This change adds an option -r that is similar to -a except only types, methods, and
fields visible from outside of an assembly are initially marked. This is useful for running the linker to
remove dead privates.
> Add an option to use only entry points visible outside of an assembly as roots.

- linker/Mono.Linker.Steps/ResolveFromAssemblyStep.cs
Pulbic nested types have IsNestedPublic set to true but IsPublic set to false.
This change fixes ResolveFromAssemblyStep.MarkType to take that into account.
Also, NestedPrivate types shouldn't be marked when root visibility is set to
PublicAndFamilyAndAssembly.
> Fix ResolveFromAssemblyStep.MarkType processing of nested types.

- corebuild/restore.cmd
- corebuild/restore.sh
- linker/Mono.Linker.csproj
Build Mono.Cecil.Pdb.dll in netcore illink builds to be able to handle native pdbs.
> Build Mono.Cecil.Pdb.dll in netcore illink builds.

- linker/Mono.Linker.Steps/MarkStep.cs
- linker/Mono.Linker/Driver.cs
- linker/Mono.Linker/LinkContext.cs
1. Keep all fields and methods in types with DebuggerDisplayAttribute.
2. Keep all fields and methods in proxy types from DebuggerTypeProxyAttribute.
> Mark methods and fields needed for types with debugger attributes.

- linker/Mono.Linker/AssemblyResolver.cs
Currently, if we have a file containing a module with a different name, the linker crashes in the mark step.
If A.exe contains a module B, when A.exe is processed by the linker, the assembly is entered AssemblyCache as _assemblies["A"]. However, when the linker is marking the methods, it looks for methods in assembly scope `B`. It cannot find it in the assembly-cache or a file named B.exe/B.dll and therefore fails.
This change fixes the problem by inserting assemblies to the cache by assembly-name, and not file name.
Fixes #61
> AssemblyCache: Index by Assemblyname, instead of file name

- linker/Mono.Linker.Steps/MarkStep.cs
Make several methods protected and add an extensibility point for MarkStep to allow derived classes to customize the behavior.
> Extensibility changes for MarkStep

- linker/Mono.Linker/AssemblyResolver.cs
- linker/Mono.Linker/Driver.cs
- linker/Mono.Linker/LinkContext.cs
Not disposing of the assembly definitions leads to file access
exceptions.
This is not causing any issues today since there is nothing that runs
the linker multiple times within the same process.
However, the new test framework does, and the lack of assembly def
disposal leads to file access exceptions during all tests after the
first.
> Dispose of loaded assembly definitions

- linker/Mono.Linker/LinkContext.cs
We have our own AnnotationsStore that we want to pass in to the LinkContext, this change exposes the ability to create our own instance and pass it in when we construct the LinkContext
> Support a custom annotation store

- linker/Mono.Linker/AssemblyResolver.cs
- linker/Mono.Linker/LinkContext.cs
We need to use our own resolver.  This PR introduces an interface for the resolver that the linker uses.  It adds a few extra things to cecil's IAssemblyResolver
There's also a change here to change the return value of CacheAssembly from void to AssemblyDefinition.  I have another PR I will post after this one lands that will make use of the return value.  There is a minor issue today where CacheAssembly is called and then the caller returns the newly loaded assembly rather than the assembly that was already in the cache.
> Linker resolver interface

- linker/Mono.Linker.Steps/TypeMapStep.cs
Fix a case where a class interface member is not removed when it is not used.
Our unit test for this case has already been ported to the new test framework.  You can find it here
https://github.com/Unity-Technologies/linker/blob/unity-master-new-test-framework-upstream-compat/linker/Tests2/Mono.Linker.Tests.Cases/Basic/InterfaceMethodImplementedOnBaseClassDoesNotGetStripped.cs
Here is the output from our failed test.
Expected Base::Unused() to not exist, but it did
*******************
Available method were: 
*******************
System.Void I1::Used()
System.Void Base::Unused()
System.Void Base::Used()
System.Void Base::.ctor()
System.Void Derived::.ctor()
System.Void Entry::Main()
*******************
> Fix unused interface method not being removed

- linker/Mono.Linker.Steps/SweepStep.cs
Our sweep step does some information gathering and outputs a report at the end.  We need to add some callbacks so that our sweep step can track all removals.
> Changes to allow tracking of all removals during sweep step

- linker/Tests/Mono.Linker.Tests.Core/DefaultChecker.cs
- linker/Tests/Mono.Linker.Tests.Core/Mono.Linker.Tests.Core.csproj
Fix assembly resolution exception that would happen during every test
The reason this issue started when the tests were moved upstream was due to a behavior change in the newer nunit.  nunit/nunit#1072
This PR implements more explicit resolution for the input & output which is more correct anyways
> Fix assembly resolution exception that would happen during every test

- linker/Tests/Mono.Linker.Tests.Core/Customizable/ObjectFactory.cs
- linker/Tests/Mono.Linker.Tests.Core/TestCaseCollector.cs
- linker/Tests/Mono.Linker.Tests.Core/TestRunner.cs
- linker/Tests/TestsCases/TestSuites.cs
I'm converting some of our tests to the new scheme that have non-linking related Assertion requirements.
For example, the tests that verify our Sweep Report I made a reference to last week need to Assert a SweepReport.log file is written and do a little light weight processing of the file to verify that it is correct
For tests like this, I want to leverage the TestCaseCollector & TestRunner, but the [Test] itself is going to end up doing all of the Assert's rather than relying on ResultChecker
This PR moves some things around to make writing [Test]'s like this easier.
* Shuffle around collector public API's to make it more reusable
* Pull result checking out of TestRunner.
> Test framework check and collect tweaking

- linker/Tests/Mono.Linker.Tests.Cases/Generics/CorrectOverloadedMethodGetsStrippedInGenericClass.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/Mono.Linker.Tests.Cases/VirtualMethods/ClassImplemtingInterfaceMethodsThroughBaseClass2.cs
- linker/Tests/Mono.Linker.Tests.Cases/VirtualMethods/ClassImplemtingInterfaceMethodsThroughBaseClass3.cs
- linker/Tests/Mono.Linker.Tests.Cases/VirtualMethods/ClassImplemtingInterfaceMethodsThroughBaseClass4.cs
- linker/Tests/Mono.Linker.Tests.Cases/VirtualMethods/ClassImplemtingInterfaceMethodsThroughBaseClass5.cs
- linker/Tests/Mono.Linker.Tests.Cases/VirtualMethods/ClassImplemtingInterfaceMethodsThroughBaseClass6.cs
- linker/Tests/Mono.Linker.Tests.Cases/VirtualMethods/VirtualMethodGetsPerservedIfBaseMethodGetsInvoked.cs
- linker/Tests/Mono.Linker.Tests.Cases/VirtualMethods/VirtualMethodGetsStrippedIfImplementingMethodGetsInvokedDirectly.cs
Bring over more of the Unity virtual method unit tests.
Note : CorrectOverloadedMethodGetsStrippedInGenericClass is currently failing.  It is fixed by https://github.com/mono/linker/pull/29
> Bring over more test cases

- linker/Mono.Linker.Steps/MarkStep.cs
I updated our fork with the latest upstream changes and one of our Window Runtime related tests started failing.  The behavior change that lead to the failure was the introduction of processing methods with IsInternalCall in https://github.com/mono/linker/pull/27
For ComImport types, we don't need to preserve the default constructor and fields.  I don't fully understand this one, so I'm going to let others who know more about it provide additional commentary :smile:
If this PR ends up landing, I will add new unit tests
> Don't preserve default constructor and fields when IsImport is true

- linker/Mono.Linker.Steps/TypeMapStep.cs
Could result in a base class method with the same name as a derived method, but a different number of generic parameters , not being stripped when it should have been.
I brought the test we wrote for this fix over to the new test framework branch.  The link to the change set is https://github.com/Unity-Technologies/linker/commit/1f3e74972be7aed20b65ffa4ffe0214d0d0d0fa3.
> FIX - GenericParam count on method not taken into consideration

- linker/Mono.Linker.Steps/TypeMapStep.cs
- linker/Mono.Linker.csproj
- linker/Mono.Linker/MethodReferenceExtensions.cs
- linker/Mono.Linker/TypeReferenceExtensions.cs
This PR fixes a bug that leads to mishandling of overloads with parameters that have types with generic parameters and use a different generic param name than the base method.
* Undo the upstream change made at https://github.com/mono/linker/commit/6f0742cdc4cdbd7627b765992e2e5baeb5edbe58 this fix was not a complete fix
* Unity hit this bug a couple years ago and we've had a fix in our linker since.  Bring over this fix which does a more exhaustive comparison of generic parameters
I have ported the unit tests that we wrote for this case into the new linker test framework (still a work in progress).  See the following change set if you would like to see examples of the cases this PR fixes.
https://github.com/Unity-Technologies/linker/commit/f7b455831f3a82b1426a5e13bcebbcc5abdc3971
> Fix complex generic param bug

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/BaseExpectedLinkedBehaviorAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptInterfaceAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/BaseMetadataAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/CoreLinkAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/NotATestCaseAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/ReferenceAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SandboxDependencyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/TestCasesRunner/LinkedTestCaseResult.cs
- linker/Tests/TestCasesRunner/ManagedCompilationResult.cs
- linker/Tests/TestCasesRunner/ResultChecker.cs
- linker/Tests/TestCasesRunner/TestCaseCompiler.cs
- linker/Tests/TestCasesRunner/TestCaseSandbox.cs
- linker/Tests/TestCasesRunner/TestRunner.cs
Compile the input test assembly with all expectation attributes removed so that they could not cause any unintended consequences during linking.
In order to make the assertions we now compile the test case assembly twice.  Once in a new "expectations"
directory with all attributes compiled in.  And then a second time in the "input" directory without the expecation attributes compiled in
The "expectations" assembly is used by the ResultChecker to determine what the expected results are
And the "input" assembly is the one passed to the linker for processing
> Test framework - No test framework attributes in linker input assembly

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptBaseTypeAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptInterfaceAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/AttributeOnPreservedTypeIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/AttributeOnPreservedTypeWithTypeUsedInConstructorIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/AttributeOnPreservedTypeWithTypeUsedInDifferentNamespaceIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/AttributeOnPreservedTypeWithTypeUsedInFieldIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/AttributeOnPreservedTypeWithTypeUsedInPropertySetterIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/AttributeOnPreservedTypeWithUsedSetter.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/AttributeOnUsedFieldIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/AttributeOnUsedMethodIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/AttributeOnUsedPropertyIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Basic/InterfaceMethodImplementedOnBaseClassDoesNotGetStripped.cs
- linker/Tests/Mono.Linker.Tests.Cases/Basic/NestedDelegateInvokeMethodsPreserved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Basic/UninvokedInterfaceMemberGetsRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Generics/CorrectOverloadedMethodGetsStrippedInGenericClass.cs
- linker/Tests/Mono.Linker.Tests.Cases/Generics/DerivedClassWithMethodOfSameNameAsBaseButDifferentNumberOfGenericParametersUnusedBaseWillGetStripped.cs
- linker/Tests/Mono.Linker.Tests.Cases/Generics/GenericInstanceInterfaceMethodImplementedWithDifferentGenericArgumentNameDoesNotGetStripped.cs
- linker/Tests/Mono.Linker.Tests.Cases/Generics/MethodWithParameterWhichHasGenericParametersAndOverrideUsesADifferentNameForGenericParameter.cs
- linker/Tests/Mono.Linker.Tests.Cases/Generics/MethodWithParameterWhichHasGenericParametersAndOverrideUsesADifferentNameForGenericParameterNestedCase.cs
- linker/Tests/Mono.Linker.Tests.Cases/Generics/MethodWithParameterWhichHasGenericParametersAndOverrideUsesADifferentNameForGenericParameterNestedCase2.cs
- linker/Tests/Mono.Linker.Tests.Cases/Generics/OverrideWithAnotherVirtualMethodOfSameNameWithDifferentParameterType.cs
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/TypeWithPreserveFieldsHasBackingFieldsOfPropertiesRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/VirtualMethods/ClassImplemtingInterfaceMethodsThroughBaseClass4.cs
- linker/Tests/Mono.Linker.Tests.Cases/VirtualMethods/ClassImplemtingInterfaceMethodsThroughBaseClass5.cs
- linker/Tests/Mono.Linker.Tests.Cases/VirtualMethods/ClassImplemtingInterfaceMethodsThroughBaseClass6.cs
- linker/Tests/Mono.Linker.Tests.Cases/VirtualMethods/TypeGetsMarkedThatImplementsAlreadyMarkedInterfaceMethod.cs
- linker/Tests/Mono.Linker.Tests.Cases/VirtualMethods/UsedVirtualMethodNotRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/VirtualMethods/VirtualMethodGetsPerservedIfBaseMethodGetsInvoked.cs
- linker/Tests/Mono.Linker.Tests.Cases/VirtualMethods/VirtualMethodGetsStrippedIfImplementingMethodGetsInvokedDirectly.cs
- linker/Tests/TestCasesRunner/AssemblyChecker.cs
This makes writing tests easier since it removes the need to craft & maintain the string type names.
While the tests all pass for this PR, this PR does assume that https://github.com/mono/linker/pull/96 will be landed and that PR should be landed first.
> Eliminate need for full type names as strings in KeptBase and KeptInterface attributes

- linker/Tests/Mono.Linker.Tests.Cases/Generics/MethodWithParameterWhichHasGenericParametersAndOverrideUsesADifferentNameForGenericParameter.cs
- linker/Tests/Mono.Linker.Tests.Cases/Generics/MethodWithParameterWhichHasGenericParametersAndOverrideUsesADifferentNameForGenericParameterNestedCase.cs
- linker/Tests/Mono.Linker.Tests.Cases/Generics/MethodWithParameterWhichHasGenericParametersAndOverrideUsesADifferentNameForGenericParameterNestedCase2.cs
in newer framework versions
System.Func used to live in System.Core, now it's in mscorlib.  As a result, when we run our unit tests against our old mono they fail because the tests only reference mscorlib right now.
We could add a reference to System.Core.dll, but there's really no reason why we need to use System.Func, so let's use IDictionary isntead
> Change some test cases to use types that have not been moved around

- linker/Mono.Linker.Steps/OutputStep.cs
Whenever the linker writes an assembly, we now check the attributes of
each module in the assembly to determine whether it has been
ready-to-run crossgen'd. We detect this by checking the module
attributes: R2R images have the flag COMIMAGE_FLAGS_IL_LIBRARY
(0x00000004) set in the CLI header.
To write back valid IL images, we unset the IL_LIBRARY flag, and set
the IL_ONLY flag. We also adjust the target architecture in the COFF
header, which for R2R images contains an xor of OS values with the
normal architecture values. From coreclr:
```
#define IMAGE_FILE_MACHINE_NATIVE_NI (IMAGE_FILE_MACHINE_NATIVE ^
IMAGE_FILE_MACHINE_NATIVE_OS_OVERRIDE)
```
We determine the target architecture from this value and write it back
without the os override used in R2R images.
@swaroop-sridhar please review
> Add support for writing pure IL for R2R assemblies

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptMemberInAssemblyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptTypeInAssemblyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/RemovedMemberInAssemblyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/RemovedTypeInAssemblyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/Mono.Linker.Tests.Cases/CoreLink/CopyOfCoreLibrariesKeepsUnusedTypes.cs
- linker/Tests/Mono.Linker.Tests.Cases/CoreLink/LinkingOfCoreLibrariesRemovesUnusedMethods.cs
- linker/Tests/Mono.Linker.Tests.Cases/CoreLink/LinkingOfCoreLibrariesRemovesUnusedTypes.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/TestCasesRunner/ResultChecker.cs
Implemented expectation attributes for verifying the outcome of types & methods in other assemblies.
Used these new attributes to implement the core link tests which verify that core assemblies are linked when linking of core libraries is requested
Also implemented a test to verify the behavior when the 'copy' mode is used for core libraries.
I didn't write many tests for a variety of reasons, but one is that tests like this will be a bit fragile.  A few tests will give us some level of coverage on the linker behavior.  And they will also verify that the *InAssemblyAttributes remain working.
Unity's plans for the *InAssemblyAttributes is to use them for some more integration type tests that verify a few special preservations we make.
> Implement core link tests

- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
This fixes an incremental build issue, in which sometimes the deps
file would be generated after the linker targets were run, causing the
deps file to be seen as up-to-date even after linking. Now instead of
marking the deps file as an output, the target uses a semaphore whose
timestamp will be out of date with respect to the deps file whenever
the deps file gets regenerated by the publish pipeline.
@swaroop-sridhar please review
/cc @ericstj
> Use semaphore for deps file linking

- corebuild/integration/test/MusicStoreTest.cs
Now that the linker can operate on R2R assemblies, we no longer need
to set the runtime framework version in MusicStore to use an older
non-crossgen'd framework.
@swaroop-sridhar PTAL
> Remove R2R workaround in MusicStore test

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptMemberInAssemblyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptTypeInAssemblyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/RemovedMemberInAssemblyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/RemovedTypeInAssemblyAttribute.cs
- linker/Tests/TestCasesRunner/ResultChecker.cs
Add support for string type name in *InAssemblyAttributes so that non-public types can be checked
> Improve assembly resolution in ResultChecker

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/ReferenceAttribute.cs
- linker/Tests/TestCasesRunner/ResultChecker.cs
* Fix an issue where [KeptTypeInAssembly("System.Core", ....)] would lead to System.dll being loaded because of a bug in the Resolve logic.  This was happening on line 91.
* Standardize on one way to call Resolve in result checker.
* Allow multiple [Reference] attributes
> More resolution clean up in ResultChecker

- linker/Mono.Linker.Steps/MarkStep.cs
- linker/Mono.Linker/Driver.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/Il8nAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/IncludeBlacklistStepAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/Mono.Linker.Tests.Cases/References/ReferencesAreRemovedWhenAllUsagesAreRemoved.cs
- linker/Tests/TestCasesRunner/LinkerArgumentBuilder.cs
- linker/Tests/TestCasesRunner/ResultChecker.cs
- linker/Tests/TestCasesRunner/TestCaseLinkerOptions.cs
- linker/Tests/TestCasesRunner/TestCaseMetadaProvider.cs
- linker/Tests/TestCasesRunner/TestRunner.cs
ReferencesAreRemovedWhenAllUsagesAreRemoved was passing when it should have been failing due to a bug in ResultChecker treating [RemovedAssembly] the same as [KeptAssembly].  Once the ResultChecker was fixed, it took a couple more changes before the test would pass.
Add a command line option to disable the blacklist step
For the test cases, disable options that tend to pollute the linked output with a bunch of preservations that are not needed for our test cases
Make assembly and module attribute marking slightly less conservative. Currently we mark them all.  With this change we will not mark assembly and module attributes when their defining module has not been marked after processing all types.
This fixes the test ReferencesAreRemovedWhenAllUsagesAreRemoved when ran against the .NET …
> Fix ReferencesAreRemovedWhenAllUsagesAreRemoved, was incorrectly passing

- linker/Mono.Linker.Steps/MarkStep.cs
Follow the same UnresolvedType handling scheme used else where in the MarkStep
> Unresolved type handling for top level attributes

- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
- set an illink flag to emit linked pdbs
- rewrite the itemgroup _DebugSymbolsIntermediatePath to include
linked pdbs in the publish output
@swaroop-sridhar PTAL
> Produce linked symbols during publish

- linker/Tests/TestCasesRunner/TestCaseMetadaProvider.cs
- linker/Tests/TestCasesRunner/TestCaseSandbox.cs
- linker/Tests/TestCasesRunner/TestRunner.cs
No more assuming all .dlls that were copied into the sandbox directory are meant to be passed as references when compiling the test cases.
While moving our WinRT tests over to the new test structure I ran into cases where we have native dlls in the sandbox.  Assuming all .dlls in the sandbox directory should be passed as references was causing problems.  Since we only depended on this implicit way of figuring out references for the Expectations dll, I thought it would be easiest to handle that case specially and then require that the [Reference] mechanism be used to define each additional reference for a test case
> Switch to explicit references only.  

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/BaseInAssemblyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptMemberInAssemblyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptTypeInAssemblyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/RemovedMemberInAssemblyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/RemovedTypeInAssemblyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
I have an upcoming PR that will make use of this change.  The upcoming PR will change ResultChecker.IsTypeInOtherAssemblyAssertion to leverage this new base attribute instead of explicitly checking for each of the attributes.  It wasn't worth the hassle of pulling the change to IsTypeInOtherAssemblyAssertion out of my other PR and into this one.
> Base attribute for InAssembly attrs

- linker/Tests/TestCasesRunner/ResultChecker.cs
- linker/Tests/TestCasesRunner/TestCaseCompiler.cs
- linker/Tests/TestCasesRunner/TestRunner.cs
I have finished moving over all of our old tests to the new test framework.  The last of the tests were the most complex and I had to make some adjustments to the core of the test framework so that we could extend it to meet our needs.
In ResultChecker
* AdditionalChecking - We use this to do a few extra things before the AssemblyDefinitions are disposed of.
* UnhandledOtherAssemblyAssertion - This is where we put the logic to handle our [StubbedMemberInAssembly] attribute.
* The change to GetOriginalTypeFromInAssemblyAttribute is simply for improved error reporting when you write a bad test
In TestCaseCompiler I had to shift a few things around  to make TestCaseCompiler a bit more reusable.  We have some tests now that use TestCaseCompiler to compile supporting .dll's so we needed the …
> Test framework extensibility improvements

- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/Mono.Linker.Tests.Cases/VirtualMethods/ClassUsedFromConcreteTypeHasInterfaceMethodRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/VirtualMethods/ClassUsedFromInterfaceHasInterfaceMethodKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/VirtualMethods/StructUsedFromConcreteTypeHasInterfaceMethodRemoved.cs
I wrote StructUsedFromConcreteTypeHasInterfaceMethodRemoved and was initially a little surprised that IFoo.Method was removed.  However this is valid.  I thought I would add some tests covering this behavior since we did not have them already.
> Add some tests for situation where interface method is removed

- linker/Tests/TestCasesRunner/LinkerArgumentBuilder.cs
- linker/Tests/TestCasesRunner/TestRunner.cs
Some of our tests need to use custom options.  This PR refactors the argument building so that we have some options for including custom options during our tests.
> Make arg builder more extensible

- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedAssemblyWithNoDefinedPreserveHasAllTypesPreserved.cs
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedAssemblyWithNoDefinedPreserveHasAllTypesPreserved.xml
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedTypeWithNoDefinedPreserveHasAllMembersPreserved.cs
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedTypeWithNoDefinedPreserveHasAllMembersPreserved.xml
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
If a link.xml file has an assembly or type element that does not have
a preserve atttribute, treat that as if it is preserve="all". These two
tests verify the existing behavior.
> Verify behavior with no preserve attribute in XML

- linker/Tests/Mono.Linker.Tests.Cases/CoreLink/LinkingOfCoreLibrariesRemovesUnusedTypes.cs
Skip PeVerifying of System.dll and System.Configuration.dll.  PeVerify
reports problems in the unlinked mono class lib version of these
assemblies as well as the .NET Framework version. 
Also change the types
used by this test.  Use types that exist in mono AOT profiles
> Fix LinkingOfCoreLibrariesRemovesUnusedTypes failing on Windows

- linker/Mono.Linker.Steps/ResolveFromXmlStep.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptBackingFieldAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedEventPreservedByLinkXmlIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedEventPreservedByLinkXmlIsKept.xml
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedPropertyPreservedByLinkXmlIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedPropertyPreservedByLinkXmlIsKept.xml
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/TestCasesRunner/AssemblyChecker.cs
- linker/Tests/TestCasesRunner/PeVerifier.cs
Greetings! 
Mono linker is a great tool that is used heavily by our team with Xamarin. But there is a little drawback with it's configuration on that platform: it requires way too much XML text to specify for C# event or property to be kept. In our project we prefer to retreat back to some kind of `LinkerPleaseInclude.cs` file, where we specify in C# all the explicit references to all the symbols that we'd wanted to keep. Personally I find this approach disgusting as it makes me to maintain both 'LinkerDescription' XML and that `LinkerPleaseInclude.cs` file where the former is referencing the latter.
So, here's my suggestion on how to improve the XML linker configuration, allowing to write less text in order to keep either an event or property. Please refer to …
> Provide 'event' and 'property' elements support with Link XML step.

- linker/Mono.Linker.Steps/ResolveFromAssemblyStep.cs
- fixes #57645
- ignore invalid forwards of nested types of exported forwarded
types, which were added by a bug in csc. description by Marek Safar
from https://bugzilla.xamarin.com/show_bug.cgi?id=57645#c13
Native csc (pre-Roslyn version) when encountered typeforwarded
type it added automatically all its nested types including
private/protected/internal ones.  This bug was fixed in Roslyn
csc but there are still many assemblies compiled with native csc
(pre VS2015) which can have typeforwarded typeref to a type which
is not available because it's not included in public API.
- ignoring these forwarders here should be harmless, because if these
types were used somewhere in the application, the linker would fail
in the mark step, when trying to resolve the typereference to them
> [linker] added workaround for invalid type forwards

- corebuild/integration/ILLink.Tasks/CompareSizes.cs
- corebuild/integration/ILLink.Tasks/ComputeManagedAssemblies.cs
- corebuild/integration/ILLink.Tasks/ILLink.Tasks.csproj
- corebuild/integration/ILLink.Tasks/Utils.cs
GetAssemblyName currently sometimes fails for crossgen'd assemblies for a different platform (see https://github.com/dotnet/coreclr/issues/13230). Until that is fixed, we use cecil to determine whether an assembly is managed.
Also includes some formatting fixes for the CompareSizes output.
@swaroop-sridhar, @erozenfeld please review.
> Work around GetAssemblyName issue

- linker/Tests/TestCasesRunner/PeVerifier.cs
In our Unity Linker test suite I'm playing around with setting MONO_PATH before running pedump so that pedump picks up the mscorlib.dll that we want.
There are two cases where setting MONO_PATH is desirable
1) During [CoreLink("link")] test cases we want to pick up the mscorlib that was linked when running pedump.  This change would be desirable upstream, however, currently all of the [CoreLink("link")] test cases have PeVerify disabled, so it's pointless to bring this change upstream.  We'd also have to then go down the path of getting the test cases to preserve the minimum set of info required by the runtime (ex: the first error I hit is CustomAttributeData).  Dealing with these issues is not a priority right now in upstream, or in our UnityLinker tests.
2) For our UnityLinker, we run …
> Extension point for setting up pedump process

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/DefineAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupCompileAfterAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupCompileBeforeAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/Mono.Linker.Tests.Cases/TestFramework/CanCompileILAssembly.cs
- linker/Tests/Mono.Linker.Tests.Cases/TestFramework/Dependencies/ILAssemblySample.cs
- linker/Tests/Mono.Linker.Tests.Cases/TestFramework/Dependencies/ILAssemblySample.il
- linker/Tests/Mono.Linker.Tests.Cases/TestFramework/VerifyDefineAttributeBehavior.cs
- linker/Tests/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/ForwarderLibrary.cs
- linker/Tests/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/ImplementationLibrary.cs
- linker/Tests/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/LibraryUsingForwarder.cs
- linker/Tests/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/ReferenceImplementationLibrary.cs
- linker/Tests/Mono.Linker.Tests.Cases/TypeForwarding/TypeForwarderOnlyAssembliesKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/TypeForwarding/TypeForwarderOnlyAssembliesRemoved.cs
- linker/Tests/Mono.Linker.Tests.csproj
- linker/Tests/TestCases/TestDatabase.cs
- linker/Tests/TestCases/TestSuites.cs
- linker/Tests/TestCasesRunner/CompilerOptions.cs
- linker/Tests/TestCasesRunner/ILCompiler.cs
- linker/Tests/TestCasesRunner/ObjectFactory.cs
- linker/Tests/TestCasesRunner/SetupCompileInfo.cs
- linker/Tests/TestCasesRunner/TestCaseCollector.cs
- linker/Tests/TestCasesRunner/TestCaseCompiler.cs
- linker/Tests/TestCasesRunner/TestCaseMetadaProvider.cs
- linker/Tests/TestCasesRunner/TestCaseSandbox.cs
- linker/Tests/TestCasesRunner/TestRunner.cs
Can now compile .il files into assemblies
Add support for [Define] to set defines for a test case
Implement some basic type forwarding test cases
> Add ability to compile assemblies before and after a test case

- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
This fixes an issue in which illink was placing the same version of a
resource dll into different language directories.
@swaroop-sridhar please review
> Don't pass satellite assemblies to the linker

- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
Before this change, setting LinkerRootAssemblies from a project
referencing the linker would have no effect when the extra root
assemblies were platform assemblies or resolved assemblies from project
dependencies.
@swaroop-sridhar please review.
> Prevent overriding custom LinkerRootAssemblies

- corebuild/integration/ILLink.Tasks/ILLink.Tasks.csproj
The linker depends on cecil, shipping with a netstandard1.3 build of
Mono.Cecil. Some of the reference assemblies for netstandard1.3 have
lower versions than the implementation shims that forward types to
mscorlib on desktop. To run the linker on desktop, we need to ensure
that this version mismatch doesn't cause binding problems. This is the
same issue described in https://github.com/dotnet/corefx/issues/16322.
Because illink ships as an msbuild task, we can't use binding
redirects (msbuild doesn't respect them) to fix this. One option is to
implement a custom AssemblyResolve event hook, but this is not robust
because it may cause problems when used in combination with other
msbuild tasks.
Instead, we avoid the version mismatch by using a build of cecil that
targets net46 directly, so …
> Build cecil in desktop configuration for net46 target

- linker/Mono.Linker.Steps/BlacklistStep.cs
- linker/Mono.Linker.Steps/ResolveFromAssemblyStep.cs
- linker/Mono.Linker.csproj
- linker/Mono.Linker/ConsoleLogger.cs
- linker/Mono.Linker/ILogger.cs
- linker/Mono.Linker/LinkContext.cs
Added the ILogger interface for logging messages from the
linker. There is a new default implementation, the DefaultLogger
class, which just continues to use simple S.C.WriteLine as before.
The LinkerContext newly contains Logger property, which can be set to
instance of class implementing ILogger interface. As an example,
Xamarin.Android linker will be able to provide own logger, forwarding
the messages to Microsoft.Build.Utilities.TaskLoggingHelper. This way
it will be possible to see linker messages, depending on the actual
msbuild's verbosity level, in the XA build output.
> Improve logging

- corebuild/integration/test/HelloWorldTest.cs
- corebuild/integration/test/IntegrationTestBase.cs
- corebuild/integration/test/MusicStoreTest.cs
- corebuild/integration/test/WebApiTest.cs
Currently we only link apps in our integration tests, but we do not run them. This change runs the apps and does some basic output validation.
The MusicStore test is currently broken (we're missing reflection roots), so I'm holding off on adding output validation to this one until we get that fixed.
@swaroop-sridhar, @erozenfeld, please review.
> Run apps and validate output in integration tests

- linker/Mono.Linker.Steps/MarkStep.cs
Push actual custom attribute type instead of cecil custom attribute
instance. It also makes dependency graph more spread as we have more
vertices instead of one overused.
So for example we now have:
`TypeDef:System.Runtime.InteropServices.ComVisibleAttribute`
vertex instead of `Other:Mono.Cecil.CustomAttribute`
Do not add predicate method to the dependencies. It doesn't add much
value and makes the graph having vertex with too many edges, so we had
a lot of vertices with 15k+ total dependencies in flat view for XA
template application. Like:
```
Distance | TypeDef:Android.App.ActivityAttribute [total deps: 15100]
------------------------------------------------------------------------
1 | Method:System.Void Android.App.ActivityAttribute::.ctor()
2 | Other:Mono.Cecil.CustomAttribute
3 | …
```
> Improve dependency dumping

- linker/Mono.Linker.Steps/ResolveFromXmlStep.cs
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedTypePreservedByLinkXmlWithCommentIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedTypePreservedByLinkXmlWithCommentIsKept.xml
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
Find 'linker' child element rather than assuming it's the first element in the file. This allows link xml files to contain comments at the start.
> Allow link xml files to start with comments

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupCompileAssemblyNameAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/TestCasesRunner/TestCaseMetadaProvider.cs
- linker/Tests/TestCasesRunner/TestRunner.cs
The UnityLinker has some logic to behave differently for "UnityEngine.*" assemblies, in order to test this logic we need to control the name of the assembly for the test case.
> Add ability to customize the name of the output assembly in tests

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SandboxDependencyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupCompileResourceAttribute.cs
- linker/Tests/Mono.Linker.Tests.csproj
- linker/Tests/TestCasesRunner/SourceAndDestinationPair.cs
- linker/Tests/TestCasesRunner/TestCaseMetadaProvider.cs
- linker/Tests/TestCasesRunner/TestCaseSandbox.cs
The sandboxing code isn't really setup to allow files being placed in arbitrary sub directories. 
Change the default destination file name from relative path to the source (ex : 'Depedencies/somefile.txt'), to just the sources file name (ex: 'somefile.txt').  This wasn't causing any issues in the tests we have today, but it would have in some new resource tests that are coming.
> Reframe alternate destination as file name only rather than relative path.

- linker/Tests/TestCasesRunner/TestRunner.cs
We have a couple niche tests that depend on the entry point preservation logic.  This PR adds back the PrepForLink method so that we can use it as a hook point to add back the hold behavior for the new tests we have that need it
> Add back PrepForLink  method for customization purposes

- linker/Mono.Linker/Driver.cs
- linker/Mono.Linker/LinkContext.cs
Add -u switch to specify action on user (non-core) assemblies similar
to -c switch for core assemblies.
> Add a switch to specify action on user assemblies.

- linker/Mono.Linker.Steps/MarkStep.cs
- linker/Mono.Linker/Driver.cs
- linker/Mono.Linker/LinkContext.cs
With this change the linker won't throw if it encounters an unresolved
type or method during MarkStep and -n true was specified.
> Add an option to ignore unresolved types and methods.

- linker/Mono.Linker.Steps/MarkStep.cs
- linker/Mono.Linker.Steps/SweepStep.cs
- linker/Mono.Linker/AssemblyAction.cs
- linker/Mono.Linker/Driver.cs
CopyUsed action specifies that the assembly should be copied intact if and only if
it is used (i.e., marked).
> Add CopyUsed assembly action.

- linker/Mono.Linker.Steps/MarkStep.cs
- linker/Mono.Linker.Steps/SweepStep.cs
- linker/Tests/Mono.Linker.Tests.Cases/Basic/UsedInterfaceIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
Make interface marking overridable by derived classes, so that derived classes
can decide whether an interface implementation should be marked or not.
Also remove any non-marked interface implementations.
> Make interface marking overridable by derived classes.

- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
With this change, the refs directory of the publish output should not
change when using the linker.
@erozenfeld please review.
> Prevent linker from interfering with ref assemblies

- .gitignore
- corebuild/integration/ILLink.Tasks/ILLink.Tasks.csproj
- linker/Mono.Linker.Steps/AddBypassNGenStep.cs
- linker/Mono.Linker.Steps/MarkStep.cs
- linker/Mono.Linker.Steps/OutputStep.cs
- linker/Mono.Linker.Steps/SweepStep.cs
- linker/Mono.Linker.csproj
- linker/Mono.Linker/AssemblyAction.cs
- linker/Mono.Linker/Driver.cs
AddBypassNGen specifies that instead of removing unreached methods
they should be marked with System.Runtime.BypassNGenAttribute. Types and fields
should be preserved.
AddBypassNGenUsed is the same as AddBypassNGen except unmarked assemblies should
be deleted.
ngen/crossgen will skip compilation of methods marked with
System.Runtime.BypassNGenAttribute so these actions can be used for conservative
linking: all msil is preserved but ngen/crossgen is run only on reachable methods.
System.Runtime.BypassNGenAttribute may not be present in the core library.
If that's the case, the linker will inject it.
> Add two new assembly actions: AddBypassNGen and AddBypassNGenUsed.

- linker/Mono.Linker.Steps/MarkStep.cs
- linker/Mono.Linker.Steps/SweepStep.cs
- linker/Tests/TestCasesRunner/AssemblyChecker.cs
- linker/Tests/TestCasesRunner/ResultChecker.cs
These are extension points we needed to implement our experimental "stub"  feature in the UnityLinker which lets you replace the implementation of a method with a throw Exception().
> Extensibility changes

- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/Mono.Linker.Tests.Cases/References/Dependencies/UserAssembliesAreLinkedByDefault_Library1.cs
- linker/Tests/Mono.Linker.Tests.Cases/References/UserAssembliesAreLinkedByDefault.cs
There was a change made about a month ago that required us to make a corresponding change to our version of Driver.cs in our UnityLinker
https://github.com/mono/linker/commit/4d2362d8083e3c71560ba1225d468a0080aeea27
This PR adds a test to verify the default user assembly behavior.
> Add test to verify the default user assembly action

- corebuild/integration/ILLink.Tasks/CreateRuntimeRootDescriptorFile.cs
- corebuild/integration/ILLink.Tasks/ILLink.Tasks.csproj
The task will run during coreclr build and compute the roots from coreclr header
files. The roots xml will be embedded as resource into System.Private.CoreLib.dll.
Example of xml computed by this task: https://gist.github.com/erozenfeld/b005d315c2f8e7da791bd40a125c07d9
> Add a task for computing System.Private.CoreLib roots needed by the coreclr runtime.

- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
- corebuild/integration/ILLink.Tasks/LinkTask.cs
- linker/Mono.Linker/Driver.cs
Made it possible to enable dumping dependencies for the
linker-analyzer tool with the command line argument
`--dump-dependencies` to the illink.
Or by setting the `LinkerDumpDependencies` msbuild property to true.
> Added cmd line option and property to the ILLink

- linker/Linker.Steps/ResolveFromXmlStep.cs
We have some error cases we would like to bubble up as the culprit, this behavior of catching all exceptions and throwing a new exception was interfering with that.
I changed our code to throw XmlResolutionExceptions in cases we don't want caught
> Don't catch and wrap if already an XmlResolutionException

- linker/Linker.Steps/BaseStep.cs
- linker/Linker.Steps/MarkStep.cs
- linker/Linker.Steps/ResolveFromAssemblyStep.cs
- linker/Linker.Steps/ResolveFromXmlStep.cs
- linker/Linker/LinkContext.cs
- linker/Linker/MarkingHelpers.cs
- linker/Mono.Linker.csproj
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/CanPreserveAnExportedType.cs
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/CanPreserveAnExportedType.xml
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/CanPreserveExportedTypesUsingRegex.cs
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/CanPreserveExportedTypesUsingRegex.xml
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/Dependencies/CanPreserveAnExportedType_Forwarder.cs
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/Dependencies/CanPreserveAnExportedType_Library.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
When KeepTypeForwarderOnlyAssemblies=false we shouldn't preserve forwarding only assemblies just because a type was preserved via link.xml
> Don't preserve forwarding assemblies when exported type preserved by xml

- linker/Linker.Steps/MarkStep.cs
Attempt to Resolve the attributes constructor rather than the AttributeType.  This is slightly more correct, technically the type could have existed but the constructor be missing and we would have tried to process it.
A secondary benefit is that we have a feature to stub missing methods and by attempting to resolve the constructor, we can call our stub method code path if it fails to resolve
> Tweak what we Resolve when processing attributes

- linker/Linker.Steps/ResolveFromXmlStep.cs
The ResolveFromXmlStep used by our UnityLinker was an older copy of ResolveFromXmlStep.  I had punted on unifying the differences earlier this year when I got our monolinker in sync with upstream.
This PR contains changes so that UnityLinker's ResolveFromXmlStep can be unified with upstream and maintain a few additional things our step does..
I took some minor clean up improvements from our step.  Mostly to do with using Try* methods instead of try/catch
> Refactoring and minor clean up in ResolveFromXmlStep

- linker/Linker.Steps/ResolveFromXmlStep.cs
- linker/Linker/Annotations.cs
Prior to https://github.com/mono/linker/commit/9cf2bb80616f1473efcfd1e651d949ef78b4e94b
ResolveFromXmlStep would produce an edge element in the dependency xml directly mapping the "link.xml" file to the methods it preserved.  We have a test in our test framework that asserts this and after updating our ResolveFromXmlStep to be based off of the latest upstream, it started failing.
The changes in this PR leave the current behavior in place, but also adds in a edge so that previous information is also available.
Prior to 9cf2bb80616f1473efcfd1e651d949ef78b4e94b, the dependency info in the xml file would look something like this for a method preserved by a link.xml
link.xml => Main()
We have a simple html visualization we output based on the dependency info and it would clearly tell you that …
> Add back edge mark behavior to ResolveFromXmlStep

- linker/Linker.Steps/ResolveFromAssemblyStep.cs
- linker/Linker.Steps/ResolveFromXmlStep.cs
- linker/Linker/Annotations.cs
Add `mark` attribute to the dependencies edge element, for these edges
added when marking.
Introduce `MarkAndPush` method. It simplifies common case, where we
called `Annotations::Mark` and `Annotations::Push`. It also avoids
adding duplicate edge in this case.
> Add mark attribute, avoid some deps duplicating

- linker/Linker.Steps/BaseStep.cs
- linker/Linker.Steps/MarkStep.cs
- linker/Linker.Steps/OutputStep.cs
- linker/Linker.Steps/ResolveFromAssemblyStep.cs
- linker/Linker.Steps/ResolveFromXmlStep.cs
- linker/Linker/Annotations.cs
- linker/Linker/LinkContext.cs
- linker/Linker/Pipeline.cs
- linker/Linker/Tracer.cs
- linker/Mono.Linker.csproj
Kept the Annotations::PrepareDependenciesDump methods, as they are
still needed for the mobile linkers. They will be removed once we
update them.
> Extracted dependency dumping into the new Tracer class

- linker/Linker/Annotations.cs
- linker/Linker/LinkContext.cs
- linker/Linker/Tracer.cs
This is a helper class, which is used in LinkContext to create
AnnotationStore, MarkingHelpers and Tracer. As the name suggest, it
uses uninitialized LinkContext. It is a slightly better than using
virtual methods in the LinkContext constructor as the class name hints
about the state of the context it uses.
It is added for Unity developers to be able to create their own
AnnotationStore, MarkingHelpers and Tracer. It is also needed for
https://github.com/mono/linker/pull/208
The class itself might be replaced later by interface with default
implementations.
> Added UnintializedContextFactory class

- corebuild/integration/ILLink.Tasks/CheckEmbeddedRootDescriptor.cs
- corebuild/integration/ILLink.Tasks/ILLink.Tasks.csproj
- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
Once we start computing System.Private.CoreLib roots during coreclr build (https://github.com/dotnet/coreclr/pull/15525)
we won't need to root all of System.Private.CoreLib if the embedded xml
root file is present.
> Don't root System.Private.CoreLib if it has an embedded root xml resource.

- linker/Linker/Driver.cs
- linker/Linker/LinkContext.cs
- linker/Linker/Tracer.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/Mono.Linker.Tests.Cases/Tracing/Individual/CanDumpDependenciesToUncompressedXml.cs
- linker/Tests/Mono.Linker.Tests.Cases/Tracing/Individual/CanEnableDependenciesDump.cs
- linker/Tests/Mono.Linker.Tests.Cases/Tracing/Individual/CanEnableReducedTracing.cs
- linker/Tests/TestCases/IndividualTests.cs
There's a lot of output in the linker-dependencies.xml.  I find it hard to reason about what is going on with so much noise.
I was thinking of ways to reduce the noise, mainly to start writing some tests for the xml output and I thought, if the assembly won't be modified, then do we really care about reporting these edges?
This PR makes it so that edges are only written to the xml when the assembly of one, or both, of the items will be modified.  This greatly reduces the output size of linker-dependencies.xml during tests and it makes it much easier to read the file and understand what is going on.
Sure there are some edge cases that would be odd, for example, code that calls into an assembly that is not linked and then a callback calls back into an assembly that is linked.  You would …
> Only record dependency info for nodes in assemblies that will be linked

- corebuild/integration/ILLink.Tasks/ILLink.Tasks.csproj
- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
- corebuild/integration/ILLink.Tasks/LinkTask.cs
- corebuild/integration/ILLink.Tasks/SetAssemblyActions.cs
This change adds 4 linker publish options:
UsedApplicationAssemblyAction, UnusedApplicationAssemblyAction,
UsedNetCoreFrameworkAssemblyAction, and UnusedNetCoreFrameworkAssemblyAction.
ILLink task takes two sets of assemblies as inputs: application assemblies and
framework assemblies.
ILLink task emits the appropriate -p switches for each assembly.
ILLink task no longer emits -c switch.
> Expose assembly actions in ILLink.

- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
The default is to root all application assemblies (and SPC if necessary).
The new property can be used to alter that behavior and
root only the Main method of the application exe (and SPC if necessary).
> Expose RootAllApplicationAssemblies property.

- linker/Linker.Steps/MarkStep.cs
- linker/Linker.Steps/SweepStep.cs
- linker/Linker/Annotations.cs
This PR exposes `MarkStep.ShouldMarkCustomAttribute` which allows a linker implementation to control which CustomAttributes should be kept.
For now, everything will be kept by default, which is the current behavior.
> Implement mechanism for removing CustomAttributes

- linker/Tests/TestCasesRunner/LinkerArgumentBuilder.cs
- linker/Tests/TestCasesRunner/TestCaseMetadaProvider.cs
This avoids polluting test case results with extra assemblies which can throw off assertions
> Default to no i18n assemblies during tests

- linker/Linker.Steps/MarkStep.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/AssemblyAttributeIsRemovedIfOnlyTypesUsedInAssembly.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/AssemblyAttributeKeptInComplexCase.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/Dependencies/AssemblyAttributeIsRemovedIfOnlyTypesUsedInAssembly_Lib.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/Dependencies/AssemblyAttributeKeptInComplexCase_Lib.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/TestCasesRunner/PeVerifier.cs
Top level CustomAttributes are marked late, after all of the main marking happens.  This lets us remove attributes when the attribute type would be the only thing used from a reference.  After marking these attributes we would process the queue one more time.  However, if that second processing pass gave us a reason to keep another top level attribute, we wouldn't circle back and process the top level attributes again
Now, we will process the main queues and the late marked attributes repeatedly until no more items are being marked
> Fix case where assembly attribute wouldn't be correctly marked

- linker/Linker.Steps/OutputStep.cs
Log output action for every assembly in the OutputStep. It uses
`MessageImportance.Low` so it will be visible in the diagnostic log
output of the mobile linkers.
It helps to quickly diagnose issues, where we want to know how was the
assembly processed. Typically whether it was dropped completely,
linked, saved or copied.
> Log output actions

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptDelegateCacheFieldAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptEventAddMethodAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptEventRemoveMethodAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/Mono.Linker.Tests.Cases/Basic/UnusedDelegateGetsRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Basic/UnusedEventGetsRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Basic/UsedEventIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Basic/UsedEventOnInterfaceIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Basic/UsedEventOnInterfaceIsRemovedWhenUsedFromClass.cs
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedEventPreservedByLinkXmlIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/TestCasesRunner/AssemblyChecker.cs
I added new [KeptEventAddMethod] and [KeptEventRemoveMethod] attributes so that the expected result could be different for the two in the future.
A new [KeptDelegateCacheField] was introduced to help with asserting that the `<>f__mg$cache` fields generated by mcs are kept.
> Add more delegate and event test cases

- linker/Linker/TypeReferenceExtensions.cs
Cecil's MetadataResolver returns null if it cannot resolve something.
This requires the callers, like TypeReferenceExtensions, to do null
checks, otherwise a  `NullReferenceException` can happens in the linker
code and it's not possible to give a useful error message to the
developer.
This is what's happening in
https://github.com/xamarin/xamarin-macios/issues/3215 (with test case)
and likely in
https://github.com/xamarin/xamarin-macios/issues/3210 (without test case)
> Add missing null checks to TypeReferenceExtensions

- corebuild/integration/test/CommandRunner.cs
- corebuild/integration/test/IntegrationTestBase.cs
- corebuild/integration/test/WebApiTest.cs
- corebuild/integration/test/test.csproj
The webapi test starts a process that does not terminate
automatically, but stops when it hits the timeout. We then expect the
output to contain some well-known string.
This was causing problems in ci because the ci machines were slow,
causing the test to frequently time out before printing the
string. Increasing the timeout to a large value caused the test to run
for too long.
This fix makes it possible to specify a termination condition. Now the
test process is killed when it prints the expected string, or hits a
timeout, currently set to 60 seconds.
As part of the change, the core process running logic has been moved
to a new class.
@erozenfeld, @JosephTremoulet PTAL
> Add functionality to terminate a test process upon output

- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
We already avoid linking passing resource assemblies to the linker
since change fe21568643da93dfdfec3698ddefe5ba633df43d. However,
removing resource assemblies from the set of managed assemblies causes
them to be included in the set of native trimming candidates.
This change excludes resources from the native trimming candidates.
This fixes https://github.com/mono/linker/issues/218.
@erozenfeld, @JosephTremoulet PTAL
> Prevent removal of resource assemblies by native trimming logic

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupCompileAfterAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupCompileBeforeAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupLinkerLinkSymbolsAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/TestCasesRunner/LinkerArgumentBuilder.cs
- linker/Tests/TestCasesRunner/SetupCompileInfo.cs
- linker/Tests/TestCasesRunner/TestCaseCompiler.cs
- linker/Tests/TestCasesRunner/TestCaseLinkerOptions.cs
- linker/Tests/TestCasesRunner/TestCaseMetadaProvider.cs
- linker/Tests/TestCasesRunner/TestCaseSandbox.cs
- linker/Tests/TestCasesRunner/TestRunner.cs
This PR contains a few small changes that will be needed by upcoming work to add a full suite of symbol tests to get coverage on handling all the various types of symbol files.
* Support defining additional compiler arguments when compiling extra assemblies for test cases
* Adjustments to how test cases setup references.  No longer will the extra assemblies inherit references added via [Reference] to the main test case.  This was done out of convenience, but it started to cause problems with the symbol tests that are coming. 
* Test case support for [SetupLinkerLinkSymbols]
> Testing infrastructure changes to prepare for symbol tests

- linker/Linker.Steps/MarkStep.cs
We need to specialize this behavior in the Unity linker, so extract it
to a virtual method that the Unity linker can override. This should not
change its behavior at all.
> Extract the reflection marking code to a method

- linker/Tests/TestCasesRunner/TestCaseMetadaProvider.cs
In some new symbol handling tests I'm working on, I need to define slight differences in expected outcome from a test between windows & non-windows.
This PR has the test framework set a special define when running on windows.
Here's a part of the test I have that highlights why this is needed
```
[Reference ("LibraryWithPdb.dll")]
[SandboxDependency ("Dependencies/LibraryWithPdb/LibraryWithPdb.dll", "input/LibraryWithPdb.dll")]
[SandboxDependency ("Dependencies/LibraryWithPdb/LibraryWithPdb.pdb", "input/LibraryWithPdb.pdb")]
[SetupLinkerLinkSymbols( "true")]
#if TEST_FW_DEFINED_WINDOWS
[KeptSymbols ("LibraryWithPdb.dll")]
#else
[RemovedSymbols("LibraryWithPdb.dll")]
#endif
[KeptMemberInAssembly ("LibraryWithPdb.dll", typeof (LibraryWithPdb), "SomeMethod()")]
[RemovedMemberInAssembly …
```
> Test framework defines TEST_FW_DEFINED_WINDOWS on windows

- linker/Linker/Driver.cs
- linker/Tests/TestCasesRunner/LinkerDriver.cs
When the linker hits an exception today during a test, the exception is caught and the test framework continues on and you get some odd failure message.
> Use Run to run the linker instead of Main so that exceptions are not caught

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupCSharpCompilerToUseAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupCompileAfterAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupCompileBeforeAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/Mono.Linker.Tests.Cases/TestFramework/CanCompileTestCaseWithCsc.cs
- linker/Tests/Mono.Linker.Tests.Cases/TestFramework/CanCompileTestCaseWithMsc.cs
- linker/Tests/Mono.Linker.Tests.Cases/TestFramework/Dependencies/CanCompileTestCaseWithCsc.txt
- linker/Tests/Mono.Linker.Tests.Cases/TestFramework/Dependencies/CanCompileTestCaseWithCsc_Lib.cs
- linker/Tests/Mono.Linker.Tests.Cases/TestFramework/Dependencies/CanCompileTestCaseWithMcs.txt
- linker/Tests/Mono.Linker.Tests.Cases/TestFramework/Dependencies/CanCompileTestCaseWithMcs_Lib.cs
- linker/Tests/TestCasesRunner/CompilerOptions.cs
- linker/Tests/TestCasesRunner/SetupCompileInfo.cs
- linker/Tests/TestCasesRunner/TestCaseCompiler.cs
- linker/Tests/TestCasesRunner/TestCaseMetadaProvider.cs
A requirement for symbol tests that are coming is access to a roslyn compiler so that we can generate portable and embedded pdbs.
This PR adds a general mechanism for tests to define which compiler they need to use when compiling a test case.
> Support for explicitly using csc to compile test case

- linker/Linker.Steps/MarkStep.cs
- linker/Linker.Steps/SweepStep.cs
- linker/Linker/Driver.cs
- linker/Linker/LinkContext.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/AttributeDefinedAndUsedInOtherAssemblyIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/AttributeUsedByAttributeIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/CanLinkCoreLibrariesWithOnlyKeepUsedAttributes.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/Dependencies/AttributeDefinedAndUsedInOtherAssemblyIsKept_Lib.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/Dependencies/UnusedAttributeWithTypeForwarderIsRemoved_Forwarder.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/Dependencies/UnusedAttributeWithTypeForwarderIsRemoved_Lib.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UnusedAttributePreservedViaLinkXmlIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UnusedAttributePreservedViaLinkXmlIsKept.xml
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UnusedAttributeTypeOnAssemblyIsRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UnusedAttributeTypeOnEventIsRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UnusedAttributeTypeOnMethodIsRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UnusedAttributeTypeOnModuleIsRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UnusedAttributeTypeOnParameterIsRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UnusedAttributeTypeOnPropertyIsRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UnusedAttributeTypeOnTypeIsRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UnusedAttributeWithTypeForwarderIsRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UsedAttributeTypeOnAssemblyIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UsedAttributeTypeOnEventIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UsedAttributeTypeOnMethodIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UsedAttributeTypeOnModuleIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UsedAttributeTypeOnParameterIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UsedAttributeTypeOnPropertyIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UsedAttributeTypeOnTypeIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/TestCasesRunner/AssemblyChecker.cs
The way attributes work currently is that once a type, method, etc is marked, all of it's CustomAttributes are marked. Which marks the attribute type, it's fields and properties.
What this PR does is add a new option that causes the CustomAttributes marking to be queued. Later, after we've traversed all the calls, we process this queue. If the attribute type of a CustomAttribute was marked, then we mark instances of that CustomAttribute. If not, we don't mark these CustomAttributes and they will be removed by the SweepStep.
If a user wants to explicitly preserve a CustomAttribute, they would preserve the attribute type via link.xml. Once they do that, all CustomAttribute instances of that type will be kept.
I've made this an opt-in option since it is a rather significant behavior change. …
> Support for removing CustomAttributes

- linker/Tests/Mono.Linker.Tests.Cases/TestFramework/CanCompileTestCaseWithCsc.cs
The purpose of this test is simply to verify that a test case can use csc.  The mono csc can error with the following on Windows
```error CS0041: Unexpected error writing debug information -- 'The version of Windows PDB writer is older than required: 'diasymreader.dll''```
In our UnityLinker test suite we use the csc with mono instead of a system install csc from MSBuild.
To get around this, use /debug:portable which is supported by both and doesn't undermine the goal of the test
> Use portable instead of pdbonly to avoid error on windows with mono csc

- linker/Linker.Steps/ResolveFromXmlStep.cs
There was a mix of patterns in use for processing Types, Methods, Fields, Properties, and Events.  This PR standardizes the pattern on what methods were doing and expose a protected virtual method for each so that we can customize the behavior of each.
> Standardize and make ResolveFromXml more customizable

- linker/Linker.Steps/OutputStep.cs
- linker/Linker/LinkContext.cs
- linker/Tests/Mono.Linker.Tests.Cases/Symbols/ReferenceWithEmbeddedPdbCopyAction.cs
This one was a bit tricky to figure out how best to fix.  The dilemma I ran into was
* When symbol linking is not enabled, we were never reading the symbols
* In order to know we are copying an assembly with embedded pdbs, we need to read the symbols.
The path I went with was to 
* Always try to read symbols regardless of whether or not symbol linking is enabled
* When about to Copy an assembly with embedded pdbs and symbol linking off, don't copy, and instead save the assembly without symbols.
An alternative idea I had was to leave SafeReadSymbols alone and leave the copying as is.  Then do another pass after the copy to read in each assembly and see if any have embedded pdbs, and if they do rewrite them without.  That seemed less efficient, but potentially have less chance of causing …
> Fix for embedded pdb when copy and no link symbols

- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
Use a set of defaults chosen to provide the key benefit for
self-contained apps while still being conservative enough to have low
risk of introducing resolution failures.  App assemblies will all be
considered roots, framework assemblies will be removed if unreferenced
at assembly granularity, and at method granularity will have prejitting
suppressed for unmarked code.
> Update managed app action defaults

- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
Setting LinkerTrimNativeDeps=false will now bypass the FindNativeDeps
task and preserve all native dependencies.
> Make native trimming optional

- .gitignore
Also add a comment header for the corebuild section, and normalize the
prefix used in it.
> .gitignore more corebuild build/test artifacts

- corebuild/integration/ILLink.Tasks/AdapterLogger.cs
- corebuild/integration/ILLink.Tasks/ILLink.Tasks.csproj
- corebuild/integration/ILLink.Tasks/LinkTask.cs
- linker/Linker/Driver.cs
Currently, attempts to log messages when the linker is invoked by the ILLink MSBuild task get swallowed because MSBuild swallows tasks' stdout.  The linker already has an ILogger interface, so enable passing one to the Driver, and update the ILLink task to pass one to the Driver which will forward messages to any attached MSBuild loggers.
> Allow custom loggers in Driver, use MSBuild log in ILLink

- analyzer/ConsoleDependencyGraph.cs
- analyzer/LinkerAnalyzerCore/DependencyGraph.cs
- analyzer/LinkerAnalyzerCore/SpaceAnalyzer.cs
- analyzer/Main.cs
- analyzer/analyzer.csproj
Adds size information to the types and methods. The size of type
includes only sum of methods IL sizes and should be considered as an
estimate.
Example output:
```
Loading dependency tree from: /Users/rodo/Projects/XATemplateLA/linker-dependencies.xml.gz
Analyzing assemblies ........
--- Type dependencies: 'Java.Interop.JavaArray`1' ----------------------
Distance | TypeDef:Java.Interop.JavaArray`1 [total deps: 9] [size: 1565]
------------------------------------------------------------------------
1 | TypeDef:Java.Interop.JavaPrimitiveArray`1 [1 deps] [size: 178]
2 | Method:System.Void Java.Interop.JniRuntime::.cctor() [2 deps] [size: 2626]
3 | TypeDef:Java.Interop.JniRuntime [1 deps] [size: 5455]
4 | TypeDef:Android.Runtime.AndroidRuntime [1 deps]
5 | Method:System.Void …
```
> Added new feature, space analyzer

- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
- linker/Linker.Steps/MarkStep.cs
- linker/Linker.Steps/ResolveFromAssemblyStep.cs
- linker/Linker.Steps/ResolveFromXmlStep.cs
- linker/Linker.Steps/SweepStep.cs
- linker/Linker/AssemblyResolver.cs
- linker/Linker/Driver.cs
- linker/Linker/LinkContext.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SkipUnresolvedAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/Mono.Linker.Tests.Cases/TypeForwarding/MissingTargetReference.cs
- linker/Tests/TestCasesRunner/LinkerArgumentBuilder.cs
- linker/Tests/TestCasesRunner/TestCaseLinkerOptions.cs
- linker/Tests/TestCasesRunner/TestCaseMetadaProvider.cs
Previously, we swallowed AssemblyResolutionException in a few places
in various steps. We need an option to be generally more tolerant of
AssemblyResolutionExceptions, because there can be cases during
portable publish in which referenced assemblies are not present during
publish because they're part of the shared framework.
Instead of handling AssemblyResolutionException in every place in the
linker that tries to resolve methods/types/etc, this change adds an
option that enables the resolver to return null when an assembly is
not found. The null result is also cached to avoid multiple lookups.
Only a few places in the linker need to be modified to handle null
results, and the existing places where we used to catch
AssemblyResolutionException now only need to deal with a null result …
> Tolerate assembly resolution errors

- corebuild/integration/ILLink.Tasks/FindNativeDeps.cs
Previously, the native dependency logic looked for the first native
dependency whose filename (without extension) matched each reference
in managed metadata.
With this change, it will find all such native dependencies, including
different files with the same name (relevant when the publish output
contains cross-arch libraries for the same platform) or native
libraries with different extensions but the same filename (relevant
when the publish output contains cross-platform libraries).
This is one prerequisite for running the linker during portable
publish, because in portable publish we often output a
runtime-specific native library for each supported platform. The case
I found was libuv, which was being published as libuv.dll for
different windows OSs, libuv.dylib for macOS, and libuv.so …
> Make native dependency logic find more cases

- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
- corebuild/integration/test/CommandRunner.cs
- corebuild/integration/test/HelloWorldTest.cs
- corebuild/integration/test/IntegrationTestBase.cs
- corebuild/integration/test/MusicStoreTest.cs
- corebuild/integration/test/WebApiTest.cs
This enables the linker to run during a portable publish.
During portable publish, the framework is shared. The set of assemblies to be excluded from publish is determined by a platform manifest that's part of the NETCore.App package. The portable publish set can include references to parts of the framework that are filtered by this mechanism, and aren't exposed as reference assemblies (for example, platform-specific assemblies that we don't want developers to compile against directly). With [tolerate resolution errors](https://github.com/mono/linker/pull/260), the linker can tolerate such missing references.
However, we still want to pass ReferencePath to the linker to prevent a large number of resolution warnings for parts of the framework that don't get published. This doesn't cover …
> Enable link during portable publish

- corebuild/integration/ILLink.CustomSteps/ClearInitLocals.cs
- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
Modified ClearInitLocalsStep to accept ClearInitLocalsAssemblies
custom parameter that can be specified via -m. The parameter
is a comma-separated list of assembly simple names that the the
step should be applied to. If the parameter is not specified ClearInitLocals
runs on all assemblies.
> Add ClearInitLocalsAssemblies parameter for ClearInitLocalsStep.

- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
- linker/Linker/Driver.cs
- linker/Linker/LinkContext.cs
Also enable it for ILLink.Tasks, which will result in resolution
errors being logged as warnings during publish.
@erozenfeld PTAL.
> Expose option to log internal exceptions

- linker/Linker.Steps/RemoveSecurityStep.cs
- linker/Linker/Driver.cs
- linker/Mono.Linker.csproj
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/RemovedPseudoAttributeAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/NoSecurity/CoreLibrarySecurityAttributeTypesAreRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/NoSecurity/SecurityAttributesOnUsedMethodAreRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/NoSecurity/SecurityAttributesOnUsedTypeAreRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/CoreLink/NoSecurityPlusOnlyKeepUsedRemovesAllSecurityAttributesFromCoreLibraries.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/TestCasesRunner/AssemblyChecker.cs
Add an option that will remove SecurityDeclarations from Types and Methods along with a few security attributes.
When this new option is used with `--strip-security`  all attributes from System.Security and System.Security.Permissions that are not used will be linked away.
> Add --strip-security option to remove security attributes

- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
- corebuild/integration/ILLink.Tasks/LinkTask.cs
This change allows ClearInitLocals and ClearInitLocalsAssemblies to be specified
directly on ILLink task, which is useful when the task  used outside of publishing (e.g., in corefx).
> Add ClearInitLocals and ClearInitLocalsAssemblies optional ILLink task parameters.

- linker/Linker/LinkContext.cs
`LinkContext.SafeReadSymbols` used to have a try / catch block around the actual symbol reading.
This got removed in [f9c0d99](https://github.com/mono/linker/commit/f9c0d99fd8630c508f2c801552282b8218ff9d3c) and is now breaking the monthly Xamarin.Android integration.
> Fix a regression introduced in f9c0d99, putting back the try/catch.

- linker/Tests/TestCases/TestDatabase.cs
We want to access TestDatabase so that we can run tests in test fixture classes that do not derive from `All`
> Make TestDatabase public

- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
This will show the size comparison on final crossgen'd assemblies,
instead of post-link assemblies that haven't been crossgen'd yet.
@erozenfeld please review.
> Take crossgen into account for size comparison

- corebuild/integration/ILLink.Tasks/ComputeCrossgenedAssemblies.cs
- corebuild/integration/ILLink.Tasks/ILLink.CrossGen.targets
- corebuild/integration/ILLink.Tasks/ILLink.Tasks.csproj
- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
This introduces behavior that will crossgen any assemblies modified by the linker that were crossgen'd before linking.
The defaults for SPC have been updated so that it will never be rooted via -a. If it has an embedded root descriptor, this is the same as before - the root descriptor will specify what to root from SPC. If it doesn't have one, then its action will be AddBypassNGenUsed as it is part of the platform.
@erozenfeld PTAL.
> Set crossgen defaults when linker is enabled

- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
The tests in the test cases assembly will always need to do things that trigger warnings.  Lower warning level to 0 to eliminate build spam.
> Disable warnings in Mono.Linker.Tests.Cases

- linker/Linker.Steps/ResolveFromXmlStep.cs
- linker/Linker/Driver.cs
- linker/Linker/LinkContext.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/StripResourcesAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/Mono.Linker.Tests.Cases/Resources/Dependencies/EmbeddedLinkXmlFileIsProcessedAndKept.xml
- linker/Tests/Mono.Linker.Tests.Cases/Resources/EmbeddedLinkXmlFileIsProcessedAndKept.cs
- linker/Tests/TestCasesRunner/LinkerArgumentBuilder.cs
- linker/Tests/TestCasesRunner/TestCaseLinkerOptions.cs
- linker/Tests/TestCasesRunner/TestCaseMetadaProvider.cs
We have a scenario when the linker is invoked on an assembly
more than once so we need to preserve the embedded xml resources.
> Make removal of processed resources optional.

- corebuild/integration/ILLink.Tasks/ILLink.Tasks.csproj
Myget lists version numbers alphabetically, and with our build numbers this means that newer packages are showing up as older on https://dotnet.myget.org/feed/dotnet-core/package/nuget/ILLink.Tasks. Updating the version number fixes this for the foreseeable future.
Now seems like a good time to do this since we're wrapping up wave 1.
@erozenfeld PTAL.
> Increment ILLink.Tasks version

- corebuild/integration/ILLink.Tasks/FindDuplicatesByMetadata.cs
- corebuild/integration/ILLink.Tasks/ILLink.Tasks.csproj
- corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets
Portable apps can have platform-specific managed assemblies, but the
linker isn't able to handle multiple assemblies with the same
identity. We detect such duplicates, and prevent them from being
linked at all. This will prevent analysis of some code paths, but
seems to be fairly rare.
I've observed the following cases:
- System.Data.SqlClient
- System.Text.Encoding.CodePages
Both were pulled in by the ASP.NET metapackage. Some of these
duplicate assemblies may have native dependencies, so the native
trimming logic does scan them.
@erozenfeld, @ericstj please review.
> Don't attempt to link duplicate managed assemblies

- linker/Linker.Steps/MarkStep.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/ContextStaticIsPreservedOnField.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/ThreadStaticIsPreservedOnField.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
These attributes are needed by the mono runtime, so they should be kept even if no managed usages of these attributes are marked
> Mark [ThreadStatic] and [ContextStatic] attributes

- linker/Linker.Steps/OutputStep.cs
- linker/Mono.Linker.csproj
This is an alternative approach to 
https://github.com/mono/linker/commit/f7f6081202417d43d5b8c3dadd2b7ccd48c2f4cf#diff-78e7cd35fdf21ba1a7924c0def208816
This commit led to a regression in our UnityLinker because we use a different compilation pipeline in certain cases and they did not define NATIVE_READER_SUPPORT.
I think the #if was always going to be fragile and error prone.  I believe this string type check will provide the same flexibility as the commit above desired without requiring special defines to be defined
> Use string type check instead of #if for native reader checking

- linker/Linker.Steps/ResolveFromXmlStep.cs
I used this to help clean up duplicate preservations in our link xml files and in the mscorlib that is embedded with mono mscorlib.  I thought this might be useful again in the future
> Log duplicate preservations from link xml files

- linker/Linker.Steps/BlacklistStep.cs
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/Dependencies/EmbeddedLinkXmlPreservesAdditionalAssemblyWithOverriddenMethod/Base.cs
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/Dependencies/EmbeddedLinkXmlPreservesAdditionalAssemblyWithOverriddenMethod/Library1.cs
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/Dependencies/EmbeddedLinkXmlPreservesAdditionalAssemblyWithOverriddenMethod/Library1.xml
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/Dependencies/EmbeddedLinkXmlPreservesAdditionalAssemblyWithOverriddenMethod/Library2.cs
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/EmbeddedLinkXmlPreservesAdditionalAssemblyWithOverriddenMethod.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
All resolving should happen before TypeMapStep just in case an embedded link xml file were to cause an additional assembly to be included
> Move resolving of embedded link xml files before TypeMapStep

- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedGenericTypeWithPreserveAllHasAllMembersPreserved.cs
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedGenericTypeWithPreserveAllHasAllMembersPreserved.xml
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
We didn't have any link xml tests that used generics.  I thought it would be helpful to have one if for no other reason than to act as documentation on how to format the preservation for a generic type
> Add a preserve test that uses generics

- linker/Linker.Steps/ResolveFromXmlStep.cs
I'd like to reuse these helpers in our resolve from xml step
> Expose some ResolveFromXmlStep members to derived types

- linker/Linker/LinkContext.cs
This change fixes the handle leak if assembly.MainModule.ReadSymbols throws an exception.
> Fix PDB handle leak in the linker.

- linker/Tests/TestCases/TestDatabase.cs
- linker/Tests/TestCases/TestSuites.cs
* Caching all of the TestCases on the first call helps improve nunit test generation time.  AllCases() is called for all of the [TestCaseSource] generation methods.  The call to TestCaseCollector.Collect is a decent amount of work, chancing the result gives a noticable reduction in the delay before tests start running in an IDE based runner
* Remove "OtherTests"  the original idea of this was to catch tests that were not sorted into an existing group.  Code reviews & convention seem to be doing a good enough job of avoiding this.  Given the minimal value OtherTests provides and the fact that it is a relatively routine source of conflicts and boiler plate plumbing, let's remove it.
> Cache collection of all test cases.  Remove OtherTests

- linker/Linker.Steps/LoadI18nAssemblies.cs
- linker/Tests/Mono.Linker.Tests.Cases/CoreLink/CanIncludeI18nAssemblies.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
When running the linker on .NET Framework and processing an assembly against mono class libraries, the LoadI18nAssemblies step would do nothing because it was checking to see if the linker was running on mono rather than if the class libraries being processed were mono class libs.
The test I wrote doesn't cover the scenario I hit.   It's just a basic test to ensure the option works.
> Fix include i18n assemblies not working

- linker/Linker.Steps/MarkStep.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupLinkerKeepDebugMembersAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerDisplayAttributeOnAssemblyUsingTarget.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerDisplayAttributeOnAssemblyUsingTargetOnUnusedType.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerDisplayAttributeOnAssemblyUsingTargetTypeNameInOtherAssembly.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerDisplayAttributeOnType.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerDisplayAttributeOnTypeThatIsNotUsed.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerTypeProxyAttributeOnAssemblyUsingTarget.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerTypeProxyAttributeOnType.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes.Debugger/Dependencies/DebuggerDisplayAttributeOnAssemblyUsingTargetTypeNameInOtherAssembly_Lib.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnAssemblyUsingTarget.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnAssemblyUsingTargetOnUnusedType.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnAssemblyUsingTargetTypeNameInOtherAssembly.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnType.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnTypeThatIsNotUsed.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerTypeProxyAttributeOnAssemblyUsingTarget.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerTypeProxyAttributeOnType.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/TestCases/TestDatabase.cs
- linker/Tests/TestCases/TestSuites.cs
- linker/Tests/TestCasesRunner/LinkerArgumentBuilder.cs
- linker/Tests/TestCasesRunner/TestCaseLinkerOptions.cs
- linker/Tests/TestCasesRunner/TestCaseMetadaProvider.cs
* Adding a test suite for debugger attributes.
* Fixing issue with debugger display attribute Target property being
stripped from assembly-level DebuggerDisplayAttribute instances.
* Updated handling of debugger display attribute types so that neither
the attribute nor the target type are marked if the target is null or
itself not marked.
> Fixes and tests for debugger attribute support in the linker

- linker/Linker.Steps/MarkStep.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/NoSecurity/CoreLibrarySecurityAttributeTypesAreRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/CanLinkCoreLibrariesWithOnlyKeepUsedAttributes.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UnusedAttributeTypeOnMethodIsRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/CoreLink/LinkingOfCoreLibrariesRemovesUnusedTypes.cs
- linker/Tests/Mono.Linker.Tests.Cases/CoreLink/NoSecurityPlusOnlyKeepUsedRemovesAllSecurityAttributesFromCoreLibraries.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/Mono.Linker.Tests.Cases/References/ReferencesAreRemovedWhenAllUsagesAreRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflection.cs
These changes mark types that are kept via reflection Type.GetType()
> Mark Types Used Via Reflection

- linker/Linker/Driver.cs
- linker/Linker/Tracer.cs
Add a finally clause that ensures that dependencies file is
written and resources are disposed if there is an unhandled exception.
> Ensure linker dependencies are properly written and closed.

- corebuild/integration/ILLink.Tasks/Microsoft.NET.Build.Tasks/LockFileCache.cs
Avoid this by using a versioned prefix for the cache key. Of course we will no longer share the read if we happen to be on the same version, but this is safer.
Fixes #308
> Fix LockFileCache when SDK and ILLink  task are using different NuGet dlls

- linker/Linker/TypeNameParser.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflectionAssemblyDoesntExist.cs
- linker/Tests/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflectionLdstrIncomplete.cs
- linker/Tests/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflectionLdstrValidButChanged.cs
- linker/Tests/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflectionTypeDoesntExist.cs
- linker/Tests/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflectionTypeNameIsSymbol.cs
- linker/Tests/Tests/TypeNameParserTests.cs
* Fix crash processing class libs due to type name portion of found ldstr being empty.  Ex: `, System`
* Fix crash that could have happened when closing `]` was missing.  Ex : `A]`
* Fix infinite loop that could have happened when `[]` were out of order.  Ex: `A][`
* Add tests for some other odd scenarios to make sure they behave as expected
> Harden TypeNameParsing to avoid crashes

- linker/Linker.Steps/SweepStep.cs
It's uncommon but, with facades..., an assembly binary can end up with
references to more than one version of an assembly, e.g.
> System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
The existing logic would `return` after processing the first reference,
which means the 2nd reference would remain in the assembly (even if it
was never marked).
This is incorrect and cause issues (for XI) where unreferenced metadata
prevent the caching of some build artifacts - which means further builds
take longer than they should.
> Sweep all, not just the first, referenced assemblies of the same name

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/ReferenceDependencyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/Mono.Linker.Tests.Cases/Symbols/ReferenceWithMdb.cs
- linker/Tests/Mono.Linker.Tests.Cases/Symbols/ReferenceWithMdbAndSymbolLinkingEnabled.cs
- linker/Tests/Mono.Linker.Tests.Cases/Symbols/ReferenceWithMdbCopyAction.cs
- linker/Tests/Mono.Linker.Tests.Cases/Symbols/ReferenceWithMdbCopyActionAndSymbolLinkingEnabled.cs
- linker/Tests/Mono.Linker.Tests.Cases/Symbols/ReferenceWithMdbDeleteAction.cs
- linker/Tests/Mono.Linker.Tests.Cases/Symbols/ReferenceWithMdbDeleteActionAndSymbolLinkingEnabled.cs
- linker/Tests/Mono.Linker.Tests.Cases/Symbols/ReferenceWithPdb.cs
- linker/Tests/Mono.Linker.Tests.Cases/Symbols/ReferenceWithPdbAndSymbolLinkingEnabled.cs
- linker/Tests/Mono.Linker.Tests.Cases/Symbols/ReferenceWithPdbCopyAction.cs
- linker/Tests/Mono.Linker.Tests.Cases/Symbols/ReferenceWithPdbCopyActionAndSymbolLinkingEnabled.cs
- linker/Tests/Mono.Linker.Tests.Cases/Symbols/ReferenceWithPdbDeleteAction.cs
- linker/Tests/Mono.Linker.Tests.Cases/Symbols/ReferenceWithPdbDeleteActionAndSymbolLinkingEnabled.cs
- linker/Tests/Mono.Linker.Tests.Cases/Symbols/ReferencesWithMixedSymbolTypes.cs
- linker/Tests/Mono.Linker.Tests.Cases/Symbols/ReferencesWithMixedSymbolTypesAndSymbolLinkingEnabled.cs
- linker/Tests/TestCasesRunner/TestCaseMetadaProvider.cs
- linker/Tests/TestCasesRunner/TestCaseSandbox.cs
This PR adds better support for referencing a pre-built assembly in a test.  Previously you had to do a round about mechanism such as
```
[Reference ("LibraryWithMdb.dll")]
[SandboxDependency ("Dependencies/LibraryWithMdb/LibraryWithMdb.dll", "input/LibraryWithMdb.dll")]
[SandboxDependency ("Dependencies/LibraryWithMdb/LibraryWithMdb.dll.mdb", "input/LibraryWithMdb.dll.mdb")]
```
This required knowledge of the temporary sandbox directory layout.
Now that same scenario looks like
```
[Reference ("Dependencies/LibraryWithMdb/LibraryWithMdb.dll")]
[ReferenceDependency ("Dependencies/LibraryWithMdb/LibraryWithMdb.dll.mdb")]
```
> Improved sandboxing of prebuilt test assembly dependencies

- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/Mono.Linker.Tests.Cases/TypeForwarding/TypeForwarderOnlyAssemblyCanBePreservedViaLinkXml.cs
- linker/Tests/Mono.Linker.Tests.Cases/TypeForwarding/TypeForwarderOnlyAssemblyCanBePreservedViaLinkXml.xml
- linker/Tests/TestCasesRunner/ResultChecker.cs
Add a test to verify that a forwarder only assembly that would normally be removed due to keep type forwarder only assemblies being false can be preserved using a link.xml file.  This worked correctly without any code changes.
* Allow [KeptTypeInAssembly] to assert exported types.
* Fix an issue in ResultChecker where we could mistakenly resolve an original assembly.  ReaderParameters stores the resolver that is used first, this led to the ExportedType.Resolve() trying to resolve the type in the original assembly.  Using a separate ReaderParameters for original and linked assemblies fixes this issue
> Add a test to verify forwarder can be preserved via xml

- linker/Linker/Annotations.cs
I'm adding some crude diagnostic steps to our linker to dump the state of some of the AnnotationsStore fields.  In order to get to this information, I need the fields to be protected.
I'm mainly interested in `assembly_actions`, `method_actions`, `marked`, and `preserved_types`, but I figured it would be less maintenance to just expose them all in case there's ever another field we'd like to access.
> Expose AnnotationsStore fields to derived types

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupCompileAsLibraryAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupLinkerLinkPublicAndFamilyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/Mono.Linker.Tests.Cases/Libraries/CanLinkPublicApisOfLibrary.cs
- linker/Tests/Mono.Linker.Tests.Cases/Libraries/DefaultLibraryLinkBehavior.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/TestCases/TestDatabase.cs
- linker/Tests/TestCases/TestSuites.cs
- linker/Tests/TestCasesRunner/AssemblyChecker.cs
- linker/Tests/TestCasesRunner/LinkerArgumentBuilder.cs
- linker/Tests/TestCasesRunner/ObjectFactory.cs
- linker/Tests/TestCasesRunner/TestCaseMetadaProvider.cs
- linker/Tests/TestCasesRunner/TestRunner.cs
* Added [SetupCompileAsLibrary] to easily compile a test as a dll
* Added [SetupLinkerLinkPublicAndFamily] to allow for tests to use the -r argument instead of -a for the input test assembly
* Fixed a NullReferenceException in AssemblyChecker that would be thrown if the test assembly didn't have an EntryPoint
> Improved test framework support for dlls

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptAllTypesAndMembersInAssemblyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/Mono.Linker.Tests.Cases/CoreLink/CopyOfCoreLibrariesKeepsUnusedTypes.cs
- linker/Tests/TestCasesRunner/ResultChecker.cs
I need this functionality for something else in our UnityLinker tests so I thought I would add it upstream.
I found an existing testing that could make use of it
> Add [KeptAllTypesAndMembersInAssembly]

- linker/Linker.Steps/MarkStep.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/Mono.Linker.Tests.Cases/Reflection/AssemblyImportedViaReflection.cs
- linker/Tests/Mono.Linker.Tests.Cases/Reflection/AssemblyImportedViaReflectionWithDerivedType.cs
- linker/Tests/Mono.Linker.Tests.Cases/Reflection/AssemblyImportedViaReflectionWithReference.cs
- linker/Tests/Mono.Linker.Tests.Cases/Reflection/Dependencies/AssemblyDependencyWithReference.cs
- linker/Tests/Mono.Linker.Tests.Cases/Reflection/Dependencies/AssemblyImportedViaReflectionWithDerivedType_Base.cs
- linker/Tests/Mono.Linker.Tests.Cases/Reflection/Dependencies/AssemblyImportedViaReflectionWithDerivedType_Reflect.cs
* Remove the logic added to the MarkStep by https://github.com/mono/linker/pull/340.  It had unexpected side effects and more design flaws than initially realized
* Two new tests have been added (but ignored) highlighting some of the additional challenges.
> Remove assembly dependencies imported via reflection logic

- linker/Linker.Steps/MarkStep.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/ComAttributesArePreserved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/ComAttributesAreRemovedWhenFeatureExcluded.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
These com related attributes are needed at runtime.  When the only keep used attributes option is enabled, we need to mark these as long as com is not an excluded feature
> Keep com attributes when only keep used and feature not excluded

- linker/Tests/Mono.Linker.Tests.Cases/Advanced/Dependencies/PreserveDependencyMethodInNonReferencedAssemblyLibrary.cs
- linker/Tests/Mono.Linker.Tests.Cases/Advanced/Dependencies/PreserveDependencyMethodInNonReferencedAssemblyLibrary.xml
- linker/Tests/Mono.Linker.Tests.Cases/Advanced/PreserveDependencyMethodInNonReferencedAssemblyWithEmbeddedXml.cs
- linker/Tests/Mono.Linker.Tests.Cases/Advanced/PreserveDependencyOnUnusedMethodInNonReferencedAssembly.cs
- linker/Tests/Mono.Linker.Tests.Cases/Advanced/PreserveDependencyOnUnusedMethodInNonReferencedAssemblyWithCopyAction.cs
- linker/Tests/Mono.Linker.Tests.Cases/Advanced/PreserveDependencyOnUnusedMethodInNonReferencedAssemblyWithEmbeddedXml.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
* Coverage of unused method with [PreserveDependency]
* Coverage of expected behavior when embedded link xml involved
* Bug found with unused method with [PreserveDependency] causing side effects
> More PreserveDependency tests

- linker/Tests/Mono.Linker.Tests.Cases/Advanced/PreserveDependencyOnUnusedMethodInNonReferencedAssemblyWithCopyAction.cs
When copy mode is used for **any** reference we don't track if the reference is used
or not. We are using `PreserveDependency` with assembly as the way to include reference to assembly which was not added to normal assembly-ref table due to for example circular build issues.
For this we want PreserveDependency copy to behave same as assembly-ref copy. The users have `copyused` option to keep the reference only when used
> Update the test which was testing not the behaviour we want.

- linker/Linker/Pipeline.cs
I'm hooking some profiling code into our linker and the call to IStep.Process() is a nice call to profile.  Exposing a protected member on Pipeline to make this call let's us derive and wrap the call.
> Expose call to IStep.Process

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupLinkerActionAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupLinkerArgumentAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupLinkerCoreActionAttribute.cs
* Simplify string usage in some attributes.  We have a new profile coming that doesn't have some string methods that are used when a switch is used.
* These attributes that were using a switch were technically out of date anyways.  They would have blocked usage of other AssemblyActions, so I don't see a harm in loosening up the error checking
* Adjust another attribute ctor, again, so that fewer members of String are used.
> Expectation attribute changes

- linker/Tests/TestCasesRunner/TestRunner.cs
My original motivation was to pass the sandbox to `AddAdditionalLinkOptions`.  Once I did that, I realized I might as well push all of the argument building down into `AddAdditionalLinkOptions`
I then renamed `AddAdditionalLinkOptions` to `AddLinkOptions` to more accurately reflect it's role
> Adjustments to how linker arguments are built

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptReferenceAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/Mono.Linker.Tests.Cases/References/ReferencesAreRemovedWhenAllUsagesAreRemoved.cs
- linker/Tests/TestCasesRunner/AssemblyChecker.cs
This attribute allows asserting the references that the test case has.
This is a niche attribute I need for the empty assembly thing I'm adding to our UnityLinker.  I'm adding it upstream because we don't do anything to directly assert a reference is removed today.
Given that most tests will never care about asserting references, I made it so that tests don't need to define [KeptAssembly] for all the references they expect to be kept until there is at least 1 of these attributes
> Add ability to assert references on test case assembly

- README.md
Adds examples of all (or almost all) of the ways the link.xml file format can be used to README.md
> Add details of the link xml file format to README.md

- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/Mono.Linker.Tests.Cases/PreserveDependencies/Dependencies/PreserveDependencyMethodInAssemblyLibrary.cs
- linker/Tests/Mono.Linker.Tests.Cases/PreserveDependencies/Dependencies/PreserveDependencyMethodInNonReferencedAssemblyBase.cs
- linker/Tests/Mono.Linker.Tests.Cases/PreserveDependencies/Dependencies/PreserveDependencyMethodInNonReferencedAssemblyBase2.cs
- linker/Tests/Mono.Linker.Tests.Cases/PreserveDependencies/Dependencies/PreserveDependencyMethodInNonReferencedAssemblyChainedLibrary.cs
- linker/Tests/Mono.Linker.Tests.Cases/PreserveDependencies/Dependencies/PreserveDependencyMethodInNonReferencedAssemblyChainedReferenceLibrary.cs
- linker/Tests/Mono.Linker.Tests.Cases/PreserveDependencies/Dependencies/PreserveDependencyMethodInNonReferencedAssemblyLibrary.cs
- linker/Tests/Mono.Linker.Tests.Cases/PreserveDependencies/Dependencies/PreserveDependencyMethodInNonReferencedAssemblyLibrary.xml
- linker/Tests/Mono.Linker.Tests.Cases/PreserveDependencies/Dependencies/PreserveDependencyOnUnusedMethodInNonReferencedAssemblyWithCopyUsedAction_Lib.cs
- linker/Tests/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyField.cs
- linker/Tests/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyMethod.cs
- linker/Tests/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyMethodInAssembly.cs
- linker/Tests/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyMethodInNonReferencedAssembly.cs
- linker/Tests/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyMethodInNonReferencedAssemblyChained.cs
- linker/Tests/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyMethodInNonReferencedAssemblyChainedReference.cs
- linker/Tests/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyMethodInNonReferencedAssemblyWithEmbeddedXml.cs
- linker/Tests/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyOnUnusedMethodInNonReferencedAssembly.cs
- linker/Tests/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyOnUnusedMethodInNonReferencedAssemblyWithCopyUsedAction.cs
- linker/Tests/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyOnUnusedMethodInNonReferencedAssemblyWithEmbeddedXml.cs
- linker/Tests/TestCases/TestDatabase.cs
- linker/Tests/TestCases/TestSuites.cs
This is a growing feature and I think it's worthy of it's own directory to keep it's tests organized.
> Move [PreserveDependency] tests into their own folder

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptInterfaceAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/UnusedAbstractMethodRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/UnusedVirtualMethodRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/UsedOverrideOfAbstractMethodIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/UsedOverrideOfVirtualMethodIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/ClassImplementingInterfaceMethodsNested.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/ClassImplemtingInterfaceMethodsThroughBaseClass2.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/ClassImplemtingInterfaceMethodsThroughBaseClass3.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/ClassImplemtingInterfaceMethodsThroughBaseClass4.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/ClassImplemtingInterfaceMethodsThroughBaseClass5.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/ClassImplemtingInterfaceMethodsThroughBaseClass6.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/ClassUsedFromConcreteTypeHasInterfaceMethodRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/ClassUsedFromInterfaceHasInterfaceMethodKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/TypeGetsMarkedThatImplementsAlreadyMarkedInterfaceMethod.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnValueType/StructImplementingInterfaceMethodsNested.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnValueType/StructUsedFromConcreteTypeHasInterfaceMethodRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnValueType/StructUsedFromInterfaceHasInterfaceMethodKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.VirtualMethods/HarderToDetectUnusedVirtualMethodGetsRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.VirtualMethods/UnusedTypeWithOverrideOfVirtualMethodIsRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.VirtualMethods/UnusedVirtualMethodRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.VirtualMethods/UsedOverrideOfVirtualMethodIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.VirtualMethods/UsedTypeWithOverrideOfVirtualMethodHasOverrideKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.VirtualMethods/VirtualMethodGetsPerservedIfBaseMethodGetsInvoked.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.VirtualMethods/VirtualMethodGetsStrippedIfImplementingMethodGetsInvokedDirectly.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/TestCases/TestDatabase.cs
- linker/Tests/TestCases/TestSuites.cs
* Fixed two tests that should have been using a class instead of a struct
* Broke up VirtualMethods test folder into 4 folders to better make room for new tests that will be coming
* Added some simple tests for abstract classes.
* Allow [KeptInterface] on interfaces
* Add new interface tests, mainly to make use of [KeptInterface] on an interface
> Refactoring of VirtualMethods test suite

- linker/Linker.Steps/OutputStep.cs
File.Copy will preserve permissions and create readonly files.
We should create writeable files instead.
See https://github.com/mono/mono/issues/10743
> [linker] OutputStep should not create readonly files

- linker/Linker.Steps/MarkStep.cs
- linker/Linker/Annotations.cs
- linker/Linker/Driver.cs
- linker/Linker/LinkContext.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/Mono.Linker.Tests.Cases/Statics/ExplicitStaticCtor.cs
- linker/Tests/Mono.Linker.Tests.Cases/Statics/MixedStaticFieldInitializerAndCtor.cs
- linker/Tests/Mono.Linker.Tests.Cases/Statics/StaticFieldInitializer.cs
- linker/Tests/Mono.Linker.Tests.Cases/Statics/UnusedStaticFieldInitializer.cs
When the type is marked with beforefieldinit the static constructor
was generated from static field initializers only. Therefore we
can mark it after any of the static field is marked.
> Optimizes marking of static constructor for beforefieldinit types.

- linker/Linker.Steps/MarkStep.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptAttributeOnFixedBufferTypeAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptFixedBufferAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/FixedLengthArrayAttributesArePreserved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/FixedLengthArrayAttributesArePreserved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/TestCasesRunner/AssemblyChecker.cs
A couple compiler generated attributes should be kept for the runtime when only keep used attributes is enabled
> Preserve attributes for fixed length arrays

- linker/Tests/Mono.Linker.Tests.Cases/Attributes/FixedLengthArrayAttributesArePreserved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/FixedLengthArrayAttributesArePreserved.cs
My PR to add these tests and another PR changed the security attribute behavior.  when the tests ran for both PR's neither had both changes.
It wasn't until both changes landed in master that the tests broke.
> Update FixedBuffer tests

- linker/Linker.Steps/MarkStep.cs
- linker/Linker/Driver.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/Mono.Linker.Tests.Cases/Statics/DisableBeforeFieldInit/UnusedStaticFieldInitializer.cs
* Disabling the option didn't restore the old before 
* ToLower() on the disable opt values so that all lower and/or enum value name works as you would expect
* Refactor static constructor marking in MarkStep.  Centralized logic and fixed if statements not working correctly when the optimization was disabled
* Fixed typo in method name
* Added new test to verify disabling works (test will fail without my changes to the MarkStep and Driver)
> Fix disable before field init not working

- linker/Linker.Steps/RemoveFeaturesStep.cs
- linker/Linker/Annotations.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/RemovedPseudoAttributeAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/ComAttributesAreRemovedWhenFeatureExcluded.cs
Once all the COM attributes are removed we need to set IsImport and IsWindowsRuntime to false since the type is no longer really a com or windows runtime type.
> IsImport and IsWindowsRuntime set to false when COM attrs removed

- linker/Linker.Steps/SweepStep.cs
- linker/Tests/Mono.Linker.Tests.Cases/Basic/UsedEnumIsKept.cs
There's no size value to changing it as far as I'm aware and it forces all tests using an enum to add the `AddedPseudoAttribute` which is one of the less intuitive attributes to have to use so it's nice to keep these to only the niches where they are truly needed
> Don't change BeforeFieldInit on enums

- linker/Tests/Mono.Linker.Tests.Cases/Statics/ExplicitStaticCtor.cs
This eliminates a source of instability in the test where it could fail if compiled with a compiler that put a `nop` into the cctor
> Compile ExplicitStaticCtor with /optimize+

- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/AssemblyWithPreserveAll.cs
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/AssemblyWithPreserveAll.xml
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
There wasn't a test for a link xml with an assembly that has preserve=all.  We document this behavior so I thought it would be good to have a test that explicitly tests this case.
> Add test when assembly preserve all

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptInterfaceOnTypeInAssemblyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/RemovedInterfaceOnTypeInAssemblyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/Mono.Linker.Tests.Cases/TestFramework/CanVerifyInterfacesOnTypesInAssembly.cs
- linker/Tests/Mono.Linker.Tests.Cases/TestFramework/Dependencies/CanVerifyInterfacesOnTypesInAssembly_Lib.cs
- linker/Tests/TestCasesRunner/ResultChecker.cs
Add support for [KeptInterfaceOnTypeInAssembly]
Add support for [RemovedInterfaceOnTypeInAssembly]
With the introduction of interface sweeping there are going to be situations where it is handy to have these attributes.  I have a PR coming that will make use of them.
> Add support for more InAssembly test attributes

- linker/Linker/Tracer.cs
The interface sweeping PR https://github.com/mono/linker/pull/394 introduced some useless information to the dependencies xml.  More detailed explanation here https://github.com/mono/linker/pull/394#issuecomment-434427588
Another PR https://github.com/mono/linker/pull/411 to fix a bug results in another 250+ entries being added with the same useless information.
```
<edge mark="1" b="Method:System.UInt32 System.UInt16::System.IConvertible.ToUInt32(System.IFormatProvider)" e="InterfaceImpl:Mono.Cecil.InterfaceImplementation" />
<edge mark="1" b="Method:System.Int64 System.UInt16::System.IConvertible.ToInt64(System.IFormatProvider)" e="InterfaceImpl:Mono.Cecil.InterfaceImplementation" />
<edge mark="1" b="Method:System.UInt64 System.UInt16::System.IConvertible.ToUInt64(System.IFormatProvider …
```
> Hack to address tracing of interface implemtnations

- linker/Linker.Steps/MarkStep.cs
- linker/Linker.Steps/ResolveFromXmlStep.cs
- linker/Linker/Annotations.cs
I left the existing IsPreserved and GetPreserve methods because I think there are still situations where it is clearer to use those methods instead of TryGetPreserve
> Add Annotations.TryGetPreserve

- linker/Tests/Mono.Linker.Tests.csproj
The Mono.Linker.Tests.Cases project received a version bump in https://github.com/mono/linker/commit/4acf7b132aeff86f4535e1d0b1635d961a0b81c5
Mono.Linker.Tests  references this project and since Mono.LInker.Tests was on 4.6.2 it stopped compiled once Mono.Linker.Tests.Cases bumped to 4.7.1
> Fix test assembly not compiling

- linker/Linker.Steps/MarkStep.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoInstanceCtor/Dependencies/NoInstanceCtorAndAssemblyPreserveAll_Lib.il
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoInstanceCtor/NoInstanceCtorAndAssemblyPreserveAll.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoInstanceCtor/NoInstanceCtorAndAssemblyPreserveAll.xml
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoInstanceCtor/NoInstanceCtorAndTypePreserveAll.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoInstanceCtor/NoInstanceCtorAndTypePreserveAll.xml
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoInstanceCtor/NoInstanceCtorAndTypePreserveFields.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoInstanceCtor/NoInstanceCtorAndTypePreserveFields.xml
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoInstanceCtor/NoInstanceCtorAndTypePreserveFieldsWithInterfacesMarked.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoInstanceCtor/NoInstanceCtorAndTypePreserveFieldsWithInterfacesMarked.xml
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoInstanceCtor/NoInstanceCtorAndTypePreserveMethods.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoInstanceCtor/NoInstanceCtorAndTypePreserveMethods.xml
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoInstanceCtor/NoInstanceCtorAndTypePreserveMethodsWithInterfacesMarked.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoInstanceCtor/NoInstanceCtorAndTypePreserveMethodsWithInterfacesMarked.xml
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoInstanceCtor/NoInstanceCtorAndTypePreserveNone.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoInstanceCtor/NoInstanceCtorAndTypePreserveNone.xml
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
When a type has TypePreserve.All it should retain all of it's interfaces.  This was not happening when the type had no instance constructors.  This is a rare border line invalid edge cases, however, we ran into it and PEVerify says the assembly is valid even though the type has no instance constructors.
This PR adds a check during `InitializeType` to ensure this scenario is handled
Note : This branch won't compile until the following open PR's land
https://github.com/mono/linker/pull/407
https://github.com/mono/linker/pull/406
> Fix an edge case with interface sweeping, no instance ctor, and preserve all

- linker/Linker.Steps/MarkStep.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtor/ExplicitInterfaceCanBeRemovedFromClassWithOnlyStaticMethodUsed.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtor/UnusedTypeHasExplicitInterfaceMethodPreservedViaXml.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtor/UnusedTypeHasExplicitInterfaceMethodPreservedViaXml.xml
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtor/UnusedTypeHasExplicitInterfacePropertyPreservedViaXml.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtor/UnusedTypeHasExplicitInterfacePropertyPreservedViaXml.xml
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtor/UnusedTypeHasInterfaceMethodPreservedViaXml.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtor/UnusedTypeHasInterfaceMethodPreservedViaXml.xml
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/UnusedExplicitInterfaceHasMethodPreservedViaXml.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/UnusedExplicitInterfaceHasMethodPreservedViaXml.xml
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/UnusedExplicitInterfaceIsRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnValueType/UnusedExplicitInterfaceIsRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
If a type somehow (ex: via link.xml) has an explicit interface member marked, then we need to mark the interface implementation for that member.  Otherwise you end up with invalid IL.
The new tests that reproduced the bug were
`UnusedTypeHasExplicitInterfaceMethodPreservedViaXml `
`UnusedTypeHasExplicitInterfacePropertyPreservedViaXml `
The other tests in this PR were added to fill out coverage of expected behavior with explicitly implemented interfaces
> Fix bug with interface sweeping, explicit impl, and xml

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/ExpectBodyModifiedAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/ExpectExceptionHandlersModifiedAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/ExpectLocalsModifiedAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/ExpectedExceptionHandlerSequenceAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/ExpectedInstructionSequenceAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/ExpectedLocalsSequenceAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/Mono.Linker.Tests.Cases/BCLFeatures/ETW/BaseRemovedEventSource.cs
- linker/Tests/Mono.Linker.Tests.Cases/BCLFeatures/ETW/LocalsOfModifiedMethodAreRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/BCLFeatures/ETW/NonEventWithLog.cs
- linker/Tests/Mono.Linker.Tests.Cases/BCLFeatures/ETW/StubbedMethodWithExceptionHandlers.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/Mono.Linker.Tests.Cases/TestFramework/VerifyExpectModifiedAttributesWork.cs
- linker/Tests/Mono.Linker.Tests.csproj
- linker/Tests/TestCasesRunner/AssemblyChecker.cs
- linker/Tests/TestCasesRunner/FormattingUtils.cs
This PR brings a handful of test framework attributes that we have had in the UnityLinker test framework for some time.  It adds support to the test framework for 
* Asserting instructions
* Asserting exception handlers
* Asserting locals
For each collection there are 2 attributes that can be used.  A sequence attribute which can be used for explicit checking.  These can become tedious to maintain and so you generally don't want to use them in any test that is concerned with testing something different.  For these cases there is a general, "expect the value to be different" attribute that you can use.
Also updates some ETW tests to take advantage of these new attributes.
Added new ETW tests for checking locals and exception handlers
> Add attributes for asserting changes to method bodies

- linker/Tests/Mono.Linker.Tests.Cases/BCLFeatures/ETW/Excluded.cs
- linker/Tests/Mono.Linker.Tests.Cases/BCLFeatures/ETW/LocalsOfModifiedMethodAreRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/BCLFeatures/ETW/NonEventWithLog.cs
- linker/Tests/Mono.Linker.Tests.Cases/BCLFeatures/ETW/StubbedMethodWithExceptionHandlers.cs
- linker/Tests/Mono.Linker.Tests.Cases/TestFramework/VerifyExpectModifiedAttributesWork.cs
Compile the tests with /optimize+ to avoid different compilers, or slightly different compiler arguments, producing slightly different IL which can then lead to instruction change asserting differences.
The case I ran across was types such as `LocalsAreCleared_RemovedEventSource` are technically having their `.ctor()` instructions cleared.  We just didn't notice because we add back instructions with the same opcode.
For some reason our tests compiled with a noop in the body, so when the CodeRewriterStep rewrite the body the noop went away and the test failed.
> ETW test tweaks

- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/Mono.Linker.Tests.Cases/Reflection/Dependencies/AssemblyDependency.cs
- linker/Tests/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflectionInDifferentAssembly.cs
I'm helping someone with a reflection usage that doesn't seem to be picked up.  We didn't have a test for their exact usage so I wanted to add one.  It works fine so the issue is something else, but I'd like to keep a test for this exact case since I think it's a common one.
> Add another GetType test

- linker/Linker.Steps/MarkStep.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/Dependencies/InterfaceTypeInOtherUsedOnlyByCopiedAssemblyExplicit_Copy.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/Dependencies/InterfaceTypeInOtherUsedOnlyByCopiedAssemblyExplicit_Link.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/Dependencies/InterfaceTypeInOtherUsedOnlyByCopiedAssembly_Copy.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/Dependencies/InterfaceTypeInOtherUsedOnlyByCopiedAssembly_Link.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/InterfaceTypeInOtherUsedOnlyByCopiedAssembly.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/InterfaceTypeInOtherUsedOnlyByCopiedAssemblyExplicit.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
Fix a bug where interface types would be stripped even when types that implement the interface exist in the output.
This would happen in the following scenario
Assembly `A` implements an interface defined in assembly `B`.  Assembly `A` is assigned `AssemblyAction.Copy` where as assembly `B` is `AssemblyAction.Link`.
When this happens the type in assembly `A` is marked during ResolveFromAssemblyStep.  However, upon getting to the MarkStep `InitializeType` will only mark the fields and methods.  Note that just because the AssemblyAction is copy doesn't mean that types in that assembly will be assigned `TypePreserve.All` As a result, an existing guard in `InitializeType` to mark interface implementations was not helpful.
To fix this, and hopefully reduce the odds of a similar issue, I've …
> Fix interface sweep bug with mix of copy and link assembly actions

- linker/Linker.Steps/OutputStep.cs
When compiling as a library, FileAttributes is ambiguous between System.IO and Mono.Cecil.
> Fix ambiguous FileAttributes

- linker/ILLink.props
See #166 for PR where this is slipped through
> Remove reference to beta .NET Core 2.0 runtime left in the illink.props

- linker/Linker/Annotations.cs
When encounter unknown assemble ruring linking phase,
which happens a lot when working with Blazor, previously IlLink
silently fails without indication what cause the error.
Now displayed name of the offending assembly
> Add diagnostics message for unknown assembly

- linker/Linker.Steps/SweepStep.cs
A hash is used to detect if types have already been resolved. But this cache wasn't consulted for exported typerefs.
This caused duplicate key argument exceptions to be thrown.
I'm not sure if the exported code should be changing the hash since it wasn't used before. But I left it and just added a guard.
> Prevent duplicate keys when resolving typerefs

- linker/Tests/Mono.Linker.Tests.Cases/Basic/UnusedFieldsOfStructsAreKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
There was no test verifying the behavior of marking the fields of a struct once the type is marked
> Add a test for a struct with unused fields

- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptReferencesInAssemblyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/Mono.Linker.Tests.Cases/References/AssemblyOnlyUsedByUsingWithCsc.cs
- linker/Tests/Mono.Linker.Tests.Cases/References/AssemblyOnlyUsedByUsingWithMcs.cs
- linker/Tests/Mono.Linker.Tests.Cases/References/Dependencies/AssemblyOnlyUsedByUsing_Copied.cs
- linker/Tests/Mono.Linker.Tests.Cases/References/Dependencies/AssemblyOnlyUsedByUsing_Lib.cs
- linker/Tests/TestCasesRunner/ResultChecker.cs
@marek-safar I could use your opinion on whether or not you think this is a bug in the linker.
This PR contains just tests to reproduce what I think is a bug.  I did not implement a fix yet.  I wanted to confirm whether or not you think it is a bug before I spend time on a fix.
`AssemblyOnlyUsedByUsingWithCsc` is the test that currently fails and I think it should pass.
What it does is
* Compile an assembly called `library.dll`
* Compile an assembly called `copied.dll` that makes use of `library.dll` with only the following code
```
// This is what triggers the behavior difference between Roslyn and mcs.  Roslyn will keep the reference
// to this assembly because of this whereas mcs will not
using ImportantForBug = Mono.Linker.Tests.Cases.References.Dependencies.AssemblyOnlyUsedByUsing_Lib …
```
> Add tests cover using statement difference between mcs and csc.

- linker/Linker.Steps/MarkStep.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptBaseOnTypeInAssemblyAttribute.cs
- linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- linker/Tests/Mono.Linker.Tests.Cases/CoreLink/DelegateAndMulticastDelegateKeepInstantiatedReqs.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/TestCasesRunner/ResultChecker.cs
Delegate and MulticastDelegate are instantiated from native code which causes us to not record that instances of these types could exist.  As a result, today we remove the interfaces from Delegate.  Removing the interfaces doesn't seem to cause any issues today, but it's probably not the greatest idea.
In the future with base sweeping or uninstantiated type method stubbing, this lack of recording these types as instance possible causes bigger problems.
> Always mark Delegate types as instantiated

- linker/Linker.Steps/MarkStep.cs
- linker/Tests/Mono.Linker.Tests.Cases/Basic/InstantiatedTypeWithOverridesFromObject.cs
- linker/Tests/Mono.Linker.Tests.Cases/Basic/NeverInstantiatedTypeWithOverridesFromObject.cs
- linker/Tests/Mono.Linker.Tests.Cases/CoreLink/InstantiatedTypeWithOverridesFromObject.cs
- linker/Tests/Mono.Linker.Tests.Cases/CoreLink/NeverInstantiatedTypeWithOverridesFromObject.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
The CoreLink version of `InstantiatedTypeWithOverridesFromObject` is the test that triggers the bug. 
Up until this PR, the way Finalize() methods would be marked was via `IsVirtualAndHasPreservedParent`.  Which is to say, once System.Object.Finalize() was marked, all the other FInalize() methods would be marked.  However, given that Finalize() is never explicitly called from managed code, the only way I can think of that Object.FInalize would be marked is via link xml.
With this PR, once the we deem that an instance of a type could exist we will mark the Finalize() method.
> Fix bug with Finalize() being removed

- linker/Linker.Steps/SweepStep.cs
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- linker/Tests/Mono.Linker.Tests.Cases/References/AssemblyOnlyUsedByUsingWithCscWithKeepFacades.cs
While pulling https://github.com/mono/linker/commit/1195feacc5bf27cc7250dec86238caf8682c10a1 into UnityLinker I hit  `AssemblyOnlyUsedByUsingWithCsc` failing with UnityLinker because `copied.dll` still had a reference to `library.dll`.  I did some digging and we keep facades by default where as upstream does not.   This also happens to be why there was no issue on master.  Once you turn on `--keep-facades` the linker will no longer remove the reference.
> Follow up fix for csc quirk

- linker/Linker.Steps/MarkStep.cs
- linker/Tests/Mono.Linker.Tests.Cases/Basic/NeverInstantiatedTypeWithOverridesFromObject.cs
- linker/Tests/Mono.Linker.Tests.Cases/CoreLink/NeverInstantiatedTypeWithOverridesFromObject.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NoKeptCtor/OverrideRemoval/OverrideOfAbstractIsKept.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NoKeptCtor/OverrideRemoval/OverrideOfVirtualCanBeRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NoKeptCtor/OverrideRemoval/OverrideOfVirtualCanBeRemoved2.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NoKeptCtor/OverrideRemoval/OverrideOfVirtualCanBeRemoved3.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NoKeptCtor/OverrideRemoval/OverrideThatAlsoFulfilsInterface.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NoKeptCtor/OverrideRemoval/PreservesOverriddenMethodOverrideOfUsedVirtualStillRemoved.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NoKeptCtor/OverrideRemoval/PreservesOverriddenMethodOverrideOfUsedVirtualStillRemoved.xml
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NoKeptCtor/OverrideRemoval/PreservesOverriddenMethodOverrideOfUsedVirtualStillRemoved2.cs
- linker/Tests/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NoKeptCtor/OverrideRemoval/PreservesOverriddenMethodOverrideOfUsedVirtualStillRemoved2.xml
- linker/Tests/Mono.Linker.Tests.Cases/LinkXml/Dependencies/EmbeddedLinkXmlPreservesAdditionalAssemblyWithOverriddenMethod/Library1.xml
- linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
If no instance of a type can exist, then it's safe to not mark overrides as long as the method being overridden is not abstract.
This change should be good to go.  I've added `WIP` as I'm still running these changes through our il2cpp test suite as that is a valuable way to get some extra coverage on linker changes.
Do not land this branch before https://github.com/mono/linker/pull/454 otherwise there will be problems.
> Override removal

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/Driver.cs
- src/linker/Linker/LinkContext.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NoKeptCtor/OverrideRemoval/CanDisableOverrideRemoval.cs
- test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
Being able to disable this optimization is helpful when trying to troubleshoot problems caused by types created via reflection or from native that do not get an instance constructor marked.
This also gives me the flexibility to pull in the latest `master` without being ready to turn on override removal.
> Add an option to disable override removal

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker.Steps/TypeMapStep.cs
- src/linker/Linker/Annotations.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtorButInterfaceNeeded/LocalAndNestedInterfaces.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtorButInterfaceNeeded/NestedInterfaces1.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtorButInterfaceNeeded/NestedInterfaces2.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtorButInterfaceNeeded/NestedInterfaces3.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtorButInterfaceNeeded/NestedInterfacesWithExplicit1.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtorButInterfaceNeeded/NestedInterfacesWithExplicitAndNormal1.cs
- test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
When processing overrides on a type that is never instantiated, it is only safe to skip marking of an interface method if the interface implementation corresponding to that method is *not* marked *and* no other interface implementations that implement that interface are marked
> Fix invalid IL when inherited interfaces

- test/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptInterfaceAttribute.cs
- test/Mono.Linker.Tests/TestCasesRunner/AssemblyChecker.cs
I'll need support for this in an upcoming PR. 
Follows the same pattern as KeptBaseType's `public KeptBaseTypeAttribute (Type baseType, params object[] typeArguments)`
> Support [KeptInterface] with generics

- NuGet.config
- eng/Signing.props
- eng/azure-pipelines.yml
- src/ILLink.CustomSteps/ILLink.CustomSteps.csproj
- src/ILLink.Tasks/ILLink.Tasks.csproj
This sets up an azure-pipelines build definition to build illink.
- Set certificates to use for signing in our official builds
- Remove dependency on NuGet.ProjectModel. This gets rid of a third-party dependency on Newtonsoft.Json. We shouldn't need the task that was using this (GetRuntimeLibraries) any more if the SDK can tell us which libraries are runtime libraries.
I will also be adding a public build definition (using the same .yml file) for ci on github PRs.
Depends on https://github.com/mono/linker/pull/475.
> Set up Azure Pipelines to build illink

- global.json
- src/ILLink.Tasks/ILLink.Tasks.targets
This will bootstrap the 3.0 SDK and use it to build illink. The targets have been updated in response to some SDK changes, along with a fix for an SDK bug: https://github.com/dotnet/sdk/issues/3007.
> Build and link using 3.0 SDK

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/MethodBodyScanner.cs
We already have this behavior for unresolved methods. This introduces
the same for fields to prevent some more resolution failures in cases
where the assembly containing the field's type is not present at link
time.
> Optionally ignore field resolution errors

- src/linker/Linker/Driver.cs
This will show up in the msbuild output with a higher importance by
default, and may also align more closely with the expectations of
command line users.
@marek-safar the other option is to make this the behavior of monolinker as well. What do you think?
> Write stack traces to stderr

- src/ILLink.Tasks/ILLink.Tasks.nuspec
- src/ILLink.Tasks/LinkTask.cs
- src/linker/ILLink.props
This changes illink to build as a framework-dependent app. Its runtimeconfig.json and deps.json get published in the package, alongside ILLink.Tasks.dll. The ILLink task will now run the linker in a new process, by implementing MSBuild's ToolTask.
This will make it possible to run illink more easily from the command line, and will give us a little more flexibility in the dependencies of illink (since they no longer have to unify with the dependencies of other tasks in the msbuild process).
> Run illink out of process

- eng/azure-pipelines.yml
Some of the options related to signing and publishing needed to be turned off for it to work in the public project. While fixing this I also started using the variable context simplification syntax: https://github.com/Microsoft/azure-pipelines-yaml/blob/04cc3e8d97d1458fb6f43c6129c824e5c156bacf/design/variables.md.
> Fix public build definition

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/InterfaceTypeInOtherUsedOnlyBySavedAssembly.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/InterfaceTypeInOtherUsedOnlyBySavedAssemblyExplicit.cs
- test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
This is similar to https://github.com/mono/linker/pull/430.
We hit the same issue when `AssemblyAction` is `Save` instead of `Copy` since this enum value was missing in `MarkStep.IsFullyPreserved()`.
Note that this needs #496 in order for the test to fail before the fix. @marek-safar suggested I split this in two PRs.
> Fix bug with interface sweeping when AssemblyAction is Save

- test/Mono.Linker.Tests.Cases/Inheritance.Complex/NoKeptCtor/OverrideOfAbstractAndInterfaceMethodWhenInterfaceRemoved.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Complex/NoKeptCtor/OverrideOfAbstractAndInterfaceMethodWhenInterfaceRemoved2.cs
- test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
Add a few complicated tests with interface sweeping and abstract classes involved.  These tests are green on master.  These tests are setup to come close to triggering a new feature I'm working on `lazy body marking`.
I'm also tired of seeing the `Inheritance.Complex` tests showing up in the Solution Explorer as missing.  Adding these tests provides something to run for that set of tests.
> Add a couple new test

- src/linker/Linker/MethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtorButInterfaceNeeded/ParameterAndLocal.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtorButInterfaceNeeded/ParameterOutAndLocal.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtorButInterfaceNeeded/ParameterRefAndLocal.cs
- test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
Fix a bug caused by parameter types not being taken into account in `AllPossibleStackTypes`
> Fix invalid IL bug with interface sweeping due to parameters

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/CoreLink/InstantiatedStructWithOverridesFromObject.cs
- test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
This wasn't causing any issues today.  ValueType is Serializable and that leads to `MarkStep.MarkSerializable` being called, which ensures `ValueType::.ctor()` is marked, which ensures `ValueType` is marked as instantiated.
However, at Unity we have a smaller class library profile that does not have the serializable code.  As a result `ValueType` is not marked as instantiated.  This leads to struct overrides of object members being removed.
Having so much hinge on `ValueType` being Serializable seems fragile.  So rather than depend on that, let's also consider `ValueType` one of the things that should always be marked instantiated if it appears.
> Always consider ValueType instantiated

- test/Mono.Linker.Tests.Cases/Attributes/Mcs/OnlyTypeUsedInAssemblyIsTypeOnAttributeCtorOnAssembly.cs
- test/Mono.Linker.Tests.Cases/Attributes/Mcs/OnlyTypeUsedInAssemblyIsTypeOnAttributeFieldOnAssembly.cs
- test/Mono.Linker.Tests.Cases/Attributes/Mcs/OnlyTypeUsedInAssemblyIsTypeOnAttributePropertyOnAssembly.cs
- test/Mono.Linker.Tests.Cases/CoreLink/CanIncludeI18nAssemblies.cs
- test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- test/Mono.Linker.Tests.Cases/References/AssemblyOnlyUsedByUsingWithMcs.cs
- test/Mono.Linker.Tests.Cases/TestFramework/CanCompileReferencesWithResourcesWithMcs.cs
- test/Mono.Linker.Tests.Cases/TestFramework/CanCompileTestCaseWithMcs.cs
Excluding mcs tests from compilation on .NET Core results in messages like
```
Could not find the matching type for test case /Users/sven/src/dotnet/linker/test/Mono.Linker.Tests.Cases/Attributes/Mcs/OnlyTypeUsedInAssemblyIsTypeOnAttributePropertyOnType.cs.  Ensure the file name and class name match
```
From @mrvoorhe in https://github.com/mono/linker/pull/489#discussion_r268153440:
> 
> 
> That output is to help identify when a test case is named incorrectly. So we really do not want to introduce these.
> 
> I would recommend we leave it how you had it originally. Add the #if NETCOREAPP w/ ignores and let's worry about this later if it becomes an annoyance. @marek-safar Are you OK with that?
> 
See also the discussion at https://github.com/mono/linker/pull/493.
This reverts commit …
> Revert "Disable mcs tests by excluding from compilation"

- eng/azure-pipelines.yml
This fixes an issue with the official build definition.
The build number was not being set correctly because `variables['Build.BuildNumber']` is not available during the early phase of pipeline processing.
Also adds a missing displayName for the macOS job.
Fixes https://github.com/mono/linker/issues/503.
> Fix build definition

- Directory.Build.targets
- after.illink.sln.targets
- illink.sln
- test/ILLink.Tasks.Tests/CommandRunner.cs
- test/ILLink.Tasks.Tests/HelloWorldTest.cs
- test/ILLink.Tasks.Tests/IntegrationTestBase.cs
- test/ILLink.Tasks.Tests/Loggers.cs
- test/ILLink.Tasks.Tests/MusicStoreTest.cs
- test/ILLink.Tasks.Tests/TestContext.cs
- test/ILLink.Tasks.Tests/WebApiTest.cs
- test/ILLink.Tasks.Tests/nuget/NuGet.config
- test/ILLink.Tasks.Tests/test.csproj
- test/ILLink.Tasks.Tests/xunit.runner.json
This moves to using the arcade-restored dotnet in our integration tests, and reacts to changes in the directory layout. The project setup logic has been moved into xunit fixtures (see the commit message in https://github.com/mono/linker/commit/01e638038516f29c3aff3390fdb5df91f993cf04).
This does not attempt to address test failures due to SDK changes. These tests won't run in ci (yet).
> Update integration test infrastructure

- test/Mono.Linker.Tests.Cases/LinkXml/UnusedMethodPreservedByLinkXmlIsKept.cs
- test/Mono.Linker.Tests.Cases/LinkXml/UnusedMethodPreservedByLinkXmlIsKept.xml
Add a link xml test that preserves a method with a generic parameter.  Adding mostly as an example of the string to put in the `signature` xml attribute
> Add another link xml test

- src/linker/Linker.Steps/LoadI18nAssemblies.cs
- src/linker/Linker.Steps/ResolveFromAssemblyStep.cs
When a custom link action for an assembly is passed to the linker on the commandline we'd override it with `Copy` in `ProcessLibrary`. Instead we now check whether we already have an assembly action before setting it.
`LoadI18nAssemblies` used this to force `Copy` on the I18N assemblies by calling `ProcessLibrary` with `RootVisibility.Any` so we need to set the assembly action explicitly to maintain that behavior.
> Fix overriding assembly action in ResolveFromAssemblyStep.ProcessLibrary

- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/BaseProvidesInterfaceMember/GenericInterfaceWithGenericBaseMethod.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/BaseProvidesInterfaceMember/GenericInterfaceWithMethodComplex.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/BaseProvidesInterfaceMember/GenericInterfaceWithMethodComplex2.cs
The .netcore testing PR started filtering out the Debuggable attribute when asserting.  One of my PR's that had been open needed to be updated to account for this behavior change.
> Fix test failures on master

- src/linker/Linker.Steps/ResolveFromAssemblyStep.cs
- src/linker/Linker/LinkContext.cs
* Rename `LinkContext.SetAction` to `LinkContext.SetActionToDefault` since that's what it is actually doing.  Setting the action to the specified user or core action.
* Add a new `LinkContext.SetAction` that will ensure the assembly is registered and has SafeReadSymbols called.  I hit an issue in our linker where I had early phase steps calling `context.Annotations.SetAction`.  If you call that directly you can get into a situation where `RegisterAssembly` does not call `SafeReadSymbols` because `SeenFirstTime` is returning true.  And when that happens, you end up breaking symbol linking for that assembly.  My hope is that this new `LinkContext.SetAction` is a slightly less error prone way of setting the action on assembly in a step that runs before `LoadReferenceStep`
> Clean up SetAction a little

- src/linker/Linker.Steps/ResolveFromAssemblyStep.cs
For some reason the linker logic in Xamarin.iOS relies on  `ResolveFromAssemblyStep.ProcessLibrary()` to overwrite the assembly action. If we don't do that it'd link an assembly that should really be copied.
I couldn't yet figure out how to fix this so best to revert this change (it was mostly needed to write a test for https://github.com/mono/linker/pull/497 but I didn't get to that yet).
Partially reverts 9b26a0973a5439ab79135ba826c539768ed7455c.
> Revert changes from https://github.com/mono/linker/pull/496

- src/linker/Linker.Steps/SweepStep.cs
- test/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/CanLinkCoreLibrariesWithOnlyKeepUsedAttributes.cs
- test/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/CoreLibraryUnusedAssemblyAttributesAreRemoved.cs
- test/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/CoreLibraryUsedAssemblyAttributesAreKept.cs
- test/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/Dependencies/AssemblyWithUnusedAttributeOnReturnParameterDefinition.il
- test/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UnusedAttributeOnReturnTypeIsRemoved.cs
- test/Mono.Linker.Tests.Cases/CoreLink/NoSecurityPlusOnlyKeepUsedRemovesAllSecurityAttributesFromCoreLibraries.cs
The introduction of `MethodWithoutParameters()` in this test causes the linker to write invalid IL. When the linker sweeps this method, a bug causes it to keep the attribute on the return type parameter. However, the attribute type itself is removed (causing it to become detached from its declaring type).
https://jenkins.mono-project.com/job/test-linker-pull-request/759/console:
```
09:58:19 1) Failed : Mono.Linker.Tests.TestCases.All.OnlyKeepUsed.UnusedAttributeOnReturnTypeIsRemoved
09:58:19 Invalid IL detected in /tmp/linker_tests/output/library.dll
09:58:19 FAIL: Invalid CustomAttribute row 0 Type field 0x00000022
09:58:19 Error count: 1
09:58:19 at Mono.Linker.Tests.TestCasesRunner.PeVerifier.CheckAssembly (Mono.Linker.Tests.Extensions.NPath assemblyPath) [0x00099] in …
```
> Fix attribute sweep bug and enable more tests on .NET Core

- test/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UnusedAttributeOnReturnTypeIsRemoved.cs
- test/Mono.Linker.Tests.Cases/TestFramework/CanCompileILAssembly.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/MissingTargetReference.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestCaseCompiler.cs
These tests were failing because the .il files depend
on mscorlib without a version, and roslyn was looking for Object in
mscorlib, Version=0.0.0.0 as a result. This doesn't happen when using
csc from the command line because csc uses a different assembly
identity comparer by default: DesktopAssemblyIdentityComparer (even on
.NET Core).
```
Failed   MissingTargetReference
Error Message:
System.AggregateException : One or more errors occurred. (Roslyn compilation errors: (19,4): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
)
----> System.Exception : Roslyn compilation errors: (19,4): error CS0012: The type 'Object' is defined in an assembly that is …
```
> Fix IL Compilation tests on .NET Core

- src/ILLink.Tasks/LinkTask.cs
When publishing a framework-dependent .NET Core app, the framework
implementation is not available during publish, and is represented to
the compiler by reference assemblies. Conceptually, reference
assemblies only represent surface area for compilation. Their
implementations can vary depending on the platform where the app is
eventually run.
There's no good way to detect whether an assembly is a reference
assembly. "True" reference assemblies will have a
ReferenceAssemblyAttribute, but the SDK's ReferencePath ItemGroup will
often contain implementation assemblies that are passed to the
compiler as references.
Ideally the linker would be able to resolve types defined in reference
assemblies without looking at IL they contain. For now, we just pass
along any reference assemblies that …
> Add ReferenceAssemblyPaths input to linker task

- test/Mono.Linker.Tests.Cases/Symbols/ReferenceWithPdbCopyActionAndSymbolLinkingEnabled.cs
The test was failing on non-windows, because it was trying and failing to save native PDBs.
```
Failed   ReferenceWithPdbCopyActionAndSymbolLinkingEnabled
Error Message:
Missing symbols for assembly `/var/folders/1g/pkblpwxd49g9gg1x80g1gddm0000gn/T/linker_tests/output/LibraryWithPdb.dll`
Stack Trace:
at Mono.Linker.Tests.TestCasesRunner.ResultChecker.VerifyKeptSymbols(CustomAttribute symbolsAttribute) in /Users/sven/src/dotnet/linker/test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs:line 140
at Mono.Linker.Tests.TestCasesRunner.ResultChecker.PerformOutputSymbolChecks(AssemblyDefinition original, NPath outputDirectory) in /Users/sven/src/dotnet/linker/test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs:line 127
at Mono.Linker.Tests.TestCasesRunner.ResultChecker.Check(LinkedTestCas …
```
> Enable native PDB copy on Windows for .NET Core

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/Dependencies/TypeWithBaseInCopiedAssembly2_Base.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/Dependencies/TypeWithBaseInCopiedAssembly3_Base.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/Dependencies/TypeWithBaseInCopiedAssembly4_Base.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/Dependencies/TypeWithBaseInCopiedAssembly6_Base.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/Dependencies/TypeWithBaseInCopiedAssembly_Base.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NotKeptCtor/NeverInstantiatedTypeWithBaseInCopiedAssembly.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NotKeptCtor/NeverInstantiatedTypeWithBaseInCopiedAssembly2.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NotKeptCtor/NeverInstantiatedTypeWithBaseInCopiedAssembly3.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NotKeptCtor/NeverInstantiatedTypeWithBaseInCopiedAssembly4.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NotKeptCtor/NeverInstantiatedTypeWithBaseInCopiedAssembly5.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NotKeptCtor/NeverInstantiatedTypeWithBaseInCopiedAssembly6.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/TypeWithBaseInCopiedAssembly.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/TypeWithBaseInCopiedAssembly2.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/TypeWithBaseInCopiedAssembly3.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/TypeWithBaseInCopiedAssembly4.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/TypeWithBaseInCopiedAssembly5.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/TypeWithBaseInCopiedAssembly6.cs
- test/Mono.Linker.Tests.Cases/Inheritance.VirtualMethods/Dependencies/TypeWithBaseInCopiedAssembly_Base.cs
- test/Mono.Linker.Tests.Cases/Inheritance.VirtualMethods/NotKeptCtor/NeverInstantiatedTypeWithBaseInCopiedAssembly.cs
- test/Mono.Linker.Tests.Cases/Inheritance.VirtualMethods/TypeWithBaseInCopiedAssembly.cs
- test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
The test `NeverInstantiatedTypeWithBaseInCopiedAssembly` is the case that would hit an invalid IL bug.
Essentially what this PR does is 
* Establishes two variations of the old `IsVirtualAndHasPreservedParent`.
* Restores the call to `IsVirtualAndHasPreservedParent` that used to be in `MarkType`
`IsVirtualNeededByTypeDueToPreservedScope` is the new variation.  This is the one that will be called during `MarkType` like we used to do before never instantiated interface sweeping landed.  This variation is updated to play nice with never instantiated interface sweeping.
`IsVirtualNeededByInstantiatedTypeDueToPreservedScope` is a rename of `IsVirtualAndHasPreservedParent`
The bug fix is restoring the `MarkMethodsIf (type.Methods, IsVirtualNeededByTypeDueToPreservedScope);` in `MarkType`
And …
> Fix a bug with preserve parent

- src/ILLink.Tasks/ILLink.Tasks.csproj
- src/ILLink.Tasks/ILLink.Tasks.nuspec
Fixes build issue with arcade update (https://github.com/mono/linker/pull/523). Since we are still using our own
.nuspec (rather than letting the nuget targets generate one), we also
need to specify the license in our custom .nuspec.
> Use PackageLicenseExpression

- src/linker/Linker.Steps/MarkStep.cs
We have a class library profile that doesn't support exceptions.  In order for MethodAction.ConvertToThrow to work with this profile I will need to be able to override enough of the pieces so that I can inject Environment.FailFast instead of throw new exception.
> Enable override of marking convert to throw exception

- test/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupLinkerArgumentAttribute.cs
Some tests landed that do this (I wrote them :) ).  It's not great to throw from an attribute ctor anyways.  Some tools will cover it up, others won't.
> Don't block usage of 1 char args

- test/Mono.Linker.Tests.Cases/Attributes/AssemblyAttributeKeptInComplexCase.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NotKeptCtor/NeverInstantiatedTypeWithBaseInCopiedAssembly2.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NotKeptCtor/NeverInstantiatedTypeWithBaseInCopiedAssembly3.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NotKeptCtor/NeverInstantiatedTypeWithBaseInCopiedAssembly4.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NotKeptCtor/NeverInstantiatedTypeWithBaseInCopiedAssembly5.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NotKeptCtor/NeverInstantiatedTypeWithBaseInCopiedAssembly6.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/TypeWithBaseInCopiedAssembly2.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/TypeWithBaseInCopiedAssembly3.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/TypeWithBaseInCopiedAssembly4.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/TypeWithBaseInCopiedAssembly5.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/TypeWithBaseInCopiedAssembly6.cs
- test/Mono.Linker.Tests.Cases/UnreachableBody/DoesNotApplyToCopiedAssembly.cs
- test/Mono.Linker.Tests.Cases/UnreachableBody/DoesNotApplyToSavedAssembly.cs
- test/Mono.Linker.Tests.Cases/UnreachableBody/LinkedOtherIncludedLibrary.cs
Avoid random failures that can occur due to https://github.com/dotnet/roslyn/issues/33320 on macOS when roslyn server mode is used.
> Workaround roslyn bug

- src/ILLink.Tasks/LinkTask.cs
LinkTask invocation involving long-paths (with spaces) failed because
the arguments to dotnet.exe Illink.dll are not within quotes.
This change fixes the problem.
Ideally, the LinkTask should use a response file, instead of the long
command line. However, dotnet.exe currently doesn't support response files.
https://github.com/dotnet/cli/issues/7657
> Handle long paths in ILLink.Tasks LinkTask

- eng/Versions.props
- src/ILLink.Tasks/ILLink.Tasks.csproj
This updates ILLink.Tasks to reference the same version of `System.Reflection.Metadata` and msbuild packages as the SDK, and includes SRM in the package for desktop, the same way that `Microsoft.NET.Build.Tasks` does it.
@nguerrera PTAL.
> Match sdk versions

- src/ILLink.Tasks/ILLink.Tasks.csproj
With the latest cecil update in https://github.com/mono/linker/pull/471, we are using SDK-style projects and building cecil for netstandard2.0, so the workaround for https://github.com/dotnet/sdk/issues/3194 is no longer necessary.
> Remove DiagnosticSource packaging workaround

- eng/Version.Details.xml
- eng/common/PublishToPackageFeed.proj
- eng/common/cross/arm64/sources.list.buster
- eng/common/cross/arm64/sources.list.stretch
- eng/common/cross/build-rootfs.sh
- eng/common/darc-init.ps1
- eng/common/darc-init.sh
- global.json
- src/linker/Linker.Steps/SweepStep.cs
- test/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/Dependencies/AssemblyWithUnusedAttributeOnGenericParameter.il
- test/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UnusedAttributeOnGenericParameterIsRemoved.cs
- test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- test/Mono.Linker.Tests/TestCases/IndividualTests.cs
This fixes test failures that show up due to NullableAttribute with recent versions of .NET Core (see the failures in https://github.com/mono/linker/pull/570). This should unblock the dependency uptake.
> Sweep attributes on GenericParameters and InterfaceImplementations

- src/linker/Linker/LinkContext.cs
Cecil throws a BadImageFormatException when trying to read assemblies with no CIL section.  This turns that exception into a AssemblyResolutionException and includes the assembly name in the information in the exception.
```
Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: '/Users/lewing/.nuget/packages/runtime.win-x86.runtime.native.system.data.sqlclient.sni/4.4.0/runtimes/win-x86/native/sni.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' ---> System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
at Mono.Cecil.PE.ImageReader.ReadOptionalHeaders(UInt16& subsystem, UInt16& dll_characteristics) in /Users/lewing/Source/linker/external/cecil/Mono.Cecil.PE/ImageReader.cs:line 199
at …
```
> Rethrow exceptions in Resolve as AssemblyResolutionException 

- src/linker/Linker.Steps/ResolveFromAssemblyStep.cs
- src/linker/Linker/LinkContext.cs
When rooting assemblies via '-a' or '-r', ResolveFromAssemblyStep sets a default action depending on whether the assembly is a library or exe. This default takes precedence over any assembly action passed for that assembly via the command line using '-p <action> <assemblyname>'.
This change makes it possible to override the default assembly action even for root assemblies.
This is useful especially in cases (like we want to do for .NET Core) where we'd like to choose a conservative default that keeps the entire app assembly, only trimming framework code.
@marek-safar PTAL
> Allow overriding assembly action on root assemblies

- src/ILLink.Tasks/LinkTask.cs
- src/linker/Linker/AssemblyResolver.cs
- src/linker/Linker/DirectoryAssemblyResolver.cs
- src/linker/Linker/Driver.cs
This introduces a command-line option, "-reference <file>", which makes it possible to give the linker full assembly paths to resolve.
LinkTask now uses "-reference" instead of "-d", to prevent the directory resolution behavior from finding dependencies next to inputs. Now it takes an explicit list of inputs, which will be the only files it resolves.
When passing along full paths to each file, the command-line becomes substantially longer. To prevent hitting command length limits, arguments are now passed via a response file (using ToolTask's GenerateResponseFileCommands).
This fixes issues like that mentioned in https://github.com/dotnet/coreclr/issues/24397#issuecomment-490807112 when trying to link WPF apps, which have a `WindowsBase.dll` in the core framework directory and also in the …
> Resolve assemblies from specific paths

- src/ILLink.Tasks/LinkTask.cs
Left-over from https://github.com/mono/linker/pull/567/files. I believe this is what's causing https://github.com/dotnet/coreclr/issues/24397#issuecomment-495720076. @marek-safar PTAL
> Use "-reference" in LinkTask

- monolinker.sln
I don't know why the cecil csproj's were removed from monolinker.sln, but the solution wouldn't build in Rider w/out the cecil csproj files in the solution.
VS2019 can build monolinker.sln with these changes
> Add cecil csproj's back to monolinker.sln

- test/Mono.Linker.Tests.Cases/CommandLine/Mvid/DefaultMvidBehavior.cs
- test/Mono.Linker.Tests.Cases/CommandLine/Mvid/DeterministicMvidWorks.cs
- test/Mono.Linker.Tests.Cases/CommandLine/Mvid/NewMvidWorks.cs
- test/Mono.Linker.Tests.Cases/CommandLine/Mvid/RetainMvid.cs
- test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- test/Mono.Linker.Tests/TestCases/IndividualTests.cs
- test/Mono.Linker.Tests/TestCasesRunner/LinkedTestCaseResult.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestRunner.cs
A number of changes to command line options related to assembly mvid's have been made recently and no tests were added.  This PR adds tests and also makes it easier to write tests for changes such as https://github.com/mono/linker/pull/583
> Add mvid tests

- src/linker/Linker/Driver.cs
This was being interpreted as '-r'. @marek-safar PTAL.
> Fix processing of -reference argument

- src/linker/Linker.Steps/RemoveFeaturesStep.cs
- src/linker/Linker/Driver.cs
When `--exclude-feature sre` is provided, then we rewrite the `System.RuntimeType.MakeTypeBuilderInstantiation` to throw.
> Add custom logic for reflection-emit to RemoveFeaturesStep.

- test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- test/Mono.Linker.Tests.Cases/Symbols/ReferenceWithEmbeddedPdbAndSymbolLinkingEnabledAndDeterministicMvid.cs
- test/Mono.Linker.Tests.Cases/Symbols/ReferenceWithEmbeddedPdbAndSymbolLinkingEnabledAndNewMvid.cs
- test/Mono.Linker.Tests.Cases/Symbols/ReferenceWithMdbAndSymbolLinkingEnabledAndDeterministicMvid.cs
- test/Mono.Linker.Tests.Cases/Symbols/ReferenceWithMdbAndSymbolLinkingEnabledAndNewMvid.cs
- test/Mono.Linker.Tests.Cases/Symbols/ReferenceWithPdbAndSymbolLinkingEnabledAndDeterministicMvid.cs
- test/Mono.Linker.Tests.Cases/Symbols/ReferenceWithPdbAndSymbolLinkingEnabledAndNewMvid.cs
- test/Mono.Linker.Tests.Cases/Symbols/ReferenceWithPortablePdbAndSymbolLinkingEnabledAndDeterministicMvid.cs
- test/Mono.Linker.Tests.Cases/Symbols/ReferenceWithPortablePdbAndSymbolLinkingEnabledAndNewMvid.cs
The test for mdb + deterministic mvid and portable pdb + deterministic mvid had to be ignored because they encounter https://github.com/jbevain/cecil/issues/583
> Add tests for mvid options and symbol files

- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
We are hitting ever more complex scenarios in our linker.  I'm finding that I'd rather know that the IL was valid before worrying about getting all the types, methods, etc correctly annotated with [Kept] attributes.
In our linker test framework we have extra attributes to allow for the cases to be executed and the output asserted.  `InitialChecking` will be the place where we do that.  Again, I'd rather see these failures first before I invest the time correctly annotating the kept attributes.
> Adjust how tests are asserted

- src/linker/Linker.Steps/RemoveFeaturesStep.cs
Rationale: allow dynamic removal (as it without rebuilding corlib) of some of the globalization code when `--exclude-feature globalization` is provided.
Currently removes the Japanese, Taiwan and Hebrew calendars as well as Hebrew numbers.
This requires https://github.com/mono/corefx/pull/298 and https://github.com/mono/mono/pull/14825.
We are using the same techinique as previously employed in https://github.com/mono/linker/pull/590 to dynamically remove the `System.Reflection.Emit` code.
Since the linker does not currently support dead code elimination, it cannot break down any conditionals inside method bodies.  One trick that we use to work around this is to move those conditional pieces into separate methods; then we can give the linker a list of those methods and tell it to replace …
> Allow some Globalization code to be dynamically removed.

- .github/CODEOWNERS
I think the reason the codeowners hasn't been working is because the directory paths need to end with a `/`
> Try to fix codeowners

- src/ILLink.Tasks/Utils.cs
This will skip linking of C++/CLI assemblies. See https://github.com/mono/linker/issues/651 for context.
There are potentially some issues with skipping the C++/CLI assembly entirely - any calls that the assembly makes to .NET dlls will no longer be analyzed. This may result in some required dependencies being dropped, though I don't know how likely that is in practice. The ideal fix would be to address https://github.com/mono/linker/issues/639 (or to preserve the ordering of the relevant C++/CLI data when linking as mentioned in https://github.com/mono/linker/issues/651#issuecomment-510689413), which would still result in the assembly being analyzed.
I marked this do not merge until we have some more confidence that this is the right fix.
> Skip C++/CLI assemblies

- src/linker/Linker.Steps/BlacklistStep.cs
- test/Mono.Linker.Tests.Cases/LinkXml/Dependencies/EmbeddedLinkXmlFromCopyAssemblyIsProcessed/CopyLibrary.cs
- test/Mono.Linker.Tests.Cases/LinkXml/Dependencies/EmbeddedLinkXmlFromCopyAssemblyIsProcessed/CopyLibrary.xml
- test/Mono.Linker.Tests.Cases/LinkXml/Dependencies/EmbeddedLinkXmlFromCopyAssemblyIsProcessed/OtherLibrary.cs
- test/Mono.Linker.Tests.Cases/LinkXml/EmbeddedLinkXmlFromCopyAssemblyIsProcessed.cs
- test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
The embedded xml files should be respected from copy assemblies the same way they are for link assemblies. I'm actually not sure why we respect them for AddBypassNGenUsed - I would expect that for assemblies that do not end up being used (even if they have action CopyUsed or AddBypassNGenUsed), we don't add roots from xml.
Necessary to make https://github.com/dotnet/wpf/pull/1387 work. We're adding roots to WPF assemblies to work around the linker's inability to process C++/CLI assemblies (https://github.com/mono/linker/pull/658).
@marek-safar PTAL.
> Respect embedded xml files from copy assemblies

- test/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/MethodWithUnmanagedConstraint.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestCaseCompiler.cs
Only added a test for when used-attrs-only is used for 2 reasons
1) That's the more interesting scenario
2) Annotating all of the compiler generated types that would survive without used-attrs-only is not possible with the current test framework abilities
> Add a test with an unmanaged constraint

- src/ILLink.Tasks/LinkTask.cs
- src/linker/Linker.Steps/ResolveFromXmlStep.cs
- src/linker/Linker/AssemblyResolver.cs
- src/linker/Linker/LinkContext.cs
src/ILLink.Tasks/LinkTask.cs – Increase Standard Error output logging importance so default verbosity is able to print it
src/linker/Linker/AssemblyResolver.cs – Include a warning message for
suspicious series of common punctuation characters in assembly names,
although supported they are likely typos in assembly names. Warning is
only printed upon failure.
src/linker/Linker/LinkContext.cs – skip assembly if it’s null (means is
an unresolved assembly and skip flag was used)
src/linker/Linker.Steps/ResolveFromXmlStep.cs – skip assembly if it’s
null (means is an unresolved assembly and skip flag was used)
See issue #653 for more information
> Improve Error Experience in the linker

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker.Steps/SweepStep.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/AttributeArgumentForwarded.cs
Adds traversing of all CA values. Fixes #737
> Move CustomAttributes scope updating to sweep step to update only needed ones

- eng/Versions.props
Arcade no longer recommends using RestoreSources, and it was causing problems (it was restoring only from these sources, when it should have been taking sources from NuGet.config). Removing RestoreSources fixes it.
edit: I need to look into the ci failures.
> Remove RestoreSources

- test/Mono.Linker.Tests.Cases/Attributes/TypeUsedInObjectArrayConstructorArgumentOnAttributeIsKept.cs
It turns out we fixed the same issue as https://github.com/mono/linker/commit/0fd66c9d65da4f60be46d178070d347df296fe4e around the same time it was fixed upstream.  Our test in the UnityLinker code base was slightly different however.  It used params.  Since upstream doesn't have any tests that use params I figured it wouldn't hurt to upstream the test we had.
> Add attribute test that uses params

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnValueType/StructWithNestedStructImplementingInterface.cs
The linker `MarkStep` can add new types with interfaces while processing
the existing types with interfaces. Make a copy of the collection to
avoid modifying it while it is being iterated.
> Handle types with interfaces added later

- src/linker/Linker.Steps/OutputStep.cs
This fixes a failure on Xamarin.Android
> Overwrite when copying satellite assemblies

- test/Mono.Linker.Tests.Cases/TypeForwarding/AttributeArgumentForwarded.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/AttributeArgumentForwardedWithCopyAction.cs
Fix two type forwarding tests.  On .NET FW the built in compiler will drop the reference to the forwarder assembly when compiling the test assembly.  Use roslyn to give consistent behavior across platforms
> Test fixes

- src/linker/Linker/AssemblyResolver.cs
I added the word Ignoring to the unresolved assembly log message for PR https://github.com/mono/linker/pull/719, but I also delete the warning word section which is useful since it can be printed using the --verbose flag in the linker options, adding it again.
> Add warning before Log message

- src/linker/Linker.Steps/SweepStep.cs
We have tests that use nunit, which leads to System.Windows.Forms being processed which leads to an attempt at resolving some type that is in `WindowsBase`.  I don't think it matters that we failed to resolve these types here.  Just ignore and continue.
> Don't crash on unresolved assembly

- src/linker/Linker.Steps/MarkStep.cs
We have a use case where we want to disable the explicit marking of of finalize methods.  I thought a general purpose hook to allow for modifying the collection of methods that are required on types that are instantiated would be a good way to go about this.
> Allow derived mark steps to change required methods

- src/linker/Linker.Steps/SweepStep.cs
Trying to change the scope of a projection results in a exception`System.InvalidOperationException : Projected type scope can't be changed`, so let's skip these.
> Don't try to change scope of windows runtime projection

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/ComponentModel/TypeDescriptionProviderAttributeOnType.cs
> Add TypeDescriptionProviderAttribute detection

- src/linker/Linker.Steps/ClearInitLocals.cs
I validated this change by recompiling, injecting back into the _coreclr_ build, and verifying that methods like `System.Text.Encoding.UTF8Encoding+UTF8EncodingSealed.get_Preamble` and `System.Collections.Generic.List<T>+Enumerator.MoveNext` have the _.locals init_ flag stripped.
For some reason I'm having trouble building the entire linker solution locally instead of this one particular project, so I haven't been able to perform regression testing outside this one very specific scenario.
> Update ClearInitLocals to also inspect nested types

- src/linker/Linker.Steps/MarkStep.cs
Added a callback that can be overridden so we can suppress warnings on instructions that have already been handled.
Also allows for checking reflection calls like `GetMethod()` and `GetConstructor()` that include parameter arrays, so we can mark only methods with matching parameters.
> Add callback for handling marking reflection calls

- src/linker/Linker.Steps/MarkStep.cs
We don't care about these type converter like dependencies.  Exposing this method for overriding is an easy way for us to disable the behavior
> Allow overriding of MarkTypeConverterLikeDependency

- test/Mono.Linker.Tests.Cases/Basic/UsedGenericInterfaceIsKept.cs
- test/Mono.Linker.Tests/TestCasesRunner/AssemblyChecker.cs
Since `[RequiredInterface]` does not allow type parameters when passing a generic interface, we need to do type resolution on the interface when comparing for marking.
> Resolve interfaces when checking KeptInterface attribute so that generic interfaces can be marked.

- .editorconfig
When using VS these new settings make VS automatically format the code the way the rest of the linker is written.
Note that linker itself is not always 100% consistent, but it's close.
> Add C# specific settings to .editorconfig.

- test/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflection.cs
Could not find a test which would explicitly verify that if a type is referenced via token (so basically `typeof(type)`), linker will mark it to be kept. So added one.
> Add a simple test for typeof(type)

- .gitignore
- eng/azure-pipelines.yml
- monobuild/Makefile
- test/Mono.Linker.Tests/Mono.Linker.Tests.csproj
- test/Mono.Linker.Tests/packages.config
We can easily replace the Jenkins build with one on Azure Pipelines now.
> Add Linux Mono build to Azure Pipeline

- src/linker/Linker/Annotations.cs
- src/linker/Linker/Driver.cs
- src/linker/Linker/IDependencyResolver.cs
- src/linker/Linker/Tracer.cs
- src/linker/Linker/XmlDependencyRecorder.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/DependencyRecordedAttribute.cs
- test/Mono.Linker.Tests.Cases/Tracing/DependencyRecorder/BasicDependencies.cs
- test/Mono.Linker.Tests/TestCases/IndividualTests.cs
- test/Mono.Linker.Tests/TestCases/TestDatabase.cs
- test/Mono.Linker.Tests/TestCases/TestSuites.cs
- test/Mono.Linker.Tests/TestCasesRunner/LinkedTestCaseResult.cs
- test/Mono.Linker.Tests/TestCasesRunner/LinkerCustomizations.cs
- test/Mono.Linker.Tests/TestCasesRunner/LinkerDriver.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestCaseMetadaProvider.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestDependencyRecorder.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestRunner.cs
Adds ;IDependencyRecorder; which separates the linker/tracer from the actual implementation which stores the dependencies.
Implements the default XML writer for the dependencies (should produce exactly the same output as before the change).
Adds test infra to test the dependency recorder directly (as a test mock) and a simple test.
Motivation: Future analyzers need to have visibility into the dependency analysis (MarkStep basically) to report what caused a given method/type to be included. We already expose this information through the dependency XML, this just adds an API to do this programatically.
> Add abstraction between the linker and the dependency tracing/recording.

- eng/azure-pipelines.yml
- src/ILLink.Tasks/ILLink.Tasks.csproj
Following https://github.com/dotnet/arcade/pull/4556
I ran an internal build with these changes here: https://dev.azure.com/dnceng/internal/_build/results?buildId=463049&view=results
> Move to new arcade publishing using yaml stages

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/References/CopyUsedAreKeptFully.cs
- test/Mono.Linker.Tests.Cases/References/CopyWithLinkedWillHaveAttributeDepsKept.cs
- test/Mono.Linker.Tests.Cases/References/CopyWithLinkedWillHaveMethodDepsKept.cs
- test/Mono.Linker.Tests.Cases/References/Dependencies/WithLinked_Attrs.cs
- test/Mono.Linker.Tests.Cases/References/Dependencies/WithLinked_Methods.cs
- test/Mono.Linker.Tests.Cases/References/SavedWithLinkedWillHaveMethodDepsKept.cs
Improved #796 which used more of the existing code
> Run full mark logic on copy and copy-used assemblies

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/IReflectionPatternRecorder.cs
- src/linker/Linker/LinkContext.cs
- src/linker/Linker/LoggingReflectionPatternRecorder.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/RecognizedReflectionAccessPatternAttribute.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/UnrecognizedReflectionAccessPatternAttribute.cs
- test/Mono.Linker.Tests.Cases/Reflection/ActivatorCreateInstance.cs
- test/Mono.Linker.Tests.Cases/Reflection/MethodUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflection.cs
- test/Mono.Linker.Tests/Extensions/CecilExtensions.cs
- test/Mono.Linker.Tests/TestCasesRunner/LinkerCustomizations.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestCaseMetadaProvider.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestReflectionPatternRecorder.cs
The Mark step performs pattern matching for some reflection methods to be able to figure out dependencies even across reflection calls. Currently it only writes to log when it finds a pattern it can't recognize.
This change introduces a new interface IReflectionPatternRecorder which is called every time the pattern matching either successfuly recognizes a pattern or fails to do so. By default this is implemented to log on failure (just like before the change).
This allows additional tools to record the failures and or the successes in a different way.
Added support to test this functionality and modified a couple of tests to validate the basics.
The biggest change is in the MarkStep where the pattern matching has been refactored a little bit to fulfill a promise of always reporting …
> Introduce IReflectionPatternRecorder to allow recording of pattern matches

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Mono.Linker.csproj
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/RecognizedReflectionAccessPatternAttribute.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/UnrecognizedReflectionAccessPatternAttribute.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/VerifyAllReflectionAccessPatternsAreHandledAttribute.cs
- test/Mono.Linker.Tests.Cases/Reflection/ConstructorUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/EventUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/ExpressionCallString.cs
- test/Mono.Linker.Tests.Cases/Reflection/FieldUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/MethodUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/PropertyUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflectionTypeDoesntExist.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestCaseMetadaProvider.cs
The code was written such that it would report almost all calls it didn't consider (or try to analyze) as unrecognized patterns.
This change adds the test infra to validate that no extra reflection patterns are recorded on a given test. It then uses this on two tests to validate the functionality.
The fix adds a boolean which tracks if the code is trying to analyze a given reflection pattern or not. It only reports unrecognized pattern if it did try to analyze a pattern, but didn't report any result explicitly.
Also unified the code in reflection pattern matching to always `break` (the `returns` were left-overs from previous attempts at this functionality).
> Fix a bug in the reflection pattern recorder usage

- eng/Signing.props
- eng/azure-pipelines.yml
- src/linker/Mono.Linker.csproj
- Move Mono build out of common arcade template to get rid of missing xunit test results warning.
- Use Microsoft copyright for Mono.Linker.csproj, it is [required by arcade](https://github.com/dotnet/arcade/blob/e8c75ece0ff35ae1f3cf4103db9873467be7690a/src/Microsoft.DotNet.Arcade.Sdk/tools/ProjectDefaults.targets#L49-L55).
> Fix warnings in arcade build

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/PreserveDependencies/Dependencies/PreserveDependencyMethodInAssemblyLibrary.cs
- test/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyMemberSignatureWildcard.cs
Let's users use `'*'` for grabbing all members of a given type in a `PreserveDependencyAttribute`. See #799.
> Preserve wildcard

- test/ILLink.Tasks.IntegrationTests/TestContext.cs
Look for ILLink.Tasks package matching the configuration used
for "dotnet test". @vitek-karas PTAL.
> Fix integration test configuration

- src/linker/Linker/Driver.cs
- test/Mono.Linker.Tests/TestCasesRunner/LinkerDriver.cs
- Remove Environment.Exit usage as it breaks linker as library hosting
- Add missing documentation entries
- Move custom steps insertion to the end to be deterministic
- Error out on invalid arguments with a reasonable message
- Allow omitting true value for bool like options
- Separate new_mvid and deterministic options
> Another pass on arguments parsing clean up

- src/linker/Linker.Steps/BlacklistStep.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/LinkContext.cs
- src/linker/Linker/LoggingReflectionPatternRecorder.cs
LinkContext.LogMessage is behaving like string.Format, so if it gets a single parameter which has `{` in it, it will break.
Fixes #945
> Fix logging of unrecognized reflection patterns

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Attributes/AttributeOnAssemblyIsKeptIfDeclarationIsSkipped.cs
This avoids issues with too aggressive linking when only reference assembly
is linked and declaration assembly is for example skipped.
> Link global attributes only when both declaration and reference are linked

- test/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UnusedDerivedAttributeType.cs
This is to validate that linker does not propagate the fact that the base attribute type is used in the code to the derived types.
> Add a test case for an unused derived attribute

- src/tuner/Mono.Tuner/RemoveAttributesBase.cs
Context: https://github.com/xamarin/xamarin-android/issues/4284
We were not removing custom attributes from the interface
implementations in type definitions.
The above mentioned issue is partially fixed by this change.
Example IL:
```
.class interface public abstract auto ansi Java.Interop.IJavaPeerable
implements [mscorlib]System.IDisposable
{
.custom instance void System.Runtime.CompilerServices.NullableContextAttribute::.ctor(uint8) = ( 01 00 01 00 00 ) 
.interfaceimpl type [mscorlib]System.IDisposable
.custom instance void System.Runtime.CompilerServices.NullableAttribute::.ctor(uint8) = ( 01 00 00 00 00 ) 
...
```
Before we were removing only `NullableContextAttribute`, after we remove `NullableAttribute` as well, in the above example.
> Remove custom attributes from interface implementations

- src/tuner/Mono.Tuner/RemoveAttributesBase.cs
Context: https://github.com/xamarin/xamarin-android/issues/4284
This change solves the remaining problems from the issue above. The
generic parameter constraint is an `ICustomAttributeProvider`.
It was not very clear, where the remaining attribute instances are
located as even `ikdasm` doesn't show them. Instead it shows the
attributes as unassigned at the end of disassembly output. In this
case like:
```
...
} // end of class '<PrivateImplementationDetails>'
// =============================================================
.custom (UNKNOWN_OWNER) instance void System.Runtime.CompilerServices.NullableAttribute::.ctor(uint8) = ( 01 00 01 00 00 )
.custom (UNKNOWN_OWNER) instance void System.Runtime.CompilerServices.NullableAttribute::.ctor(uint8) = ( 01 00 01 00 00 )
// *********** …
```
> Remove attributes from generic parameter constraints

- test/Mono.Linker.Tests.Cases/UnreachableBlock/BodiesWithSubstitutions.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/ComplexConditions.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/DeadVariables.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/MultiStageRemoval.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/ReplacedReturns.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/SimpleConditionalProperty.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/SizeOfInConditions.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/TryFinallyBlocks.cs
Explicitly enable `IPConstantPropagation` during the `UnreachableBlock` tests.  This gives implementors of a linker executable the freedom to pick which optimizations are enabled by default while also ensuring that they can pass all tests.
This is consistent with other optimizations such as unreachable bodies, used attrs only, etc.
> Explicitly enable optimization during test

- src/linker/Linker/Driver.cs
- src/linker/README.md
- test/Mono.Linker.Tests.Cases/CommandLine/AddCustomStep.cs
- test/Mono.Linker.Tests.Cases/CommandLine/Dependencies/CustomStepDummy.cs
- test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- test/Mono.Linker.Tests/TestCasesRunner/TestCaseMetadaProvider.cs
Fixes #969: These changes add the ability to specify the assembly where a custom step is defined by either specifying its full path or its file name, which we'll be looked for into the additional directories passed to the linker through the command line (with `-d`).
> Resolve custom steps from external assemblies

- test/Mono.Linker.Tests/TestCasesRunner/TestCaseCompiler.cs
Using the CodeDomCompiler has been a constant source of windows only test failures being introduced.
I believe the reason CodeDomCompiler was still sticking around was because it was faster than roslyn but with server mode now widely supported and so many of our tests simply depending on roslyn now I don't think there is any advantage to using CodeDomCompiler anymore.
We switch to using roslyn by default a long time ago and it's been seamless so I expect making this same change upstream will be seamless as well.
Note that I did add /shared to our csc command line now.  Without it, roslyn is noticeably slowing than CodeDomCompiler.
Note that with this change we could remove the `[SetupCSharpCompilerToUse("csc")]` and `compilerToUse: "csc"` usages in the tests.  I did not do that as part of …
> Make roslyn the default compiler for test cases

- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtor/PreserveDependencyPreservesInterfaceMethod.cs
- test/Mono.Linker.Tests.Cases/PreserveDependencies/Dependencies/PreserveDependencyAttribute.cs
- test/Mono.Linker.Tests.Cases/PreserveDependencies/Dependencies/PreserveDependencyInCopyAssembly.cs
- test/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyField.cs
- test/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyFromCopiedAssembly.cs
- test/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyKeptOption.cs
- test/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyMemberSignatureWildcard.cs
- test/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyMethod.cs
- test/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyMethodInAssembly.cs
- test/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyMethodInNonReferencedAssembly.cs
- test/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyMethodInNonReferencedAssemblyChained.cs
- test/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyMethodInNonReferencedAssemblyChainedReference.cs
- test/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyMethodInNonReferencedAssemblyWithEmbeddedXml.cs
- test/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyOnUnusedMethodInNonReferencedAssembly.cs
- test/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyOnUnusedMethodInNonReferencedAssemblyWithCopyUsedAction.cs
- test/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyOnUnusedMethodInNonReferencedAssemblyWithEmbeddedXml.cs
- test/Mono.Linker.Tests.Cases/UnreachableBody/WorksWithPreserveDependency.cs
The expectations assembly should never survive linking.  However, putting this attribute in there was causing it to survive during some tests.
I moved the attribute into it's own assembly that is compiled during the tests that need it
> Remove PreserveDependencyAttribute from the expectations assembly

- test/Mono.Linker.Tests.Cases/Reflection/ActivatorCreateInstance.cs
- test/Mono.Linker.Tests.Cases/Reflection/ConstructorUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/CoreLibMessages.cs
- test/Mono.Linker.Tests.Cases/Reflection/EventUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/ExpressionCallString.cs
- test/Mono.Linker.Tests.Cases/Reflection/FieldUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/MethodUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/PropertyUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflectionTypeDoesntExist.cs
Need to explicitly use roslyn in order for these tests to pass on windows.  Otherwise they fail complaining about the nameof() usages in attributes.
> Fixes to reflection tests when running on windows

- test/Mono.Linker.Tests.Cases/UnreachableBlock/ComplexConditions.cs
This test fails PEVerify on windows
Invalid IL detected in F:\Temp\linker_tests\output\test.exe
[IL]: Error: [F:\Temp\linker_tests\output\test.exe : Mono.Linker.Tests.Cases.UnreachableBlock.ComplexConditions::Test_1][offset 0x0000001D] Stack depth differs depending on path.
1 Error(s) Verifying F:\Temp\linker_tests\output\test.exe
> Ignore complex conditions test

- test/Mono.Linker.Tests/Mono.Linker.Tests.csproj
To run tests from VS the NUnit3TestAdapter package is required, otherwise VS doesn't correctly recognize NUnit tests.
> Enable running monolinker tests in VS

- src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/ComplexConditions.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/ReplacedReturns.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/SimpleConditionalProperty.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/TryCatchBlocks.cs
The CLR spec in Backward Branch Contraints recognizes only unconditional
jumps. For any other instruction including nop it mandates
>In particular, if that single-pass analysis arrives at an instruction,
call it location X, that immediately follows an unconditional branch,
and where X is not the target of an earlier branch instruction, then the
state of the evaluation stack at X, clearly, cannot be derived from
existing information. In this case, the CLI demands that the evaluation
Fixes #975
> Don't use nop(s) for removed instructions in RemoveUnreachableBlocksStep

- src/linker/Linker.Steps/ResolveFromXmlStep.cs
- test/Mono.Linker.Tests.Cases/LinkXml/CanPreserveMarkedChildrenOfUnrequiredType.cs
- test/Mono.Linker.Tests.Cases/LinkXml/CanPreserveMarkedChildrenOfUnrequiredType.xml
- test/Mono.Linker.Tests.Cases/LinkXml/Dependencies/CanPreserveMarkedChildrenOfUnrequiredType_Library.cs
This fixes #965 by preserving all children marked in a XML descriptor regardless of the `required` attribute value.
> Preserve marked children of XML descriptor

- test/Mono.Linker.Tests/TestCases/IndividualTests.cs
- test/Mono.Linker.Tests/TestCases/TestDatabase.cs
Don't assume that the test is running from the project directory.  Some test runners will set the CurrentDirectory to a temporary directory.
> Fix for pinvoke output test

- src/linker/Linker.Steps/ClearInitLocals.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker.Steps/OutputStep.cs
- src/linker/Linker.Steps/ReflectionBlockedStep.cs
- src/linker/Linker.Steps/ResolveFromAssemblyStep.cs
- src/linker/Linker.Steps/ResolveFromXmlStep.cs
- src/linker/Linker/Annotations.cs
- src/linker/Linker/DependencyInfo.cs
- src/linker/Linker/DirectoryAssemblyResolver.cs
- src/linker/Linker/Driver.cs
- src/linker/Linker/IDependencyRecorder.cs
- src/linker/Linker/LinkContext.cs
- src/linker/Linker/MarkingHelpers.cs
- src/linker/Linker/MethodBodyScanner.cs
- src/linker/Linker/Pipeline.cs
- src/linker/Linker/Tracer.cs
- src/linker/Linker/XmlDependencyRecorder.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestCaseMetadaProvider.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestDependencyRecorder.cs
This supplies a "reason" every time that we mark a piece of IL.
A "reason" is an instance of a new type, DependencyInfo, which tracks
a single source object and a flag (DependencyKind) indicating what
kind of dependency this is. Annotations.Mark now expects a
DependencyInfo, and the dependency reporting interface is extended to
report these reasons.
The mark sites within MarkStep and other steps have been updated with
specific reasons, and the corresponding Mark* methods have been
modified to take a reason that is passed through as many layers of the
marking logic as necessary until it reaches a call to
Annotations.Mark. The marking logic has been modified to more
frequently allow marking Cecil objects multiple times for different
reasons - while still ensuring that any expensive …
> Add tracing reasons

- src/linker/Linker.Steps/MarkStep.cs
The method returns the same thing so it's quite uninteresting. We don't want to lose dataflow information though.
> [feature/dataflow] Treat GetTypeInfo same as MakeGenericType

- test/Mono.Linker.Tests/TestCasesRunner/TestCaseMetadaProvider.cs
This would allow us to use reflection assertions inside nested types, e.g.:
```C#
public class Foo {
public static void Main () {
new Bar ();
}
class Bar {
[UnrecognizedReflectionAccessPattern ( ... )]
public void SomeMethodToCheck () { .. }
}
}
```
> Add reflection pattern recorder if needed by any nested type

- src/linker/Linker.Dataflow/DynamicallyAccessedMemberKinds.cs
- src/linker/Linker.Dataflow/FlowAnnotations.cs
- src/linker/Linker.Dataflow/IFlowAnnotationSource.cs
- src/linker/Linker/FieldDefinitionExtensions.cs
- src/linker/Linker/MethodDefinitionExtensions.cs
* `IFlowAnnotationSource` lets us abstract away the source of the annotations. We expect to have an attribute-based one and JSON-based one (the JSON based one mostly for internal purposes right now - it probably won't be public).
* The `FlowAnnotations` class deals with caching and propagating the attributes from properties to the accessor methods and backing fields. The cache is per-type because the properties make this more complicated. Being per-type is also more memory efficient because we don't have to keep track of all methods/fields that we looked at and found out they're not interesting (the majority of cases). Not interesting things are not tracked and that's cached at the type level.
Vitek is working on the thing that consumes this. I already tested it a bit with Vitek's thing.
> [feature/dataflow] Implement FlowAnnotations helper class

- Directory.Build.props
https://github.com/mono/linker/pull/1029 didn't fix the issue because
Arcade sets its own defaults that override those in
Directory.Build.props. This moves the import so that our setting wins.
Validated by doing a local build, setting OfficialBuildId manually. I
did the same validation in the last change, but maybe I was working
with a dirty build that somehow had a pdb. I think this should
actually fix it.
> Fix ref assembly symbols issue (try 2)

- src/linker/Linker.Dataflow/AttributeFlowAnnotationSource.cs
- src/linker/Linker.Dataflow/FlowAnnotations.cs
- src/linker/Linker.Dataflow/MethodBodyScanner.cs
- src/linker/Linker.Dataflow/ValueNode.cs
- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/RecognizedReflectionAccessPatternAttribute.cs
- test/Mono.Linker.Tests.Cases.Expectations/Support/DynamicallyAccessedMembersAttribute.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodParametersDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodReturnParameterDataFlow.cs
- test/Mono.Linker.Tests.Cases/Reflection/ActivatorCreateInstance.cs
- test/Mono.Linker.Tests/TestCases/TestDatabase.cs
- test/Mono.Linker.Tests/TestCases/TestSuites.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
Implements propagation of data flow annotations from/to method parameters and from/to method return value.
Still lacks some functionality:
* Not all member access kinds are implemented - only ctors are
* Error reporting is pretty bad, needs more work
> [feature/dataflow] Propagate data flow annotations across method calls

- test/Mono.Linker.Tests.Cases/Reflection/ExpressionCallString.cs
- test/Mono.Linker.Tests.Cases/Reflection/ExpressionFieldString.cs
- test/Mono.Linker.Tests.Cases/Reflection/ExpressionPropertyString.cs
Currently this is hitting a bug https://github.com/mono/linker/issues/1042.
> Add tests for Expression.Call/Field/Property for members on a base class

- Directory.Build.targets
- src/ILLink.Tasks/ILLink.Tasks.csproj
- src/analyzer/analyzer.csproj
- src/linker/Directory.Build.props
- src/linker/Mono.Linker.csproj
- src/linker/ref/Mono.Linker.csproj
- test/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
- test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- test/Mono.Linker.Tests/Mono.Linker.Tests.csproj
This makes a few changes to the illink reference assembly build and package.
As discussed in https://github.com/mono/linker/pull/1014#discussion_r399565691:
- Removes the net471 target from illink
- Changes the reference assembly to build for netcoreapp3.0 instead of netstandard2.0
- Includes the implementation assembly in the package as well
Closes https://github.com/mono/linker/issues/1023:
- Changes the package name to Microsoft.NET.ILLink
Note that the ILLink.Tasks continues to ship as a separate package.
This also includes minor cleanup I made as I was going:
- factoring of properties shared by impl and ref assemblies
- removal of explicit Debug/Release Configurations
- addition of a sanity check for ILLink.Tasks packaging
> Retarget reference assembly

- src/linker/Linker/IReflectionPatternRecorder.cs
- src/linker/Linker/LoggingReflectionPatternRecorder.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestReflectionPatternRecorder.cs
We implement detection of methods such as IsAssignableFrom which requires marking of an InterfaceImplementation.  An InterfaceImplementation is not an IMemberDefinition so I was unable to record this reflection pattern.
Changing RecognizedReflectionAccessPattern to accept an IMetadataTokenProvider allows us to record this detection.
> Open up ReflectionPatternRecorder more

- test/Mono.Linker.Tests.Cases/DataFlow/FieldDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodParametersDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodReturnParameterDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/PropertyDataFlow.cs
These tests don't rely on the Kept validation, instead they use the reflection pattern recorder to validate the product behavior. Using Kept attributes just makes the tests unnecessarily verbose.
> [feature/dataflow] Remove Kept attributes from dataflow annotation propagation tests

- src/linker/Linker.Dataflow/FlowAnnotations.cs
- src/linker/Linker.Steps/MarkStep.cs
Fix a nullref when JSON annotation is applied to an abstract property.
Record the method for which we create default return value (happens for example when the code calls `typeof(T)`)
> Small fixes - flow annotations and warnings

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AttributeConstructorDataflow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AttributeFieldDataflow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AttributePropertyDataflow.cs
A custom attribute application should be treated the same as a method call (followed by potentially several calls to property setters and field stores). All parameters will be statically known by definition.
I plan to fix up the string-based tests before this is merged (going to merge after #1078 that is a prerequisite).
Fixes #1072
> [feature/dataflow] Implement dataflow to custom attributes

- src/linker/Linker.Dataflow/MethodBodyScanner.cs
- src/linker/Linker.Dataflow/ScannerExtensions.cs
- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/DataFlow/ByRefDataflow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodParametersDataFlow.cs
We track indirect writes to method parameters and fields. This is necessary to support dataflow annotations on `out` and `ref` parameters.
> [feature/dataflow] Add support for byref operations

- test/Mono.Linker.Tests.Cases/DataFlow/MethodThisDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/PropertyDataFlow.cs
I noticed that the explicit property tests had annotations that applied to `this` on the getter/setter, but they happened to work because the annotation propagation for properties was applying to the `return`/`param`. I also added tests that actually check the `this` annotations on properties.
> Fix property annotation test

- src/linker/Linker.Dataflow/ValueNode.cs
- src/linker/Mono.Linker.csproj
Redoing the change mentioned in https://github.com/mono/linker/issues/999. We still need the BCL package, but only when building for mono.
> Use HashCode struct

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Reflection/ExpressionCallString.cs
- test/Mono.Linker.Tests.Cases/Reflection/ExpressionFieldString.cs
- test/Mono.Linker.Tests.Cases/Reflection/ExpressionPropertyString.cs
If a field, property or method which is accessed via reflection is not found inside the callers type, look for it in it's base type (if any). This fixes #1042.
> [feature/dataflow] Look for fields, properties and methods in base type

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MemberKinds.cs
Posting this mostly to ask a question @MichalStrehovsky @vitek-karas
The attribute encoding sort of assumes that the default ctor is public. The logic that keeps default ctors works for private default ctors, but the logic that keeps public ctors will not keep a private default ctor. Should we do something differently to prevent the behavior illustrated in this failing testcase? (`RequireDefaultConstructor` works, but `RequireDefaultOrPublicConstructors` will not keep the default private ctor on `PrivateDefaultAndPublicConstructorsType`).
> [feature/dataflow] Only keep public DefaultConstructor

- src/ILLink.Tasks/ILLink.Tasks.csproj
The change from `ProjectReference` to `PackageReference` was causing cecil not to be published with the full framework `ILLink.Tasks` project due to inconsistencies in how `PrivateAssets` are handled. This fixes the issue in https://github.com/dotnet/sdk/pull/11214#issuecomment-613566926.
> Fix Cecil PackageReference publishing

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Reflection/ActivatorCreateInstance.cs
This implements it for Activator.CreateInstance* with strings, AppDomain.CreateInstance* and Assembly.CreateInstance.
The implementation is basically just copying the existing behavior. Didn't try to improve it much yet.
Added tests.
> [feature/dataflow] Implement pattern recognition for the rest of CreateInstance overloads

- src/ILLink.Tasks/ILLink.Tasks.csproj
I've kept the assembly name and project names the same (`ILLink.Tasks`) like we have done for Mono.Linker. The only thing that changes is the package name, which is only expected to be used by .NET repos. We'll need to update the `PackageReferences` from runtime and sdk.
> Package ILLink.Tasks as Microsoft.NET.ILLink.Tasks

- src/linker/Linker.Steps/SweepStep.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/RemovedAssemblyReference.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/UsedAndUnusedForwarderWithAssemblyCopy.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
regenerating the assembly.
Fixes #1108
> Don't import references for forwarders which will be removed when

- src/linker/Linker.Steps/OutputStep.cs
- src/linker/Linker/AssemblyResolver.cs
- src/linker/Linker/DirectoryAssemblyResolver.cs
- src/linker/Linker/LinkContext.cs
...using one weird trick.
Cecil uses file I/O to read assemblies, but for our use cases this means we're spending a ton of time context switching between kernel mode and user mode.
Memory mapped I/O is more efficient for these access patterns.
The change is bigger than I would want it to be because:
* Loading assemblies from disk is not centralized in linker (and in fact there are more extensibility points that encourage everyone to do their own loading)
* Cecil violates OOP principles by giving certain kinds of streams preferential treatment (`ModuleDefinition.FileName` is useless if the assembly wasn't opened with the blessed stream kind and Cecil doesn't have a way to provide it through other means).
> Speed up linker by 10%

- src/ILLink.Tasks/LinkTask.cs
Introduced in f8d216d8611265af051163b07bccc6fdb83f3571
> Fixes regression caused by missing space after `--custom-data` argument

- docs/design/reflection-flow.md
This would let us expand on what reflection use can the linker reason about.
The main problem it's trying to tackle is whether we can build a solution that has:
1) Actionable warnings when code is not linker-safe
2) Gives confidence that when there are no warnings, no problems will occur at runtime
Being able to make arbitrary code linker-safe is an explicit non-goal – from our past experience we know we can’t provide tools that meet goal 1 & 2 for that: it would be solving the halting problem.
Cc @vitek-karas @marek-safar
> Add proposal for enhanced dataflow analysis

- src/ILLink.Tasks/LinkTask.cs
The line is already appended to the response file above this code on line 317:
```
if (_clearInitLocals is bool clearInitLocals) {
SetOpt (args, "clearinitlocals", clearInitLocals);
} else {
clearInitLocals = false;
}
```
So there is no need to add it here again.
cc @sbomer
> Remove duplicate --enable-opt clearinitlocals in ILLink

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/MethodDefinitionExtensions.cs
- src/linker/Linker/TypeDefinitionExtensions.cs
* It's not mandatory to name the single instance field on enums `value__`. C#/VB do that, but the spec only requires there is an instance field. The name check is unnecessary work.
* The `IsFinalizer` extension method was wrong: one one side it includes unnecessary methods (for people who like to fight CS0465 warning from the C# compiler and name their methods `Finalize` - and yes there are those people), and on the other side it doesn't include finalizers that are not named `Finalize` (one can just `MethodImpl` the `Finalize` method). Instead of trying to get the extension method right, just letting the general virtual method handling take care of it.
> Fix a couple nits

- src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs
It's no longer need after recent changes as the exception blocks are
removed completely when unreachable
Fixes #1183
> Remove handling of verifiable unreachable exception blocks

- docs/error-codes.md
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/Annotations.cs
- src/linker/Linker/LinkerAttributesInformation.cs
- src/linker/Linker/LinkerFatalErrorException.cs
- src/linker/System.Diagnostics.CodeAnalysis/RequiresUnreferencedCodeAttribute.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/LogContainsAttribute.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/LogDoesNotContainAttribute.cs
- test/Mono.Linker.Tests.Cases.Expectations/System.Diagnostics.CodeAnalysis/RequiresUnreferencedCodeAttribute.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs
- test/Mono.Linker.Tests/TestCases/TestDatabase.cs
- test/Mono.Linker.Tests/TestCases/TestSuites.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestCaseMetadaProvider.cs
Introduces a cache of "linker attributes", currently only RequiresUnreferencedCodeAttribute is supported, but it's highly likely we will need this for other attributes as well (DynamicDependency, future AOT/Single-file related attributes, UnconditionalSuppressMessage, ...). The cache is on Annotations class and should also act as a natural point to unify attribute and XML based inputs (once we have the XML based attribute injection).
RequiresUnreferencedCode now causes a linker warning whenever a method with it is called.
It also auto-suppresses warnings within the method with this attribute - it actually disables data flow analysis on the method right now.
In the future when we have AOT/Single-File related analysis we will need to modify this to selectively support a subset and only …
> Implement support for RequiresUnreferencedCodeAttribute

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/Reflection/NestedTypeUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/ObjectGetType.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeDelegator.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
* `Type.GetNestedType` - should be straighforward
* `TypeDelegator..ctor` - this is used in CoreLib - we should just treat it as identity so that we don't lose dataflow annotations
* `object.GetType` - I specifically need the delegate part for `CoreLib`; the rest of the behavior is nice to have but I don't expect it to kick in too often.
Creating as draft because it obviously misses tests, but it's Friday...
> Implement a couple more dataflow intrinsics

- src/linker/Linker.Dataflow/FlowAnnotations.cs
`RuntimeType` and `TypeBuilder` are both interesting from the dataflow perspective.
> Respect flow annotations on RuntimeType and TypeBuilder

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker/LoggingReflectionPatternRecorder.cs
- test/Mono.Linker.Tests.Cases/Reflection/ConstructorUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/EventUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/FieldUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/MethodUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/PropertyUsedViaReflection.cs
Adds a location for messages which don't have source code location. For now this is added as the name of the method where the warning occured. This is definitely a temporary improvement and we should do better once we invest more into the location information.
Fixes several smaller issues with warning messages:
- In some cases Cecil doesn't have parameter names, so use parameter index in that case
- Correctly specify the "this" parameter (which doesn't have a Cecil representation) as the method definition itself which will lead to the correct message
> Improve messages for reflection warnings

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Dataflow/ReflectionPatternContext.cs
- src/linker/Linker/IReflectionPatternRecorder.cs
- src/linker/Linker/LoggingReflectionPatternRecorder.cs
- test/Mono.Linker.Tests/TestCasesRunner/LinkerCustomizations.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestCaseMetadaProvider.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestReflectionPatternRecorder.cs
With the upcoming support for DynamicallyAccessedMembersAttribute on generic parameters, the source of the access pattern will no longer be any code, but it can be a type declaration or field definition and so on. In such cases trying to point back to some line of code is complicated and in lot of cases confusing.
This change allows more values to be passed as the source of a reflection access pattern. Currently there's no use case for it. The one which comes close is attribute fields, but those make sense to use the attribute ctor as the source of the problem and use the field as the "accessed" item.
Corresponding changes to the test infra to allow for wider range of values and to handle missing values better.
> Allow types and other metadata item as source for reflection access pattern

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayOnTypeWithCallToExtensionMethodOnFieldType.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayOnTypeWithCallToMethodOnFieldType.cs
This  change fixes a crash that would occur if the linker tried to process a DebuggerDisplayAttribute that referred to a method on a member. 
Robustly handling this scenario doesn't seem worth the effort.  This bug has gone unnoticed for a couple years in Unity which implies this isn't a particularly common thing to do.  Much less to also have zero usages of that member appear in a used code path.
The full exception stack was 
```
Mono.Linker.MarkException : Error processing method: 'System.Void Mono.Linker.Tests.Cases.Attributes.Debugger.KeepDebugMembers.DebuggerDisplayOnTypeWithCallToExtensionMethodOnFieldType::Main()' in assembly: 'test.exe'
----> System.NullReferenceException : Object reference not set to an instance of an object.
at Mono.Linker.Steps.MarkStep.ProcessQueue() in …
```
> Fix a crash processing DebuggerDisplayAttribute

- src/linker/Linker/DocumentationSignatureParser.cs
- test/Mono.Linker.Tests/Tests/DocumentationSignatureParserTests.cs
Because generic methods don't have mangled names, a generic method
signature could match a type if we don't check its arity.
> Fix edge case in signature parser

- src/linker/Linker.Dataflow/DynamicallyAccessedMembersBinder.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
This will be used for DynamicDependencyAttribute as well.
In https://github.com/mono/linker/pull/1215#discussion_r431685282 there were concerns about the performance of `HasFlag`, potentially boxing on Unity for example. Let's continue the discussion here.
> Factor out binding logic for DynamicallyAccessedMemberTypes

- src/ILLink.Tasks/CombineLinkerXmlFiles.cs
- src/ILLink.Tasks/ILLink.Tasks.csproj
- test/ILLink.Tasks.Tests/CombineLinkerXmlFilesTests.cs
This task combines multiple linker xml files into a single, combined xml file.
@sbomer @marek-safar
> Add CombineLinkerXmlFiles task

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/DataFlow/EmptyArrayIntrinsicsDataFlow.cs
- test/Mono.Linker.Tests.Cases/Reflection/ConstructorUsedViaReflection.cs
Also recognize `Type.EmptyTypes` and `Array.Empty<Type>`.
Fixes #1222.
> Scope down PublicConstructors to DefaultConstructor if possible

- docs/data-formats.md
Note that the field substitutions are for static fields only.
@eerhardt
> Clarify substitution documentation

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/UnconditionalSuppressMessageAttributeState.cs
- test/Mono.Linker.Tests.Cases/WarningSuppression/SuppressWarningsInAssembly.cs
- test/Mono.Linker.Tests.Cases/WarningSuppression/SuppressWarningsInMembersAndTypesUsingTarget.cs
- test/Mono.Linker.Tests.Cases/WarningSuppression/SuppressWarningsInModule.cs
Continuing with the work of https://github.com/mono/linker/pull/1185 this PR adds the ability to suppress warnings throughout a module or assembly. It also adds support for using the `Target` and `Scope` properties for global suppression on types and members.
> Add more warning suppression scenarios

- docs/error-codes.md
- src/ILLink.Tasks/LinkTask.cs
- src/linker/Linker.Steps/ClearInitLocals.cs
- test/ILLink.Tasks.Tests/ILLink.Tasks.Tests.cs
- Avoids changing assembly action
- Uses assembly optimizations instead of custom data
- Fixes https://github.com/mono/linker/issues/1129
> Clean up clearinitlocals handling

- src/linker/Linker/LoggingReflectionPatternRecorder.cs
- src/linker/Linker/UnconditionalSuppressMessageAttributeState.cs
Nit: use the new logging methods instead of passing a `MessageContainer` directly.
> Update log methods

- docs/error-codes.md
- src/linker/Linker.Dataflow/FlowAnnotations.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodThisDataFlow.cs
We had to allow the attribute on a method so that we could annotate System.Type instance methods. In that case the attribute on the method means "annotate the this parameter with this".
But using the attribute anywhere else is not allowed. Linker should warn about this.
> Warn if DynamicallyAccessedMembersAttribute is used directly on a method

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Dataflow/ValueNode.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AssemblyQualifiedNameDataflow.cs
This will propagate whatever annotations there are on the type to the string.
Makes it possible to recognize the pattern used by ComponentModel/TypeDescriptionProviderAttribute as safe (the pattern is to accept both a `string` and a `Type`, store the value as a `string`, and `Type.GetType` the type out of that string, before passing it to `Activator`).
> Recognize Type.AssemblyQualifiedName as intrinsic

- docs/error-codes.md
- src/linker/Linker.Dataflow/FlowAnnotations.cs
- test/Mono.Linker.Tests.Cases/DataFlow/PropertyDataFlow.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
When we propagate data flow annotations from the property to its getter/setter/backing field there are cases which the code doesn't handle. This change will issue warnings for most of those cases:
- If we can't detect backing field
- If there already is a data flow annotation in a place where we would try to apply it
Added tests for these cases
> Warnings during propagation of data flow annotations in properties

- docs/error-codes.md
- src/linker/Linker.Dataflow/FlowAnnotations.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/DynamicDependencyLookupStep.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/Annotations.cs
- src/linker/Linker/DynamicDependency.cs
- src/linker/Linker/LinkContext.cs
- src/linker/Linker/LinkerAttributesInformation.cs
- src/linker/Linker/LoggingReflectionPatternRecorder.cs
- src/linker/Linker/MessageContainer.cs
- src/linker/Linker/MessageOrigin.cs
- src/linker/Linker/MethodReferenceExtensions.cs
- src/linker/ref/Linker/MessageOrigin.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodThisDataFlow.cs
- test/Mono.Linker.Tests.Cases/DynamicDependencies/DynamicDependencyMemberSignatureWildcard.cs
- test/Mono.Linker.Tests.Cases/DynamicDependencies/DynamicDependencyMethod.cs
- test/Mono.Linker.Tests.Cases/Logging/SourceLines.cs
- test/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyDeprecated.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs
I'm moving the optional `ilOffset` parameter that was originally passed to `TryGetOrigin` to `LogWarning`, so that we can delay the retrieval of the source information for warnings until it's needed (i.e., after we're sure that the warning isn't suppressed).
Solves https://github.com/mono/linker/issues/1221
> Remove TryGetOrigin from MessageOrigin

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerDisplayAttributeOnGenerics.cs
I added these asserts because these methods retrieve members on
resolved base TypeDefinitions - uninstantiated types, in the case of
generics - losing information about generic arguments. I was concerned
that we might leave some of the generic argument types unmarked as a
result.
Inspecting the callers of these methods, I am now pretty sure that we
can only get to these helpers along code paths that also mark the base
TypeReference.
For example, MarkType usually gets called on the declaring type, and
MarkType will mark the unresolved base type. In other cases,
MarkEntireType is called on the declaring type, and this calls into
helpers to mark members which then call MarkType on the unresolved
base type. When marking custom attributes, we mark the constructor
which marks the unresolved …
> Remove unnecessary asserts

- src/linker/Linker.Dataflow/FlowAnnotations.cs
- src/linker/Linker.Dataflow/MethodBodyScanner.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Dataflow/ValueNode.cs
- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/RecognizedReflectionAccessPatternAttribute.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/UnrecognizedReflectionAccessPatternAttribute.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterDataFlow.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestCaseMetadaProvider.cs
The checks are done when linker calls `MarkType(TypeReference)` or `MarkMethod(MethodReference)`. The check itself is straightforward as it uses existing functionality.
Added annotations in `FlowAnnotations` for generic parameters.
Added one parameter to `MarkType` to better track the location where the type reference comes from. This enables much more precise reporting of warnings.
On test side this makes the recognized/unrecognized attributes applicable to many more things as warnings can come from types, fields and so on.
Fixes #1086
> Implement data flow annotations on generic parameters

- src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/BodiesWithSubstitutions.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/InstanceMethodSubstitutions.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/InstanceMethodSubstitutions.xml
So far we only allowed inlining of return values for methods which are static, with this change we also allow it on an instance method which is explicitly substituted.
> Allow inlining of return values of instance methods which are explicitly substituted

- src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/BodiesWithSubstitutions.cs
This was probably a "bug" as the code is designed to do this and it will work for methods with multiple branches, but it doesn't work for methods which simply return a value from another method (no branching).
This has small impact - in CoreLib this actually only kicks in about 4 times.
> This allows linker to propagate constant return values higher up the callstack

- docs/data-formats.md
- docs/error-codes.md
- src/linker/Linker.Steps/BodySubstituterStep.cs
- src/linker/Linker.Steps/LinkAttributesStep.cs
- src/linker/Linker.Steps/ResolveFromXmlStep.cs
- src/linker/Linker/FeatureSettings.cs
- test/Mono.Linker.Tests.Cases/FeatureSettings/Dependencies/ResourceFile.txt
- test/Mono.Linker.Tests.Cases/FeatureSettings/FeatureDescriptors.cs
- test/Mono.Linker.Tests.Cases/FeatureSettings/FeatureDescriptors.xml
- test/Mono.Linker.Tests.Cases/FeatureSettings/FeatureDescriptorsGlobalFalse.xml
- test/Mono.Linker.Tests.Cases/FeatureSettings/FeatureDescriptorsGlobalTrue.xml
- test/Mono.Linker.Tests.Cases/FeatureSettings/FeatureSubstitutions.cs
- test/Mono.Linker.Tests.Cases/FeatureSettings/FeatureSubstitutions.xml
- test/Mono.Linker.Tests.Cases/FeatureSettings/FeatureSubstitutionsGlobalFalse.xml
- test/Mono.Linker.Tests.Cases/FeatureSettings/FeatureSubstitutionsGlobalTrue.xml
- test/Mono.Linker.Tests.Cases/FeatureSettings/FeatureSubstitutionsInvalid.cs
- test/Mono.Linker.Tests.Cases/FeatureSettings/FeatureSubstitutionsInvalid.xml
- test/Mono.Linker.Tests.Cases/FeatureSettings/FeatureSubstitutionsNested.cs
- test/Mono.Linker.Tests.Cases/FeatureSettings/FeatureSubstitutionsNested.xml
- test/Mono.Linker.Tests/TestCases/TestDatabase.cs
- test/Mono.Linker.Tests/TestCases/TestSuites.cs
Fixes https://github.com/mono/linker/issues/1268.
> Support feature settings on descriptor files

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/Reflection/ActivatorCreateInstance.cs
If `CreateInstance<T>` is used with a generic parameter that is annotated to keep the public parameterless ctor, the use is safe.
> Accept default constructor annotation in CreateInstance<T>

- src/linker/Linker.Steps/ResolveFromXmlStep.cs
Related to #1289. Whenever we mark a member with `ResolveFromXmlStep` we also have to mark its declaring type. Because there can be multiple calls to this step, each marking a different member from the same declaring type, there's a chance that the linker will output this warning multiple times without having the possibility to resolve it.
> Don't warn on duplicate preserve for types

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Dataflow/ReflectionPatternContext.cs
- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapabilityReflectionAnalysisEnabled.cs
RequiresUnreferencedCode attribute should only suppress reflection analysis warnings for a given method, but reflection analysis should still run.
Should basically fix https://github.com/mono/linker/issues/1167.
> RequiresUnreferencedCode should not suppress reflection analysis

- src/linker/Linker.Steps/CodeRewriterStep.cs
- src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/InstanceMethodSubstitutions.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/MethodWithParametersSubstitutions.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/MethodWithParametersSubstitutions.xml
This is currently limitted only to method explicitly substituted via substitution.xml and only to methods with in parameters. Out and Ref parameters are not allowed.
Fixes https://github.com/mono/linker/issues/1288.
/cc @eerhardt
> Support propagation of constant return value from methods with parameters

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/Annotations.cs
- test/Mono.Linker.Tests.Cases/Generics/ArrayVariantCasting.cs
- test/Mono.Linker.Tests.Cases/Generics/MdArrayVariantCasting.cs
- test/Mono.Linker.Tests.Cases/Generics/VariantCasting.cs
- test/Mono.Linker.Tests.Cases/Reflection/IsAssignableFrom.cs
This is actually 3 separate things:
* Bugfix in linker where linker was stripping type `Foo` despite the program containing a `new Foo[x,y]` statement. I hit this while writing tests for this.
* If a type is used as an array element or as a generic argument, don't strip any of its interfaces because they might be necessary for variant casting later.
* If a type is visible from reflection, don't strip any of its interfaces.
Fixes #1235.
> Correctness fixes to interface stripping

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Attributes/MarshalAsCustomMarshaler.cs
Fixes #1281.
We also need a trimming directive in CoreLib that says we want to keep all methods on ICustomMarshaler to make this work E2E, but that's not a linker concern anymore (and it's not testable here...).
> Keep GetInstance method on custom marshalers

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Attributes.StructLayout/ExplicitClass.cs
- test/Mono.Linker.Tests.Cases/Attributes.StructLayout/SequentialClass.cs
We can postpone marking fields on types with layout until we're really sure they're needed. They're needed if they're visible to reflection, or considered instantiated (valuetypes are implicitly considered instantiated).
I'm also allowing stripping fields on Auto layout structs. This is a rare sight, but there's no reason that I know of to force them to have all their fields kept.
> Postpone marking fields on types with layout

- src/linker/Linker.Dataflow/DiagnosticUtilities.cs
- src/linker/Linker.Dataflow/DynamicallyAccessedMembersBinder.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/System.Diagnostics.CodeAnalysis/DynamicallyAccessedMemberTypes.cs
- test/Mono.Linker.Tests.Cases.Expectations/System.Diagnostics.CodeAnalysis/DynamicallyAccessedMemberTypes.cs
- test/Mono.Linker.Tests.Cases/DataFlow/ApplyTypeAnnotations.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AssemblyQualifiedNameDataflow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/ByRefDataflow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/EmbeddedLinkAttributes.cs
- test/Mono.Linker.Tests.Cases/DataFlow/EmbeddedLinkAttributes.xml
- test/Mono.Linker.Tests.Cases/DataFlow/EmptyArrayIntrinsicsDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/FieldDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GetTypeDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/LinkerAttributeRemoval.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MemberTypes.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodParametersDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodReturnParameterDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/PropertyDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/SuppressWarningWithLinkAttributes.cs
- test/Mono.Linker.Tests.Cases/DataFlow/SuppressWarningWithLinkAttributes.xml
- test/Mono.Linker.Tests.Cases/DataFlow/VirtualMethodHierarchyDataflowAnnotationValidation.cs
- test/Mono.Linker.Tests.Cases/DataFlow/XmlAnnotations.cs
- test/Mono.Linker.Tests.Cases/DataFlow/XmlAnnotations.xml
- test/Mono.Linker.Tests.Cases/DynamicDependencies/DynamicDependencyMemberTypes.cs
- test/Mono.Linker.Tests.Cases/Reflection/ActivatorCreateInstance.cs
- test/Mono.Linker.Tests.Cases/Reflection/ConstructorUsedViaReflection.cs
This turned out to be important as we used the enum name in linker attribute XML as well (so we would not recognize the correct name).
I tried to rename everything, including test type/method names and so on.
This also includes remaining renames of DynamicallyAccessedMemberKinds to DynamicallyAccessedMemberTypes (mostly local variable names and such).
No functional changes.
> Rename DefaultConstructor to PublicParameterlessConstructor

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Attributes.StructLayout/SequentialClass.cs
Should fix the [issue](https://github.com/mono/linker/pull/1309) observed in CoreLib where `RawData` class is used with `Unsafe.As` to break type safety and linker stripped its fields because it's not seen as instantiated.
> Keep all fields on sequential/explicit layout classes if a field was kept

- src/linker/Linker.Steps/LinkAttributesStep.cs
Currently, the code tries to continue processing attributes when internal attribute RemoveAttributeInstances is detected causing a warning since the internal attribute doesn't contain fullname. Correct behavior should be: continue after a RemoveAttributeInstances attribute has been detected.
This fixes #1337  #1338
> Stop processing attributes after RemoveAttributeInstances

- src/linker/Linker.Dataflow/MethodBodyScanner.cs
We now need this to link CoreLib.
https://github.com/dotnet/runtime/pull/32520/files#r451338721
> Add handling of calli in MethodBodyScanner

- src/linker/Linker/TypeReferenceExtensions.cs
- test/Mono.Linker.Tests/Tests/GetDisplayNameTests.cs
I changed the algorithm to not rely on teh backtick notation (parsing numbers from names) and instead use Cecil's generic parameter counts.
This also changes how instantiated generics are handled (GenericInstanceType) - now we just store the generic arguments and loop again on the open generic type (ElementType) which will apply the generic arguments if available.
Added test for the failing case as well as another one for partially instantiated generics.
Related https://github.com/mono/linker/issues/1321
> Fix problem with GetDisplayName on nested generic types

- src/linker/Linker.Steps/LinkAttributesStep.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker.Steps/ProcessLinkerXmlStepBase.cs
- src/linker/Linker.Steps/ResolveFromXmlStep.cs
- src/linker/Linker/Annotations.cs
- src/linker/Linker/CustomAttributeSource.cs
- src/linker/Linker/LinkerAttributesInformation.cs
- test/Mono.Linker.Tests.Cases/DataFlow/Dependencies/LinkerAttributeRemovalAttributeToRemove.cs
- test/Mono.Linker.Tests.Cases/DataFlow/Dependencies/LinkerAttributeRemovalCopyAssembly.cs
- test/Mono.Linker.Tests.Cases/DataFlow/LinkerAttributeRemoval.cs
- test/Mono.Linker.Tests.Cases/DataFlow/LinkerAttributeRemoval.xml
- test/Mono.Linker.Tests.Cases/DynamicDependencies/DynamicDependencyFromAttributeXml.Attributes.xml
- test/Mono.Linker.Tests.Cases/DynamicDependencies/DynamicDependencyFromAttributeXml.cs
MarkStep go over all assemblies (Regardless if they're being linked or just copied) and marks everything as usual. But in the end it will not "trim" anything from the copy assembly. So we must make sure that everything the assembly needs is marked.
Attribute removal needs to comply with this behavior as well.
This change fixes several other issues around link attribute XML files:
- If the XML refers to an attribute which will in turn bring in new assemblies to the closure it would not correctly register all of them - the step needs to behave just like any other step which can bring in new assembly to the closure
- Several places in MarkStep didn't use the CustomAttributeSource to detect presense of attributes - meaning that injecting attributes via the XML on a member which had no other …
> Attribute removal should not kick in for assemblies which are not linked

- docs/illink-tasks.md
- src/ILLink.Tasks/LinkTask.cs
- test/ILLink.Tasks.Tests/ILLink.Tasks.Tests.cs
`Action` and `DefaultAction` become `TrimMode`, and updates documentation to match.
The documentation needs more work, but this at least replaces some incorrect information.
Part of https://github.com/dotnet/sdk/issues/12035. The SDK side of this is implemented in https://github.com/dotnet/sdk/pull/12116. Once the SDK part is in, I will update the SDK here to get the integration tests working with the change.
> Update option names and docs

- docs/data-formats.md
- src/linker/Linker.Steps/LinkAttributesStep.cs
- src/linker/Linker/LinkerAttributesInformation.cs
- test/Mono.Linker.Tests.Cases/DataFlow/OverrideAttributeRemoval.cs
- test/Mono.Linker.Tests.Cases/DataFlow/OverrideAttributeRemoval.xml
Added override mechanism for RemoveAttributeInstances option using the descriptor file, fixes #1327
> Add override mechanism for RemoveAttributeInstances

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/Driver.cs
- src/linker/Linker/LinkContext.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerAttributesRemoved.xml
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerDisplayAttributeOnAssemblyUsingTarget.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerDisplayAttributeOnAssemblyUsingTargetOnUnusedType.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerDisplayAttributeOnAssemblyUsingTargetTypeNameInOtherAssembly.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerDisplayAttributeOnTypeCopy.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerDisplayAttributeOnTypeThatIsNotUsed.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerTypeProxyAttributeOnAssemblyUsingTarget.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerTypeProxyAttributeOnType.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnAssemblyUsingTarget.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnAssemblyUsingTargetOnUnusedType.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnAssemblyUsingTargetTypeNameInOtherAssembly.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnAssemblyUsingTargetTypeNameInSameAssembly.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnAssemblyUsingTargetTypeNameOfGenericTypeInOtherAssembly.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnAssemblyUsingTargetTypeNameOfNestedTypeInOtherAssembly.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnGenerics.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnType.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnTypeThatIsNotUsed.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayOnTypeWithCallToExtensionMethodOnFieldType.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayOnTypeWithCallToMethodOnFieldType.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerTypeProxyAttributeOnAssemblyUsingTarget.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerTypeProxyAttributeOnType.cs
- Remove conflicting -v option from ILLink
- Add more test coverage for attributes removal with debugger attributes
> Cleanup debugger attributes removed for ILLink

- test/Mono.Linker.Tests.Cases/DataFlow/LinkerAttributeRemovalWithOverride.xml
- test/Mono.Linker.Tests.Cases/DataFlow/OverrideAttributeRemoval.cs
There is an error in the ci testing currently since the OverrideAttributeRemoval test is not able to find an assembly,  OverrideAttributeRemoval was reusing LinkerAttributeRemoval.xml which was recently changed, this change makes the OverrideAttributeRemoval test to have its own LinkAttributes file
> Fix override attribute removal test

- src/linker/Linker.Steps/MarkStep.cs
Linker tries to mark all instance fields on types referenced from p/invoke signatures but fails for function pointers because of a Cecil footgun (`TypeSpecification` has an `ElementType` property that is the actual element type for pointers/byrefs/arrays, is the generic definition for generic types, and `null` for pointer types).
(We shouldn't actually need to mark the instance fields in the first place because these need to have a non-Auto layout but I digress. If something actually needs that behavior, this is still buggy because it needs to happen recursively to actually work in interop, but CoreCLR would block Auto classes/structs right away.)
Fixes #1345.
> Don't crash if pinvoke has a function pointer

- src/linker/Linker.Steps/ResolveFromAssemblyStep.cs
- src/linker/Linker/Driver.cs
- src/linker/Linker/LinkerAttributesInformation.cs
- src/linker/Linker/LinkerFatalErrorException.cs
- test/ILLink.Tasks.Tests/ILLink.Tasks.Tests.cs
- test/ILLink.Tasks.Tests/Mock.cs
Fixes https://github.com/mono/linker/issues/1319. This will also help with https://github.com/mono/linker/issues/811.
This has two parts:
1. Changes the nullref exception into the following:
```
Unhandled exception. Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Threading.Tasks.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
---> System.IO.FileNotFoundException: Unable to find 'System.Threading.Tasks.dll.dll' or 'System.Threading.Tasks.dll.exe' file
at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
at Mono.Linker.LinkContext.Resolve(String …
```
> Show error for unresolved root assemblies

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Attributes.StructLayout/SequentialClass.cs
If a field is accessed on a sequential/explicit class, we need to keep the instance fields on base types intact so that the offsets match. This happens naturally, except for the case where the type is not seen as allocated and we still have a field access somewhere (which could be in dead code or code that throws a nullreference, or code that did shenanigans with Unsafe.As and actually operates on an instance of a different type).
> Keep base fields of non-auto layout classes

- src/linker/Linker.Steps/TypeMapStep.cs
- src/linker/Linker/TypeReferenceExtensions.cs
I can't tell if I'm deleting a bunch of cargo cults or if this is necessary for something. The tests seem to be passing.
I stumbled over this when trying to find a place where to slot in default interface method support (#427).
TypeMapStep was computing interface implementation by doing two passes:
1. For each interface & for each method on the interface, try to find a name/sig match on the current class and all the bases. If the match happens on the current class, do nothing, otherwise record the overrides/base relationship.
2. For each virtual method on the class & for each interface implemented by the class try to find a name/sig match of the virtual method on the interface. If one is found, record that info.
We were basically running two `O(N*M*L)` algorithms for something that should …
> Simplify interface handling in TypeMapStep

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Basic/DelegateBeginInvokeEndInvokePair.cs
- test/Mono.Linker.Tests.Cases/Basic/NestedDelegateInvokeMethodsPreserved.cs
- test/Mono.Linker.Tests.Cases/Basic/UsedEventIsKept.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/BaseProvidesInterfaceMember/GenericInterfaceWithEvent.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/BaseProvidesInterfaceMember/SimpleEvent.cs
Per ECMA-335 I.8.9.3, the `BeginInvoke` and `EndInvoke` methods are not mandatory. On .NET Core, these methods only throw, so it's unlikely that apps would actually have a reference to them. This lets us strip the methods and the associated interfaces.
> Allow stripping Delegate.BeginInvoke/EndInvoke

- src/linker/Linker.Dataflow/FlowAnnotations.cs
- src/linker/Linker/TypeHierarchyCache.cs
- test/Mono.Linker.Tests.Cases/DataFlow/IReflectDataflow.cs
Fixes #1365.
Extracted the base type caching into a separate class. We might want to make this more global and use this where we're doing similar checks within linker (we have existing code that is checking whether a type is EventSource or deriving from some security attribute). It feels like a general purpose question, but those things are out of scope of this pull request.
> Use class hierarchy in IsTypeInterestingForDataflow

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker.Steps/TypeMapStep.cs
- src/linker/Linker/Annotations.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/DefaultInterfaceMethods/DefaultInterfaceMethodCallIntoClass.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/DefaultInterfaceMethods/GenericDefaultInterfaceMethods.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/DefaultInterfaceMethods/SimpleDefaultInterfaceMethod.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/DefaultInterfaceMethods/UnusedDefaultInterfaceImplementation.cs
- test/Mono.Linker.Tests/Mono.Linker.Tests.csproj
Spec for default interface methods is here: https://github.com/dotnet/runtime/blob/master/docs/design/features/default-interface-methods.md
But the short version is basically:
* Default interface methods only kick in if there's no implementation on the class
* The default implementation can either be provided by the method that declares the interface slot, or by any other interface that requires the interface in question. In that case, we look for an override record. These are not done by name and sig match.
Fixes #427.
> Add support for default interface methods

- docs/error-codes.md
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/TypeReferenceExtensions.cs
- test/Mono.Linker.Tests.Cases/Interop/PInvoke/Warnings/ComPInvokeWarning.cs
COM represents a problem for trimming because the usage of the interfaces are not visible to the linker.
The problem is twofold:
* The IDispatch interface that COM objects can be cast to is basically reflection.
* IUnknown.QueryInterface lets the native side get to any COM visible interface on the managed side. COM visible is pretty much everything because it's the default. We can't root those because it would make trimming ineffective.
> Warn about some COM usage

- src/ILLink.Tasks/LinkTask.cs
- src/linker/Linker/Driver.cs
- test/ILLink.Tasks.Tests/ILLink.Tasks.Tests.cs
- test/ILLink.Tasks.Tests/Mock.cs
Adds the ILLink Task options `WarningsAsErrors` and `WarningsNotAsErrors` which map to the command-line options `--warnaserror` and `--warnaserror-` respectively.
> Add WarningsAsErrors and WarningsNotAsErrors

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerDisplayAttributeOnTypeWithNonExistentMethod.cs
This fixes #1375 the code is inside a loop to get a certain method inside the Type or any of its BaseType. In this case, the method does not exist so the linker should return null but instead while evaluating the BaseType of Object type (which is null) the linker fails to resolve it and ends the execution
> Linker fails when BaseType is null

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/AddSuppressionsBeforeAttributeRemoval.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/AddSuppressionsBeforeAttributeRemoval.xml
Fixes #1392. This will add suppressions before checking if the attribute (`UnconditionalSuppressMessage`) was marked for removal by a custom attribute annotation.
/cc @eerhardt
> Add suppressions before checking for ca removal instances

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/DefaultInterfaceMethods/Dependencies/InterfaceWithAttributeOnImpl.il
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/DefaultInterfaceMethods/InterfaceWithAttributeOnImplementation.cs
Fixes #1394.
The problem was that marking the interface implementation marks the custom attributes on the InterfaceImpl record which enqueues the attribute constructor. The constructor is already processed, but enqueuing a new method causes the main processing loop to run again. This will rerun the virtual method logic and cause the attribute constructor to be re-added, forever.
Normally, linker protects itself from things like this by having a "processed" state along with "marked" state for various entities. InterfaceImpls don't have a "processed" state and calling Mark will cause the same logic to run. Alternative fix would be to add a "processed" state.
There's no regression test because I couldn't get Roslyn to generate the custom attribute on the MethodImpl record. I'm unclear why …
> Do not call MarkInterfaceImplementation if already marked

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterDataFlow.cs
These two are equivalent.
Fixes #1412.
> Allow new() constraint to satisfy DynamicallyAccessedMemberTypes.PublicParameterlessConstructor

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/InterfaceNeededOnUnrelatedInterfaceList.cs
`IsInterfaceImplementationMarkedRecursively` was incorrectly rewritten from a global prepass to a local interface walk in #1186.
The new code was looking at the wrong interface list (looking at `IBar`'s interface list instead of `Bar`). We need to keep looking at the same interface list that we started with.
Fixes #1421.
> Check the correct interface list in IsInterfaceImplementationMarkedRecursively

- docs/error-codes.md
- src/linker/Linker.Steps/MarkStep.cs
It warns about places in COM related interop where we know ILLink could break the app by removing more than it should.
In a way it's similar to refleciton - a mechanism outside of .NET whihc let's you affect the ILLink behavior.
> Waring IL2050 should be considered TrimAnalysis warning

- docs/error-codes.md
- src/linker/Linker/Driver.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/SkipRemainingErrorsValidationAttribute.cs
- test/Mono.Linker.Tests.Cases/Warnings/CanDisableWarnAsError.cs
- test/Mono.Linker.Tests.Cases/Warnings/NoWarnRegardlessOfWarnAsError.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/CanGenerateWarningSuppressionFileXml.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
We pass NoWarn which may contain warning codes for other tools. This is causing failures in https://github.com/dotnet/sdk/pull/12948.
Adds a check that testcases don't produce unexpected errors, which validates this behavior together with this existing testcase: https://github.com/mono/linker/blob/2b04c065c84aa8f30600e3b1989c537fc77de95b/test/Mono.Linker.Tests.Cases/Warnings/CanDisableWarnings.cs#L12
> Don't error on non-IL warning codes

- docs/error-codes.md
- src/linker/Linker.Dataflow/FlowAnnotations.cs
- test/Mono.Linker.Tests.Cases/DataFlow/FieldDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodParametersDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/PropertyDataFlow.cs
- test/Mono.Linker.Tests/TestCasesRunner/LinkerTestLogger.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
`DynamicallyAccessedMembersAttribute` is only supported on items of type `System.Type` or `System.String` (and derived classes) otherwise linker will ignore it. When it happens it's very likely not intentional and so linker should warn about it. Since it only affects analysis results, these are marked as TrimAnalysis.
> Warn when DynamicallyAccessedMembersAttribute is used on a member of unsupported type

- src/linker/Linker/TypeReferenceExtensions.cs
We currently assume that generic type names always encode its arity in the IL, whereas the ECMA explicitly states that both the grave accent and arity are optional.
Fixes #1435 and #1448
> Check if generic types encode its arity when using GetDisplayName

- Directory.Build.props
- eng/Versions.props
- external/Mono.Cecil.overrides
Doing this will change a few things:
- Our package will no longer include Mono.Cecil.Mdb or Mono.Cecil.Rocks. (These all included with the official package, but we don't depend on them when building against the individual projects. We might want to filter them out even when we go back to building against the package).
- The ref package produced from `release/5.0` will now have a dependency on the local cecil version (it gets a `5.0.0-rc*` version from our Versions.props). To consume it, the consuming project needs to include a version of Mono.Cecil compatible with this version, which in practice probably means also building against the submodule and giving it a custom version. @marek-safar I assume that this is OK since we will go back to shipping with the official package when use the …
> [release/5.0] Build against Cecil submodule

- src/linker/Mono.Linker.csproj
Linker doesn't need it and it causes us to carry 3 more files in the SDK.
> Remove reference to System.Text.Json

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MemberTypes.cs
The method recursively calls itself to mark nested types and base types. This means that if nested type has the parent type as its base type, the method will cause stack overflow.
Fixing this by adding a hash of already visited types to break the recursion.
Added tests for the repro and similar cases.
Should fix #1470 (although we don't have a repro, so it's hard to validate)
> Fix possible endless recursion in MarkEntireType

- src/linker/Mono.Linker.csproj
Linker doesn't need it and it causes us to carry 3 more files in the SDK.
This is the 5.0 port of #1480
> [release/5.0] Remove reference to System.Text.Json (#1480)

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MemberTypes.cs
This is a port of https://github.com/mono/linker/pull/1478 to relelase/5.0
> [release/5.0] Fix possible endless recursion in MarkEntireType (#1478)

- test/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerDisplayAttributeOnTypeCopy.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/DefaultInterfaceMethods/DefaultInterfaceMethodCallIntoClass.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/DefaultInterfaceMethods/GenericDefaultInterfaceMethods.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/DefaultInterfaceMethods/SimpleDefaultInterfaceMethod.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/DefaultInterfaceMethods/UnusedDefaultInterfaceImplementation.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/AttributesScopeUpdated.cs
Every test .cs file must be able to resolve a type of the same name during test execution.  Otherwise it triggers a warning and if warnings ever accumulate it becomes impossible to notice when you have a test type name that doesn't match the file name
The rule of thumb to follow is, never #if out the test case type definition.  Include an ignore and and exclude any code that can't compile.
* Fix `DebuggerDisplayAttributeOnTypeCopy` only existing when `NETCOREAPP` is defined.  I just removed the define.  I don't see why it wouldn't work on .NET Framework
* Fix `DefaultInterfaceMethodCallIntoClass` only existing when `NETCOREAPP` is defined.  I most of the test is #if away when not `NETCOREAPP` app and an `[IgnoreTestCase]` is included
* Fix `GenericDefaultInterfaceMethods` only existing …
> Fix some tests

- src/linker/Mono.Linker.csproj
Following @MichalStrehovsky advice I set the `ServerGarbageCollection`... and it looks good.
The server GC mode allows for multiple GC threads to exists simultaneously - one for each CPU available. It improves the throughput of the linker quite a bit by allowing the GC to process as much data as it can in a time unit. Trade off here is memory cost: memory use will be higher, since GCs will happen less often.
Linking a hello world app with `ServerGarbageCollection` set improves the linker total CPU time by ~20% (20,600ms vs 16,380ms) and brings down the total GC pause from 4,816.2ms to 317.4ms, the peak GC process working set augmented from 304MB to 371MB (of course perf gains are dependent upon # of CPUs - I ran this on a machine with 6 processors.)
> Use ServerGarbageCollection=true

- src/linker/Linker/DirectoryAssemblyResolver.cs
`ReaderParams` gets allocated multiple times inside `DirectoryAssemblyResolver`, accounting for about 4.6% of the memory allocated in the process when linking a hello world app. Preventing this many allocations can help us improve the performance of the linker just a little bit by easing up the GC work.
Comparison table (linking a hello world app)
|                      | Before   | After    |
|----------------------|----------|----------|
| Total Allocs            | 324MB | 305MB |
| Total CPU Time       | 20,642ms | 19,672ms |
| Total GC CPU Time    | 4,546ms  | 4,235ms  |
| Total GC Pause       | 4,795ms  | 4,468ms  |
| % Time paused for GC | 24%      | 23.2%    |
/cc @agocke
> Prevent multiple allocations of ReaderParameters

- src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/TryFilterBlocks.cs
> [5.0] Process also exception filters when marking unreachable blocks

- src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/Dependencies/LocalsWithoutStore.il
- test/Mono.Linker.Tests.Cases/UnreachableBlock/UninitializedLocals.cs
Should avoid #1508 from happening. I suspect that the only way in which the key wouldn't exist here is by linking unverifiable CIL. From the ECMA: 
> For verifiable code, this instruction [ldloc] shall guarantee that it is not loading an uninitialized value –
> whether that initialization is done explicitly by having set the localsinit bit for the method, or by
> previous instructions (where the CLI performs definite-assignment analysis).
/cc @agocke
> Use TryGetValue when retrieving local variables from stack

- src/linker/Linker/Driver.cs
We have our own driver class and would like to reuse this helper method to parse the value of the --generate-warning-suppressions
> Expose method on Driver

- src/linker/Linker/TypeNameResolver.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflection.cs
When TypeParser.ParseTypeName hits an exception it returns null.  That null leads to NullReferenceException here https://github.com/mono/linker/blob/b89cb90abdfdc4e1ccd0822b62d367fa35d30f00/src/linker/Linker/TypeNameResolver.cs#L80 which then leads to the exception below.
```
Mono.Linker.LinkerFatalErrorException: ILLink: error IL1005: Mono.Linker.Tests.Cases.Reflection.TypeUsedViaReflectionInvalidName.Main(): Error processing method 'Mono.Linker.Tests.Cases.Reflection.TypeUsedViaReflectionInvalidName.Main()' in assembly 'test.exe' ---> System.InvalidOperationException: Internal error: A reflection pattern was analyzed, but no result was reported. System.Void Mono.Linker.Tests.Cases.Reflection.TypeUsedViaReflectionInvalidName::Main() -> System.Type System.Type::GetType(System.String)
at …
```
> Fix reflection pattern error

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/LinkAttributesStep.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/TypeNameResolver.cs
- test/Mono.Linker.Tests.Cases/DataFlow/ApplyTypeAnnotations.cs
We always assumed that the generic parameters would come from the same assembly as the generic type itself.
Adds a new test to validate the scenario.
Fixes the primary issue in #1536 
The other parts to make that scenario work fully are tracked by different issues.
> Correctly handle assembly qualified names in generic parameters

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/MarkStep.cs
Allow ReflectionMethodBodyScanner's HandleCall() to skip processing an instruction if its MarkStep's ProcessReflectionDependency() returns true.
> Allow skipping the processing of a reflection call if its MarkStep's ProcessReflectionDependency() returns true

- test/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/CanLinkCoreLibrariesWithOnlyKeepUsedAttributes.cs
This test fails on windows when ran against .NET FW class libraries because System.dll fails peverify
> Fix CanLinkCoreLibrariesWithOnlyKeepUsedAttributes

- src/linker/Linker.Steps/MarkStep.cs
Previously we overrode `GetRequiredMethodsForInstantiatedType` and used that to disable marking of Finalize during a special use case we have.
That broke with https://github.com/mono/linker/commit/9c84659e8ff12a7af366a5f4d64ffc6c3623618c
This PR adds a simple bool property to allow us to switch the new behavior that change added off.
> Restore the ability to not mark System.Object.Finalize

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/XmlDependencyRecorder.cs
This gives us a way to punt on giving reasons to all of our marking behaviors.
> Don't record unspecified dependencies

- test/Mono.Linker.Tests.Cases/Warnings/Dependencies/TriggerWarnings_Lib.cs
- test/Mono.Linker.Tests.Cases/Warnings/Individual/CanGenerateWarningSuppressionFileCSharp.cs
- test/Mono.Linker.Tests.Cases/Warnings/Individual/CanGenerateWarningSuppressionFileXml.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsUsingTargetViaXml.cs
* Explicitly declare a reference to System.Core.dll
* Remove unused using statement
* Use typeof overload instead of string to make it easier trace usages
> Test Clean up

- src/linker/Linker.Steps/DynamicDependencyLookupStep.cs
- test/Mono.Linker.Tests.Cases/DynamicDependencies/Dependencies/DynamicDependencyFromAttributeXmlOnNonReferencedAssemblyLibrary.cs
- test/Mono.Linker.Tests.Cases/DynamicDependencies/DynamicDependencyFromAttributeXmlOnNonReferencedAssembly.cs
- test/Mono.Linker.Tests.Cases/DynamicDependencies/DynamicDependencyFromAttributeXmlOnNonReferencedAssembly.mono.Attributes.xml
- test/Mono.Linker.Tests.Cases/DynamicDependencies/DynamicDependencyFromAttributeXmlOnNonReferencedAssembly.netcore.Attributes.xml
The `DynamicDependencyLookupStep` would not process `DynamicDependencyAttribute` specified via XML on a member without real attributes (from IL).
Fix is to not rely on `member.HasCustomAttributes` as that doesn't see attributes specified via XML.
Fixes #1547
> Fix processing of DynamicDependency when specified via attribute XML

- test/Mono.Linker.Tests.Cases/References/ReferencesAreRemovedWhenAllUsagesAreRemoved.cs
This fixes ReferencesAreRemovedWhenAllUsagesAreRemoved when ran from monolinker.sln on Windows.
> Fix ReferencesAreRemovedWhenAllUsagesAreRemoved

- src/linker/Linker.Steps/RemoveFeaturesStep.cs
- test/Mono.Linker.Tests.Cases/BCLFeatures/ETW/BaseRemovedEventSource.cs
- test/Mono.Linker.Tests.Cases/BCLFeatures/ETW/BaseRemovedEventSourceEmptyBody.cs
- test/Mono.Linker.Tests.Cases/BCLFeatures/ETW/BaseRemovedEventSourceNonVoidReturn.cs
- test/Mono.Linker.Tests.Cases/BCLFeatures/ETW/Excluded.cs
- test/Mono.Linker.Tests.Cases/BCLFeatures/ETW/NonEventWithLog.cs
- test/Mono.Linker.Tests.Cases/BCLFeatures/ETW/StubbedMethodWithExceptionHandlers.cs
It is somewhat common for the ETW pattern to be incorrectly implemented.  For example the `IsEnabled` check can be inside of the method on the EventSource type.  When we replace the body with a throw this leads to
runtime exceptions.  Let's just clear the bodies of the methods on the EventSource type when the return type is void.  For non-void returning methods let's continue to add a throw since replacing the body with something like `return null` could result in unexpected errors later down the line.
> Stub void return ETW bodies instead of throw

- test/Mono.Linker.Tests.Cases/DataFlow/ComplexTypeHandling.cs
Mostly array resolution issue related to https://github.com/mono/linker/pull/1566
Note that all of these are disabled - even though I wrote them to pass since the other tests in this class crash the linker for now.
> Add test cases for complex type data flow tests

- src/linker/ref/Linker/MessageOrigin.cs
This makes it much easier for custom steps to log messages pointing to code. Linker has the code to figure out source/line information from member reference and IL offset, opening this .ctor makes this code available to custom steps.
> Make the MessageOrigin..ctor which takes a member reference public

- src/ILLink.Tasks/ILLink.Tasks.csproj
- src/linker/Mono.Linker.csproj
- test/ILLink.Tasks.Tests/ILLink.Tasks.Tests.csproj
The goal is to build a package which has the ref assembly in it and a package dependency on Mono.Cecil package (which acts like ref for Mono.Cecil and Mono.Cecil.Pdb).
NuGet automatically converts all ProjectReferences into package dependencies - to avoid that PrivateAssets=all must be added.
Fixes https://github.com/mono/linker/issues/1579
> Exclude Mono.Cecil.Pdb from package dependencies

- external/corert/src/System.Private.CoreLib/src/System/Reflection/Runtime/TypeParsing/TypeName.cs
- src/linker/Linker.Dataflow/MethodBodyScanner.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker/TypeNameResolver.cs
- src/linker/Linker/TypeReferenceExtensions.cs
- test/Mono.Linker.Tests.Cases/DataFlow/ApplyTypeAnnotations.cs
- test/Mono.Linker.Tests.Cases/DataFlow/ComplexTypeHandling.cs
- test/Mono.Linker.Tests.Cases/DynamicDependencies/DynamicDependencyFromCopiedAssembly.cs
- test/Mono.Linker.Tests.Cases/Reflection/PropertyUsedViaReflection.cs
Currently, the linker won't mark the generic arguments of a dynamically accessed type that is passed as a string. For an example, see #1537.
> Mark generic arguments of dynamically accessed types passed as string

- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs
Sample test for https://github.com/mono/linker/issues/1607 - test is disabled as it will fail currently.
> Adding test case for RequiresUnreferencedCode on a method refered to only by reflection

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/Driver.cs
- src/linker/Linker/LinkContext.cs
- test/Mono.Linker.Tests.Cases/Advanced/TypeCheckRemovalDisabled.cs
It's needed in quirky linker mode used for libraries build
> Add command line option to disable type checks inlining

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/DataFlow/EmptyArrayIntrinsicsDataFlow.cs
With https://github.com/dotnet/runtime/issues/42753, we are adding a new overload to Type.GetConstructor that only takes BindingFlags and Type[].
However, this new overload exposes a bug in the ILLinker where it is using the wrong parameter count to find how many constructor parameters are being used.
Fixing the issue by using the correct parameter count in the switch statement.
@vitek-karas @MichalStrehovsky @marek-safar
> Fix ArgumentOutOfRange in GetConstructor scanning

- src/linker/Linker.Steps/MarkStep.cs
Marking fields and methods of the type should already take care of marking
generic arguments of the base type.
Fixes https://github.com/mono/linker/issues/1627
> Remove incorrect assert

- src/linker/Linker.Steps/MarkStep.cs
Backport of #1535
> When we fail to resolve a type we try and recreate it and keep the IL valid rather than fail.  We have a test that ensures an unresolved attribute on an AssemblyDefinition can be recreated.  It started failing with the sync up.   LazyMarkCustomAttributes should not skip any attributes.  This would give inconsistent behavior with references that only have attributes marked.  It was also problematic because LazyMarkCustomAttributes would call HandleUnresolvedType on the type where as ProcessLazyAttributes will call HandleUnresolvedMethod. A call to HandleUnresolvedMethod is necessary for us to recreate valid IL.
> I went ahead and added null checks to other places that were missing them.
> [release/5.0] Unresolved attribute fixes

- src/linker/Linker/Driver.cs
- test/ILLink.Tasks.Tests/ILLink.Tasks.Tests.cs
- test/ILLink.Tasks.Tests/Mock.cs
- test/Mono.Linker.Tests/Tests/ParseResponseFileLinesTests.cs
Fixes https://github.com/mono/linker/issues/1638
The generated response file has newlines and whitespace like this:
```
--warnaserror "
CS8600;
CS8601;
"
```
but the response file parser assumed that each argument was on a single line:
https://github.com/mono/linker/blob/bfab847356063d21eb15e79f2b6c03df5bd6ef3d/src/linker/Linker/Driver.cs#L88
This fixes the parser to handle newlines correctly, and allows more whitespace between the warning codes.
> Fix handling of newlines in warning arguments

- src/linker/Linker.Dataflow/MethodBodyScanner.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker/TypeReferenceExtensions.cs
- test/Mono.Linker.Tests.Cases/DataFlow/ComplexTypeHandling.cs
- test/Mono.Linker.Tests.Cases/Reflection/PropertyUsedViaReflection.cs
This PR mimics the behavior of #1566 without making use of the new type name parser introduced in #1472.
> [release/5.0] Mark generic arguments of dynamically accessed types

- src/linker/Linker/DocumentationSignatureParser.cs
- src/linker/Linker/ModuleDefinitionExtensions.cs
- src/linker/Linker/TypeNameResolver.cs
- test/Mono.Linker.Tests.Cases/DynamicDependencies/Dependencies/FacadeAssembly.cs
- test/Mono.Linker.Tests.Cases/DynamicDependencies/Dependencies/ImplementationLibrary.cs
- test/Mono.Linker.Tests.Cases/DynamicDependencies/Dependencies/ReferenceImplementationLibrary.cs
- test/Mono.Linker.Tests.Cases/DynamicDependencies/DynamicDependencyOnForwardedType.cs
- test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
The linker currently fails to resolve forwarded types that were passed as strings since these exist in a module's exported types, which we never look into.
> Try to resolve type from exported types

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupCompileBeforeAttribute.cs
- test/Mono.Linker.Tests.Cases/DataFlow/Dependencies/UnresolvedLibrary.cs
- test/Mono.Linker.Tests.Cases/DataFlow/UnresolvedMembers.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
- test/Mono.Linker.Tests/TestCasesRunner/SetupCompileInfo.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestCaseCompiler.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestCaseMetadaProvider.cs
Unresolved types should be handled as "unknown" value nodes. This is already the case when they appear in a method body. But when they're used either as generic arguments or in attribute instantiations linker doesn't handle this case correctly.
For generics linker would fail with an exception. For attributes linker would ignore the type.
Both cases are wrong since linker needs to make sure to issue a warning if it can't guarantee to meet the requirements posed by the data flow annotations. So ignoring unresolved types is also wrong.
The change fixes these behaviors to treat the value as "unknown" which leads into warnings when used somewhere with data flow requirements.
There's also a small change in where the attribute related warnings are reported - now they should consistently report …
> Fix linker crash on unresolved types in generic and attribute data flow handling

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/Reflection/UnderlyingSystemType.cs
This is used in CoreLib a lot and we shouldn't lose tracking for this.
> Recognize UnderlyingSystemType as an intrinsic

- src/analyzer/ConsoleDependencyGraph.cs
Avoid getting caught in infinite loops. I think these are related to
new `DynamicDependency` attributes. So stop graph traversal and report
the loop as warning.
> [analyzer] Break infinite loops

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/DataFlow/Dependencies/UnresolvedLibrary.cs
- test/Mono.Linker.Tests.Cases/DataFlow/UnresolvedMembers.cs
Fixes https://github.com/mono/linker/issues/1634
This is a servicing version of https://github.com/mono/linker/pull/1645
Only the necessary changes to make the fix - no cleanup, no better warnings, no new test features.
If linker finds an unresolved type used in either attribute parameter, or generic parameter and the parameter has data flow annotations on it, linker will fail and cause the entire dotnet publish to fail as well.
Unresolved types are relatively common for linker and it should be able to handle these without failing.
Any application which contains references to types which are not in the application closure may fail to link (depending on where and how the type is used). Missing types or assemblies are relatively common, for example even the core framework has references to …
> [release/5.0] Fix linker crash on unresolved types in generic and attribute data flow handling

- docs/data-formats.md
Some additional description of the various formats and when/how they can be used.
> Add description how to embed linker XML files

- src/linker/Linker.Steps/SweepStep.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/AttributeArgumentForwarded.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/ForwarderLibrary.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/ImplementationLibrary.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/ReferenceImplementationLibrary.cs
Sweep step resolves type forwarders and replaces them with direct type refs. There were already special cases for generic instantiations and array, but other type specifications were missing, most notably pointer types.
Added handling of all type specifications and added some tests.
Fixes #1673
> Fix pointer type forwarding

- test/Mono.Linker.Tests/TestCasesRunner/TestCaseSandbox.cs
It makes failing tests diagnostics much easier.
> Use artifacts folder as a location for test cases artefacts.

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GetTypeDataFlow.cs
- test/Mono.Linker.Tests.Cases/Reflection/AsType.cs
These popped up in an app that I was analyzing. The string.Empty occurence causes a spurious warning in framework code (https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.ObjectModel/src/System/ComponentModel/TypeConverterAttribute.cs#L27).
> Add intrinsic handling of AsType and String.Empty

- test/Mono.Linker.Tests.Cases/LinkAttributes/Dependencies/LinkerAttributeRemovalEmbeddedAndLazyLoad.cs
- test/Mono.Linker.Tests.Cases/LinkAttributes/LinkerAttributeRemoval.cs
- test/Mono.Linker.Tests.Cases/LinkAttributes/LinkerAttributeRemoval.xml
Currently this doesn't work as it should, the test is to cover the scenario - once we fully implement lazy loading this should be fixed.
> Add a test for attribute removal using wildcard and lazy loading

- src/linker/Linker.Dataflow/DynamicallyAccessedMembersBinder.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/Reflection/ActivatorCreateInstance.cs
- test/Mono.Linker.Tests.Cases/Reflection/ConstructorUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/EventUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/FieldUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/MethodUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/NestedTypeUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/PropertyUsedViaReflection.cs
-Add a flag to mark when the overload has a binding flag that the linker could not figure out
-Mark everything when an unknown binding flag is present
-Add tests
Fixes #1617
> Mark everything if BindingFlags are not recognized by the linker

- src/ILLink.RoslynAnalyzer/RequiresUnreferencedCodeAnalyzer.cs
- test/ILLink.RoslynAnalyzer.Tests/LinkerTestCases.cs
-Check for the parent to see if it has any UnreferencedCodeAttribute
-Since AllowMultiple is disabled by default, only check the attributes until first UnreferencedCodeAttribute is found
> Support for RequiresAndCallsOtherRequiresMethods

- src/ILLink.RoslynAnalyzer/ILLink.RoslynAnalyzer.csproj
This packs the analyzer build so that we can integrate it with the SDK and remove the single-file analyzer from dotnet/roslyn-analyzers.
> Package ILLink.RoslynAnalyzer for SDK

- docs/design/assembly-loading.md
This is a proposal for lazy loading to solve https://github.com/mono/linker/issues/1164 and related issues. This replaces the plan outlined in https://github.com/mono/linker/issues/1164#issuecomment-714732178, but there is some overlap because we still need to process references up-front for the `copy` action, if we want to preserve the current behavior.
I created a new branch for the feature that we can use to avoid breaking the constant propagation behavior in master.
> Add design for lazy loading

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GetNestedTypeOnAllAnnotatedType.cs
If the parent type value is annotated with `DynamicallyAccessedMemberTypes.All` then the GetNestedType can return a value also annotated with `DynamicallyAccessedMemberTypes.All` since the `All` is recursively applied to nested types (`MarkStep.MarkEntireType` basically recursively calls `MarkEntireType` on nested types).
This helps with patterns like:
```C#
void Test([DynamicallyAccessedMembers(All)] parentType)
{
parentType.GetNestedType("KnownNestedType").GetFields();
}
```
Without this there would be no way to do this without warning suppressions, even though it's a perfectly valid code as per the rules around `All`.
> Better intrinsic handling of GetNestedType if input has All

- src/linker/Linker/Annotations.cs
- src/linker/Linker/Driver.cs
- src/linker/Linker/TypeMapInfo.cs
Separating this change out from https://github.com/mono/linker/pull/1666. This implements the behavior described in the first point under https://github.com/mono/linker/blob/feature/lazyload/docs/design/assembly-loading.md#additional-processing-done-lazily.
> The overrides tracked for a method may be incomplete, and will be updated as new assemblies are loaded. This is compatible with the current design of MarkStep which re-processes virtual methods, but this could be optimized in the future.
> Run TypeMap logic on demand

- NuGet.config
That site is no longer available (returns 404) - and we don't need it to build anymore.
> Fix the build after removal of dotnet.myget.org

- src/ILLink.RoslynAnalyzer/SingleFileAnalyzer.cs
These rules had a help link when they were in roslyn-analyzers repository (see https://github.com/dotnet/roslyn-analyzers/pull/4680/), but the help link was lost after porting it here.
This PR adds the help link back.
Tagging @mavasani in case he wants the documentation to be ported from dotnet/docs to somewhere else.
> Add help link for IL3000 and IL3001

- src/analyzer/README.md
As per the actual property checked in https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ILLink.targets#L122
> Updating the Linker Analyzer readme to use _TrimmerDumpDependencies

- src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs
- test/Mono.Linker.Tests.Cases.Expectations/Support/IntrinsicAttribute.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/BodiesWithSubstitutions.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/BodiesWithSubstitutions.xml
In #1734 a change was made that substitutions are only considered for methods which are not intrinsic or no-inline. That is not how it should work, even intrinsic or no-inline methods should still allow substitutions and constant propagation from those.
What intrinsic and no-inline methods should not do is participate in constant propagation as intermediate methods (so methods which become constant because they're calling other constant methods).
In short substitutions effectively override the intrinsic/no-inline.
Added test cases.
Fixes #1747
> Fix constant prop around intrinsic

- NuGet.config
That site is no longer available (returns 404) - and we don't need it to build anymore.
> [release/5.0] Fix the build after removal of dotnet.myget.org

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/Reflection/MethodUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflection.cs
We have special handling for cases where ignoreCase is not constant false (since linker won't be able to correctly mark the required types). This handling was written such that it assumed the value for the parameter was "known" that is we know at least something about it. If it's completely unknown, that's represented as null and the code crashes on it.
Added a test case for this and made the fix.
Fixes #1741
> Fix nullref caused by unknown value to the ignoreCase parameter of Type.GetType

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/DependencyInfo.cs
- test/Mono.Linker.Tests.Cases/Attributes/TypeWithDynamicInterfaceCastableImplementationAttributeIsKept.cs
This PR adds support to the linker for IDynamicInterfaceCastable implementation types. These types might be referenced statically in an IDynamicInterfaceCastable implementation (custom targeted COM wrappers scenario), but they also may be dynamically discovered via reflection (C#/WinRT scenario).
This PR collects a list of all types with the `DynamicInterfaceCastableImplementationAttribute` applied that implement at least one interface and only marks them if any interface they implement is marked.
By collecting the list of types to mark in this way at initialization time, we handle both the dynamic and static cases at once.
Fixes #1244
> Keep types marked with DynamicInterfaceCastableImplementationAttribute when any interface they implement is kept

- test/Mono.Linker.Tests.Cases/DataFlow/MemberTypes.cs
- test/Mono.Linker.Tests.Cases/DynamicDependencies/DynamicDependencyMemberTypes.cs
Delegates are nested types (with special base class) - so they should behave exactly like nested types with regard to data flow annotations.
> Add tests validating annotation behavior on delegates

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/Reflection/MethodUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflection.cs
5.0 port of #1752 
Fix for #1741
> [release/5.0] Fix nullref caused by unknown value to the ignoreCase parameter of Type.GetType

- docs/error-codes.md
- src/linker/Linker.Steps/MarkExportedTypesTargetStep.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker.Steps/RootAssemblyInputStep.cs
- src/linker/Linker.Steps/SweepStep.cs
- src/linker/Linker/Annotations.cs
- src/linker/Linker/Driver.cs
- src/linker/Linker/TypePreserve.cs
- src/linker/Linker/TypePreserveMembers.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptMemberInAssemblyAttribute.cs
- test/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupCompileBeforeAttribute.cs
- test/Mono.Linker.Tests.Cases/Libraries/CanLinkPublicApisOfLibrary.cs
- test/Mono.Linker.Tests.Cases/Libraries/Dependencies/RootLibraryVisibleForwarders_Lib.cs
- test/Mono.Linker.Tests.Cases/Libraries/RootLibraryVisibleAndDescriptor.cs
- test/Mono.Linker.Tests.Cases/Libraries/RootLibraryVisibleAndDescriptor.xml
- test/Mono.Linker.Tests.Cases/Libraries/RootLibraryVisibleForwardersWithoutReference.cs
- test/Mono.Linker.Tests.Cases/LinkXml/Dependencies/UsedNonRequiredExportedTypeIsKeptWhenRooted_fwd.cs
- test/Mono.Linker.Tests.Cases/LinkXml/Dependencies/UsedNonRequiredExportedTypeIsKeptWhenRooted_lib.cs
- test/Mono.Linker.Tests.Cases/LinkXml/Dependencies/UsedNonRequiredExportedTypeIsKept_fwd.cs
- test/Mono.Linker.Tests.Cases/LinkXml/Dependencies/UsedNonRequiredExportedTypeIsKept_lib.cs
- test/Mono.Linker.Tests.Cases/LinkXml/UsedNonRequiredExportedTypeIsKept.cs
- test/Mono.Linker.Tests.Cases/LinkXml/UsedNonRequiredExportedTypeIsKept.xml
- test/Mono.Linker.Tests.Cases/LinkXml/UsedNonRequiredExportedTypeIsKeptWhenRooted.cs
- test/Mono.Linker.Tests.Cases/LinkXml/UsedNonRequiredExportedTypeIsKeptWhenRooted.xml
- test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
- test/Mono.Linker.Tests/TestCasesRunner/SetupCompileInfo.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestCaseCompiler.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestCaseMetadaProvider.cs
- test/Mono.Linker.Tests/Tests/PreserveActionComparisonTests.cs
- It'd be too messy to track inside single enum
- Delay resolving exported types to the point where all references are known
Contributes to #1610
> Refactor type members preservation coming from assembly roots.

- src/linker/Linker.Steps/RootAssemblyInputStep.cs
- test/Mono.Linker.Tests.Cases/Libraries/CopyUsedAssemblyWithMainEntryRoot.cs
- test/Mono.Linker.Tests.Cases/Libraries/Dependencies/CopyUsedAssemblyWithMainEntryRoot_Lib.cs
I noticed this when some of my lazy loading tests started failing after a rebase: an explicit copyused root assembly doesn't get the entry point marked because of the missing case in Initialize. It looks like the bug has been there for a while, but it didn't show up because our tests used `[SetupLinkerUserAction ("copyused")]` - in this case, `ResolveFromAssemblyStep` would change the action of a root assembly to `link`. But when copyused is set explicitly for an assembly via "-p", we forget to root it.
This change fixes it by treating `copyused` the same as `link` in the root step - this will also have the side effect of changing the action to `copy` if the root mode was `AllMembers`.
> Ensure that CopyUsed entry point gets marked

- docs/error-codes.md
- src/ILLink.RoslynAnalyzer/ILLink.RoslynAnalyzer.csproj
- src/ILLink.RoslynAnalyzer/RequiresAssemblyFilesAnalyzer.cs
- src/ILLink.RoslynAnalyzer/RequiresUnreferencedCodeAnalyzer.cs
- src/ILLink.RoslynAnalyzer/Resources.resx
- src/ILLink.RoslynAnalyzer/xlf/Resources.cs.xlf
- src/ILLink.RoslynAnalyzer/xlf/Resources.de.xlf
- src/ILLink.RoslynAnalyzer/xlf/Resources.es.xlf
- src/ILLink.RoslynAnalyzer/xlf/Resources.fr.xlf
- src/ILLink.RoslynAnalyzer/xlf/Resources.it.xlf
- src/ILLink.RoslynAnalyzer/xlf/Resources.ja.xlf
- src/ILLink.RoslynAnalyzer/xlf/Resources.ko.xlf
- src/ILLink.RoslynAnalyzer/xlf/Resources.pl.xlf
- src/ILLink.RoslynAnalyzer/xlf/Resources.pt-BR.xlf
- src/ILLink.RoslynAnalyzer/xlf/Resources.ru.xlf
- src/ILLink.RoslynAnalyzer/xlf/Resources.tr.xlf
- src/ILLink.RoslynAnalyzer/xlf/Resources.zh-Hans.xlf
- src/ILLink.RoslynAnalyzer/xlf/Resources.zh-Hant.xlf
- test/ILLink.RoslynAnalyzer.Tests/RequiresAssemblyFilesAnalyzerTests.cs
- test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs
- test/ILLink.RoslynAnalyzer.Tests/TestCaseUtils.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs
PR for #1786
-Change resource file to have a default message and accept arguments
-Add test for RequiresAssemblyFilesAttribute with Url named argument only
> RequiresAssemblyFilesAttribute resource manager changes

- src/linker/Linker/LinkContext.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MemberTypes.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodThisDataFlow.cs
- test/Mono.Linker.Tests.Cases/DynamicDependencies/DynamicDependencyMemberTypes.cs
- test/Mono.Linker.Tests.Cases/LinkXml/EmbeddedLinkXmlUnresolvedReferencesAreReported.cs
- test/Mono.Linker.Tests.Cases/LinkXml/LinkXmlErrorCases.cs
- test/Mono.Linker.Tests.Cases/LinkXml/LinkXmlErrorCases.xml
- test/Mono.Linker.Tests.Cases/LinkXml/PreserveIndividualMembersOfNonRequiredType.cs
- test/Mono.Linker.Tests.Cases/LinkXml/PreserveIndividualMembersOfNonRequiredType.xml
- test/Mono.Linker.Tests.Cases/LinkXml/UsedNonRequiredTypeIsKeptWithSingleMethod.cs
- test/Mono.Linker.Tests.Cases/Reflection/EventUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/ExpressionPropertyString.cs
- test/Mono.Linker.Tests.Cases/Reflection/MethodUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/PropertyUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/RuntimeReflectionExtensionsCalls.cs
Whole runtime repo now passes with it and I could not repro xamarin issue
locally. If this will turn out problem again it can now temporary disabled
on per assembly basis.
> Reenable default UnreachableBodies optimization

- test/Mono.Linker.Tests.Cases/Reflection/ExpressionCallString.cs
A sample test for https://github.com/mono/linker/issues/1819
Also some general improvement of the test in this file (more precise validation, better naming)
> Add a test for using Expression.Call on a generic method

- src/linker/Linker.Steps/SweepStep.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/LibraryWithSecurityAttributes.il
- test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/SecurityAttributeForwarderLibrary.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/SecurityAttributeScope.cs
This fixes a bug in the linker where it would not update the scope of TypeReferences on ISecurityAttributeProviders
This would result in references to `netstandard` surviving linking in situations where netstandard was linked away and SecurityAttribute's survived.  For us this would happen when facades were linked away and an assembly had the `AssemblyAction.Copy`.  There may have been other scenarios where it was possible to hit this.
I did not write a test for this.  It would be hard to write one.  I don't think it's worth the effort.
> Fix scopes not updated on SecurityAttributes

- src/ILLink.Tasks/Sdk/Sdk.props
If the Microsoft.NET.ILLink.Tasks package is package referenced directly, overwriting `ILLinkTasksAssembly` guarantees that the SDK uses the right ILLink assembly. Github org searches didn't show any consumer of the private properties, hence removing them for simplification.
https://github.com/dotnet/arcade/pull/6936 benefits from this change.
> Overwrite ILLinkTasksAssembly

- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapabilityReflectionAnalysisEnabled.cs
The intended behavior is:
* Callers will get a warning due to the `RequiresUnreferencedCode`
* Callers will apply the requirements of the `DynamicallyAccessedMembers` on the method parameters
* The method body will not produce data flow warnings
* The method body is still fully analyzed and if it adds requirements on something that will be applied
Test for https://github.com/mono/linker/issues/1815
> Add a test to validate that using RequiresUnreferencedCode and DynamicallyAccessedMembers on the same method works

- src/ILLink.Tasks/ILLink.Tasks.csproj
- src/ILLink.Tasks/build/Microsoft.NET.ILLink.Tasks.props
- src/ILLink.Tasks/sdk/Sdk.props
Having both a build and sdk folder allows the package not just be used as an SDK package but also used via a PackageReference with which the .props file gets honored then. This is needed for the linker tests in dotnet/runtime but is generally the recommended pattern when creating sdk packages.
> Allow illink pkg to be referenced directly

- src/ILLink.Tasks/ILLink.Tasks.csproj
- src/ILLink.Tasks/sdk/Sdk.props
The PackageType was missing to indicate that the package is an msbuild sdk package, and the `Sdk` folder should start with a capital S. Hopefully that fixes the issue that we observed.
> Fix Sdk folder path in linker.tasks pkg

- eng/azure-pipelines.yml
We don't run tests there so we get a warning about missing test result files in the official build.
> Don't publish test results in official build

- src/ILLink.Tasks/ILLink.Tasks.csproj
- src/ILLink.Tasks/build/Microsoft.NET.ILLink.Tasks.props
- src/ILLink.Tasks/build/Microsoft.NET.ILLink.Tasks.targets
- src/ILLink.Tasks/sdk/Sdk.props
- src/ILLink.Tasks/sdk/Sdk.targets
NuGet generated props and targets are imported before the SDK's props and targets. To avoid the SDK overriding the nuget path, add an additional property which is being checked on.
> Don't override the ILLinkTaskAssembly in the SDK

- .editorconfig
Git usually handles this correctly, and there are a number of problems with using LF locally on Windows.
For instance, testing code fixes needs to have a baseline file, but the codefix APIs always insert
Environment.Newline when applying the refactoring, which makes it difficult to record the baseline in the file.
> Remove line ending config from editorconfig

- .editorconfig
- eng/azure-pipelines.yml
- lint.cmd
- lint.sh
Latest lint writes formatDiagnosticLog.binlong next to the solution file when running with --verbosity diagnostic. There's no way to redirect or disable this - https://github.com/dotnet/format/issues/1041.
So this change disables --verbosity diagnostic for local runs of lint and adds it only to the CI (where the machine will clean the enlistment anyway).
> Fix lint to avoid generating binlog file

- docs/error-codes.md
- src/linker/Linker.Dataflow/MethodBodyScanner.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Dataflow/ValueNode.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Resources/Strings.Designer.cs
- src/linker/Resources/Strings.resx
- src/linker/Resources/xlf/Strings.cs.xlf
- src/linker/Resources/xlf/Strings.de.xlf
- src/linker/Resources/xlf/Strings.es.xlf
- src/linker/Resources/xlf/Strings.fr.xlf
- src/linker/Resources/xlf/Strings.it.xlf
- src/linker/Resources/xlf/Strings.ja.xlf
- src/linker/Resources/xlf/Strings.ko.xlf
- src/linker/Resources/xlf/Strings.pl.xlf
- src/linker/Resources/xlf/Strings.pt-BR.xlf
- src/linker/Resources/xlf/Strings.ru.xlf
- src/linker/Resources/xlf/Strings.tr.xlf
- src/linker/Resources/xlf/Strings.zh-Hans.xlf
- src/linker/Resources/xlf/Strings.zh-Hant.xlf
- test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterDataFlow.cs
- test/Mono.Linker.Tests.Cases/Reflection/ExpressionPropertyMethodInfo.cs
Adds the ability to track some basic patterns around `MethodBase`/`MethodInfo`. Linker now recognizes `ldtoken` for a method as well as tracks return value of `Type.GetMethod`.
With this, the change implements two improvements:
#1814 - Mark property as accessed via reflection when using Expression.Property(Expression,MethodInfo)
Added a new warning to report cases where the intrinsic handling of the Property call doesn't work.
#1727 - Ability to handle simple MakeGenericMethod calls without generating a warning
If the generic method has no annotations on the generic arguments, linker will no longer warn.
Added tests for all the new behaviors.
Improved tests for MakeGenericMethod and MakeGenericType.
Implement checking for new constraint in MakeGenericType - it now behaves the same as if …
> Basic tracking of MethodInfo and use it to improve Expression.Property and MakeGenericMethod

- .gitattributes
This fixes the problem on Windows where files are checked out as LF, but formatting/lint will enforce CRLF.
To apply to an existing clone of the repo run from the repo root. There should be no un-commited local changes, it should work find with locally commited changes.
```console
git rm -r :/
git checkout HEAD -- :/
```
> Change line endings to auto

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AttributeConstructorDataflow.cs
If the type has a custom attribute which will cause MarkEntireType on the type itself (for example through data flow annotation), we will end up recursively calling MarkEntireType with the same input - leading to stack overflow.
The existing protection against SO in MarkEntireType is not enough since it only works on immediate recursion, not through custom attribute marking.
So moved the hashset of entire types marked as global on MarkStep, which prevents the recursion no matter the codepath.
> Fix stack overflow in MarkEntireType

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterDataFlow.cs
`struct` and `unmanaged` constraint also imply `new()` constraint, but any type allowable for `struct` or `unmanaged` constraints always has public parameterless constructor. Or rather the type can be constructed without parameters (the `.ctor` itself is actually not accessible through reflection).
Since `MakeGenericType` and `MakeGenericMethod` both enforce that only types compatible with `struct` or `unmanaged` constraints can be passed as type arguments to such generic parameters, there's no need for linker to validate this as well. At runtime it will always work - and on top of that, there's nothing for linker to mark - struct and unmanaged don't have a parameterless `.ctor` in IL - it's just that at runtime they behave as if they do.
So enforcing the `new()` constraint in …
> Relax validtion of MakeGeneric* on struct and unmanaged constraint

- test/Mono.Linker.Tests.Cases.Expectations/Helpers/DataFlowTypeExtensions.cs
- test/Mono.Linker.Tests.Cases.Expectations/Helpers/PlatformAssemblies.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnAssemblyUsingTarget.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnAssemblyUsingTargetOnUnusedType.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnAssemblyUsingTargetTypeNameInOtherAssembly.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnAssemblyUsingTargetTypeNameInSameAssembly.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnAssemblyUsingTargetTypeNameOfGenericTypeInOtherAssembly.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnAssemblyUsingTargetTypeNameOfNestedTypeInOtherAssembly.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerDisplayAttributeOnType.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerTypeProxyAttributeOnAssemblyUsingTarget.cs
- test/Mono.Linker.Tests.Cases/Attributes.Debugger/KeepDebugMembers/DebuggerTypeProxyAttributeOnType.cs
- test/Mono.Linker.Tests.Cases/Attributes/CoreLibraryAssemblyAttributesAreKept.cs
- test/Mono.Linker.Tests.Cases/Attributes/NoSecurity/CoreLibrarySecurityAttributeTypesAreRemoved.cs
- test/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/CoreLibraryUnusedAssemblyAttributesAreRemoved.cs
- test/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/CoreLibraryUsedAssemblyAttributesAreKept.cs
- test/Mono.Linker.Tests.Cases/CoreLink/CopyOfCoreLibrariesKeepsUnusedTypes.cs
- test/Mono.Linker.Tests.Cases/CoreLink/DelegateAndMulticastDelegateKeepInstantiatedReqs.cs
- test/Mono.Linker.Tests.Cases/CoreLink/LinkingOfCoreLibrariesRemovesUnusedMethods.cs
- test/Mono.Linker.Tests.Cases/CoreLink/LinkingOfCoreLibrariesRemovesUnusedTypes.cs
- test/Mono.Linker.Tests.Cases/CoreLink/NoSecurityPlusOnlyKeepUsedRemovesAllSecurityAttributesFromCoreLibraries.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GetNestedTypeOnAllAnnotatedType.cs
- test/Mono.Linker.Tests.Cases/LinkAttributes/EmbeddedLinkAttributesInCorelib.cs
- test/Mono.Linker.Tests.Cases/References/ReferencesAreRemovedWhenAllUsagesAreRemoved.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapabilityReflectionAnalysisEnabled.cs
- test/Mono.Linker.Tests/Tests/TestFrameworkRulesAndConventions.cs
Several of the DataFlow tests use the `RequirePublicMethods` or similar methods to perform validation. These methods are always the same, so there no reason to duplicate them across tests.
In the infra I added an exception that the Expectation assembly can contain non-attribute classes if they're in the Helper namespace.
It's cumbersome to add these helpers into the TestCases because each test case would have to add an explicit compilation attribute to include the source file in the test compilation.
If there are too many helpers, we might consider creating a new assembly for them instead.
> Introduce test helpers and add DataFlowTypeExtensions

- src/linker/Linker.Steps/MarkStep.cs
- test/ILLink.RoslynAnalyzer.Tests/LinkerTestCases.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs
Whenever a static member is referenced, static constructors on the declared type are called. If the cctor is annotated with `RequiresUnreferencedCode`, this should warn.
> Warn on cctors annotated with RUC if a field triggers its marking

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/Reflection/ConstructorUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/MethodUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/UsedViaReflectionIntegrationTest.cs
In .NET 6 we've added new overloads for `Type.GetConstructor` and `Type.GetMethod`, linker has intrinsics for these so this change adds support for the new overloads.
I made another change as well. Previously calling `type.GetConstructor(Types.Empty)` would be recognized as special (empty array) and it would only require `PublicParameterlessConstructor` annotation on `type`.
But calling `typeof(TestType).GetConstructor(Types.Empty)` would still mark all public `.ctor`s on `TestType`. This is at least inconsistent.
This change also implements the same special logic for empty types array for known types - so in the above case only the public parameterless `.ctor` of `TestType` will be preserved.
This change rewrites the tests for `GetConstructor` and `GetMethod` - previously these randomly …
> Intrinsics for new overloads of GetConstructor and GetMethod

- test/Mono.Linker.Tests.Cases/DataFlow/PropertyDataFlow.cs
Add Recognized Reflection Access Pattern to PropertyIndexers test otherwise linker will not test for errors
> Add Recognized pattern to PropertyIndexers test

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Attributes/IVTUsed.cs
This can be the only place where IVT attribute is marked
Fixes #1913
> Run primary queue processing after IVT attributes are checked.

- test/ILLink.RoslynAnalyzer.Tests/RequiresAssemblyFilesAnalyzerTests.cs
- test/ILLink.RoslynAnalyzer.Tests/Verifiers/CSharpAnalyzerVerifier`1.cs
This change will allow us to test our roslyn analyzers with the latest dotnet/runtime bits.
> Compile roslyn analyzer tests using repo's assembly refs

- global.json
- test/Mono.Linker.Tests.Cases/ComponentModel/CustomTypeConvertor.cs
Runtime in this SDK has the `DynamicallyAccessedMembersAttribute` allowed on types.
> Update SDK to latest version

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterDataFlow.cs
- test/Mono.Linker.Tests.Cases/Reflection/ExpressionCallString.cs
Also improved validation done by MakeGenericMethod to avoid warning if no type arguments are passed in.
Added tests.
Fixes #1819
> Expression.Call can act as MakeGenericMethod so make it perform same validation

- src/ILLink.CodeFix/ILLink.CodeFixProvider.csproj
Fixes problem in https://github.com/dotnet/sdk/pull/16820
The build is automatically inserting a package dependency on "ILLink.RoslynAnalyzer" (the name of the dependent project) but both assemblies are included in the same package. Adding the `SuppressDependenciesWhenPacking` seems to do the trick.
> Suppress dependencies for analyzer package

- src/linker/Linker.Steps/SweepStep.cs
Should fix https://github.com/dotnet/runtime/pull/50846
We mark all type forwarders for copy assemblies during MarkStep; this may end up marking forwarders that are not resolvable (i.e., `td = forwarder.Resolve()` will be null) -- which is fine. During SweepStep we update scopes of forwarders so that we point to the correct assembly ref, although, we might end up returning early if there was a forwarder which could not be resolved:
https://github.com/mono/linker/blob/eded7e5b8aaa09d0d4c9564b5419ab35a057507c/src/linker/Linker.Steps/SweepStep.cs#L681-L687
If we return early, some forwarders that are actually used, might have assembly refs pointing to nowhere.
> Continue updating forwarder scopes even if a non resolvable forwarder is found

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/MessageContainer.cs
- test/Mono.Linker.Tests.Cases/LinkAttributes/Dependencies/LinkerAttributeRemovalAttributeFromCopyAssembly.cs
- test/Mono.Linker.Tests.Cases/LinkAttributes/LinkerAttributeRemoval.cs
- test/Mono.Linker.Tests.Cases/LinkAttributes/LinkerAttributeRemoval.xml
Both of these issues were found by the same test, so that's why fixing them together.
* Null ref in the recently added single-warning logic. If the origin of the warning is a top-level TypeDefinition, the code nullrefs.
* If there's an attribute type which should be removed (like NullableAttribute) in a copy assembly, we keep the type. Since all of its members are also marked the code will call MarkType many times on it - the current guard which prevents spurious 2045 warnings doesn't work in this case since the source location member is null (in theory it should be the "copy assembly", but currently we can't represent that). To prevent the warnings it's better to rely on reason.Source as that will be the member always.
Tweaked existing tests to cover this case and also added one more …
> Fixes a nullref and spurious warnings

- docs/error-codes.md
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/LinkAttributesParser.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/TypeNameResolver.cs
- test/Mono.Linker.Tests.Cases/ComponentModel/TypeConverterOnMembers.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AssemblyQualifiedNameDataflow.cs
See #1895. Mimic `Type.GetType` when resolving a type from a type name string. This is, if the type name is not assembly qualified, we will try to search for it in the caller's assembly, mscorlib and System.Private.CoreLib, in that same order. If the type is not found anywhere, linker will produce a warning.
> Resolving a type represented by a type name string should mimic Type.GetType behavior

- src/linker/Linker/TypeReferenceExtensions.cs
- test/Mono.Linker.Tests/Tests/GetDisplayNameTests.cs
Fix #1967. If a type lives in the global namespace, `GetDisplayName` will prepend a period `<emptystring>.MyType.MyMember`.
> Check for namespace in GetDisplayName

- src/linker/Linker.Dataflow/DynamicallyAccessedMembersTypeHierarchy.cs
- test/Mono.Linker.Tests.Cases/Reflection/ObjectGetType.cs
The original code didn't take into account the fact that applying annotations can lead to marking of additional types which will interact with the cache data structure which is used to drive the application of annotations.
This change adds several new test cases with complex hierarchies and interactions and implements fixes in the code for those.
Fixes #1969
> Fix marking of annotations on complex type hierarchies

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterDataFlow.cs
- test/Mono.Linker.Tests.Cases/Reflection/ExpressionCallString.cs
The validator must ignore methods which don't have any requirements. So even if the passed in array doesn't match the method, it needs to not warn in such cases. This is because we can't guarantee we always find the exact method info to work on, instead we compensate by considering potentially multiple candidates. Some of which may not even be generic, or may not have any requirements and so on. In such cases the validator should only warn if there's potentially a real problem - not if the reflection API will fail (that's a non-failure for the validator).
This should fix the problem in https://github.com/dotnet/runtime/pull/51558#issuecomment-823430400.
> Fix generic parameter validation in MakeGenericMethod and similar

- src/linker/Linker.Dataflow/DynamicallyAccessedMembersBinder.cs
- src/linker/Linker.Dataflow/FlowAnnotations.cs
- src/linker/Linker.Dataflow/MethodBodyScanner.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Dataflow/ValueNode.cs
- src/linker/Linker.Steps/CodeRewriterStep.cs
- src/linker/Linker.Steps/LinkAttributesParser.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker.Steps/SealerStep.cs
- src/linker/Linker.Steps/SweepStep.cs
- src/linker/Linker.Steps/UnreachableBlocksOptimizer.cs
- src/linker/Linker/Annotations.cs
- src/linker/Linker/BCL.cs
- src/linker/Linker/LinkContext.cs
- src/linker/Linker/MarkingHelpers.cs
- src/linker/Linker/MethodBodyScanner.cs
- src/linker/Linker/TypeDefinitionExtensions.cs
- src/linker/Linker/TypeHierarchyCache.cs
- src/linker/Linker/TypeMapInfo.cs
- src/linker/Linker/TypeReferenceExtensions.cs
- src/linker/ref/Linker/LinkContext.cs
This change introduces a commonplace for resolving definition for types,
methods and fields. This is useful for following reasons
- Speeds up linker by 20% for default Blazor app (more for large apps)
- Any custom step can avoid building local mapping cache
- Custom steps could support `--skip-unresolved` linker option
- Consistent error handling for unresolved references
Most of the changes are just mechanical method replacement and
Link context passing.
Contributes to #918
Fixes #1953
> Unified handling of Resolve calls

- src/linker/Linker.Steps/SweepStep.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/AttributeEnumArgumentForwarded.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/AttributeEnumArgumentForwardedCopyUsedWithSweptForwarder.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/AttributeWithEnumArgument.cs
@vitek-karas noticed an issue where we stopped updating typerefs from copyused assemblies in some cases. This fixes the issue by always updating scopes in copyused assemblies.
This will be subtly different from the behavior before @mateoatr's changes in case the copyused assembly doesn't reference a removed assembly (we used to not rewrite references in that case, but now we will). I think this is the right thing to do since I believe the old behavior could have caused bugs similar to this one.
> Fix issue with forwarders in copyused assemblies

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/Reflection/ObjectGetType.cs
This is currently unsupported, so linker should warn, but we didn't have any tests for it.
> Add tests for object.GetType over generic type arguments

- eng/Versions.props
- global.json
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
* Pick up the DynamicallyAccessedMemberTypes.Interfaces enum from runtime
* Update branding of the linker assembly
* Fix nullref in tests - corelib now has an assembly level attribute with annotations (so the reported "source" is null - since we can't represent assembly as a source just yet).
> Update linker repo to the latest SDK

- src/Directory.Build.props
- src/ILLink.Tasks/ILLink.Tasks.csproj
- src/ILLink.Tasks/LinkTask.cs
- src/ILLink.Tasks/build/Microsoft.NET.ILLink.Tasks.props
- src/ILLink.Tasks/build/Microsoft.NET.ILLink.Tasks.targets
- test/Mono.Linker.Tests/TestCasesRunner/TestCaseSandbox.cs
This is so that linker can rely on new 6.0 APIs, like `DynamicallyAccessedMemberTypes.Interfaces`.
> Upgrade linker TFM to net6.0

- src/Directory.Build.props
- src/ILLink.Tasks/ILLink.Tasks.csproj
- src/ILLink.Tasks/LinkTask.cs
- src/ILLink.Tasks/build/Microsoft.NET.ILLink.Tasks.props
- src/ILLink.Tasks/build/Microsoft.NET.ILLink.Tasks.targets
- test/Mono.Linker.Tests/TestCasesRunner/TestCaseSandbox.cs
This reverts commit bf37b2909bbfb2942173e7b383642c9b32ae0e79.
I intentionally kept the new version of SDK in the repo - we need at least P4 anyway due to tests added for APIs added in that release. Ideally we would keep the SDK in sync with dotnet/runtime, but that really hard to do if linker needs to react to API changes in the runtime repo.
> Revert "Upgrade linker TFM to net6.0 (#1996)"

- src/ILLink.Tasks/CreateRuntimeRootDescriptorFile.cs
- test/ILLink.Tasks.Tests/CombineLinkerXmlFilesTests.cs
- test/ILLink.Tasks.Tests/CreateRuntimeRootDescriptorFileTests.cs
- test/ILLink.Tasks.Tests/ILLink.Tasks.Tests.cs
- test/ILLink.Tasks.Tests/Mock.cs
The CreateRuntimeRootDescriptorFile task parses some header files from the CoreCLR and produces an XML descriptor. This change adds support for understanding simple ifdefs.
Also added tests.
This is the mono/linker part of fix for #1973
> Implement support for ifdefs in header file parsing

- src/linker/Linker/MessageOrigin.cs
- test/Mono.Linker.Tests.Cases/Logging/SourceLines.cs
In specific cases (see the test added) there might be a warning comming from compiler generated code with no user code to assign to it. In such case the compiler generates a sequence point with a special line number, marking it as "hidden code". Showing that line number is weird and doesn't make any sense. Especially if the warning comes from method which has several overloads, it's basically impossible to tell which one it was.
So instead use the first sequence point with non-hiden line number.
> Avoid showing hidden lines in warning location

- docs/error-codes.md
- src/ILLink.Tasks/LinkTask.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker.Steps/RootAssemblyInputStep.cs
- src/linker/Linker.Steps/SweepStep.cs
- src/linker/Linker/Annotations.cs
- src/linker/Linker/Driver.cs
- src/linker/Linker/FeatureSettings.cs
- src/linker/Linker/LinkContext.cs
- src/linker/Linker/MetadataTrimming.cs
- test/ILLink.Tasks.Tests/ILLink.Tasks.Tests.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/RemovedNameValueAttribute.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/VerifyMetadataNamesAttribute.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodParametersDataFlow.cs
- test/Mono.Linker.Tests.Cases/Libraries/RootLibrary.cs
- test/Mono.Linker.Tests.Cases/Metadata/NamesAreKept.cs
- test/Mono.Linker.Tests.Cases/Metadata/NamesAreRemoved.cs
- test/Mono.Linker.Tests.Cases/Reflection/ActivatorCreateInstance.cs
- test/Mono.Linker.Tests.Cases/Reflection/ParametersUsedViaReflection.cs
- test/Mono.Linker.Tests/Extensions/CecilExtensions.cs
- test/Mono.Linker.Tests/TestCases/TestDatabase.cs
- test/Mono.Linker.Tests/TestCases/TestSuites.cs
- test/Mono.Linker.Tests/TestCasesRunner/AssemblyChecker.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
The total saving for Blazor template app is about 135k uncompressed. The
names are still kept for reflection and debugging scenarios.
I had to update the verification infrastructure to make the testing
easier when the names are not available.
> Trim parameter names metadata when they are not needed.

- src/linker/Linker/Driver.cs
- test/Mono.Linker.Tests.Cases/CommandLine/AddCustomStep.cs
- test/Mono.Linker.Tests.Cases/CommandLine/CustomStepData.cs
- test/Mono.Linker.Tests.Cases/Extensibility/CustomStepCanPreserveMethodsAfterMark.cs
- test/Mono.Linker.Tests.Cases/Extensibility/CustomStepCanPreserveMethodsBeforeMark.cs
- test/Mono.Linker.Tests.Cases/Extensibility/CustomStepsCanShareState.cs
- test/Mono.Linker.Tests.Cases/Extensibility/Dependencies/CustomStepsWithSharedState.cs
- test/Mono.Linker.Tests.Cases/Extensibility/SubStepDispatcherFields.cs
- test/Mono.Linker.Tests.Cases/Extensibility/SubStepDispatcherUsage.cs
Loading from byte array would load each `--custom-step` argument into a new ALC, even when using the same assembly for multiple custom steps. Instead of going all-in with ALCs, this change just loads custom steps into the default ALC to allow sharing state. This means it won't be possible to use custom steps from different assemblies which happen to have the same name.
In the future if we need to support isolated custom steps with dependencies, we could consider following the guidance for plugins at https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support, which would involve:
- loading each plugin into an isolated ALC
- loading dependencies with AssemblyDependencyResolver
- building the plugins without including shared types in plugin assemblies, and …
> Allow custom steps to share state

- test/Mono.Linker.Tests.Cases/DataFlow/MethodReturnParameterDataFlow.cs
Test for bug https://github.com/mono/linker/issues/2025.
Some cleanup of the test.
> Add a test for always throwing method with annotated return value

- src/linker/Linker.Dataflow/DynamicallyAccessedMembersBinder.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Dataflow/ReflectionPatternContext.cs
- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases.Expectations/Helpers/DataFlowTypeExtensions.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GetInterfaceDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MemberTypes.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MemberTypesRelationships.cs
- test/Mono.Linker.Tests/TestCasesRunner/AssemblyChecker.cs
Implement marking logic for Interfaces
- Transitively mark all interface implementations on a type
- Mark all interface implementations on all base types as well
Implement annotation propagation over `Type.GetInterface`
Add tests for marking behavior as well as annotation behavior
Workaround: Currently the Interfaces enum value can't be used by the linker itself
since it can't yet rely on high enough version of framework. Worked around this
by adding an overlay class and a const value. Once linker is upgraded to high enough
framework version, this workaround should be removed.
> Implement `DynamicallyAccessedMemberTypes.Interfaces`

- src/linker/Linker.Steps/BodySubstituterStep.cs
- src/linker/Linker.Steps/BodySubstitutionParser.cs
- src/linker/Linker.Steps/DescriptorMarker.cs
- src/linker/Linker.Steps/LinkAttributesParser.cs
- src/linker/Linker.Steps/LinkAttributesStep.cs
- src/linker/Linker.Steps/ProcessLinkerXmlBase.cs
- src/linker/Linker.Steps/ProcessLinkerXmlStepBase.cs
- src/linker/Linker.Steps/ResolveFromXmlStep.cs
- src/linker/Linker/Driver.cs
- src/linker/Linker/EmbeddedXmlInfo.cs
- src/linker/Linker/UnconditionalSuppressMessageAttributeState.cs
- test/ILLink.Tasks.Tests/Mock.cs
- test/Mono.Linker.Tests.Cases/LinkAttributes/LinkAttributeErrorCases.cs
- test/Mono.Linker.Tests.Cases/LinkXml/LinkXmlErrorCases.cs
- test/Mono.Linker.Tests.Cases/Substitutions/SubstitutionsErrorCases.cs
This basically improves the precision of errors we report from XML files by providing sourceline/column information.
Required refactoring how we create XML, since I wanted only one place to actually parse the XML (since we need to do it in a special way to get line/position info).
Also required to change to use XDocument instead of XPathDocument, as the latter doesn't store line/position info. This will slightly increase memory consumption for any XML processed, but since that number is already very low and we don't expect it to go high, it's not a problem.
> Add line number/position info to warnings from XML files

- src/linker/Linker.Steps/DescriptorMarker.cs
- test/Mono.Linker.Tests.Cases/LinkXml/LinkXmlErrorCases.cs
Following #2039, this adds line source line info. for warnings IL2001 and IL2002. This will cause the warnings to be triggered even in cases where the annotated types are trimmed.
Note that we still have to keep producing these warnings in `ApplyPreserveInfo` for cases where a user applies a `TypePreserve` using the Annotations API:
https://github.com/mono/linker/blob/30f2498c2a3de1f7e236d5793f5f1aca6e5ba456/src/linker/Linker.Steps/MarkStep.cs#L2427-L2434
> Add line info in IL2001 and IL2002

- src/linker/Linker.Dataflow/DynamicallyAccessedMembersBinder.cs
- src/linker/Linker.Dataflow/FlowAnnotations.cs
- src/linker/Linker.Dataflow/MethodBodyScanner.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/CodeRewriterStep.cs
- src/linker/Linker.Steps/LinkAttributesParser.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker.Steps/SealerStep.cs
- src/linker/Linker.Steps/SweepStep.cs
- src/linker/Linker.Steps/UnreachableBlocksOptimizer.cs
- src/linker/Linker/BCL.cs
- src/linker/Linker/LinkContext.cs
- src/linker/Linker/MarkingHelpers.cs
- src/linker/Linker/MethodBodyScanner.cs
- src/linker/Linker/TypeHierarchyCache.cs
- src/linker/Linker/TypeMapInfo.cs
- src/linker/Linker/TypeReferenceExtensions.cs
- src/linker/ref/Linker/LinkContext.cs
This will allow extension methods that take an `IMetadataResolver` like
in https://github.com/xamarin/java.interop/pull/842/ to use the
LinkContext Resolve cache.
Context: https://github.com/xamarin/xamarin-android/pull/5748#discussion_r633948697
The Resolve cache added in https://github.com/mono/linker/pull/1979
requires calling `Resolve*Definition` methods directly on `LinkContext`,
which means that any extension methods that do resolution logic need to
take a `LinkContext`. This doesn't work well with the layering in
xamarin-android, where java.interop uses a resolution cache with cecil,
but doesn't depend on the linker. Instead it uses a custom
`TypeResolutionCache` for extension methods like `GetBaseDefinition`:
https://github.com/xamarin/java.interop/blob/main/src/Java.Interop.Tools. …
> Implement IMetadataResolver for LinkContext

- src/ILLink.Tasks/CreateRuntimeRootDescriptorFile.cs
- test/ILLink.Tasks.Tests/CreateRuntimeRootDescriptorFileTests.cs
Added support to parse native header files that have the [feature switch macro](https://github.com/dotnet/runtime/pull/52940) defined. Should be a no-op if the feature switch macro is not defined in a header file
> Parsing update for native header files with feature switch

- src/ILLink.Tasks/CreateRuntimeRootDescriptorFile.cs
- test/ILLink.Tasks.Tests/CreateRuntimeRootDescriptorFileTests.cs
Descriptors have the behavior that specifying just the assembly element without any children will root the entire assembly (and everything in it). The same applies to types (specifying just the type element will mark the entire type).
With the new feature switches, we have to be careful to not generate an empty assembly element, otherwise we will accidentally root the entire corelib.
Fixes the problem seen in https://github.com/dotnet/runtime/pull/53144.
> Fix a problem where generating an empty FS assembly element roots the whole assembly

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/MarkScopeStack.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/MessageOrigin.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs
Marking needs to know where to report a warning if it comes up. So far this has been done by passing around a refence to the member (type, method, ...) typically in a parameter called `sourceLocation`. Going forward this is problematic:
* It's verbose, we're passing this around lot of methods in the MarkStep, without needing to modify it.
* It's hard to enforce rules about it since there's no central location where handling of these things is done.
* With the coming changes for compiler generated code, we will need to pass around more state
* It's technically imprecise, in some cases we can point to exact instruction as the location, but the current mechanism has no way to represent that.
This change introduces a new class `MarkStepScope` which uses a stack to track the active scopes. …
> Introduce scopes into MarkStep to track the location for warnings

- test/ILLink.RoslynAnalyzer.Tests/TestCaseUtils.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/ExpectedWarningAttribute.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/Dependencies/RequiresUnreferencedCodeInCopyAssembly.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
Probably due to copy/paste error we've validated the attribute by looking at all warning messages at once. This means that potentially any warning can be matched to the attribute even if its location doesn't match.
This change fixes that but uncovers some small test issues:
* The expected warnings happen in different places - fixed that
* Some warnings can't be reported by the Roslyn Analyzer as they require global view - added a mechanism to mark these
Refactored a bit of the Roslyn analyzer validation code to support named properties in attributes.
> Fix validation of ExpectedWarning attribute

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/DataFlow/Dependencies/MemberTypesAllBaseTypeAssembly.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MemberTypesAllOnCopyAssembly.cs
"Copy" assembly calls `MarkEntireType` on all types in the assembly, but it specified to not include base and interface types. We cache if a type was marked as a whole, so to not repeat the process (and also to avoid potential recursion). But the cache doesn't differentiate if the type was mark with its base/interface types or not.
So in the "copy" assembly case, the type is first marked without base/interface marking, and that is cached. Later on we apply the All annotation to the type, which calls `MarkEntireType` again, but since it's already cached it doesn't do anything. But All annotation should preserve base/interface types as well, which will not happen in this case.
Fixed this by making the cache aware of the base/interface flag and repeat the marking if base/interface is …
> Fix applying All annotation on a type from "copy" assembly

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/BCLFeatures/ETW/CustomEventSource.cs
We still cannot take out the special handling for EventSource due to [test failures ](https://dev.azure.com/dnceng/public/_build/results?buildId=1159451&view=ms.vss-test-web.build-test-results-tab&runId=34991568&paneView=debug&resultId=163140)in runtime repo. Will reopen #1949
This reverts commit 2cf308289ea6140bbee332318e3ac45c1a6d0342.
> Revert "Remove custom marking of nested types for event sources (#2032)"

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/DataFlow/Dependencies/MemberTypesAllBaseTypeAssembly.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MemberTypesAllOnCopyAssembly.cs
This is a port of https://github.com/mono/linker/pull/2060 to `release/6.0` branch - to include the fix in .NET 6 Preview 5.
"Copy" assembly calls `MarkEntireType` on all types in the assembly, but it specified to not include base and interface types. We cache if a type was marked as a whole, so to not repeat the process (and also to avoid potential recursion). But the cache doesn't differentiate if the type was mark with its base/interface types or not.
So in the "copy" assembly case, the type is first marked without base/interface marking, and that is cached. Later on we apply the All annotation to the type, which calls `MarkEntireType` again, but since it's already cached it doesn't do anything. But All annotation should preserve base/interface types as well, which will not happen in …
> [release/6.0] Fix applying All annotation on a type from "copy" assembly

- docs/error-codes.md
- src/linker/Linker.Dataflow/FlowAnnotations.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodReturnParameterDataFlow.cs
- test/Mono.Linker.Tests/TestCasesRunner/LinkerTestLogger.cs
Also added a small fix in the test infra
Fixes https://github.com/mono/linker/issues/2065
> Warn when method return type is annotated but it's not Type or String

- src/linker/Linker.Steps/UnreachableBlocksOptimizer.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/MethodWithParametersSubstitutions.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/MethodWithParametersSubstitutions.xml
In some cases the compiler can generate instructions like:
```
ret;
call instance bool SomeMethod()
```
If `SomeMethod` is substituted via XML, this can lead to the logic which tries to overwrite method parameter loading with nops to encounter the `ret` instruction. This was not handled before.
Handle the `ret` by bailing out (it would mean we would have to start understanding branches, which adds lot of complexity).
Added a test case.
Fixes https://github.com/mono/linker/issues/2061
> Fix issue in const propagation if there's a ret instruction during method parameter processing

- src/linker/Linker.Dataflow/DynamicallyAccessedMembersTypeHierarchy.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Dataflow/ReflectionPatternContext.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/IReflectionPatternRecorder.cs
- src/linker/Linker/LoggingReflectionPatternRecorder.cs
- test/Mono.Linker.Tests.Cases/Logging/SourceLines.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestReflectionPatternRecorder.cs
Recent chaneg introduced a scope stack to marking which carries `MessageOrigin` around so that warnings can be reported with precise origin. The one exception to this was the `ReflectionMethodBodyScanner`.
This change integrates the scope stack with `ReflectionMethodBodyScanner`. The visible result is more precise reporting of some warnings. This change will be needed for the work around compiler generated code (since then MessageOrigin will carry even more information than it does currently).
The main API change is addition of the `MessageOrigin` parameter to the `IReflectionPatternRecorder.UnrecognizedReflectionAccessPattern`. There are plans to remove this interface completely, so there' not much need to clean it up right now (so I left the potentially duplicated `origin` and `source` …
> Use full MessageOrigin when reporting data flow warnings

- src/ILLink.RoslynAnalyzer/ISymbolExtensions.cs
- src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
- src/ILLink.RoslynAnalyzer/RequiresAssemblyFilesAnalyzer.cs
- test/ILLink.RoslynAnalyzer.Tests/LinkerTestCases.cs
- test/ILLink.RoslynAnalyzer.Tests/TestCaseUtils.cs
- test/ILLink.RoslynAnalyzer.Tests/TestChecker.cs
- test/ILLink.RoslynAnalyzer.Tests/Verifiers/CSharpAnalyzerVerifier`1.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/UnrecognizedReflectionAccessPatternAttribute.cs
- test/Mono.Linker.Tests.Cases/DataFlow/FieldDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GetTypeDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodReturnParameterDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodThisDataFlow.cs
- test/Mono.Linker.Tests.Cases/Reflection/ActivatorCreateInstance.cs
- test/Mono.Linker.Tests.Cases/Reflection/RunClassConstructorUsedViaReflection.cs
This PR adds support for `UnrecognizedReflectionAccessPattern` in the analyzer test infra and refactors the existing code in ILLink.RoslynAnalyzer.Tests.TestCaseUtils.
> Add support for UnrecognizedReflectionAccessPattern in analyzer test infra

- test/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflection.cs
Add a test that Type.GetType correctly handles generic parameter annotations
Add a test that if a gener parameter has annotation and the type with that parameter is referenced via `Type.GetType`, the annotation gets applied.
There is already a test for `string` data flow handling in `ApplyTypeAnnotations.TestFromConstantWithGeneric`, but there was no test for `Type.GetType` (which uses slightly different codepath in the product).
> Type get type generic annotation test

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GetInterfaceDataFlow.cs
This case assume that all code branches should have same minimal dynamic access pattern
Was discovered as part of https://github.com/dotnet/runtimelab/issues/1187
Issue happens when 2 code blocks has diferent requirements for dynamic code access, and this produce MergePoint. This case was not handled.
> Handle different dynamic member access for multiple branches

- .gitignore
formatDiagnosticLog.binlog was generated by .\lint.cmd -v diagnostic
> Ignore binlog files in the root.

- test/Mono.Linker.Tests.Cases/Interop/PInvoke/Warnings/ComPInvokeWarning.cs
Use the ExpectedWarning test attributes. Add tests for more cases. Add tests for suppression and for RUC interaction.
Related to discussion in https://github.com/mono/linker/issues/1989.
> Improve tests for COM warnings from PInvokes

- src/linker/Linker/Driver.cs
- test/ILLink.Tasks.Tests/ILLink.Tasks.Tests.cs
- test/ILLink.Tasks.Tests/Mock.cs
- test/Mono.Linker.Tests.Cases/Extensibility/CustomStepsCanShareState.cs
One of the issues I hit in https://github.com/xamarin/xamarin-macios/pull/11739 was caused by the custom steps being processed backwards. This fixes the order so they're processed in the order specified.
It's unfortunately still easy to get this wrong - I filed https://github.com/mono/linker/issues/2081 to track it.
> Fix order of custom steps

- src/linker/Linker/LinkContext.cs
- src/linker/ref/Linker/LinkContext.cs
Fixes https://github.com/mono/linker/issues/2073
> Expose Resolve helper for assemblies

- src/linker/Linker/LinkContext.cs
- src/linker/Linker/MessageContainer.cs
- test/Mono.Linker.Tests.Cases/Warnings/Dependencies/TriggerWarnings_TrimmableLib.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningsFromTrimmableAssembliesCanSurviveSingleWarn.cs
This lets RUC warnings intentionally left in IsTrimmable-attributed assemblies survive collapsing, so that the user-readable message is shown.
This is a workaround for the lack of a more well-defined model for "global" warnings (such as RUC methods behind a disabled feature switch, or RUC code that's part of an override which _may_ be called virtually). In the framework libraries we took the approach of moving `RUC` to helper methods that always have a direct callsite in managed code, and we gave the attribute a message indicating the global problem. These warnings will no longer be collapsed, but they still have a message and origin mentioning a call from non-RUC to RUC inside of the library. 
Addresses part of https://github.com/mono/linker/issues/2004.
> Always show IL2026 for IsTrimmable assemblies

- src/linker/Linker.Dataflow/MethodBodyScanner.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Interop/PInvoke/Warnings/ComPInvokeWarning.cs
This fixes `PInvoke` analysis similar to other methods as discussed in issue #1989. 
- We now generate the warnings from the `callsite` as opposed to for the `PInvoke `call itself. We do this by moving the analysis to `MethodBodyScanner `and `ReflectionMethodBodyScanner`
- Dangerous `PInvokes `(the ones that we generate warnings) have an implicit relationship with built-in COM interop support. Specifically, [IsComInterop](https://github.com/mono/linker/blob/caeaf2a3fb3f636805fdd4881df4f9a539fff8f6/src/linker/Linker.Steps/MarkStep.cs#L3103)method in the linker tries to match the logic in [MarshalInfo::MarshalInfo](https://github.com/dotnet/runtime/blob/fef9b592b28bc4b906091b1361f097da63bf418c/src/coreclr/vm/mlinfo.cpp#L1086). This means that when `BuiltInComInteropSupport `property is …
> Handle PInvoke analysis similar to other methods

- docs/error-codes.md
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/MarkScopeStack.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/CompilerGeneratedState.cs
- src/linker/Linker/LinkContext.cs
- src/linker/Linker/MessageOrigin.cs
- src/linker/Linker/UnconditionalSuppressMessageAttributeState.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/ExpectedWarningAttribute.cs
- test/Mono.Linker.Tests.Cases/Logging/CommonLogs.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeInCompilerGeneratedCode.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsInCompilerGeneratedCode.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
This change implements the following high-level functionality:
* `UnconditionalSuppressMessage` applies to the entire method body even for iterators, async methods
* `RequiresUnreferencedCode` automatically suppresses trim analysis warnings from entire method body for iterators, async methods
Solution approach:
* Detect compiler generated code by using the `IteratorStateMachineAttribute`, `AsyncStateMachineAttribute` and `AyncIteratorStateMachineAttribute`.
* When a method which is compiler generated (detected by looing for `<` in its name) is processed the original "user method" is determined by looking for a method with the "state machine" attribute pointing to the compiler generated type.
* This information is cached to avoid duplication of relatively expensive detection logic.
* Looks …
> Warning suppressions in compiler generated code

- test/Mono.Linker.Tests.Cases/TypeForwarding/UsedForwarderInGenericIsDynamicallyAccessedWithAssemblyCopyUsed.cs
This test is the easy repro for https://github.com/mono/linker/issues/1536 (which is relatively complicated to understand).
In short when we resolve type name to type reference where the type is a generic and the generic parameter is a fully qualified type name pointing to a facade, linker will not preserve that facade (even though it will correctly resolve the type and mark it in the implementation assembly).
This works if the facade type is resolved directly, but not if it's used as a generic argument.
> Add a test case for string->type resolution with forwarded type in generic argument

- src/linker/Linker.Steps/MarkStep.cs
- test/ILLink.RoslynAnalyzer.Tests/LinkerTestCases.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/ExpectedWarningAttribute.cs
- test/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyMethod.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/Dependencies/RequiresUnreferencedCodeInCopyAssembly.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.descriptor.xml
Adds several new tests for various RUC scenarios.
Cleans up the RUC tests to correctly baseline all warnings it produces.
Fixes a product issue with RUC on attribute property setter.
Small refactoring in the product.
> Better tests for various RUC scenarios and fixes

- test/ILLink.RoslynAnalyzer.Tests/ILLink.RoslynAnalyzer.Tests.csproj
- test/ILLink.RoslynAnalyzer.Tests/RequiresAssemblyFilesAnalyzerTests.cs
- test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs
- test/ILLink.RoslynAnalyzer.Tests/TestCaseUtils.cs
- test/ILLink.RoslynAnalyzer.Tests/UnconditionalSuppressMessageCodeFixTests.cs
- test/ILLink.RoslynAnalyzer.Tests/Verifiers/CSharpAnalyzerVerifier`1.cs
The version is currently hardcoded in TestCaseUtils.cs, but since
these are reference assemblies, as long as the surface area isn't
predicted to change, we can update as necessary.
> Use net6.0 reference assemblies in analyzer tests

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs
Fixes https://github.com/mono/linker/issues/2122
> Don't warn for RUC from DebuggerDisplayAttribute

- src/linker/Linker.Steps/DiscoverCustomOperatorsHandler.cs
- src/linker/Linker/DependencyInfo.cs
- src/linker/Linker/Driver.cs
- src/linker/Linker/LinkContext.cs
- test/Mono.Linker.Tests.Cases/LinqExpressions/CanDisableOperatorDiscovery.cs
- test/Mono.Linker.Tests.Cases/LinqExpressions/CanPreserveCustomOperators.cs
- test/Mono.Linker.Tests.Cases/LinqExpressions/CanPreserveNullableCustomOperators.cs
- test/Mono.Linker.Tests.Cases/LinqExpressions/CanRemoveMethodsNamedLikeCustomOperators.cs
- test/Mono.Linker.Tests.Cases/LinqExpressions/CanRemoveOperatorsWhenNotUsingLinqExpressions.cs
- test/Mono.Linker.Tests.Cases/LinqExpressions/CustomOperatorsWithUnusedArgumentTypes.cs
- test/Mono.Linker.Tests/TestCases/TestDatabase.cs
- test/Mono.Linker.Tests/TestCases/TestSuites.cs
This will keep custom operators on marked types whenever System.Linq.Expressions
is used, and the operator input types are marked.
The behavior is enabled by default, and can be disabled by passing
--disable-operator-discovery.
Addresses https://github.com/mono/linker/issues/1821
> Preserve custom operators

- docs/error-codes.md
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/DocumentationSignatureParser.cs
- src/linker/Linker/Driver.cs
- src/linker/Linker/UnconditionalSuppressMessageAttributeState.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/ModuleSuppressionWithMemberScopeNullTarget.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/ModuleSuppressionWithModuleScopeNullTarget.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/ModuleSuppressionWithNullScopeNullTarget.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsInModule.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/TargettedModuleSuppressionWithUnmatchedScope.cs
The `Scope` parameter is only relevant in the context of global suppressions (put in a module or an assembly); and the only scopes that we support are `module`, `type` and `member`. Whenever the scope is set to a value other than these three, we log a message stating that the used argument is not supported -- this was changed to log a warning instead.
Unconditional suppressions put on a module/assembly that specify a target are registered as if they were put on the target (e.g., on a type, field, etc.); thus, when looking if a warning is suppressed on a global level, we must make sure to only look in global suppressions that do not specify a target -- this was fixed.
> Check target of module/assembly level suppressions

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MemberTypesRelationships.cs
- test/Mono.Linker.Tests.Cases/Reflection/ActivatorCreateInstance.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
The core already recognized empty array as no args, but null means the same thing.
This change also:
* Fixes a bug when PublicConstructors was required but only PublicParameterlessConstructor were provided the warning message would not say what the requirement was.
* Fixes another bug where Activator.CreateInstance(... NonPublic ) (only NonPublic binding) will not accept PublicParameterlessConstructor
* Simplifies some of the code
* Better matching for UnrecognizedReflectionAccessPattern and warnings in tests
* Added tests
Fixes https://github.com/mono/linker/issues/2110
> Passing null to args for Activator.CreateInstance means no args

- src/linker/Linker.Dataflow/DynamicallyAccessedMembersTypeHierarchy.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker.Steps/RootAssemblyInputStep.cs
- src/linker/Linker/LinkContext.cs
- test/Mono.Linker.Tests.Cases/BCLFeatures/ETW/CustomEventSource.cs
- test/Mono.Linker.Tests.Cases/BCLFeatures/ETW/CustomLibraryEventSource.cs
- test/Mono.Linker.Tests.Cases/Reflection/MembersUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/ObjectGetTypeLibraryMode.cs
We added type hierarchy support to the linker via #1929 but the annotations to the derived types were only triggered via `object.GetType()` in code. This causes problems in library mode linking, especially for internal types when the assembly does not have code that triggers `object.GetType()`. Library mode linking can remove members in such cases which might be needed later by application code that invokes the removed internal code via reflection. A specific example is an internal type like [NetEventSource](https://github.com/dotnet/runtime/blob/3924d0308110f6365e47e784b8c7cf1e8f7efa2b/src/libraries/Common/src/System/Net/Logging/NetEventSource.Common.cs#L39) in `System.Net.Mail.dll` library, where the library does not have code that triggers `object.GetType()`. Library mode linking …
> Add a library mode for type hierarchy marking

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeHierarchyLibraryModeSuppressions.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeHierarchySuppressions.cs
Currently it's not possible to suppress warnings that originate from types in most cases, because we don't process the suppression attributes until after we've processed the type for type hierarchy related warnings.
https://github.com/mono/linker/pull/2114 changes the library-mode behavior of type hierarchy marking to apply the DAMT annotation when the type with the annotation is first seen. So far we have been reporting an inconsistent warning origin for these (sometimes the GetType call, sometimes the type - see https://github.com/mono/linker/issues/2136). But by applying the annotations when the type is first marked, we are now reporting warnings from the type, which is introducing some of the additional warnings in https://github.com/dotnet/runtime/pull/55636 that were previously …
> Fix warning suppressions on types for type hierarchy

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/Reflection/ActivatorCreateInstance.cs
When no ctor parameters are passed, and non-public binding flags are
used, we only need to require parameterless public constructors. Fixes one of the issues in https://github.com/dotnet/runtime/pull/55636.
> Fix Activator.CreateInstance case

- src/linker/Linker/Annotations.cs
If the type in question has unresolvable base type, we null ref.
> Fixes a null reference when trying to get RUC on a type

- illink.sln
- src/ILLink.RoslynAnalyzer/ILLink.RoslynAnalyzer.csproj
- src/ILLink.Shared/ILLink.Shared.projitems
- src/ILLink.Shared/ILLink.Shared.shproj
- src/ILLink.Shared/MessageFormat.cs
- src/ILLink.Shared/SharedStrings.resx
- src/linker/Mono.Linker.csproj
We already share code between analyzer and linker, this only adds a shared project that makes intentions more transparent and files easily discoverable inside VS. Moving forward with the analyzer, I think we'd like to share more and more code between the two; for one, I'd like to share as much as possible related to the diagnostic creation / warnings.
> Add ILLink.Shared shared project

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/UnconditionalSuppressMessageAttributeState.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsInCopyAssembly.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsInMembersAndTypes.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsViaXml.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsViaXml.xml
Previously attribute suppressions were populated while marking
the attributes. This meant that any suppression checks before the
attributes got marked would not see the suppressions. Doing this
lazily fixes the problem, but may result in scanning the attributes
multiple times.
Fixes https://github.com/mono/linker/issues/2163
FIxes https://github.com/mono/linker/issues/2095
Fixes https://github.com/dotnet/runtime/issues/56252
This also fixes an issue where we were not respecting
UnconditionalSuppressMessageAttribute injected via
XML for anything other than assembly/module level attributes.
> Check attribute suppressions lazily

- docs/error-codes.md
- src/linker/Linker.Dataflow/FlowAnnotations.cs
- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AnnotatedMembersAccessedViaReflection.cs
- test/Mono.Linker.Tests.Cases/DataFlow/VirtualMethodHierarchyDataflowAnnotationValidation.cs
- test/Mono.Linker.Tests.Cases/Reflection/ExpressionCallString.cs
Any access to DAM annotated method must be validated by the trimmer. Normal calls and such are handled already, but direct reflection access or other indirect accesses can lead to trimmer allowing potential invocation of DAM annotated method without validating the annotations. This change will warn whenever such potential "leak" happens.
This applies to method parameter, method return value and field annotations.
Uses the same infra as RUC already just adds additional checks.
Tests for the new cases.
Fixes https://github.com/mono/linker/issues/1764
> Warn when accessing DAM annotated method via reflection

- docs/error-codes.md
- src/linker/Linker.Dataflow/DynamicallyAccessedMembersTypeHierarchy.cs
- src/linker/Linker.Dataflow/FlowAnnotations.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/DependencyInfo.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeHierarchyLibraryModeSuppressions.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeHierarchyReflectionWarnings.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeHierarchySuppressions.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
Fixes https://github.com/mono/linker/issues/2136.
The warnings pretty much work as described in https://github.com/mono/linker/issues/2136#issuecomment-879146153, and the scenario from https://github.com/mono/linker/issues/2136#issuecomment-881681867 will warn on the derived type. There's still an issue where the member warnings can't be suppressed on the member because we haven't marked custom attributes at that point.
> Fix warning origin for DAM on types

- docs/error-codes.md
- src/linker/Linker.Steps/MarkStep.cs
This warning mentions "field" but is about a method.
> Fix typo in warning message

- src/ILLink.RoslynAnalyzer/AnalyzerOptionsExtensions.cs
- src/ILLink.RoslynAnalyzer/DiagnosticDescriptors.cs
- src/ILLink.RoslynAnalyzer/IOperationExtensions.cs
- src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
- src/ILLink.RoslynAnalyzer/RequiresUnreferencedCodeAnalyzer.cs
- src/ILLink.Shared/DiagnosticString.cs
- src/ILLink.Shared/SharedStrings.resx
- test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs
A `dynamic` type causes reflection to be performed on the runtime type, making it trimmer-incompatible. This analyzer will warn on any invocation on a dynamic type with `IL2026`.
Happy to read any suggestion(s) on interesting testing scenarios.
> Add `dynamic` analyzer

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/Annotations.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs
Avoid the propagation of RequiresUnreferencedCode to nested classes
When suppressing warnings only ask the declaring type instead of the effective type
Fixes #2151
> Avoid the propagation of RequiresUnreferencedCode to nested classes

- src/linker/Linker.Steps/DiscoverCustomOperatorsHandler.cs
- test/Mono.Linker.Tests.Cases/LinqExpressions/CanPreserveCustomOperators.cs
- test/Mono.Linker.Tests.Cases/LinqExpressions/CanPreserveNullableCustomOperators.cs
Fixes https://github.com/dotnet/runtime/issues/56819
The issue occurs when preserving an operator method with an argument like `Foo?[]`. We need to preserve the operator if `Foo` was marked. This was done by checking if the argument resolves to `Nullable<T>`, and if so, extracting the generic argument from the unresolved typeref. Cecil resolves `Foo?[]` to `Nullable<T>`, but we weren't prepared to handle this case because `Foo?[]` doesn't have generic arguments.
The fix unwraps the typereference until we get to the `Nullable<Foo>` so that we can extract the generic argument `Foo`.
I wasn't sure how to reproduce the original failing test in https://github.com/dotnet/runtime/issues/56819, but I see that the tests use this pattern. I did confirm that a local testcase reproduced the …
> Fix nullref in operator handling

- src/linker/Linker/Annotations.cs
I found it rather confusing how/why DoesMethodRequireUnreferencedCode and IsMethodInRequiresUnreferencedCodeScope are different conditions. So I added a comment describing the intent and behavior.
> Add comment on RUC-on-type methods

- src/linker/Linker.Dataflow/DynamicallyAccessedMembersBinder.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AnnotatedMembersAccessedViaReflection.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterDataFlow.cs
- test/Mono.Linker.Tests.Cases/DynamicDependencies/DynamicDependencyMemberTypes.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeHierarchyReflectionWarnings.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeHierarchySuppressions.cs
Fixes https://github.com/mono/linker/issues/2159.
This should also fix https://github.com/mono/linker/issues/2160 but I'm not sure we have a great way to test that. I will look into it more later today.
> Fix warnings for DAM.All

- src/Directory.Build.props
- src/ILLink.Tasks/ILLink.Tasks.csproj
- src/ILLink.Tasks/build/Microsoft.NET.ILLink.Tasks.props
Fixes https://github.com/mono/linker/issues/2118
> Target net6.0 for linker

- src/linker/Linker/UnconditionalSuppressMessageAttributeState.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsInMembersAndTypes.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsInMembersAndTypesUsingTarget.cs
The change in https://github.com/mono/linker/pull/2171 was incorrect
because it didn't account for the possibility that the suppressions
cache already contains assembly or module suppressions for the provider.
(The same cache is used for both - the provider here is the suppression
target, not the attribute provider).
This fixes the check by re-using the cache to also track whether we have
scanned for suppression attributes on the provider. This caching is
necessary since we warn about duplicate suppressions.
Providers without any suppressions may still be scanned multiple times
since we don't cache the negative result.
I encountered this while investigating warnings in runtime, but it appears to
have been the result of an inconsistent state in my case - I don't believe
this change is …
> Fix suppression check with assembly suppressions

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/Advanced/TypeCheckRemoval.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/ReplacedReturns.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/TryFilterBlocks.cs
- test/Mono.Linker.Tests/TestCasesRunner/AssemblyChecker.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
The isinst optimization replaces that instruction with a `pop, ldnull` when the type is not instantiated. This changes the instruction and also changes the length of the instruction in that position. Cecil unfortunately doesn't update try/catch/filter references and they keep pointing to the old `isinst` instruction which not part of the method body anymore. When saving the assembly the offsets stores in the try/catch/filter records end up effective random and corrupted.
This is a short-term fix to unblock failures in runtime due to this problem. 
Medium term fix would be to carefully handle all IL replacements in the linker with regard to try/catch/filter records.
Ideally the long term fix would be to do this in Cecil in such a way that IL replacements would be correctly handled on their …
> Fix broken try/catch/filter offsets after isinst optimization

- src/linker/Linker.Dataflow/DynamicallyAccessedMembersBinder.cs
- src/linker/Linker.Dataflow/DynamicallyAccessedMembersTypeHierarchy.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/Reflection/ObjectGetType.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeHierarchyReflectionWarnings.cs
https://github.com/mono/linker/pull/2191 addressed issues with redundant
warnings from base types, but interfaces need to be handled specially.
There were a few issues with the interface handling in that change:
- The binding logic didn't include interfaces for DAM.All when
declaredOnly was specified, as @vitek-karas pointed out in
https://github.com/mono/linker/pull/2206#discussion_r687573854.
This could have led to us not marking interfaces for types derived
from a DAMT.All-annotated type. Either way, the binding logic
should not select interface _members_ when declaredOnly is specified.
- The DAMT-on-type logic had special handling for base types, but
didn't separately mark interface members, which is needed when
applying annotations DAMT.All or DAMT.Interfaces. This could have led
to …
> Fix warnings for DAMT on interfaces

- test/Mono.Linker.Tests/TestCasesRunner/PeVerifier.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
We are migrating our unit test projects to run on net5.  However, we will continue to run our linker tests against a mono like profile (since that is what Unity is based on).
Eliminating PeVerifier entirely when building for net5 causes us problems.  We want to continue running it on the linker test executables.
This PR refactors how PeVerifier is made to do nothing when compiling with NETCOREAPP defined.  This approach lets the illink tests continue to operate as they do now.  While also giving us the ability to run our `Unity.Linker.Tests` project on net5, our test case assemblies compiled against a .NET Framework profile, and have our test framework continue to run PeVerifier
> Refactor PeVerifier

- eng/Versions.props
- src/linker/BannedSymbols.txt
- src/linker/Linker.Dataflow/DynamicallyAccessedMembersTypeHierarchy.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/LinkAttributesParser.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker.Steps/ProcessLinkerXmlBase.cs
- src/linker/Linker.Steps/SweepStep.cs
- src/linker/Linker/DocumentationSignatureGenerator.PartVisitor.cs
- src/linker/Linker/DocumentationSignatureGenerator.cs
- src/linker/Linker/DocumentationSignatureParser.cs
- src/linker/Linker/Driver.cs
- src/linker/Linker/LinkContext.cs
- src/linker/Linker/LinkerILProcessor.cs
- src/linker/Linker/MethodReferenceExtensions.cs
- src/linker/Linker/ModuleDefinitionExtensions.cs
- src/linker/Linker/OverrideInformation.cs
- src/linker/Linker/SerializationMarker.cs
- src/linker/Linker/TypeMapInfo.cs
- src/linker/Linker/TypeNameResolver.cs
- src/linker/Linker/TypeReferenceExtensions.cs
- src/linker/Linker/UnconditionalSuppressMessageAttributeState.cs
- src/linker/Linker/WarningSuppressionWriter.cs
- src/linker/Linker/XmlDependencyRecorder.cs
- src/linker/Mono.Linker.csproj
- test/Mono.Linker.Tests/Tests/DocumentationSignatureParserTests.cs
- Prevent usage of Cecil's Resolve
- Prevent usage of Cecil's ILProcessor
This adds an `ITryResolveMetadata` to let the test infrastructure use the `TryResolve` helpers without creating a `LinkContext`.
> Add BannedApiAnalyzer

- test/Mono.Linker.Tests/TestCases/TestDatabase.cs
This confuses IDE tests runners in different ways.
1) In Rider, if two folders contain a test with the same name, only 1 will ever run.  Rider silently drops the other and never runs it.
2) In Visual Studio 2022 Preview the tests a grouped oddly in the UI.  For example, tests under `Attributes.Csc.*` will appear as having their own top level grouping rather than nested under `Attributes`.  I did not test if VS suffered from (1) the above.  It may also.
This change is important for additional changes I have coming.  I'm trying to take the parallel test running changes into our fork's active branch and I'm hitting all sorts of path length problems.  I'm doing what I can to bring lengths down.  One of the things I will do is dropping the redundant file name prefix from files in …
> Don't drop suite name from test name.

- test/Mono.Linker.Tests.Cases/CoreLink/CopyOfCoreLibrariesKeepsUnusedTypes.cs
We up dated our mono and new assemblies survive.  One of which is Mono.Security.  This test isn't really concerned with peverify so just disable it across the board
> Skip peverify on CopyOfCoreLibrariesKeepsUnusedTypes

- .gitmodules
GitHub is removing support for unencrypted git soon: https://github.blog/2021-09-01-improving-git-protocol-security-github/
> Stop using git protocol for submodule

- .gitmodules
GitHub is removing support for unencrypted git soon: https://github.blog/2021-09-01-improving-git-protocol-security-github/
Backport of #2248
> [release/6.0] Stop using git protocol for submodule

- src/ILLink.RoslynAnalyzer/DiagnosticDescriptors.cs
This PR tags the set of diagnostics produced by the trimmer analyzer as non configurable so that the option to generate a global suppression file is not shown to the user (since this would not work for these diagnostics, see #2251).
> Tag analyzer diagnostics as non configurable

- .gitmodules
GitHub is removing support for unencrypted git soon: https://github.blog/2021-09-01-improving-git-protocol-security-github/
Backport of #2248
> [release/5.0] Stop using git protocol for submodule

- src/linker/Linker.Dataflow/FlowAnnotations.cs
- src/linker/Linker.Dataflow/MethodBodyScanner.cs
- src/linker/Linker.Steps/BodySubstitutionParser.cs
- src/linker/Linker.Steps/CodeRewriterStep.cs
- src/linker/Linker.Steps/DescriptorMarker.cs
- src/linker/Linker.Steps/LinkAttributesParser.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker.Steps/OutputStep.cs
- src/linker/Linker.Steps/OutputWarningSuppressions.cs
- src/linker/Linker.Steps/ProcessLinkerXmlBase.cs
- src/linker/Linker/Driver.cs
- src/linker/Linker/LinkContext.cs
- src/linker/Linker/SubstitutionInfo.cs
- src/linker/Linker/TypeReferenceExtensions.cs
- test/Mono.Linker.Tests/Tests/AnnotationStoreTest.cs
- test/Mono.Linker.Tests/Tests/MessageContainerTests.cs
Enable nullable annotations for LinkContext and the XML processing classes. I chose these as a starting point for no reason in particular, except that they produced a lot of warnings. Also includes other small fixes for things I noticed. In particular PTAL at the removed `ReportUnresolved` calls in `LinkContext.Resolve` - those looked like they were producing redundant warnings for cached `null` results.
> Nullable annotations part 1

- src/ILLink.RoslynAnalyzer/DiagnosticDescriptors.cs
Reverts mono/linker#2252. Unfortunately, this not only stops showing the "suppress this warning" message in the IDE, but will make `NoWarn` unusable on these diagnostics.
> Revert "Tag analyzer diagnostics as non configurable"

- eng/Versions.props
Like https://github.com/mono/linker/pull/2258, uses an unchanging numerical prerelease label.
I also removed the `DotNetFinalVersionKind` setting since I don't think we use it. (I left it as-is in the 6.0 branch just in case - there I wanted to avoid breaking things as much as possible).
> Remove preview branding

- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NoKeptCtor/OverrideRemoval/Dependencies/OverrideOfAbstractIsKeptNonEmptyLibrary.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NoKeptCtor/OverrideRemoval/Dependencies/OverrideOfAbstractIsKeptNonEmptyLibraryWithNonEmpty.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NoKeptCtor/OverrideRemoval/OverrideOfAbstractIsKeptNonEmpty.cs
This uncovers a null ref in sweepstep.
The test is order dependent:
- Assembly (librarywithnonemtpy) has a virtual method which referes to type from second library (library). This processes the type reference.
- The type is removed from library
- The virtual method is re-processed again -> hits a type def which does not belong to any assembly/scope
For this to happen the virtual method must be processed after the type has been removed.
This also requires the method to be meant for removal later on (the body will be rewritten to throw), since otherwise the type would have been marked.
This also requires the library with the removed type to be kept (so something else in it must be kept).
> Add a test for #2260

- src/linker/Linker.Steps/SweepStep.cs
- test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NoKeptCtor/OverrideRemoval/OverrideOfAbstractIsKeptNonEmpty.cs
Basically a workaround for #2260. This simply goes back to using the `Resolve` method and avoid the cache for now.
> Workaround NRE in SweepStep

- src/ILLink.RoslynAnalyzer/ISymbolExtensions.cs
- src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
- src/ILLink.RoslynAnalyzer/RequiresUnreferencedCodeAnalyzer.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs
> Warn on RUC annotated ctors invoked through `new()` constraint in analyzer

- src/ILLink.RoslynAnalyzer/RequiresUnreferencedCodeAnalyzer.cs
- src/ILLink.Shared/DiagnosticId.cs
- src/ILLink.Shared/SharedStrings.resx
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Resources/Strings.Designer.cs
- src/linker/Resources/Strings.resx
- test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs
Now that `MakeGenericMethod` and `MakeGenericType` methods were annotated in the runtime, we need to special case these in the analyzer to emit the right warning (IL2060 and IL2055, respectively).
> Special case `MakeGenericMethod/Type` in RUC analyzer

- eng/Versions.props
As discussed, use an unchanging numerical prerelease label. This produces versions like `6.0.100-1.short_date.revision` for both the package and the AssemblyInformationalVersion. The package version isn't user-facing since it just flows into the SDK, but we wanted the informational version not to say "preview" or "rtm". This also prevents us from having to update the prerelease labels in the future (we have never been very consistent about it in the past).
The assembly versions should be unchanged (`6:0:100:0` for the linker, versions like `6:0:4:45308` for the MSBuild task and analyzers where the last two components are computed from the date).
I noticed that there's another way to remove prerelease labels - you can just not set one, which defines it to be a "release-only" package per …
> [release/6.0] Remove preview branding

- docs/error-codes.md
- src/ILLink.Shared/DiagnosticId.cs
- src/ILLink.Shared/SharedStrings.resx
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/Annotations.cs
- test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs
- test/ILLink.RoslynAnalyzer.Tests/UnconditionalSuppressMessageCodeFixTests.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs
> [release/6.0] Add static constructor behavior for RUC on type (port of #2207)

- src/ILLink.CodeFix/BaseAttributeCodeFixProvider.cs
- src/ILLink.CodeFix/RequiresAssemblyFilesCodeFixProvider.cs
- src/ILLink.CodeFix/RequiresUnreferencedCodeCodeFixProvider.cs
- src/ILLink.CodeFix/UnconditionalSuppressMessageCodeFixProvider.cs
- test/ILLink.RoslynAnalyzer.Tests/RequiresAssemblyFilesAnalyzerTests.cs
- test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs
Backport of #2250 
Applying code fixes suggested by our fixer was causing multiple applications of the same fix (see [here](https://github.com/dotnet/roslyn/issues/54602)). This was caused by a race condition due to sharing the same instance of a `SyntaxEditor` across multiple invocations (see [comment](https://github.com/mono/linker/pull/2250#issuecomment-912926483)).
> [release/6.0] Update edited document before continuing code fixing

- test/Mono.Linker.Tests/TestCasesRunner/ILCompiler.cs
The ILCompiler class is giving me some grief.  These changes make it a little easier to deal with.
The first issue is that every test fails if ilasm cannot be located.  I think it would be better if only the tests that need ilasm fail when it cannot be found.  So instead of locating at construction time, locate ilasm when it is needed.
The next issue is that the `#if NETCOREAPP` logic for finding ilasm doesn't work when Mono.Linker.Tests is in our source tree, using our build process.  Currently, when we run the Mono.Linker.Tests in our source tree we are actually being routed down the `#else` path because our fork is fairly far behind and our version has `#if ILLINK` instead.  That causes us to call `LocateIlasmOnWindows` which doesn't find ilasm when targeting net5.  I think it's fairly …
> Make ILCompiler more flexible.

- src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
- test/ILLink.RoslynAnalyzer.Tests/LinkerTestCases.cs
- test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs
- test/ILLink.RoslynAnalyzer.Tests/TestCaseUtils.cs
- test/ILLink.RoslynAnalyzer.Tests/TestChecker.cs
- test/ILLink.RoslynAnalyzer.Tests/Verifiers/CSharpAnalyzerVerifier`1.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/ExpectedWarningAttribute.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/ProducedBy.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/Dependencies/RequiresUnreferencedCodeOnAttributeCtorAttribute.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeInCompilerGeneratedCode.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeOnAttributeCtor.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
> Warn on RUC annotated attribute ctors (analyzer)

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/Annotations.cs
Enable nullable on Annotations.cs
Change the MarkStep condition to check for null after TryResolve
Fixes https://github.com/dotnet/linker/issues/2274
I couldn't add a test case because I couldn't come up with a scenario in which the TypeReference Type.BaseType is not null but resolving the TypeReference is null
> Enable nullable on annotations

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/TypeReferenceMarker.cs
- test/Mono.Linker.Tests.Cases/BCLFeatures/ETW/CustomEventSource.cs
- test/Mono.Linker.Tests.Cases/BCLFeatures/ETW/CustomLibraryEventSource.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MemberTypes.cs
- test/Mono.Linker.Tests.Cases/DynamicDependencies/DynamicDependencyMemberTypes.cs
- test/Mono.Linker.Tests.Cases/Extensibility/CustomStepCanResolveTypesAfterSweep.cs
- test/Mono.Linker.Tests.Cases/Extensibility/Dependencies/ResolveTypesSubStep.cs
- test/Mono.Linker.Tests.Cases/References/AssemblyOnlyUsedByUsingWithCsc.cs
- test/Mono.Linker.Tests.Cases/References/AssemblyOnlyUsedByUsingWithCscWithKeepFacades.cs
- test/Mono.Linker.Tests.Cases/Reflection/EventUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/RuntimeReflectionExtensionsCalls.cs
- test/Mono.Linker.Tests.Cases/Serialization/CanDisableSerializationDiscovery.cs
- test/Mono.Linker.Tests.Cases/Serialization/DataContractJsonSerialization.cs
- test/Mono.Linker.Tests.Cases/Serialization/DataContractSerialization.cs
- test/Mono.Linker.Tests.Cases/Serialization/DataContractSerializationUnused.cs
- test/Mono.Linker.Tests.Cases/Serialization/SerializationTypeRecursion.cs
- test/Mono.Linker.Tests.Cases/Serialization/XmlSerialization.cs
- test/Mono.Linker.Tests.Cases/Serialization/XmlSerializationUnused.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/UsedAndUnusedForwarderWithAssemblyCopy.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/ComplexConditions.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestCaseMetadaProvider.cs
Fixes https://github.com/dotnet/linker/issues/2267.
This fixes the issue by taking the first approach mentioned in https://github.com/dotnet/linker/issues/2267#issuecomment-916379762. We now mark type forwarders referenced from any `TypeReference` we discover for a copy assembly, including `TypeReference`s to built-in types which only exist as bytes in metadata rather than typeref rows.
The walking logic in `TypeReferenceMarker` is copied from `AssemblyReferencesCorrector` in `SweepStep` and adjusted so that instead of updating the scopes of typereferences, it just marks any type forwarders they point to. The walking logic was duplicated to avoid touching `SweepStep` to reduce the risk of this change.
This includes a change to the test infrastructure to build tests against …
> Mark forwarders for all TypeReferences

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/TypeReferenceMarker.cs
- test/Mono.Linker.Tests.Cases/BCLFeatures/ETW/CustomEventSource.cs
- test/Mono.Linker.Tests.Cases/BCLFeatures/ETW/CustomLibraryEventSource.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MemberTypes.cs
- test/Mono.Linker.Tests.Cases/DynamicDependencies/DynamicDependencyMemberTypes.cs
- test/Mono.Linker.Tests.Cases/Extensibility/CustomStepCanResolveTypesAfterSweep.cs
- test/Mono.Linker.Tests.Cases/Extensibility/Dependencies/ResolveTypesSubStep.cs
- test/Mono.Linker.Tests.Cases/References/AssemblyOnlyUsedByUsingWithCsc.cs
- test/Mono.Linker.Tests.Cases/References/AssemblyOnlyUsedByUsingWithCscWithKeepFacades.cs
- test/Mono.Linker.Tests.Cases/Reflection/EventUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/RuntimeReflectionExtensionsCalls.cs
- test/Mono.Linker.Tests.Cases/Serialization/CanDisableSerializationDiscovery.cs
- test/Mono.Linker.Tests.Cases/Serialization/DataContractJsonSerialization.cs
- test/Mono.Linker.Tests.Cases/Serialization/DataContractSerialization.cs
- test/Mono.Linker.Tests.Cases/Serialization/DataContractSerializationUnused.cs
- test/Mono.Linker.Tests.Cases/Serialization/SerializationTypeRecursion.cs
- test/Mono.Linker.Tests.Cases/Serialization/XmlSerialization.cs
- test/Mono.Linker.Tests.Cases/Serialization/XmlSerializationUnused.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/UsedAndUnusedForwarderWithAssemblyCopy.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/ComplexConditions.cs
- test/Mono.Linker.Tests/TestCasesRunner/TestCaseCompilationMetadataProvider.cs
Port https://github.com/dotnet/linker/pull/2276 to main.
In a follow-up I plan to dedup by factoring out the shared code from SweepStep and TypeReferenceMarker.
> Mark forwarders for all TypeReferences (#2276)

- src/linker/Linker.Dataflow/DynamicallyAccessedMembersBinder.cs
- src/linker/Linker.Dataflow/FlowAnnotations.cs
- src/linker/Linker.Dataflow/MethodBodyScanner.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Dataflow/ValueNode.cs
This enables nullable annotations in a few files related to the dataflow analysis and support data structures. A lot of places are changed to use nullable `ValueNode?` - this is because we currently use `null` to represent unknown values during the dataflow. Later the unknown values typically are replaced with `UnknownValue.Instance` in the call to `UniqueValues`.
> Nullable annotations part 3

- eng/azure-pipelines.yml
We're required to move all servicing branches to the new 1ES servicing pools by September 30. This accomplishes that for release/latest.
Tracking issue: https://github.com/dotnet/core-eng/issues/14276
> Switch to servicing pools on release/6.0

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker.Steps/SweepStep.cs
- src/linker/Linker/TypeReferenceWalker.cs
Factor out the logic for walking an assembly to discover typerefs into a new abstract class, `TypeReferenceWalker`.
> Share logic for discovering typereferences

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/Reflection/MethodUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/MethodsUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/PropertiesUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/PropertyUsedViaReflection.cs
`IgnorableBindingFlags` are all new - we wouldn't consider them supported in the past. I'm also adding `BindingFlags.ExactBinding` in the first group - that one was considered unsupported in the past but this flag just disallows implicit widening and similar things that don't affect our binding logic (I don't think we would ever want to go in that territory).
> Make BindingFlagsAreUnsupported more precise

- src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
- test/ILLink.RoslynAnalyzer.Tests/LinkerTestCases.cs
- test/ILLink.RoslynAnalyzer.Tests/RequiresAssemblyFilesAnalyzerTests.cs
- test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs
- test/ILLink.RoslynAnalyzer.Tests/TestCaseUtils.cs
- test/ILLink.RoslynAnalyzer.Tests/TestChecker.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs
This makes the analyzer test validation more similar to the linker test validation and adds extra reporting when tests fail. The change caught a few differences between the linker and analyzer behavior:
- Analyzer was producing cctor warnings - so I removed that
- Analyzer was producing duplicate warnings for RUC properties set in attributes
- Analyzer behavior for reference to a testcase dependency assembly was already fixed
As part of this I also had to tweak the logic for checking whether a diagnostic originates from a particular member.
> Analyzer test infra improvements

- src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs
- src/ILLink.RoslynAnalyzer/ISymbolExtensions.cs
- src/ILLink.Shared/Annotations.cs
- test/ILLink.RoslynAnalyzer.Tests/DynamicallyAccessedMembersAnalyzerTests.cs
@mateoatr I was looking again at the analyzer and saw some opportunity to simplify. I didn't understand why we check for `Conversion` operations specifically at https://github.com/dotnet/linker/blob/feature/damAnalyzer/src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs#L125
so I wrote a test that should show a case where we might want different behavior for a conversion operator.
For now this pipes the `targetIsMethodReturn` argument through a few helpers, but soon we should be able to get rid of it and have a uniform representation of the source/target values.
> Simplify DAM analyzer and add conversion test

- src/ILLink.RoslynAnalyzer/COMAnalyzer.cs
- src/ILLink.RoslynAnalyzer/ISymbolExtensions.cs
- src/ILLink.Shared/DiagnosticId.cs
- src/ILLink.Shared/SharedStrings.resx
- test/ILLink.RoslynAnalyzer.Tests/LinkerTestCases.cs
- test/ILLink.RoslynAnalyzer.Tests/TestCaseUtils.cs
- test/Mono.Linker.Tests.Cases/Interop/PInvoke/Warnings/ComPInvokeWarning.cs
This adds support for `IL2050`. It is intended to be used for all other diagnostics related to COM in the analyzers. I didn't add any new tests -- we are reusing the ones under `Interop`.
> Add COMAnalyzer

- test/Mono.Linker.Tests.Cases/RequiresCapability/Dependencies/RequiresInCopyAssembly.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/Dependencies/RequiresOnAttributeCtorAttribute.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresCapability.attributes.xml
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresCapability.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresCapability.descriptor.xml
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresCapabilityFromCopiedAssembly.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresCapabilityReflectionAnalysisEnabled.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresInCompilerGeneratedCode.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresOnAttributeCtor.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.descriptor.xml
Rename RequiresUnreferencedCode to Requires to make the file agnostic of the attribute that is using, this is to later on use other Requires attributes in the same files
Only making changes to names since renaming files causes github to flag everything as conflicts. This will make it easier to make future changes
> Rename RequiresUnreferencedCode to Requires 

- eng/azure-pipelines.yml
We are migrating the build pools to 1ES hosted pools. This PR updates pipeline to use the new pools.
Tracking issue: https://github.com/dotnet/core-eng/issues/14276
> Migrate to 1ES hosted pools

- src/ILLink.RoslynAnalyzer/COMAnalyzer.cs
- src/ILLink.RoslynAnalyzer/ISymbolExtensions.cs
- src/ILLink.Shared/DiagnosticId.cs
- src/ILLink.Shared/SharedStrings.resx
- test/ILLink.RoslynAnalyzer.Tests/LinkerTestCases.cs
- test/ILLink.RoslynAnalyzer.Tests/TestCaseUtils.cs
- test/ILLink.RoslynAnalyzer.Tests/TestChecker.cs
- test/Mono.Linker.Tests.Cases.Expectations/Assertions/ProducedBy.cs
- test/Mono.Linker.Tests.Cases/Interop/PInvoke/Warnings/ComPInvokeWarning.cs
Rebased #2275 on top of main. ILLinkAnalyzer test checker was validating `ExpectedWarningAttribute`s for any diagnostic id -- I made changes in this PR so that we only validate diagnostic ids supported by the analyzer we are testing:
https://github.com/mateoatr/linker/blob/a540731187a7a0f1a7beb3d648d79003c589e4a6/test/ILLink.RoslynAnalyzer.Tests/TestChecker.cs#L34-L39
> Add COMAnalyzer 

- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresInCompilerGeneratedCode.cs
Let the warnings be generated by Trimmer and analyzer
Whenever discrepancies ocurred open an issue to track and let the test pass
> [DAM Analyzer] RequiresCapability now runs the DAM analyzer

- src/linker/Linker/Driver.cs
- test/Mono.Linker.Tests/TestCasesRunner/LinkerDriver.cs
When a test hits a `LinkerFatalErrorException` the test will fail with the following error
```
The linked output assembly was not found.  Expected at C:\Unity\dev\unity-monolinker-2\artifacts\testcases\illink\Attributes\GenericEnumInAttribute\...
The linked output assembly was not found.  Expected at C:\Unity\dev\unity-monolinker-2\artifacts\testcases\illink\Attributes\GenericEnumInAttribute\output\test.exe
Expected: True
But was:  False
```
This is not helpful and is very confusing.
Instead, when running tests, rethrow the `LinkerFatalErrorException` so that the tests correctly report an error.  Ex:
```
Mono.Linker.LinkerFatalErrorException : ILLink: error IL1005: Mono.Linker.Tests.Cases.Attributes.GenericEnumInAttribute.Main(): Error processing method …
```
> Improve test failure message when a fatal linker error exception happens

- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Properties/launchSettings.json
For https://github.com/dotnet/linker/issues/2089
Enabled by `--custom-data DisableMarkingOfCopyAssemblies=true` on the command line. Assumes that ALL assemblies on the input are in "copy" action (it doesn't validate this fact).
It disables marking basically fully - linker will go over all assemblies, and process them in "copy" mode (copy the original file over) and will call all the custom steps and so on, but it will do no marking (or very little, depends on descriptors and such which this doesn't disable).
This is intentionally non-discoverable feature, to be used only by the mono AOT toolchain.
/cc @rolfbjarne
> Add a custom flag to disable marking of copy assemblies

- src/linker/Linker/TypeMapInfo.cs
- test/Mono.Linker.Tests.Cases/FunctionPointers/CanCompileInterfaceWithFunctionPointerParameter.cs
- test/Mono.Linker.Tests.Cases/FunctionPointers/CanCompileMethodWithFunctionPointerParameter.cs
- test/Mono.Linker.Tests/TestCases/TestDatabase.cs
- test/Mono.Linker.Tests/TestCases/TestSuites.cs
One of my projects was throwing a `NullReferenceException` in .NET 6 RC2:
```
All projects are up-to-date for restore.
TerraFX.Interop.Windows -> C:\Users\tagoo\Source\repos\terrafx.interop.windows\artifacts\bin\sources\TerraFX.Interop.Windows\Release\net6.0\TerraFX.Interop.Windows.dll
TerraFX.Samples.DirectX -> C:\Users\tagoo\Source\repos\terrafx.interop.windows\artifacts\bin\samples\TerraFX.Samples.DirectX\Release\net6.0\win-x64\TerraFX.Samples.DirectX.dll
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [C:\Users\tagoo\Source\repos\terrafx.interop.windows\samples\DirectX\TerraFX.Samples.DirectX.csproj]
Fatal error in IL Linker
Unhandled exception. System.NullReferenceException: Object reference not …
```
> Fixing a null ref exception related to function pointers and interfaces

- test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/ImplementationLibrary.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/NestedForwarderLibrary.il
- test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/NestedForwarderLibrary_2.il
- test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/ReferenceImplementationLibrary.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/MultiForwardedTypesWithCopyUsed.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/MultiForwardedTypesWithLink.cs
- test/Mono.Linker.Tests/TestCasesRunner/ILCompiler.cs
The problematic scenario is if there's a "copy" assembly with a forwarder  to a "link" assembly with a forwarder. The forwarder is for a nested class.
Test for #2359.
The reason for "Random" behavior is a Cecil issue: https://github.com/jbevain/cecil/issues/812.
Also improved the test infra to print out errors from ilasm if they happen.
> Adds a test for multiple nested forwarders in a row with copy/link

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/NestedForwarderLibrary.il
- test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/NestedForwarderLibrary_2.il
- test/Mono.Linker.Tests.Cases/TypeForwarding/MultiForwardedTypesWithCopyUsed.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/MultiForwardedTypesWithLink.cs
When create a type reference for the target of a type forwarder, if the type forwarder is for a nested type, we have to build a whole tree of type references for all of the declaring types and not just the final nested type.
Enabled tests which were already added for this case (and fixed a bug in them)
This is a fix for https://github.com/dotnet/linker/issues/2359
> Fix marking of nested type forwarders

- .editorconfig
- lint.cmd
- lint.sh
- src/analyzer/ConsoleDependencyGraph.cs
- src/analyzer/LinkerAnalyzerCore/DependencyGraph.cs
- src/analyzer/LinkerAnalyzerCore/SpaceAnalyzer.cs
- src/analyzer/Main.cs
- test/ILLink.RoslynAnalyzer.Tests/CompilationExtensions.cs
- test/ILLink.RoslynAnalyzer.Tests/TestCaseCompilation.cs
- test/ILLink.RoslynAnalyzer.Tests/TestChecker.cs
- test/ILLink.Tasks.Tests/Mock.cs
- test/Mono.Linker.Tests/Extensions/CecilExtensions.cs
- test/Mono.Linker.Tests/Extensions/NiceIO.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
- test/Mono.Linker.Tests/Tests/DocumentationSignatureParserTests.cs
These were causing dotnet format to produce warnings because
they didn't have code fixes available. There are still some IDE0060
rule violations left over that I am not fixing here because they occur
in test projects (and I didn't want to silence all such warnings in the
test projects).
> Fix some analyzer warnings

- test/Mono.Linker.Tests.Cases/DataFlow/MethodByRefParameterDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodByRefReturnDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodParametersDataFlow.cs
Tests based on discussion in https://github.com/dotnet/linker/issues/2158.
> Add some tests for by ref type data flow

- src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs
- src/ILLink.Shared/DataFlow/ValueSet.cs
- src/ILLink.Shared/DataFlow/ValueSetLattice.cs
The idea is simple, store only a single object field.
If the field is null, the set is empty.
If the field is a HashSet, then it contains multiple values in that hashset.
If the field is TValue, then it set contains single value - that value.
I probably went a bit overboard on optimizations here, but I wanted to try what it takes to implement a good collection class. The result should not allocate at all when "Foreached" over if it contains no or single value (by far the most common case).
~~Unfortunately it still has to box the value. Maybe we should store two fields to avoid boxing by adding a cost of a single pointer field.~~
I just realized that all our uses cases will store reference types as values (`SingleValue` is a record class, `ValueNode` in the linker currently is just a …
> Improve ValueSet implementation to avoid HashSet creation every time

- eng/azure-pipelines.yml
See https://github.com/dotnet/core-eng/issues/14783.
Also switch to latest macOS/Ubuntu/Windows vmImage.
> Use non-deprecated Windows pool in Azure Pipelines

- eng/azure-pipelines.yml
Port of (#2393)
See https://github.com/dotnet/core-eng/issues/14783.
Also switch to latest macOS/Ubuntu/Windows vmImage.
> [feature/damAnalyzer] Use non-deprecated Windows pool in Azure Pipelines

- eng/azure-pipelines.yml
Port of (#2393)
See https://github.com/dotnet/core-eng/issues/14783.
Also switch to latest macOS/Ubuntu/Windows vmImage.
> [release/6.0.2xx] Use non-deprecated Windows pool in Azure Pipelines

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/BodySubstitutionParser.cs
- src/linker/Linker.Steps/DescriptorMarker.cs
- src/linker/Linker.Steps/DiscoverCustomOperatorsHandler.cs
- src/linker/Linker.Steps/MarkExportedTypesTargetStep.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker.Steps/ProcessLinkerXmlBase.cs
- src/linker/Linker.Steps/ProcessReferencesStep.cs
- src/linker/Linker.Steps/RootAssemblyInputStep.cs
- src/linker/Linker/Annotations.cs
- src/linker/Linker/CustomAttributeSource.cs
- src/linker/Linker/MarkingHelpers.cs
- src/linker/Linker/MessageContainer.cs
- src/linker/Linker/MessageOrigin.cs
- src/linker/Linker/SerializationMarker.cs
- test/Mono.Linker.Tests.Cases/LinkAttributes/LinkerAttributeRemovalAndPreserveAssembly.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresCapability.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresCapability.descriptor.xml
If we end up marking a type due to descriptor and the type marking will cause a warning (for example a removed attribute type does this in some cases), the warning infra would fail.
This is because it requires all warnings to have a valid origin including which assembly it came from. But descriptors didn't provide this information.
Most of the change here are to fix that lack of information. When marking through annotations, we now store the message origin for the mark operation along with the target of the marking. This is then restored on the scope stack to be used when reporting warnings caused by such marking.
This required lot of changes to pass the message origin in all places which end up marking things in annotations.
This also required some small fixes as it uncovered previously …
> Fixes a null-ref/NotSupportedException in warning infra

- src/ILLink.Shared/DataFlow/ValueSet.cs
- src/linker/Linker.Dataflow/MethodBodyScanner.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Dataflow/ValueNode.cs
- test/ILLink.RoslynAnalyzer.Tests/TestChecker.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodReturnParameterDataFlow.cs
Currently linker uses ValueNode to represent both single and multi-values. The multi-value is stored as a special value MergePoint. This means that basically every "Reader" should call UniqueValues which enumerates all values in the value. Otherwise it may only react to single-values and not function correctly for multi-values.
Also in order to share more code with the analyzer, we need to switch to the new model, where multi-values is stored in an explicit ValueSet.
This change replaces all the places where multiple values can be stored with MultiValue (=ValueSet<ValueNode>). Then it removes the MergePoint values and the entire infrastructure around it.
Other notable changes:
- Added implicit conversion from single TValue to ValueSet<TValue> to make it much easier to work with
- Changed …
> [feature/damAnalyzer] Change linker dataflow to use ValueSet/MultiValue

- src/linker/Linker.Dataflow/MethodBodyScanner.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Dataflow/ValueNode.cs
This is in preparation to merging the value type system with the analyzer and the `SingleValue` type.
Removes the Kind enum and uses type checks instead (there are not that many places actually since we already used type checks in lot of places).
Cleans up some of the value .ctors and properties.
Remove Equals/GetHashCode implementation where possible (leave it up to record).
> Convert ValueNode to record

- src/linker/Linker/LinkerAttributesInformation.cs
Fix for issue https://github.com/dotnet/linker/issues/2387 to use a list instead of a dictionary for LinkerAttributesInformation._linkerAttributes since the size of the collection is usually very small.
> Changes LinkerAttributesInformation._linkerAttributes to a List instead of a Dictionary

- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresCapability.cs
New test class DerivedClassWithAllWarnings was missing an `ExpectWarning` for IL3051
> Adds an ExpectedWarning for IL3051 to DerivedClassWithAllWarnings

- src/ILLink.RoslynAnalyzer/COMAnalyzer.cs
- src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
- src/ILLink.RoslynAnalyzer/RequiresISymbolExtensions.cs
- src/ILLink.RoslynAnalyzer/RequiresUnreferencedCodeAnalyzer.cs
- src/ILLink.RoslynAnalyzer/RequiresUnreferencedCodeUtils.cs
Add TargetHasRequiresAttribute to RequiresISymbolExtensions file
Add a RequiresUnreferencedCodeUtils file so other analyzers dont have to pass the RUC name everytime they use the RequiresISymbolExtensions
Refactor the RequiresAnalyzerBase to not have to verify the arguments while getting the attribute since the specific details on how to validate the attribute arguments are specific of the attribute implementation
Change COMAnalyzer to use the RequiresUnreferencedCodeUtils instead of the RequiresISymbolExtensions
This PR will help the DynamicallyAccessedMembersAnalyzer to produce RUC warnings
> Add TargetHasRequiresAttribute to RequiresISymbolExtensions file

- src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
- src/ILLink.RoslynAnalyzer/RequiresUnreferencedCodeAnalyzer.cs
- src/ILLink.Shared/DiagnosticId.cs
- src/ILLink.Shared/SharedStrings.resx
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/MemberReferenceExtensions.cs
- src/linker/Linker/MessageContainer.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresCapability.cs
Fixes https://github.com/dotnet/linker/issues/2416 by emitting IL2109 (Derived class without RUC derives from base class with RUC). Also modifies the path of nested types in warnings to use dots as type delimiters instead of a slash. (e.g. "namespace1.namespace2.base.nested.nested2" instead of "namespace1.namespace2.base/nested1/nested2")
> Fix Issue 2416: RUC Analyzer doesn't emit IL2109

- src/ILLink.RoslynAnalyzer/RequiresISymbolExtensions.cs
After separating the argument verification from getting the attribute in method TryGetRequiresAttribute, the method is just TryGetAttribute, so deleting the method to simplify stuff
> Simplify RequiresAttribute calls

- src/linker/Linker/MessageContainer.cs
Diagnostic messages would occasionally use the Cecil `FullName` property which uses '/' as a delimiter for nested classes. The standard is to use '.' instead. This fix uses `GetDisplayName()` instead to accomplish this.
Fixes https://github.com/dotnet/linker/issues/2441
> Remove cecil FullName property from diagnostic messages

- test/ILLink.Tasks.Tests/ILLink.Tasks.Tests.cs
The problem is that we run the task in a way which never happens in SDK. In SDK we always specify ToolPath/ToolExe values, but the test doesn't. The default implementation of these values rely on DOTNET_HOST_PATH which is not set when running from VS.
The fix calculates path to dotnet.exe from the test itself - it's not the most elegant way, but for now should always work as we only support running the tests on .NET Core (NOT on .NET Framework).
This only fixes the test `TestErrorHandling` when ran from VS.
I created a separate issue: https://github.com/dotnet/linker/issues/2452
To track the removal of support for running the task without setting the paths.
This is related to https://github.com/dotnet/linker/issues/806.
> Fix Task test which only fails in VS

- src/linker/Linker.Dataflow/MethodBodyScanner.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Dataflow/ValueNode.cs
So far the source was a ValueNode but the target was a Cecil's metadata item representation. In order to share this code with analyzer/AOT, we need to move away from metadata representations. Also in the improved data flow more of these "output" values will be tracked and thus must be stored as ValueNode anyway. And also in some cases the output value already is a ValueNode (storing to by ref values).
This is mostly mechanical change. The only test change is a fix for parameter names in messages, everything else works as before.
> [feature/damAnalyzer] Refactor linker's data flow to use ValueNode to represent the target of annotated value assignment

- test/Mono.Linker.Tests.Cases/DataFlow/AnnotatedMembersAccessedViaReflection.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeHierarchyReflectionWarnings.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresCapability.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresInCompilerGeneratedCode.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsInCompilerGeneratedCode.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
Previously the ExpectedWarning attribute in linker will silence multiple warnings if they matched the requirements. This allowed duplicated warnings to be generated without noticing. Analyzer silences only one warning per attribute showing some bugs in linker. This PR changes the ExpectedWarning behavior in linker to only silence one warning per attribute.
> ExpectedWarning silences only one warning per attribute

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/ImplementationLibrary.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/NestedForwarderLibrary.il
- test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/NestedForwarderLibrary_2.il
- test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/ReferenceImplementationLibrary.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/MultiForwardedTypesWithCopyUsed.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/MultiForwardedTypesWithLink.cs
- test/Mono.Linker.Tests/TestCasesRunner/ILCompiler.cs
Port of #2385 
Fixes marking of nested type forwarders.
Part of https://github.com/dotnet/linker/issues/2359.
Trimmer incorrectly removes type forwarders for nested type in some cases, breaking the application. One such impacted assembly is `Azure.ResourceManager.dll` (from Azure's NuGet package).
Added targeted test to the infrastructure. Validated that the change fixes the reported problem on a provided sample app.
Low. Before the change some nested type references were incorrect and Cecil would fail to resolve them effectively ignoring them in the process. After the change the nested type references are correctly created and Cecil can correctly resolve them, leading to including them in the output.
> [release/6.0.2xx] Fix marking of nested type forwarders

- src/linker/Linker.Steps/MarkStep.cs
This is a release/6.0.2xx port of #2370
Enabled by `--custom-data DisableMarkingOfCopyAssemblies=true` on the command line. Assumes that ALL assemblies on the input are in "copy" action (it doesn't validate this fact).
It disables marking basically fully - linker will go over all assemblies, and process them in "copy" mode (copy the original file over) and will call all the custom steps and so on, but it will do no marking (or very little, depends on descriptors and such which this doesn't disable).
This is intentionally non-discoverable feature, to be used only by the mono AOT toolchain.
Fixes https://github.com/dotnet/linker/issues/2089.
Xamarin "notrim" mode (used in AOT scenarios for debug builds for example) regressed with .NET 6 trimmer. The trimmer used to run quickly (several …
> [release/6.0.2xx] Add a custom flag to disable marking of copy assemblies

- src/ILLink.RoslynAnalyzer/DataFlow/LocalDataFlowVisitor.cs
- src/ILLink.RoslynAnalyzer/DataFlow/OperationWalker.cs
- src/ILLink.RoslynAnalyzer/DataFlow/StackGuard.cs
Thanks @vitek-karas for pointing this out!
> [DAM analyzer] Always recurse into child operations in visitor

- src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisPatternStore.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisVisitor.cs
During the analysis, we may pass over an operation multiple times with different dataflow states. As we go, we cache the dataflow values that are later used to produce warnings. This change makes the logic more robust by ensuring we never lose cached values.
As part of this I discovered (via some test failures) that caching these by operation isn't enough - for example, in `return Foo();` the `Foo()` may produce warnings both for a mismatch on the implicit receiver (`this`), and for the return value of `Foo()`. To fix this, I think it's enough to cache them by operation and whether it is a returned value.
> Ensure trim analysis patterns are additive

- eng/azure-pipelines.yml
Basically copied from release/6.0.2xx.
This is needed to make CI work on release/6.0
> Update CI pools to latest images

- src/ILLink.RoslynAnalyzer/RequiresISymbolExtensions.cs
- test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresOnAttributeCtor.cs
Porting https://github.com/dotnet/linker/pull/2530 to main.
> Fix analyzer nullref on assembly attribute

- src/ILLink.Shared/DiagnosticString.cs
- src/ILLink.Shared/SharedStrings.resx
Currently, missing resources will default to an empty string printing an empty message for the diagnostics. Code should not try to gracefully handle errors. 
Included in this PR:
DiagnosticString should be able to locate a title and message resource strings otherwise it throws
Add title resource strings for all missing diagnostic Ids
> Title and message resources should be enforced to exist to prevent printing empty messages

- src/linker/Linker.Dataflow/DiagnosticContext.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
Simplify diagnostic generation in ReflectionMethodBodyScanner after removal of Recognized/Unrecognized Reflection Access Pattern
Couldn't fully test these changes because of https://github.com/dotnet/linker/issues/2545
> [Feature/damAnalyzer] Simplify diagnostics

- test/Mono.Linker.Tests.Cases/DataFlow/GetInterfaceDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/LocalDataFlow.cs
"fixes" a test case in `GetInterface` which was not meant to run into the wrong linker behavior as per bug https://github.com/dotnet/linker/issues/2550
> Add a link to an issue for existing test case

- test/ILLink.RoslynAnalyzer.Tests/LinkAttributesTests.cs
- test/ILLink.RoslynAnalyzer.Tests/TestCaseCompilation.cs
- test/ILLink.RoslynAnalyzer.Tests/TestCaseUtils.cs
- test/ILLink.RoslynAnalyzer.Tests/XmlText.cs
Creates a new implementation of the `AdditionalText` class to use when passing xml files to the analyzers and adds test file path parameters to `CreateCompilation` signatures to find the xml files. The names of the test files are found in the `[SetupCompileResourceAttribute]` and `[SetupLinkAttributesFile]` attributes, then the paths are resolved relative to the test files and added to the compilation as "ILLink.LinkAttributes.xml". This does not yet add substitution and descriptor xml files, but it should be easy to add those later.
LinkAttributesTests test cases always fail, but they all include a LinkAttributes.xml file and are good for debugging to check that the ILLink.LinkAttributes.xml file shows up in the analyzers.
> Enable LinkAttributes.xml to be passed to analyzers in unit tests in AdditionalFiles

- src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
- src/ILLink.RoslynAnalyzer/RequiresISymbolExtensions.cs
- src/ILLink.RoslynAnalyzer/RequiresUnreferencedCodeAnalyzer.cs
- test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/LocalDataFlow.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresAccessedThrough.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresOnAttributeCtor.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresOnClass.cs
While investigating failures in https://github.com/dotnet/linker/pull/2536 I came across a bunch of places where we check for RequiresAttribute without considering RUC on type.
- DAM analyzer:
- checking for dataflow warnings. @tlakollo fixed these in https://github.com/dotnet/linker/pull/2536/commits/8121647f09929ed49f072ff878fe2681361c1c80. This change contains a few more tests.
- checking for generic method warnings. These tests aren't turned on yet but I added a few testcases that should be enabled as part of https://github.com/dotnet/linker/issues/2364.
- Requires analyzer:
- checking for attributes on ctors of types substituted for generic parameters with new constraint
- the above should be silenced if the declaring type of the caller has RequiresAttribute
- checking for …
> Fix inconsistencies in Requires attribute checks

- src/ILLink.RoslynAnalyzer/RequiresISymbolExtensions.cs
- test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresOnAttributeCtor.cs
The analyzer runs for property assignment operations, including those in
attributes. To check whether the property assignment should warn, we
look for RUC on the containing symbol. However, assembly-level attributes
are contained in the global namespace, which has a null containing type.
Assembly-level attribute with property assignment causes a crash in the RequiresAttribute analyzers. https://github.com/dotnet/linker/issues/2563 hits what is likely this issue.
Unit tests added in this change. This was originally discovered as part of running the analyzer over the existing linker tests as part of https://github.com/dotnet/linker/pull/2523.
Very low risk - the change adds an extra null check without impacting other code paths.
> [release/6.0.2xx] Fix analyzer nullref on assembly attribute

- src/ILLink.RoslynAnalyzer/DataFlow/LocalDataFlowVisitor.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisVisitor.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GetInterfaceDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodParametersDataFlow.cs
This is necessary for correct data flow processing since we need to check the arguments to ctor the same way we do any other method.
Added couple of simple tests.
> Handle object creation as a call to .ctor

- .editorconfig
- eng/azure-pipelines.yml
- lint.cmd
- lint.sh
- src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
- test/ILLink.RoslynAnalyzer.Tests/LinkAttributesTests.cs
- test/ILLink.RoslynAnalyzer.Tests/RequiresDynamicCodeAnalyzerTests.cs
- test/ILLink.RoslynAnalyzer.Tests/TestCaseCompilation.cs
- test/ILLink.RoslynAnalyzer.Tests/TestCaseUtils.cs
- test/ILLink.RoslynAnalyzer.Tests/XmlText.cs
It did run linter, but didn't fail if any changes were to be applied, instead it actually applied them (and then dropped). So the job would actually never fail.
> Fix lint job in CI

- src/ILLink.RoslynAnalyzer/RequiresUnreferencedCodeAnalyzer.cs
- test/ILLink.RoslynAnalyzer.Tests/ReflectionTests.cs
- test/Mono.Linker.Tests.Cases/DataFlow/ApplyTypeAnnotations.cs
- test/Mono.Linker.Tests.Cases/DataFlow/ComplexTypeHandling.cs
Fixes #2578 - temporary fix so as for the analyzer to not generate warnings until we add intrinsic support. This PR suppresses RUC and combined with #2596 should generate no warnings.
> No analyzer warnings for intrinsics

- src/ILLink.Shared/TrimAnalysis/HandleCallAction.cs
- test/ILLink.RoslynAnalyzer.Tests/DataFlowTests.cs
- test/ILLink.RoslynAnalyzer.Tests/ReflectionTests.cs
- test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs
This skips unimplemented intrinsics in the dataflow analyzer and enables more tests. Addresses part of https://github.com/dotnet/linker/issues/2578. Now the remaining warnings in skipped tests are all about RUC which @LakshanF is working on.
> [DAM analyzer] Disable dataflow warnings for unimplemented intrinsics

- src/ILLink.RoslynAnalyzer/DataFlow/LocalDataFlowVisitor.cs
- src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs
- src/ILLink.RoslynAnalyzer/ITypeSymbolExtensions.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisVisitor.cs
- test/Mono.Linker.Tests.Cases/DataFlow/FieldDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodParametersDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodReturnParameterDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodThisDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/PropertyDataFlow.cs
Produce warnings for annotations on invalid types using a symbol analyzer
Don't produce dataflow warnings for annotations on invalid types
Add extension file to ask if a type is interesting for dataflow
Fixes https://github.com/dotnet/linker/issues/2598
> Produce warnings for annotations on invalid types

- src/ILLink.RoslynAnalyzer/DataFlow/LocalDataFlowVisitor.cs
- test/Mono.Linker.Tests.Cases/DataFlow/PropertyDataFlow.cs
The value of a property set expression is the value, not the return value of the set method (void).
> [DAM analyzer] Fix property set expression value

- src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs
- test/ILLink.RoslynAnalyzer.Tests/Warnings.WarningSuppressionTests.cs
- test/Mono.Linker.Tests.Cases/DataFlow/FieldDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodParametersDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodReturnParameterDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodThisDataFlow.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresInCompilerGeneratedCode.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsInCompilerGeneratedCode.cs
Fixes #2587. This fix is temporary until we fix the linker.
- #2561 impacts the local functions and lambda data flow analysis
- The fix is sub-optimal in going through all the `IOperations `in a method to detect candidates for compiler generated code (other than async)
- Roslyn should expose `IsIterator `as a public API, which is a feature [request ](https://github.com/dotnet/roslyn/issues/20179)currently.
> Suppressing analyzer for compiler generated methods

- src/ILLink.RoslynAnalyzer/DataFlow/ControlFlowGraphProxy.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimDataFlowAnalysis.cs
- src/ILLink.Shared/DataFlow/ForwardDataFlowAnalysis.cs
- src/ILLink.Shared/DataFlow/IControlFlowGraph.cs
- test/ILLink.RoslynAnalyzer.Tests/AdvancedTests.cs
- test/ILLink.RoslynAnalyzer.Tests/UnreachableBlockTests.cs
- test/Mono.Linker.Tests.Cases/DataFlow/ExceptionalDataFlow.cs
This adds support for exception filters in the analyzer. Now the exception state will flow from from try blocks to any catch blocks without filters, or to the filter regions of any catch blocks that do have filters. Additionally, the dataflow state flows from a filter region to the next filter or catch. We don't check whether the exception type of the filter regions match, but conservatively assume that control can flow out of any filter to the next filter or catch.
This also assumes that control leaves the filter region from its last block - I don't know if there are cases where a filter region can contain more than one basic block, so if this is possible the logic might need to be updated.
I added a few testcases with dataflow and side effects in filter regions. This fixes …
> [DAM analyzer] Analyze exception filters

- test/ILLink.RoslynAnalyzer.Tests/DataFlowTests.cs
- test/Mono.Linker.Tests.Cases/DataFlow/ApplyTypeAnnotations.cs
- test/Mono.Linker.Tests.Cases/DataFlow/ComplexTypeHandling.cs
Analyzer intentionally "ignores" intrinsics which linker recognizes, but analyzer doesn't yet. Meaning it will not produce any warnings due to them.
Some tests didn't reflect this change correctly.
> Update tests to match analyzer behavior around intrinsics

- test/Mono.Linker.Tests.Cases/DataFlow/PropertyDataFlow.cs
The tests use fake generated backing fields, which the linker recognizes as the real thing, but the analyzer is not fooled. So it's expected the analyzer would produce warnings here - and the developer who writes code like this (hard to imagine why) should fix those warnings anyway.
> Update comments on tests with fake generated backing fields

- test/Mono.Linker.Tests.Cases/DataFlow/MethodByRefParameterDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodOutParameterDataFlow.cs
This adds tests for https://github.com/dotnet/linker/issues/2632
> Add tests for out and ref parameter data flow

- src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/BasicRequires.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresOnClass.cs
Add a condition to bypass `nameof` usage since it will not invoke the member and instead will be translated to load a string
Add tests
Fix ExpectedWarnings from disabled intrinsics that were producing warnings from accessing fields in a `nameof` call
Fixes #2647
> nameof calls should not warn on analyzer

- src/ILLink.RoslynAnalyzer/COMAnalyzer.cs
- test/Mono.Linker.Tests.Cases/Interop/PInvoke/Warnings/ComPInvokeWarning.cs
Analyzing the ContainingNamespace for a pointer type returns null, operating with this null value causes a crash in the COMAnalyzer analyzer. 
An analyzer crash will generate a compiler warning. Depending on user settings this could make the build to fail if warn as error is enabled.
Link to customer issue: https://github.com/dotnet/linker/issues/2622
Unit tests were added to this change.
Very low risk - the change adds an extra check for pointer type before operating with the value, this makes the method return before impacting other code paths.
Fixes #2622
> [release 6.0.2xx] Port Fix: Add check for pointer types in IsComInterop (#2623)

- src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresCapability.cs
Brings the fix @agocke made as part of https://github.com/dotnet/linker/pull/2540 to 6.0.2. Fixes https://github.com/dotnet/linker/issues/2642.
Updating VS from 17 to 17.1 brings in a 6.0.2 SDK which causes the analyzer to crash on a project that previously worked, producing a warning. The warning also shows up in CI when using the 6.0.2 SDK, and fails the build with warnaserror. See details in https://github.com/dotnet/linker/issues/2642.
Unit tests confirmed the issue and the fix. This was originally discovered as part of running the analyzer over itself and the linker in https://github.com/dotnet/linker/pull/2523.
Very low risk - this turns a cast to a type check, and skips the case which used to throw an InvalidCastException.
> [release/6.0.2xx] Fix invalid cast of type parameter

- src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisVisitor.cs
- test/ILLink.RoslynAnalyzer.Tests/DataFlowTests.cs
- test/Mono.Linker.Tests.Cases/DataFlow/FieldDataFlow.cs
Also enable a skipped test with `allowMissingWarnings`.
Runtime is producing warnings with the latest analyzer on https://github.com/dotnet/runtime/blob/959a13fa0d1822dc4c7bfc99a9d5e7a0c50d6306/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ToolboxItemAttribute.cs#L90. This fixes that by detecting string.Empty like the linker does. The other field that the linker handles specially is System.Type.EmptyTypes - I'm not addressing that here because we don't track arrays yet.
> Understand String.Empty

- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
This warning message should refer to `ExpectedNoWarnings`, not `ExpectedWarning`
> Fix Typo in test failure warning

- src/ILLink.RoslynAnalyzer/TrimAnalysis/HandleCallAction.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/MethodParameterValue.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/ReflectionAccessAnalyzer.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisVisitor.cs
- src/ILLink.Shared/TrimAnalysis/HandleCallAction.cs
- src/ILLink.Shared/TrimAnalysis/SystemReflectionMethodBaseValue.cs
- src/linker/Linker.Dataflow/HandleCallAction.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Dataflow/ValueNode.cs
- test/ILLink.RoslynAnalyzer.Tests/DynamicallyAccessedMembersAnalyzerTests.cs
- test/ILLink.RoslynAnalyzer.Tests/ReflectionTests.cs
- test/ILLink.RoslynAnalyzer.Tests/generated/ILLink.RoslynAnalyzer.Tests.Generator/ILLink.RoslynAnalyzer.Tests.TestCaseGenerator/ReflectionTests.g.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AnnotatedMembersAccessedViaReflection.cs
- test/Mono.Linker.Tests.Cases/DataFlow/DynamicDependencyDataflow.cs
- test/Mono.Linker.Tests.Cases/Reflection/MethodsUsedViaReflection.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresAccessedThrough.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresOnClass.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresWithCopyAssembly.cs
Other than sharing more code and adapting it so that it works on both linker and analyzer, this change brings simple analysis of constant integer values in the analyzer. This is necessary to make most reflection API calls recognize binding flags. For example `GetMethods(BindingFlags.Public | BindingFlags.Static)`. So this change adds analysis of constant values (as recognized by the Roslyn's operation tree) and the OR binary operator for integers and enums.
Added some new tests for the binding flags handling.
Reenabled some disabled tests for analyzer.
Moved the main affected tests from the generated source files to the hardcoded one and force them to exact match of warnings for both linker and analyzer.
> Share intrinsic handling of GetMember and similar APIs

- docs/design/reflection-flow.md
Fixes https://github.com/dotnet/linker/issues/2657#issuecomment-1051702302
> Remove mention of PreserveDependencyAttribute from docs

- src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/HandleCallAction.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/ReflectionAccessAnalyzer.cs
- src/ILLink.Shared/TrimAnalysis/HandleCallAction.cs
- src/linker/Linker.Dataflow/HandleCallAction.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/ILLink.RoslynAnalyzer.Tests/ReflectionTests.cs
- test/ILLink.RoslynAnalyzer.Tests/generated/ILLink.RoslynAnalyzer.Tests.Generator/ILLink.RoslynAnalyzer.Tests.TestCaseGenerator/ReflectionTests.g.cs
- test/Mono.Linker.Tests.Cases/Reflection/ExpressionFieldString.cs
- test/Mono.Linker.Tests.Cases/Reflection/ExpressionPropertyMethodInfo.cs
- test/Mono.Linker.Tests.Cases/Reflection/ExpressionPropertyString.cs
Shares two more intrinsics, with supporting infra.
Fixed a bug in the intrinsics - passing null to the name of a property/field will throw at runtime, so no need to validate anything.
Modifies the existing tests to add warnings, since that is the only verifyable behavior for the analyzer.
> Share intrinsics for Expression.Property and Field

- eng/Versions.props
- test/ILLink.RoslynAnalyzer.Tests/TestChecker.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresInCompilerGeneratedCode.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsInCompilerGeneratedCode.cs
- test/Mono.Linker.Tests/Mono.Linker.Tests.csproj
This updates a few of the compiler-generated code tests to put the `ExpectedWarning` attribute on lambdas and local functions when possible, removing the need for `CompilerGeneratedCode = true` in these places.
Unfortunately the formatting became weird - dotnet format seems to require the lambda to not be indented following the attribute, and I couldn't find a good workaround so I'm leaving it as-is. (Filed https://github.com/dotnet/format/issues/1548) edit: Ok, I changed it to at least unindent the attributes as well to match the lambda expression. Otherwise multiple attributes on lambdas have inconsistent indentation.
> Use attributes on lambdas in tests

- src/ILLink.Shared/TrimAnalysis/HandleCallAction.cs
- test/Mono.Linker.Tests.Cases/DataFlow/TypeBaseTypeDataFlow.cs
@vitek-karas this should fix some of the issues you are seeing with dataflow in foreach loops involving `Type.BaseType`.
@vitek-karas shared the following testcase which was warning:
```csharp
// Can only work with All annotation as NonPublicProperties doesn't propagate to base types
static void EnumeratePrivatePropertiesOnBaseTypesWithForeach ([DynamicallyAccessedMembers (DynamicallyAccessedMemberTypes.All)] Type type)
{
const BindingFlags DeclaredOnlyLookup = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly;
Type? t = type;
while (t != null) {
foreach (var p in t.GetProperties (DeclaredOnlyLookup)) {
// Do nothing
}
t = t.BaseType;
}
}
```
This was producing a warning because during the first pass of the analysis over …
> Fix empty/null handling for Type.BaseType intrinsic

- test/Mono.Linker.Tests.Cases/DataFlow/GetInterfaceDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/TypeBaseTypeDataFlow.cs
@vitek-karas just adding the testcases you shared with me (should already be fixed, by https://github.com/dotnet/linker/pull/2694).
> Add test get interfaces

- test/Mono.Linker.Tests/Tests/GetDisplayNameTests.cs
There seems to be a race condition on Cecil while trying to get GenericParameters, if a multithreaded test asks simultaneously about GenericParameters on the same type Cecil answers could vary creating test failures. 
Fixes #2693
> Avoid running GetDisplayNameTests in parallel

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/ComponentModel/TypeDescriptionProviderAttributeOnType.cs
(cherry picked from commit b10e1bc3da22862b4ddedc2b50639dee9d8dacfd)
The linker has had a special case for the TypeConverterAttribute for a while. In .NET 6, the logic was properly annotated, and the special casing can actually produce spurious warnings. This change removes the special casing.
Consumers like MAUI use TypeConverterAttribute and are seeing lots of spurious warnings, which is harming their ability to make things trimmable for .NET 6.
Low. Removes special casing.
> [release/6.0.2xx] Remove special logic for TypeConverterAttribute (#2659)

- test/Mono.Linker.Tests.Cases/DataFlow/ArrayDataFlow.cs
It looks like there was a mistake on the tests for array tracking. Passing an array element as a ref parameter should reset that element, but not others. Previously it expected that it would not reset the known index.
> Update array data flow test

- src/ILLink.RoslynAnalyzer/RequiresISymbolExtensions.cs
- src/linker/Linker/Annotations.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresOnStaticConstructor.cs
We don't allow RUC on static constructors, and putting one there produces a warning. The current behavior happens to silence warnings from the cctor but it seems more consistent for it not to have any effect on the warnings since it isn't supported.
> Don't let RUC on cctor silence warnings

- src/ILLink.RoslynAnalyzer/RequiresISymbolExtensions.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/Annotations.cs
- src/linker/Linker/CallGraph.cs
- src/linker/Linker/CompilerGeneratedNames.cs
- src/linker/Linker/CompilerGeneratedState.cs
- src/linker/Linker/UnconditionalSuppressMessageAttributeState.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresInCompilerGeneratedCode.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsInCompilerGeneratedCode.cs
This adds support for `RequiresUnreferencedCode` and `UnconditionalSuppressMessage` on lambdas and local functions, relying on heuristics and knowledge of compiler implementation details to detect lambdas and local functions.
This approach scans the code for IL references to lambdas and local functions, which has some limitations.
- Unused local functions aren't referenced by the containing method, so warnings from these will not be suppressed by suppressions on the containing method. Lambdas don't seem to have this problem, because they contain a reference to the generated method as part of the delegate conversion.
- The IL doesn't in general contain enough information to determine the nesting of the scopes of lambdas and local functions, so we make no attempt to do this. We only try to …
> Lambda and local function suppressions

- src/linker/Linker.Dataflow/ArrayValue.cs
- src/linker/Linker.Dataflow/FieldValue.cs
- src/linker/Linker.Dataflow/GenericParameterValue.cs
- src/linker/Linker.Dataflow/MethodParameterValue.cs
- src/linker/Linker.Dataflow/MethodReturnValue.cs
- src/linker/Linker.Dataflow/MethodThisParameterValue.cs
- src/linker/Linker.Dataflow/RuntimeMethodHandleValue.cs
- src/linker/Linker.Dataflow/SingleValueExtensions.cs
Fixes new headers which were causing the build to fail after https://github.com/dotnet/linker/commit/4f0d349e43a71d44ef71339293701fcfc2da997e.
> Fix headers in new files

- src/linker/Linker/CompilerGeneratedNames.cs
Forgot to check for array length in https://github.com/dotnet/linker/pull/2689.
I'll see if I can find out what methods were hitting this in https://github.com/dotnet/runtime/pull/67381#issuecomment-1086214962, to see if they need different handling.
edit: the logs from that run suggest it might have been hit for the method `SimpleWasmTestRunner.<Main>(String[])`. I'm not clear on why the main method would be emitted with that name, but in any case this seems to be one example.
> Fix IndexOutOfRangeException

- src/ILLink.RoslynAnalyzer/DataFlow/LocalDataFlowVisitor.cs
- test/Mono.Linker.Tests.Cases/DataFlow/PropertyDataFlow.cs
This fixes one of NREs encountered in https://github.com/dotnet/linker/issues/2718, where the analyzer failed to analyze an assignment to a get-only property. The linker will warn about the compiler-generated backing field in this case.
This fix just skips this case in the analyzer. It would be more correct to produce a warning because this represents a legitimate dataflow issue. The problem is that the analyzer has no insight into the compiler-generated backing field, as far as I know.
One option would be to produce a warning with the same code as the linker, but adjust the message so that it mentions the property instead of the backing field - it would require some changesto the DiagnosticId infrastructure since we would need slightly different messages for all of the warnings where a …
> Don't throw on write to get-only property

- src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterDataFlow.cs
- test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
Add check for cref in generic parameter dataflow to avoid failing with a nullreference exception
Refactor code to reuse the while loop for both INamedType and Method symbols
Add tests
Fixes https://github.com/dotnet/linker/issues/2724
> Avoid analyzing cref for generic parameters

- src/linker/Mono.Linker.csproj
Fixes https://github.com/dotnet/linker/issues/2615
This will need to be backported to 6.0 as it is a source-build regression in the sense that it introduces a prebuilt.
> Condition out the BannedApiAnalyzers usage in source-build

- src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimDataFlowAnalysis.cs
When debugging applications via de console is very useful to have a Console print about the different values being used. In the case of debugging via the Test Explorer in Visual Studio, the Console output is not available to the user.
This PR adds the functionality to be able to choose to print to the Debug console that is available in Visual Studio while running a test via the Test Explorer
Adds enum to choose between Console and Debug output
> Add support for Debug output in Analyzer

- src/linker/Mono.Linker.csproj
Cherry pick https://github.com/dotnet/linker/commit/6564aad35881703832aab9edb81558e0b6dd5698
Related to https://github.com/dotnet/linker/issues/2615
Can someone please confirm this is the right branch for the changes to flow into the 6.0.3xx sdk?  TIA
> [release/6.0.x] Condition out the BannedApiAnalyzers usage in source-build (#2742)

- src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisMethodCallPattern.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisVisitor.cs
- test/ILLink.RoslynAnalyzer.Tests/ReflectionTests.cs
- test/ILLink.RoslynAnalyzer.Tests/generated/ILLink.RoslynAnalyzer.Tests.Generator/ILLink.RoslynAnalyzer.Tests.TestCaseGenerator/ReflectionTests.g.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeDelegator.cs
Some intrinsics require generic instantiation handling. Currently the shared code doesn't have the abitlity to do this, so we leave it as a special case and analyzer/linker have special code to handle it.
In the analyzer this code was missing from the diagnsotic reporting part and thus the intrinsic was handled as a normal method call - which caused problems with TypeDelegator.
Added tests for TypeDelegator which cover these issues.
This is blocking linker->runtime flow: https://github.com/dotnet/runtime/pull/68386
> Fix handling of special intrinsics in analyzer

- src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/GenericParameterProxy.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/GenericParameterValue.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/MethodProxy.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisAssignmentPattern.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisMethodCallPattern.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisVisitor.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/TypeProxy.cs
- src/ILLink.Shared/TrimAnalysis/GenericParameterValue.cs
- src/ILLink.Shared/TrimAnalysis/HandleCallAction.cs
- src/ILLink.Shared/TrimAnalysis/RequireDynamicallyAccessedMembersAction.cs
- src/ILLink.Shared/TypeSystemProxy/GenericParameterProxy.cs
- src/ILLink.Shared/TypeSystemProxy/MethodProxy.cs
- src/ILLink.Shared/TypeSystemProxy/TypeProxy.cs
- src/linker/Linker.Dataflow/GenericParameterProxy.cs
- src/linker/Linker.Dataflow/GenericParameterValue.cs
- src/linker/Linker.Dataflow/MethodProxy.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Dataflow/TypeProxy.cs
- test/ILLink.RoslynAnalyzer.Tests/DataFlowTests.cs
- test/ILLink.RoslynAnalyzer.Tests/ReflectionTests.cs
- test/ILLink.RoslynAnalyzer.Tests/generated/ILLink.RoslynAnalyzer.Tests.Generator/ILLink.RoslynAnalyzer.Tests.TestCaseGenerator/ReflectionTests.g.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AnnotatedMembersAccessedViaReflection.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MakeGenericDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/NullableAnnotations.cs
- test/Mono.Linker.Tests.Cases/Reflection/ExpressionCallString.cs
- test/Mono.Linker.Tests.Cases/Reflection/ExpressionCallStringAndLocals.cs
Moves the intrinsic handling of `MakeGenericType`, `MakeGenericMethod` and `Expression.Call` into the shared code.
Other changes:
* Some small refactorings on the shared type system and value system.
* Expose generic parameters on type system proxies
* Fix a bug in analyzer when we're recording patterns, the values must be cloned (as they can mutate during analysis after the record is taken)
* Fix some problems in Nullable<T> handling in MakeGenericType - specifically if we don't know what the T is going to be, we now return just Nullable<> known type (but unknown T).
* Add couple new tests - update existing ones (mainly due to limitation in the analyzer)
> Share MakeGeneric.. and Expression.Call

- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresOnClass.cs
The analyzer produces warning in this case which the linker doesn't.
Test for bug https://github.com/dotnet/linker/issues/2763
> Add a test for RUC on type with override method

- src/linker/Linker.Dataflow/DynamicallyAccessedMembersTypeHierarchy.cs
- src/linker/Linker.Dataflow/HandleCallAction.cs
- src/linker/Linker.Dataflow/ReflectionMarker.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Dataflow/RequireDynamicallyAccessedMembersAction.cs
Follow-up to https://github.com/dotnet/linker/pull/2747. This is a factoring change only and doesn't introduce functional changes.
This does two things to move the method body scanner to be more similar to the trim analysis visitor:
- Uses `DiagnosticContext` to record diagnostics. Right now, this still happens inline as we run the scanner, but the idea will be to move this out to a driver that runs the analysis, and then records diagnostics from the recorded patterns (like how it is done in the analyzer)
- Moves reflection-marking helpers out of `ReflectionMethodBodyScanner` to a separate class. This prevents us from having to pass around the scanner to other helpers, and makes it more obvious which parts of the code to scanning only vs other things. The new `ReflectionMarker` is …
> Factor ReflectionMethodBodyScanner to be more similar to analyzer

- src/ILLink.RoslynAnalyzer/TrimAnalysis/FlowAnnotations.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/ReflectionAccessAnalyzer.cs
- src/ILLink.Shared/TrimAnalysis/FlowAnnotations.cs
- src/linker/Linker.Dataflow/FlowAnnotations.cs
To avoid unnecessary allocations, as per the feedback from @vitek-karas: https://github.com/dotnet/linker/pull/2757#discussion_r858524693
> Make FlowAnnotations and ReflectionAccessAnalyzer structs

- src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/HandleCallAction.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/MethodProxy.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/ReflectionAccessAnalyzer.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/RequireDynamicallyAccessedMembersAction.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisVisitor.cs
- src/ILLink.Shared/TrimAnalysis/HandleCallAction.cs
- src/ILLink.Shared/TrimAnalysis/IntrinsicId.cs
- src/ILLink.Shared/TrimAnalysis/Intrinsics.cs
- src/ILLink.Shared/TrimAnalysis/RequireDynamicallyAccessedMembersAction.cs
- src/ILLink.Shared/TypeSystemProxy/MethodProxy.cs
- src/linker/Linker.Dataflow/HandleCallAction.cs
- src/linker/Linker.Dataflow/MethodProxy.cs
- src/linker/Linker.Dataflow/ReflectionMarker.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Dataflow/RequireDynamicallyAccessedMembersAction.cs
- test/ILLink.RoslynAnalyzer.Tests/DataFlowTests.cs
- test/ILLink.RoslynAnalyzer.Tests/ReflectionTests.cs
- test/ILLink.RoslynAnalyzer.Tests/generated/ILLink.RoslynAnalyzer.Tests.Generator/ILLink.RoslynAnalyzer.Tests.TestCaseGenerator/ReflectionTests.g.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GetTypeDataFlow.cs
- test/Mono.Linker.Tests.Cases/Reflection/ActivatorCreateInstance.cs
- test/Mono.Linker.Tests.Cases/Reflection/ExpressionNewType.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflection.cs
This shared pretty much all of the remaining intrinsics except for `object.GetType` (type hierarchy marking).
The linker move is straightforward and the only functional changes are:
* `Type.GetType()` with unsupported case insensitive search will not produce warnings from its return value
* Removed intrinsics handling of `Activator.CreateInstance<T>` - it's not needed, annotations do the same thing, and avoid generating duplicate warnings. This fixes: https://github.com/dotnet/linker/issues/1483
In the analyzer there are two behavioral differences from linker:
* Searching for assembly name + type name is completely disabled (no warnings, ignored) - see the comment added, but there's no good way to do it in most cases and probably not common. We can improve if really necessary.
* …
> Share Type.GetType and similar intrinsics

- src/linker/Linker.Steps/SweepStep.cs
- test/Mono.Linker.Tests.Cases/Libraries/Dependencies/CopyLibrary.cs
- test/Mono.Linker.Tests.Cases/Libraries/Dependencies/SkipLibrary.cs
- test/Mono.Linker.Tests.Cases/Libraries/RootLibrary.cs
- test/Mono.Linker.Tests/TestCasesRunner/AssemblyChecker.cs
Before removing overrides, we should check if the overridden method is
in an ignore scope.
In the linker we consider types and methods in a `skip` assembly as "removed", so when the linker would check if an overridden method is removed, it would see that it is considered removed, even though it should be considered kept. The workaround is to use the IgnoreScope helper to determine if the interface method is in a `link` assembly and removed, and only remove the MethodImpl if both are true.
Now, whether `ShouldRemove` should return true or false for things in a skip assembly, I'm not sure. It depends on whether it does / should mean "Actively removed from the assembly" or "not in the final output".
This PR fixes the issues found in https://github.com/dotnet/runtime/pull/68612.
> Don't remove MethodImpl if overridden method is not in a link assembly

- src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisVisitor.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GetTypeDataFlow.cs
This means the value of the fields is tracked as a const value instead of a field reference.
This is to support some additional code patterns as well as align the behavior with the linker. Compiler will inline the const fields into the IL effectively removing the field reference in these cases and linker only sees the constant. So ideally the analyzer should have a similar behavior.
This is currently blocking runtime integration: https://github.com/dotnet/runtime/pull/68650
> Add ability for the analyzer to recognize const fields

- src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
- src/ILLink.RoslynAnalyzer/RequiresISymbolExtensions.cs
- src/ILLink.RoslynAnalyzer/RequiresUnreferencedCodeUtils.cs
- src/ILLink.Shared/DiagnosticId.cs
- src/ILLink.Shared/ILLink.Shared.projitems
- src/ILLink.Shared/MessageSubCategory.cs
- src/ILLink.Shared/SharedStrings.resx
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker.Steps/ValidateVirtualMethodAnnotationsStep.cs
- src/linker/Linker/Annotations.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresOnStaticConstructor.cs
Match analyzer and linker requires methods to be more similar according to their behavior
Sync diagnostic Id in NativeAOT with the information in linker
> Match analyzer and linker requires methods

- test/Mono.Linker.Tests.Cases/DataFlow/AttributeConstructorDataflow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AttributeFieldDataflow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AttributePropertyDataflow.cs
Use RUC warnings to validate correct marking caused by attribute data flow.
The analyzer side of these tests doesn't work yet as they use string->type marking and the analyzer is missing a type name parser for now.
> Better tests for attribute dataflow

- test/Mono.Linker.Tests.Cases/Reflection/ObjectGetType.cs
- test/Mono.Linker.Tests.Cases/Reflection/TypeHierarchyReflectionWarnings.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresOnVirtualsAndInterfaces.cs
First one is for the case where Derived type is annotated and has a virtual RUC method (and the base type has that same method with RUC as well). The warning should be generated for the base RUC method.
Second one is for type hierarchy marking of non-public members on base types when the derived type has the annotation. This is a test for https://github.com/dotnet/linker/issues/2813
> Add two specific tests for type hierarchy marking

- .editorconfig
- eng/Versions.props
- src/ILLink.RoslynAnalyzer/ILLink.RoslynAnalyzer.csproj
- src/ILLink.Shared/TrimAnalysis/IntrinsicId.cs
- src/ILLink.Shared/TypeSystemProxy/WellKnownType.cs
- src/linker/Mono.Linker.csproj
In some cases, it is helpful to only cover named values of enums in a switch without a catch-all at the bottom. Since the warning code is different for named and unnamed variants we can disable the unnamed variants warning. This way, if all named variants are accounted for without the catch-all and a new variant is added it will warn in that location rather than only showing up at runtime.
> Don't warn on enum switch if named values are exhaustive

- test/Mono.Linker.Tests.Cases/DataFlow/IReflectDataflow.cs
There's no bug in this, I just found this use case interesting and wanted to add a test into linker to make sure we don't break this.
> Add a test for IReflect which simulates usage from winforms

- src/ILLink.RoslynAnalyzer/TrimAnalysis/HandleCallAction.cs
- src/ILLink.Shared/TrimAnalysis/HandleCallAction.cs
- src/linker/Linker.Dataflow/HandleCallAction.cs
- src/linker/Linker.Dataflow/ReflectionMarker.cs
- src/linker/Linker/LinkContext.cs
- src/linker/Linker/TypeNameResolver.cs
- test/Mono.Linker.Tests.Cases/DataFlow/ComplexTypeHandling.cs
- test/Mono.Linker.Tests.Cases/TypeForwarding/UsedForwarderInGenericIsDynamicallyAccessedWithAssemblyCopyUsed.cs
- test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
Previously we only marked the type forwarder for the outer-most type (if any), but the same problem can happen with type names in generic arguments. If they are forwarder we need to mark those type forwarders as well.
This change records all type resolutions during the string->Type resolution and then makes sure that all type forwarders used get marked.
Renamed a method on HandleCallAction to make it more descriptive of what it actually does. Also unifies all string->Type resolution into the ReflectionMarker.
Enabled test which has been already added for the bug and added another variation (CreateInstance).
Improved ResultsChecker to include assembly names in validation messages.
Fixes https://github.com/dotnet/linker/issues/1536
> Mark all type forwarders used during string->Type resolution

- src/linker/Linker.Dataflow/MethodProxy.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodByRefParameterDataFlow.cs
In the linker, ParameterReferenceKind expects the IL parameter index (with `this` as 0), but MethodProxy would pass the index without this. This fix adds a test that failed with the incorrect order, but works after accounting for the offset.
> Adjust ref param kind check for IL offset

- src/ILLink.RoslynAnalyzer/DiagnosticDescriptors.cs
- src/ILLink.Shared/DiagnosticId.cs
- src/ILLink.Shared/TrimAnalysis/DiagnosticContext.cs
- src/linker/Linker/CompilerGeneratedState.cs
- src/linker/Linker/MessageOrigin.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AttributeConstructorDataflow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AttributeFieldDataflow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AttributePropertyDataflow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/ByRefDataflow.cs
* Move GetDiagnosticCategory into shared code
* Describe the intent around usage of DiagnosticContext in a comment
* Minor fix in MessageOrigin GetHasCode
* Add tests for patterns which NativeAOT had trouble with
Linker changes made for https://github.com/dotnet/runtime/pull/71485
> Small updates to help with linker->aot port

- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/AddSuppressionsBeforeAttributeRemoval.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/AddSuppressionsBeforeAttributeRemoval.xml
The test generated warnings which were not checked. The XML file was pointing to the wrong assembly and the linker raised IL2072 warning. Instead, the test verified the suppression of warning IL2067, which was not raised by the linker in the first place.
@vitek-karas
> Fixed AddSuppresionsBeforeAttributeRemoval test

- test/ILLink.RoslynAnalyzer.Tests/generated/ILLink.RoslynAnalyzer.Tests.Generator/ILLink.RoslynAnalyzer.Tests.TestCaseGenerator/UnreachableBlockTests.g.cs
- test/Mono.Linker.Tests.Cases/UnreachableBlock/ComplexConditionsOptimized.cs
This is a test for https://github.com/dotnet/linker/issues/2872
> Add a test for unsupported branch instruction crash

- src/linker/Linker.Dataflow/AttributeDataFlow.cs
- src/linker/Linker.Dataflow/CompilerGeneratedCallGraph.cs
- src/linker/Linker.Dataflow/CompilerGeneratedState.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AttributeConstructorDataflow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AttributeFieldDataflow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AttributePropertyDataflow.cs
This also makes small tweaks to help with linker->AOT sync.
> Fix a bug with null value passed to annotated parameter on attribute

- src/ILLink.CodeFix/BaseAttributeCodeFixProvider.cs
- src/ILLink.CodeFix/RequiresAssemblyFilesCodeFixProvider.cs
- src/ILLink.CodeFix/RequiresDynamicCodeCodeFixProvider.cs
- src/ILLink.CodeFix/RequiresUnreferencedCodeCodeFixProvider.cs
- src/ILLink.CodeFix/UnconditionalSuppressMessageCodeFixProvider.cs
- src/ILLink.RoslynAnalyzer/ISymbolExtensions.cs
- test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs
The syntax node scope should be the innermost node, otherwise
GetSymbolInfo will often return null. As an example, GetSymbolInfo will
return null for an ArgumentSyntax node, but the underlying expression
will likely resolve into a symbol.
Also adds proper null checks in case any of the providers return null.
> Fix syntax node scope and nullable warnings

- test/Mono.Linker.Tests.Cases/DataFlow/CompilerGeneratedCodeAccessedViaReflection.cs
The lambda calls a generic method which has annotation on the generic argument to keep `All`, and the lambda passes its own parent type as the argument. So the annotation will end up marking the lambda itself.
This is a test for https://github.com/dotnet/linker/issues/2903
The test is disabled by commenting out the code which causes the bug.
> Add a test for stack overflow when marking lambda which indirectly marks itself

- docs/design/redundant-suppressions.md
Problem description and potential solution overview.
@vitek-karas
> Redundant warning suppressions detection

- src/analyzer/LinkerAnalyzerCore/DependencyGraph.cs
- src/analyzer/README.md
The linker dumps unzipped files when dependencies are generated. This request ensures that users of the analyzer can dump dependencies and then immediately use the analyzer without having to unzip their files first. I also updated the README to reflect the changes.
> Synchronize file type between analyzer and linker

- test/ILLink.RoslynAnalyzer.Tests/generated/ILLink.RoslynAnalyzer.Tests.Generator/ILLink.RoslynAnalyzer.Tests.TestCaseGenerator/DataFlowTests.g.cs
- test/Mono.Linker.Tests.Cases/DataFlow/CompilerGeneratedCodeInPreservedAssembly.cs
- test/Mono.Linker.Tests.Cases/DataFlow/CompilerGeneratedCodeInPreservedAssembly.xml
See the test for description of what it does. It's basically the linker repro for the case hit in https://github.com/dotnet/runtime/issues/73027#issuecomment-1199199943
> Add an interesting test case for compiler generated code marking

- src/ILLink.Shared/TrimAnalysis/HandleCallAction.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MakeGenericDataFlow.cs
For correctness linker must be able to validate that generic parameters with new constraint will have their default .ctor preserved. If that can't be guaranteed, it needs to warn.
Added tests for cases around this.
`Nullable<>` is the only exception to this rule, so changed the code to completely skip any validation for it.
Fixes https://github.com/dotnet/linker/issues/2934
/cc @jkurdek
> New constraint on a generic argument involved in MakeGenericType/Method should warn

- test/Mono.Linker.Tests.Cases/DataFlow/ByRefDataflow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodByRefParameterDataFlow.cs
Test for https://github.com/dotnet/linker/issues/2874.
> Adds a test with two annotated out params for the same method.

- docs/data-formats.md
- test/Mono.Linker.Tests.Cases/LinkXml/CanPreserveNamespace.cs
- test/Mono.Linker.Tests.Cases/LinkXml/CanPreserveNamespace.xml
- test/Mono.Linker.Tests.Cases/LinkXml/CanPreserveTypesUsingRegex.cs
* Add a test for the `<namespace>` element.  There were no tests.
* Expand `CanPreserveTypesUsingRegex` to help highlight how it behaves differently from `<namespace>`
* Add more examples to the docs
> Improve tests and docs

- src/analyzer/LinkerAnalyzerCore/DependencyGraph.cs
The existing code used exceptions as a way to determine if item is part of a dictionary. That is pretty expensive and slows down loading of the dependencies quite a bit (we do it A LOT).
Rewrite the code to avoid exceptions in this case.
> [analyzer tool] Avoid exceptions when loading dependencies

- eng/Versions.props
- test/ILLink.RoslynAnalyzer.Tests/generated/ILLink.RoslynAnalyzer.Tests.Generator/ILLink.RoslynAnalyzer.Tests.TestCaseGenerator/BasicTests.g.cs
- test/Mono.Linker.Tests.Cases/Basic/LinkerHandlesRefFields.cs
- test/Mono.Linker.Tests.Cases/Basic/UnusedFieldsOfStructsAreKept.cs
Adds some tests with basic usage of ref fields to ensure the linker doesn't crash or produce incorrect warnings. Ref structs can't be used as type parameters, so some things like IEnumerable<RS> can't be tested.
Please let me know if I'm missing other cases where this could cause some issues.
> Test that basic ref field operations don't crash linker

- src/linker/Linker/MessageOrigin.cs
If we produce a warning for the method itself (no IL offset) and the method has debug symbols, it can happen that there's no sequence point for the first instruction. In that case the current code will crash because we expect to always find sequence point for offset 0.
Fix this by looking for the first sequence point instead.
Fixes https://github.com/dotnet/linker/issues/2971
> Fix exception when generating warning for method definition

- test/Mono.Linker.Tests.Cases/DataFlow/MakeGenericDataFlow.cs
Part of https://github.com/dotnet/linker/issues/2058
> Add MakeGenericMethod tests for static interface methods

- src/ILLink.RoslynAnalyzer/RequiresISymbolExtensions.cs
- test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresOnClass.cs
Suppress warning in instance fields if the instance constructors are annotated with Requires
Fixes https://github.com/dotnet/linker/issues/2970
Related to https://github.com/dotnet/runtime/pull/73853
> Suppress warning in instance fields 

- src/linker/Linker.Steps/MarkStep.cs
We can use a HashSet instead of a List for _virtual_methods to avoid having duplicates that cause a slowdown.
This change speeds up my repro of https://github.com/dotnet/linker/issues/2975 to speeds similar to the commit before the issue.
> Use HashSet instead of List for _virtual_methods

- src/linker/Linker.Steps/CheckSuppressionsDispatcher.cs
- src/linker/Linker.Steps/LinkAttributesParser.cs
- src/linker/Linker.Steps/MarkStep.cs
- src/linker/Linker/AttributeInfo.cs
- src/linker/Linker/CustomAttributeSource.cs
- src/linker/Linker/UnconditionalSuppressMessageAttributeState.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/DetectRedundantSuppressionsFromXML.cs
Fixes #2923. Redundant suppressions from XML will be reported in XML, not target.
\cc @vitek-karas
> IL2121 warnings point to XML files correctly

- src/ILLink.CodeFix/DAMCodeFixProvider.cs
Move attribute generation from RegistersCodeFixAsync() to AddAttributeAsync() for performance optimization
> Refactor attribute generation in DAM Code Fix

- src/linker/Linker.Steps/CheckSuppressionsDispatcher.cs
- src/linker/Linker/UnconditionalSuppressMessageAttributeState.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/DetectRedundantSuppressionsInMembersAndTypes.cs
- test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/DetectRedundantSuppressionsTrimmedMembersTarget.cs
The code allowed for reporting redundant suppressions on members which were removed by the linker.
This was possible e.g. when we had an assembly level suppression targeting a trimmed away member and had another warning triggered in the assembly. 
Added filter checking whether the suppression's provider is marked. Should fix #2990 
The change run into problems with suppressions on properties and events (they are not marked, only their accessors are). The PR introduces workaround for this.
> Do not report redundant suppressions on trimmed members

- test/Mono.Linker.Tests.Cases/DataFlow/Dependencies/TestSystemTypeBase.cs
Using TestSystemTypeBase generated annotations mismatch warnings which we did not check for. Added DAM annotations to eliminate this.
> Annotated TestSystemTypeBase

- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
- test/Mono.Linker.Tests.Cases/DataFlow/CompilerGeneratedCodeAccessedViaReflection.cs
The motivation of the change is to reduce the number of unnecessary warnings around PInvokes. The change makes the RequiresReflectionMethodBodyScannerForCallSite check for COM to decide whether dataflow analysis is needed for PInvokes.
> Verify if COM dangerous during call site check

- src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs
- test/ILLink.RoslynAnalyzer.Tests/DynamicallyAccessedMembersAnalyzerTests.cs
In the cref some of the symbols (for example the type argument) are missing containing symbols, which leads to null refs.
In any case, we should not perform any analysis on symbols inside crefs, only on real code.
So this modifies the analyzer to ignore any symbol inside a cref.
Adds a test to validate this.
Fixes https://github.com/dotnet/linker/issues/3014
> Fixes a null ref which happens when an XML comment cref contains generic instantiation

- src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs
- test/ILLink.RoslynAnalyzer.Tests/DynamicallyAccessedMembersAnalyzerTests.cs
In the cref some of the symbols (for example the type argument) are missing containing symbols, which leads to null refs.
In any case, we should not perform any analysis on symbols inside crefs, only on real code.
So this modifies the analyzer to ignore any symbol inside a cref.
Adds a test to validate this.
Backport of https://github.com/dotnet/linker/pull/3015 to 70
> [release/7.0] Fixes a null ref which happens when an XML comment cref contains generic instantiation

- eng/Versions.props
- eng/azure-pipelines.yml
- src/ILLink.CodeFix/RequiresAssemblyFilesCodeFixProvider.cs
- src/ILLink.CodeFix/RequiresDynamicCodeCodeFixProvider.cs
- src/ILLink.CodeFix/RequiresHelpers.cs
- src/ILLink.CodeFix/RequiresUnreferencedCodeCodeFixProvider.cs
- src/ILLink.RoslynAnalyzer/CompilationExtensions.cs
- src/ILLink.Tasks/CreateRuntimeRootDescriptorFile.cs
- src/analyzer/LinkerAnalyzerCore/DependencyGraph.cs
- src/linker/Linker.Dataflow/AttributeDataFlow.cs
- src/linker/Linker.Dataflow/FlowAnnotations.cs
- src/linker/Linker.Dataflow/MethodBodyScanner.cs
- src/linker/Linker.Steps/DiscoverCustomOperatorsHandler.cs
- src/linker/Linker.Steps/UnreachableBlocksOptimizer.cs
- src/linker/Linker/AssemblyResolver.cs
- src/linker/Linker/DgmlDependencyRecorder.cs
- src/linker/Linker/LinkerAttributesInformation.cs
- src/linker/Linker/ParameterHelpers.cs
- src/linker/Linker/SerializationMarker.cs
- src/linker/Linker/Tracer.cs
- src/linker/Linker/XmlDependencyRecorder.cs
- test/ILLink.RoslynAnalyzer.Tests/RequiresAssemblyFilesAnalyzerTests.cs
- test/ILLink.RoslynAnalyzer.Tests/UnconditionalSuppressMessageCodeFixTests.cs
- test/Mono.Linker.Tests.Cases/Attributes/GenericAttributes.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodParametersDataFlow.cs
- test/Mono.Linker.Tests/TestCases/TestDatabase.cs
Use new version of MicrosoftCodeAnalysisVersion in linker (Copy from runtime) to fix the dotnet format (lint.cmd|sh) command
Run the dotnet format command on the repo
> Fix lint command

- src/ILLink.Shared/SharedStrings.resx
- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/DynamicDependencies/DynamicDependencyMemberSignatureWildcard.cs
- test/Mono.Linker.Tests.Cases/DynamicDependencies/DynamicDependencyMethod.cs
Include both the member name being looked up, as well as the type the lookup is done on.
Fixes: https://github.com/dotnet/linker/issues/1601
> Better warning message for DynamicDependency problem

- test/Mono.Linker.Tests.Cases/LinkAttributes/LinkAttributeErrorCases.cs
- test/Mono.Linker.Tests.Cases/LinkAttributes/LinkAttributeErrorCases.xml
- test/Mono.Linker.Tests.Cases/LinkAttributes/LinkerAttributeRemoval.cs
We were lacking validation for some of the warnings, and so change in behavior of the product wasn't reflected in the tests. This cleans up tests for IL2053 and IL2054 (which are not produced anymore).
> Cleanup tests for cases which use different warnings codes that the test mentions

- src/linker/Linker.Steps/MarkStep.cs
I haven't been able to reproduce the issue, but I think this should be a fix for https://github.com/dotnet/runtime/issues/76167 (I can't think of anywhere else there would be a null ref in that method). I would guess that it would also be throwing in other places before the interfaces are handled though, so I'm going to continue trying to repro.
> Check for nulls in IsInterfaceImplementationNeededByTypeDueToInterface

- src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisMethodCallPattern.cs
- src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisVisitor.cs
- src/ILLink.Shared/TrimAnalysis/HandleCallAction.cs
- src/ILLink.Shared/TrimAnalysis/IntrinsicId.cs
- src/ILLink.Shared/TrimAnalysis/Intrinsics.cs
- src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
In ReflectionMethodBodyScanner and HandleCallAction, we do many of the same checks that already occur in `GetIntrinsicIdFromMethod`, and in a few places we have 'when' conditions that could just be regular cases. This removes the extra checks so the switch can be simpler and more optimized.
In the linker, we also get the IntrinsicId twice, so this adds an optional parameter for a known IntrinsicId.
> Remove redundant checks in IntrinsicId switch statements

- src/linker/BannedSymbols.txt
- src/linker/Linker.Steps/CodeRewriterStep.cs
- src/linker/Linker.Steps/MarkExportedTypesTargetStep.cs
- src/linker/Linker.Steps/ProcessLinkerXmlBase.cs
- src/linker/Linker.Steps/SweepStep.cs
- src/linker/Linker/LinkContext.cs
- src/linker/Linker/MarkingHelpers.cs
- src/linker/Linker/MethodReferenceExtensions.cs
- src/linker/Linker/ModuleDefinitionExtensions.cs
- src/linker/Linker/TypeReferenceExtensions.cs
When profiling ASP.Net benchmark builds, I found significant time was being spent resolving `ExportedType`
's since we don't have a cache for those like we do for TypeReference and MethodReference.
Bans MethodReference.Resolve and ExportedType.Resolve and recommend LinkContext.Resolve instead (except in SweepStep).
Adds a cache on LinkContext for resolving ExportedTypes and replaces calls to Cecil's Resolve.
Replaces some calls to MethodReference.Resolve.
Together with https://github.com/dotnet/linker/pull/3073, performance improves to better than before the virtual method regression in August.
Trimmer CPU milliseconds on ASP.Net benchmarks build:
27325 before the regression related to https://github.com/dotnet/linker/issues/3067
87310 in main
23520 after …
> Use LinkContext caching when resolving ExportedTypes

- eng/Analyzers.props
- eng/Versions.props
- eng/ilasm.ilproj
- src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
- test/ILLink.RoslynAnalyzer.Tests/RequiresAssemblyFilesAnalyzerTests.cs
- test/ILLink.RoslynAnalyzer.Tests/RequiresDynamicCodeAnalyzerTests.cs
- test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs
- test/ILLink.RoslynAnalyzer.Tests/UnconditionalSuppressMessageCodeFixTests.cs
- test/Mono.Linker.Tests/TestCasesRunner/AssemblyChecker.cs
Took the versions from dotnet/runtime.
> Change analyzer versions such that the repo can be built with .NET 7 RC2 SDK

- eng/Versions.props
- global.json
- test/Mono.Linker.Tests/Mono.Linker.Tests.csproj
There are official build warnings because some references are too old. This is an attempt to bring them all up to date.
> Upgrade transitive references to avoid warnings

- eng/Versions.props
- global.json
- src/ILLink.Tasks/ILLink.Tasks.csproj
- test/ILLink.Tasks.Tests/ILLink.Tasks.Tests.csproj
The official build has an old version of MSBuild so we can't use a new version of MSBuild. However, we do need a higher version of MSBuild as our ref for the tasks, so this also upgrades the version of MSBuild.
The two changes are technically separate, even though they both involve MSBuild.
> Upgrade MSBuild ref and downgrade global.json

- src/ILLink.RoslynAnalyzer/ILLink.RoslynAnalyzer.csproj
The hardcoded Microsoft.CodeAnalysis.CSharp version reference in ILLink.RoslynAnalyzer.csproj causes a prebuilt for source-build.  We should be referencing the versions.props property to keep the reference to the latest version for source-build.
> Update ILLink.RoslynAnalyzer.csproj Microsoft.CodeAnalysis.CSharp version

- eng/Versions.props
- eng/ilasm.ilproj
- test/ILLink.RoslynAnalyzer.Tests/ILLink.RoslynAnalyzer.Tests.csproj
The analyzer testing infrastructure uses an old version of NuGet.Protocol, which is generating warnings. This upgrades to a newer version.
> Get rid of warnings about old version of NuGet.Protocol

- src/linker/Linker.Steps/MarkStep.cs
- test/ILLink.RoslynAnalyzer.Tests/generated/ILLink.RoslynAnalyzer.Tests.Generator/ILLink.RoslynAnalyzer.Tests.TestCaseGenerator/Inheritance.VirtualMethodsTests.g.cs
- test/Mono.Linker.Tests.Cases/Inheritance.VirtualMethods/OverrideOfAbstractInUnmarkedClassIsRemoved.cs
Adds a check to ensure the declaring type is marked in `ShouldMarkOverrideForBase`.
Adds a test to check for this behavior.
Should fix the issues in linker flow to sdk at https://github.com/dotnet/sdk/pull/28796.
Before the change, in OverrideInUnmarkedClassIsRemoved we would mark `UnmarkedDerived.Method` and `UnmarkedDerived` because `MarkedBase.Method` was marked and `abstract`.
> Don't mark override of abstract base if the override's declaring type is not marked

- eng/Versions.props
Looks like the new builds weren't quite new enough. I tracked down the MSBuild reference and it looks like it's a transitive dependency on netstandard2.0 that's the problem. 17.2.2 should remove that dependency and still be supported for all net6.0 platforms.
> Increase build versions again

- .config/tsaoptions.json
- eng/azure-pipelines.yml
CodeQL is a static analysis tool that is able to scan source code to help detect security vulnerabilities. In dotnet/linker, there already exists auto-injection of CodeQL's init and finalize tasks within the official default pipeline.
This PR does the following:
Enables CodeQL
Enable TSA with CodeQL
> Enable CodeQL with TSA

- src/ILLink.RoslynAnalyzer/TrimAnalysis/ParameterProxy.cs
- test/Mono.Linker.Tests.Cases/DataFlow/MethodByRefParameterDataFlow.cs
Expecting IMethodSymbol.ContainingSymbol to be an ITypeSymbol is causing a type cast exception for local methods that require dataflow analysis (https://github.com/dotnet/linker/issues/3106), and it makes more sense to use ContainingType. I haven't been able to repro the issue (I've had problems building asp.net), but it seems pretty clear this is the fix.
> Use ContainingType instead of ContainingSymbol in GetReferenceKind

- test/ILLink.RoslynAnalyzer.Tests/generated/ILLink.RoslynAnalyzer.Tests.Generator/ILLink.RoslynAnalyzer.Tests.TestCaseGenerator/DataFlowTests.g.cs
- test/ILLink.RoslynAnalyzer.Tests/generated/ILLink.RoslynAnalyzer.Tests.Generator/ILLink.RoslynAnalyzer.Tests.TestCaseGenerator/Inheritance.VirtualMethodsTests.g.cs
- test/Mono.Linker.Tests.Cases/DataFlow/Dependencies/TypeInfoCalls.il
- test/Mono.Linker.Tests.Cases/DataFlow/TypeInfoIntrinsics.cs
This is a port of the tests from https://github.com/dotnet/linker/pull/3109 (the fix is not needed since the code now works differently and doesn't have the problem)
> Tests for TypeInfo intrinsics

- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/BaseProvidesInterfaceEdgeCase/BaseProvidesInterfaceMethodCircularReference.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/BaseProvidesInterfaceEdgeCase/Dependencies/Base.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/BaseProvidesInterfaceEdgeCase/Dependencies/Derived1.cs
- test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/BaseProvidesInterfaceEdgeCase/Dependencies/IFoo.cs
Adds a minimal repro for #3112.
The scenario looks like this:
Types;
Base type B has method M.
Derived type D1 derives from B, and implements interface I1 with methods from B.
Derived type D2 derives from B, and implements interface I2 with methods from B.
Assembly A1 has B.
Assembly A2 has D1.
Assembly A3 has I1 and D2.
I2 can be in any assembly.
In the trimmer:
D1 is marked instantiated.
-> B is marked instantiated (as a base type)
-> D1's interfaces are marked, and the implementation methods are marked
-> B.M() is marked
-> I.M() is added as a base method for B.M()
Later, B.M() is passed to IsMethodNeededByInstantiatedTypeDueToPreservedScope()
-> Base methods of B.M() are iterated over
-> I.M() is one of the base methods, and is passed to IsMethodNeedeByTypeDueToPreservedScope()
-> …
> Add test case for #3112 with pseudo-circular reference when base provides iface method

- src/linker/Linker/TypeReferenceExtensions.cs
- test/Mono.Linker.Tests/TestCasesRunner/AssemblyChecker.cs
If there's a TypeReference which is not a definition (for example it's a by-ref, or a pointer, ...) and it's also a nested type, the current code would not include the owning type in the type name. For type defs we always include the owning type name.
This change fixes that.
Also a small tweak in the test infra to avoid adding the same values into a hashset every time we visit a type.
> Improves GetDisplayName for types

- global.json
This essentially reverts https://github.com/dotnet/linker/pull/2945, the default msbuild version is now recent enough and specifying an old version actually causes issues now.
> Remove explicit xcopy-msbuild version from global.json

- global.json
Backport of https://github.com/dotnet/linker/pull/3136
> [release/7.0] Remove explicit xcopy-msbuild version from global.json

- src/linker/Linker.Steps/MarkStep.cs
Fixes https://github.com/dotnet/linker/issues/3137
We unconditionally add a method to the MarkStep._methods queue and perform a filtering check in ProcessMethod later. This causes _methods to grow to be as large as 110 mb in some cases (see https://github.com/dotnet/linker/issues/3126#issuecomment-1329508820). If we instead perform the filtering check before enqueuing the method, MarkStep_methods reach a max size of ~14mb (in the same repro).
> Call CheckProcessed before enqueuing to MarkStep._methods

- test/ILLink.RoslynAnalyzer.Tests/generated/ILLink.RoslynAnalyzer.Tests.Generator/ILLink.RoslynAnalyzer.Tests.TestCaseGenerator/DataFlowTests.g.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterDataFlow.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterWarningLocation.cs
Adds a test which focused on warnings produced due to annotated generic parameters. This is relatively tricky for the product to deal with since it's often part of the type system and not code. So this test focused on all the different situations such warning can occur and the location where the warning is generated.
> Generic warning location tests

- src/linker/Linker.Dataflow/CompilerGeneratedState.cs
- test/Mono.Linker.Tests/Tests/PerfTestGeneratorForCompilerGeneratedCode.cs
The way this code was supposed to work was that it would scan the compiler- generated type and all its descendents, record each generated type it found, then fill in information for all of the found types. The way it actually worked was that it would scan the descendents, record each generated type, then try to fill in information *for all generated types found in the program*. This is quadratic as you start adding types, as you rescan everything you've added before. The fix is to record just the types from the current pass, and then add them to the larger bag when everything's complete.
> Fix quadratic algorithm in CompilerGeneratedState

- test/ILLink.RoslynAnalyzer.Tests/DataFlowTests.cs
- test/Mono.Linker.Tests.Cases/DataFlow/ConstructedTypesDataFlow.cs
This was prompted by https://github.com/dotnet/linker/issues/3158
So I just added several tests for various shapes of type deconstructions. To make it symmetric I also added tests for what I call type construction (tuples, anonymous types, records).
The naming is probably pretty bad and thus the test is undiscoverable. If somebody knows the right terminology or has a better idea for naming, please :-)
> Add tests for type deconstruction and construction

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/DataFlow/AnnotatedMembersAccessedViaReflection.cs
LdToken acts basically as a reflection access and so it needs to warn about the returned member if that has annotations on it.
This adds tests for https://github.com/dotnet/linker/issues/3172 which is not fixed by this change.
> Add tests for ldtoken analysis and fixes a small bug for a field

- src/ILLink.Tasks/CreateRuntimeRootDescriptorFile.cs
- src/linker/Linker/LinkerAttributesInformation.cs
First encountered in https://github.com/dotnet/runtime/pull/80235, so copying the change to dotnet/linker
> Fix new warning which shows up with latest roslyn

- eng/Analyzers.props
- eng/Versions.props
This removes the version number added in https://github.com/dotnet/linker/pull/3077, which is no longer necessary to build with the released .NET 7 bits and was causing problems in https://github.com/dotnet/installer/pull/15228#issuecomment-1379601205 (it was hitting the check added in https://github.com/dotnet/roslyn-analyzers/commit/187b69eb2ad2097cb065a0565b90b556a206c2b6).
> Unpin Microsoft.CodeAnalysis.NetAnalyzers version

- src/ILLink.Tasks/ILLink.Tasks.csproj
This is an attempt to fix a race condition in our build, where Mono.Cecil was being built twice into the same output path. See https://github.com/dotnet/installer/pull/15228#issuecomment-1381987801 for context.
Before this change, I saw this line twice in the output:
```
Mono.Cecil -> C:\Users\svbomer\src\linker\artifacts\bin\Mono.Cecil\Debug\netstandard2.0\Mono.Cecil.dll
```
After this change, I only see it once. I don't understand why `SetTargetFramework` was needed in the first place in https://github.com/dotnet/linker/pull/1891#discussion_r593494437, but it no longer seems necessary. Probably the recent changes to the cecil build (arcade onboarding) caused this to become a problem.
I have been able to build locally >100 times in a row with this change, without hitting the race, so I …
> Fix race condition in build

- src/linker/Linker.Steps/MarkStep.cs
- test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterWarningLocation.cs
The warning needs to be generated from the origin where the field reference comes from - so if it's a method body, then from the method body. This is because the instantiation is determined by that place, not the field itself (the field is defined on an open generic definition of the type).
This syncs the relevants tests with a NativeAOT work-in-progress change, but in generately it adds a lot more cases and some better comments.
> Fix a small bug in message origin for warnings from static field access on generic type

- eng/Versions.props
The version of `Microsoft.Build.Framework` that we depend on has a transitive dependency on `System.Drawing.Common` that is being flagged due to a security vulnerablility in https://github.com/dotnet/sdk/issues/29927. The dependency is probably unused, but we would like to fix it to prevent further false positive reports.
This is being referenced as a transitive dependency of `Microsoft.Build.Framework`: Microsoft.Build.Framework/17.0.0-preview-21267-01 -> System.Security.Permissions/4.7.0 -> System.Windows.Extensions/4.7.0 -> System.Drawing.Common/4.7.0. 
`dotnet/sdk` uses a lower version (15.4.8) of `Microsoft.Build.Framework`, which doesn't have a dependency on System.Drawing.Common. `dotnet/linker` used to reference the same version but we bumped it in …
> Match SDK versions of MSBuild framework

- eng/Versions.props
Backport of https://github.com/dotnet/linker/pull/3187. Fixes component governance warnings described in https://github.com/dotnet/sdk/issues/29927.
> [release/7.0] Bump MSBuild framework versions
