dotnet/linker

netci.groovy

The argument to setRecursiveSubmoduleOption should be newJob.

Fix submodule option on build jobs

---

linker/Mono.Linker.Steps/MarkStep.cs

This change adds marking of fields for types of parameters of pinvokeimpl and interop methods.
Before this change this was done only for byref types. Also, the code in MarkType marks fields of
types with sequential or explicit layout; however, sometimes auto-layout is used for types of parameters of
internal or pinvokeimpl calls (e.g., when there is just one field).

Fixes for processing interop parameters.

---

linker/Mono.Linker/Annotations.cs

If duplicate preservations, keep the one that results in preserving the most

Preservation fix

---

linker/Mono.Linker/LinkContext.cs

We need to customize the behavior of this method for our WinRT support

Allow overriding SafeReadSymbols

---

linker/Mono.Linker.Steps/SweepStep.cs
linker/Mono.Linker/Driver.cs
linker/Mono.Linker/LinkContext.cs

Expose some methods that the unity linker needs to call or override

Expose some methods

---

linker/Mono.Linker.Steps/LoadReferencesStep.cs
linker/Mono.Linker.Steps/ResolveFromXmlStep.cs
linker/Mono.Linker/LinkContext.cs

So that collection of dependencies can be customized by other linkers

Introduce DependenciesFor

---

linker/Mono.Linker.Steps/MarkStep.cs
linker/Mono.Linker.csproj
linker/Mono.Linker/MarkException.cs

Include the name of the method in the exception that is thrown when there is an exception marking a method

Improve error message

---

linker/Mono.Linker.Steps/LoadReferencesStep.cs
linker/Mono.Linker.csproj
linker/Mono.Linker/LoadException.cs

is thrown while loading references

Improve exception message when exception

---

linker/Mono.Linker.Steps/MarkStep.cs

1. Mark static fields in Keywords, Tasks, and Opcodes classes nested inside EventSource-derived classes.
Details on the pattern relying on this are described here: https://msdn.microsoft.com/en-us/library/dn774985(v=pandp.20).aspx
2. Mark public instance properties inside types with EventDataAttribute.
Details are here: https://msdn.microsoft.com/en-us/library/dn823294(v=vs.110).aspx

Mark members of Event-related types.

---

linker/Mono.Linker.Steps/MarkStep.cs

This change adds the following to handling of DebuggerDisplayAttribute and DebuggerTypeProxyAttribute:
1. The type proxy can be specified either as System.Type or as a string. This change handles the latter.
2. Both DebuggerDisplayAttribute and DebuggerTypeProxyAttribute can be specified at assembly level. In that case the attributes have either Target property (of type System.Type) or TargetTypeName property (of string type). This change handles these cases and marks the type proxies appropriately when the corresponding targets are marked.

Make handling of debugger attributes more complete.

---

linker/Mono.Linker.Steps/MarkStep.cs

The MarkStep doesn't handle function pointer types correctly.
For example, the linker crashes while marking the method Fnxn.
.method int32 Fnxn(method explicit instance int32 *(int32), int32)
{
...
}
This change fixes the bug in MarkStep.

Fix marking of FunctionPointer Types

---

linker/Mono.Linker.Steps/SweepStep.cs

For our WinRT support there are types that we don't want to change the scope on.  This PR gives us the extension point we need to skip scope changing on certain types

Scope change extension point

---

linker/Tests/Mono.Linker.Tests.Cases/Generics/DerivedClassWithMethodOfSameNameAsBaseButDifferentNumberOfGenericParametersUnusedBaseWillGetStripped.cs
linker/Tests/Mono.Linker.Tests.Cases/Generics/MethodWithParameterWhichHasGenericParametersAndOverrideUsesADifferentNameForGenericParameterNestedCase.cs
linker/Tests/Mono.Linker.Tests.Cases/Generics/MethodWithParameterWhichHasGenericParametersAndOverrideUsesADifferentNameForGenericParameterNestedCase2.cs
linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj

A couple of these tests do depend on my open bug fix PR's landing in order to pass.  If you are trying to keep the tests green on the `test-framework` branch, then don't merge this PR yet.

Bring over some newly added test cases

---

linker/Tests/Mono.Linker.Tests.Core/Mono.Linker.Tests.Core.csproj
linker/Tests/TestsCases/TestDatabase.cs
linker/Tests/TestsCases/TestSuites.cs

Breakup AllTests into multiple Tests
Fix NUnit reference path

Test framework suite cleanup

---

linker/Tests/Mono.Linker.Tests.Cases/Interop/InternalCalls/Com/DefaultConstructorOfParameterIsRemoved.cs
linker/Tests/Mono.Linker.Tests.Cases/Interop/InternalCalls/Com/DefaultConstructorOfReturnTypeIsRemoved.cs
linker/Tests/Mono.Linker.Tests.Cases/Interop/InternalCalls/Com/FieldsOfParameterAreRemoved.cs
linker/Tests/Mono.Linker.Tests.Cases/Interop/InternalCalls/Com/FieldsOfReturnTypeAreRemoved.cs
linker/Tests/Mono.Linker.Tests.Cases/Interop/InternalCalls/Com/FieldsOfThisAreRemoved.cs
linker/Tests/Mono.Linker.Tests.Cases/Interop/PInvoke/Com/DefaultConstructorOfParameterIsRemoved.cs
linker/Tests/Mono.Linker.Tests.Cases/Interop/PInvoke/Com/DefaultConstructorOfReturnTypeIsRemoved.cs
linker/Tests/Mono.Linker.Tests.Cases/Interop/PInvoke/Com/FieldsOfParameterAreRemoved.cs
linker/Tests/Mono.Linker.Tests.Cases/Interop/PInvoke/Com/FieldsOfReturnTypeAreRemoved.cs
linker/Tests/Mono.Linker.Tests.Cases/Interop/PInvoke/Com/FieldsOfThisAreRemoved.cs
linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj

This PR adds tests covering the recent ComImport changes.
https://github.com/mono/linker/commit/f688937f3cb3901c17acd689d94f377180c0646c
https://github.com/mono/linker/commit/401978f93efd948f972f52c9bb3e6ec468cdce8a

Add tests for ComImport cases

---

linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/IgnoreTestCaseAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptAssemblyAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptAttributeAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptBaseTypeAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptInterfaceAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptMemberAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptMemberInAssemblyAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptTypeInAssemblyAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/RemovedAssemblyAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/RemovedMemberInAssemblyAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/RemovedTypeInAssemblyAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/CoreLinkAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/ReferenceAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SandboxDependencyAttribute.cs

Remove fields from attributes in expectations assembly

---

linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptInterfaceAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptMemberAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/NotATestCaseAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases/Basic/UsedStructIsKept.cs
linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
linker/Tests/Mono.Linker.Tests.Cases/VirtualMethods/StructUsedFromInterfaceHasInterfaceMethodKept.cs
linker/Tests/TestCasesRunner/AssemblyChecker.cs

Support the Expectation attributes that are valid to place on structs

Better struct support in test framework

---

linker/Mono.Linker/LinkContext.cs

This is the alternative to https://github.com/mono/linker/pull/103

Make GetAssemblies virtual

---

linker/Mono.Linker.Steps/MarkStep.cs
linker/Mono.Linker.Steps/ResolveFromXmlStep.cs
linker/Mono.Linker/Annotations.cs

* Break recursive chains in the xml report
* Override ToString in ResolveFromXmlStep
* Improve annotations tracking in some places

annotations changes

---

linker/Tests/Extensions/NiceIO.cs

Sync up with NiceIO  at https://github.com/lucasmeijer/NiceIO/commit/30c78865094183c4aebe9f2094faa4f4497a1fcd

Sync up with NiceIO 

---

tuner/Mono.Tuner/RemoveResources.cs

- Refactor skip logic into function for readability

Strip mscorlib.xml from mscorlib.dll when linking

---

.gitignore
corebuild/integration/ILLink.CustomSteps/ClearInitLocals.cs
corebuild/integration/ILLink.CustomSteps/ILLink.CustomSteps.csproj
corebuild/integration/ILLink.Tasks/ILLink.Tasks.csproj
corebuild/integration/test/NuGet.config
corebuild/integration/test/TestContext.cs
corebuild/linker.sln
linker/Mono.Linker.csproj

Add the first ILLInk custom step to clear InitLocals on all methods.
Clean up corebuild to make sure all output is placed in bin or tools
subdirectories.

Add ILLink.CustomsSteps.dll.

---

linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SandboxDependencyAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupCompileResourceAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
linker/Tests/Mono.Linker.Tests.Cases/Resources/Dependencies/EmbeddedLinkXmlFileIsNotProcessedIfNameDoesNotMatchAnAssembly.xml
linker/Tests/Mono.Linker.Tests.Cases/Resources/Dependencies/EmbeddedLinkXmlFileIsNotProcessedWhenBlacklistStepIsDisabled.xml
linker/Tests/Mono.Linker.Tests.Cases/Resources/Dependencies/EmbeddedLinkXmlFileIsNotProcessedWhenCoreLinkActionIsSkip.xml
linker/Tests/Mono.Linker.Tests.Cases/Resources/Dependencies/EmbeddedLinkXmlFileIsProcessed.xml
linker/Tests/Mono.Linker.Tests.Cases/Resources/Dependencies/NonLinkerEmbeddedResourceHasNoImpact.xml
linker/Tests/Mono.Linker.Tests.Cases/Resources/EmbeddedLinkXmlFileIsNotProcessedIfNameDoesNotMatchAnAssembly.cs
linker/Tests/Mono.Linker.Tests.Cases/Resources/EmbeddedLinkXmlFileIsNotProcessedWhenBlacklistStepIsDisabled.cs
linker/Tests/Mono.Linker.Tests.Cases/Resources/EmbeddedLinkXmlFileIsNotProcessedWhenCoreLinkActionIsSkip.cs
linker/Tests/Mono.Linker.Tests.Cases/Resources/EmbeddedLinkXmlFileIsProcessed.cs
linker/Tests/Mono.Linker.Tests.Cases/Resources/NonLinkerEmbeddedResourceHasNoImpact.cs
linker/Tests/Mono.Linker.Tests.csproj
linker/Tests/TestCases/TestDatabase.cs
linker/Tests/TestCases/TestSuites.cs
linker/Tests/TestCasesRunner/CompilerOptions.cs
linker/Tests/TestCasesRunner/SourceAndRelativeDestinationPair.cs
linker/Tests/TestCasesRunner/TestCaseCompiler.cs
linker/Tests/TestCasesRunner/TestCaseMetadaProvider.cs
linker/Tests/TestCasesRunner/TestCaseSandbox.cs
linker/Tests/TestCasesRunner/TestRunner.cs

This is the first in what will be a series of PR's improving the linker resource handling and tests.
This PR contains
* Testing enhancements to support resources 
* Tests verifying the behavior of the black list step.

Implement tests for processing of embedded link xml resources

---

corebuild/integration/test/WebApiTest.cs

Increase webapi test timeout

---

linker/Mono.Linker.Steps/ResolveFromXmlStep.cs

This gives us better dependency information for the parts preserved by
XML linker descriptions in the ResolveFromXmlStep

Collect more information for the linker-analyzer

---

corebuild/integration/test/MusicStoreReflection.xml

Add several roots from System.Private.Corelib.
Remove "required" = true since it's the default.

Update MusicStore roots.

---

linker/Linker/Annotations.cs

So that it can be used in the linker analyzer as a key to the type
sizes dictionary in the space analyzer.
The `IsAssemblyBound` method checks whether a type is visible outside
of an assembly. We need it for classes like
`<PrivateImplementationDetails>/__StaticArrayInitTypeSize=120`.
In this case the class hierarchy looks like this:
```
.class private auto ansi sealed '<PrivateImplementationDetails>'
extends System.Object
{
.class explicit ansi sealed nested private '__StaticArrayInitTypeSize=120'
extends System.ValueType
{
...
}
}
```

Add assembly name to the private types when dumping dependencies

---

linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupLinkerArgumentAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
linker/Tests/Mono.Linker.Tests.Cases/References/Individual/CanSkipUnresolved.cs
linker/Tests/Mono.Linker.Tests.Cases/References/Individual/Dependencies/CanSkipUnresolved_Library.cs
linker/Tests/Mono.Linker.Tests.csproj
linker/Tests/TestCases/IndividualTests.cs
linker/Tests/TestCases/TestDatabase.cs
linker/Tests/TestCasesRunner/LinkerArgumentBuilder.cs
linker/Tests/TestCasesRunner/TestCaseCollector.cs
linker/Tests/TestCasesRunner/TestCaseLinkerOptions.cs
linker/Tests/TestCasesRunner/TestCaseMetadaProvider.cs

Plus add a test for --skip-unresolved which utilizes this new attribute

Add attribute to allow arbitrary linker option definition in tests

---

linker/Linker/Driver.cs

It specifies the path for the dependencies dump file
Also removed reflection usage, when starting the dump

Add `--dependencies-file` cmd line option

---

corebuild/integration/test/MusicStoreTest.cs

This revision points to the updated aspnet dev feed.

Update JitBench git revision for MusicStore testing.

---

linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupCompileArgumentAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
linker/Tests/Mono.Linker.Tests.Cases/TestFramework/CanCompileTestCaseWithDebugPdbs.cs
linker/Tests/TestCasesRunner/CompilerOptions.cs
linker/Tests/TestCasesRunner/TestCaseCompiler.cs
linker/Tests/TestCasesRunner/TestCaseMetadaProvider.cs
linker/Tests/TestCasesRunner/TestRunner.cs

Also includes a test to verify we can build an assembly with debug info

Add support for setting up arbitrary compiler options.

---

linker/Linker.Steps/MarkStep.cs
linker/Tests/Mono.Linker.Tests.Cases/LinkXml/PreserveBackingFieldWhenPropertyIsKept.cs
linker/Tests/Mono.Linker.Tests.Cases/LinkXml/PreserveBackingFieldWhenPropertyIsKept.xml
linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj

Add missing checks for property variants when looking for property backing field

---

Contributing.md

Fixed invalid hyperlinks in `Contributing.md`

Fix hyperlinks in Contributing.md

---

linker/Linker.Steps/OutputStep.cs

We have our own UnityOutputStep that was not unified with OutputStep.  Ours is mostly a copy of OutputStep, plus some WinRT logic, plus some different symbol handling where we tried to fix symbol issues.
This PR does the following
* Refactors and exposes the hooks we need to maintain our winrt logic
* Cleans up an inconsistency with how SaveAssembly and CopyAssembly check if symbols should be included
* Moves the CloseSymbol() call from the default clause of the switch into a finally.   It's best to make sure you always close the symbols.  If a test were to hit an exception and CloseSymbol not be called, all subsequent tests would fail.  I didn't want to remove the `CloseSymbol` call in the Copy and Delete cases.     In some cases I think it's important that the symbols be closed prior to …

OutputStep refactoring to make it more extensible and consistent

---

corebuild/integration/ILLink.CustomSteps/ILLink.CustomSteps.csproj
corebuild/integration/ILLink.Tasks/ILLink.Tasks.csproj
corebuild/linker.sln
linker.sln
linker/Mono.Linker.csproj
linker/Tests/Mono.Linker.Tests.Cases/Symbols/AssemlbyWithDefaultSymbolsAndSymbolLinkingEnabled.cs
linker/Tests/Mono.Linker.Tests.Cases/Symbols/ReferenceWithMdbAndSymbolLinkingEnabled.cs
linker/Tests/Mono.Linker.Tests.Cases/Symbols/ReferenceWithMdbCopyActionAndSymbolLinkingEnabled.cs
linker/Tests/Mono.Linker.Tests.Cases/Symbols/ReferencesWithMixedSymbolTypesAndSymbolLinkingEnabled.cs
linker/Tests/Mono.Linker.Tests.csproj
monobuild/Makefile

All that was needed was to reference Mono.Cecil.Mdb so that the assembly would be built

Fix mdb symbol handling.

---

corebuild/integration/ILLink.Tasks/ComputeReadyToRunAssemblies.cs
corebuild/integration/ILLink.Tasks/Utils.cs
linker/Linker.Steps/OutputStep.cs
linker/Linker/AssemblyUtilities.cs
linker/Mono.Linker.csproj

- Use cecil's ILLibrary attribute (https://github.com/jbevain/cecil/pull/475)
- Factor common logic into a new function
@erozenfeld PTAL

Clean up ready-to-run detection

---

corebuild/integration/ILLink.Tasks/CreateRuntimeRootDescriptorFile.cs

1. Include the contents of coreclr\src\mscorlib\ILLinkTrim.xml
(that will be added shortly to coreclr) into the descriptor computed
by CreateRuntimeRootDescriptorFile.
2. Preserve constructors in exceptions declared in rexcep.h.

Updates for CreateRuntimeRootDescriptorFile msbuild task.

---

README.md
corebuild/README.md
corebuild/integration/ILLink.Tasks/LinkTask.cs
linker/README.md

@erozenfeld, @richlander PTAL.

Add documentation for ILLink.Tasks

---

corebuild/integration/ILLink.Tasks/ILLink.CrossGen.targets
corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets

- Turn off crossgen by default when linking is off
- Fix native trimming option
@erozenfeld PTAL

Option fixes

---

linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
linker/Tests/Mono.Linker.Tests.Cases/Resources/Dependencies/EmbeddedLinkXmlFileInReferencedAssemblyIsNotProcessedIfActionIsCopy_Lib1.cs
linker/Tests/Mono.Linker.Tests.Cases/Resources/Dependencies/EmbeddedLinkXmlFileInReferencedAssemblyIsNotProcessedIfActionIsCopy_Lib1.xml
linker/Tests/Mono.Linker.Tests.Cases/Resources/Dependencies/EmbeddedLinkXmlFileInReferencedAssemblyIsProcessedIfActionIsLink_Lib1.cs
linker/Tests/Mono.Linker.Tests.Cases/Resources/Dependencies/EmbeddedLinkXmlFileInReferencedAssemblyIsProcessedIfActionIsLink_Lib1.xml
linker/Tests/Mono.Linker.Tests.Cases/Resources/EmbeddedLinkXmlFileInReferencedAssemblyIsNotProcessedIfActionIsCopy.cs
linker/Tests/Mono.Linker.Tests.Cases/Resources/EmbeddedLinkXmlFileInReferencedAssemblyIsNotProcessedIfNameDoesNotMatchAnAssembly.cs
linker/Tests/Mono.Linker.Tests.Cases/Resources/EmbeddedLinkXmlFileInReferencedAssemblyIsProcessedIfActionIsLink.cs

This is a follow-up to https://github.com/mono/linker/pull/275.

Add tests for resources embedded in referenced assemblies.

---

linker/Tests/TestCasesRunner/TestRunner.cs

This is an alternative to
https://github.com/mono/linker/pull/290
So that we can put the behavior in that PR in our test runner

Make TestRunner.Run virtual so that we can customize it a bit

---

linker/Linker.Steps/MarkStep.cs

We would like finer grain control over when to mark custom attributes.  Including the provider with the should mark calls will give us the extra information we need

Include provider to ShouldMark attribute calls

---

linker/Tests/TestCasesRunner/TestRunner.cs

The input and expectations versions of the assemblies that we build for the tests are completely isolated from each other.  Compiling them in parallel helps to make tests run a bit faster

Compile input & expectations in parallel

---

linker/Tests/TestCasesRunner/TestRunner.cs

The recent change to compile test cases in parallel led to nunit exceptions thrown from calls such as Assert.Ignore() not propagating back out.  Instead an AggregateException would be thrown and nunit would, in the case of ignore, not fail the test instead of ignore it.
The only tests that do an Assert.Ignore during test case compilation are tests that need to use mcs when running on windows.  We don't run the tests on windows during CI so that is how this slipped by.

Fix nunit exceptions thrown during compile

---

linker/Tests/TestCasesRunner/TestRunner.cs

If the input assembly compilation threw, for example,  due to an Assert.Ignore() , we would not wait on the expectations compilation to complete for continuing.  This could lead to a race condition with the next test that runs over files in the sandbox directory.
This PR fixes the race by waiting on the expectations compilation task to complete when an exception is thrown.

Fix possible race condition during test assembly compile

---

linker/Linker.Steps/SweepStep.cs
linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/Dependencies/AssemblyWithUnusedAttributeOnReturnParameterDefinition.il
linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/UnusedAttributeOnReturnTypeIsRemoved.cs
linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj

This will fix the two test failures currently on master

Fix custom attributes on method return not being removed

---

linker/Linker.Steps/MarkStep.cs
linker/Linker.Steps/PreserveDependencyLookupStep.cs
linker/Linker/Driver.cs
linker/Mono.Linker.csproj
linker/Tests/Mono.Linker.Tests.Cases/Advanced/Dependencies/PreserveDependencyMethodInNonReferencedAssemblyBase.cs
linker/Tests/Mono.Linker.Tests.Cases/Advanced/Dependencies/PreserveDependencyMethodInNonReferencedAssemblyLibrary.cs
linker/Tests/Mono.Linker.Tests.Cases/Advanced/PreserveDependencyMethodInNonReferencedAssembly.cs
linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj

by introducing new step to setup all hierarchical dependencies correctly

Handle PreserveDependency which imports new assembly dependencies better

---

linker/Linker.Steps/MarkStep.cs

For Fields,Properties, and events.

Add AdditionalProcessing callbacks

---

linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/KeptAttributeInAssemblyAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Assertions/RemovedAttributeInAssembly.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
linker/Tests/Mono.Linker.Tests.Cases/Attributes/CoreLibraryAssemblyAttributesAreKept.cs
linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/CoreLibraryUnusedAssemblyAttributesAreRemoved.cs
linker/Tests/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/CoreLibraryUsedAssemblyAttributesAreKept.cs
linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
linker/Tests/Mono.Linker.Tests.Cases/TestFramework/Dependencies/VerifyAttributesInAssemblyWorks_Base.cs
linker/Tests/Mono.Linker.Tests.Cases/TestFramework/Dependencies/VerifyAttributesInAssemblyWorks_Lib.cs
linker/Tests/Mono.Linker.Tests.Cases/TestFramework/VerifyAttributesInAssemblyWorks.cs
linker/Tests/Mono.Linker.Tests.Cases/TestFramework/VerifyAttributesInAssemblyWorksWithStrings.cs
linker/Tests/TestCasesRunner/ResultChecker.cs

included 2 two test attributes for asserting attributes on Assemblies, Types, and Members in other assemblies.

Add support for asserting CustomAttributes in other assemblies

---

linker/Tests/Mono.Linker.Tests.Cases/LinkXml/CanPreserveTypesUsingRegex.cs
linker/Tests/Mono.Linker.Tests.Cases/LinkXml/CanPreserveTypesUsingRegex.xml
linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedEventPreservedByLinkXmlIsKept.cs
linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedEventPreservedByLinkXmlIsKept.xml
linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedFieldPreservedByLinkXmlIsKept.cs
linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedFieldPreservedByLinkXmlIsKept.xml
linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedMethodPreservedByLinkXmlIsKept.cs
linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedMethodPreservedByLinkXmlIsKept.xml
linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedPropertyPreservedByLinkXmlIsKept.cs
linker/Tests/Mono.Linker.Tests.Cases/LinkXml/UnusedPropertyPreservedByLinkXmlIsKept.xml

I'm working on a PR to add documentation to the README.md for the link xml format.  I want to make sure we have test coverage on every example I put in the readme.  This PR extends our existing tests to cover more of the possible valid usages.

Adding to the xml tests

---

linker/Linker/Driver.cs

--strip-resources
--strip-security

Update command line help and change two advanced option defaults.

---

linker/Linker.Steps/CodeRewriterStep.cs
linker/Linker.Steps/MarkStep.cs
linker/Linker.Steps/RemoveFeaturesStep.cs
linker/Linker/BCL.cs
linker/Linker/Driver.cs
linker/Linker/KnownMembers.cs
linker/Linker/LinkContext.cs
linker/Linker/MethodAction.cs
linker/Linker/MethodDefinitionExtensions.cs
linker/Linker/TypeReferenceExtensions.cs
linker/Mono.Linker.csproj
linker/Tests/Mono.Linker.Tests.Cases/BCLFeatures/ETW/BaseRemovedEventSource.cs
linker/Tests/Mono.Linker.Tests.Cases/BCLFeatures/ETW/CustomEventSource.cs
linker/Tests/Mono.Linker.Tests.Cases/BCLFeatures/ETW/Excluded.cs
linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
linker/Tests/TestCases/TestDatabase.cs
linker/Tests/TestCases/TestSuites.cs

Adds support for excluding ETW code paths

Event Tracking for Windows (ETW) exclusion support

---

linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/InterfaceMarkOrderingDoesNotMatter.cs
linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/InterfaceMarkOrderingDoesNotMatter.xml
linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/InterfaceMarkOrderingDoesNotMatter2.cs
linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/InterfaceMarkOrderingDoesNotMatter2.xml
linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/InterfaceMarkOrderingDoesNotMatter3.cs
linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/InterfaceMarkOrderingDoesNotMatter3.xml
linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj

While trying to find a bug and building up more test coverage in general I wrote these tests.  They passed and didn't end up being related to bug I was looking for but I think they are still worth keeping.

Add ordering doesn't matter tests

---

linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtor/UnusedTypeWithPreserveFields.cs
linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtor/UnusedTypeWithPreserveFields.xml
linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtor/UnusedTypeWithPreserveMethods.cs
linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtor/UnusedTypeWithPreserveMethods.xml
linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtor/UnusedTypeWithPreserveMethodsAndInterfaceTypeMarked.cs
linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/NoKeptCtor/UnusedTypeWithPreserveMethodsAndInterfaceTypeMarked.xml
linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj

More tests that I wrote trying to find a bug.  These didn't end up being related to bug but still improve coverage

Unused type with preserve tests

---

linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/UnusedInterfaceHasMethodPreservedViaXml.cs
linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnReferenceType/UnusedInterfaceHasMethodPreservedViaXml.xml
linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnValueType/UnusedExplicitInterfaceHasMethodPreservedViaXml.cs
linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnValueType/UnusedExplicitInterfaceHasMethodPreservedViaXml.xml
linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnValueType/UnusedInterfaceHasMethodPreservedViaXml.cs
linker/Tests/Mono.Linker.Tests.Cases/Inheritance.Interfaces/OnValueType/UnusedInterfaceHasMethodPreservedViaXml.xml
linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj

While attempting to pin point a bug, I wrote a few more variations of some existing tests.  These tests passed and were not related to the bug but the tests are worth keeping for improved coverage

Add a few more interface sweeping tests

---

linker/Linker/Driver.cs
linker/Linker/LinkContext.cs

This allows consumers to use this code without Driver.cs
Fixes #434

Move CodeOptimizations to LinkerContext.cs

---

corebuild/dotnet.cmd

Allow build project using VS2017 and VS2015

---

linker/Tests/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupLinkerResponseFileAttribute.cs
linker/Tests/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj
linker/Tests/Mono.Linker.Tests.Cases/CommandLine/Dependencies/ResponseFilesWork.rsp
linker/Tests/Mono.Linker.Tests.Cases/CommandLine/ResponseFilesWork.cs
linker/Tests/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
linker/Tests/TestCases/TestDatabase.cs
linker/Tests/TestCases/TestSuites.cs
linker/Tests/TestCasesRunner/LinkerArgumentBuilder.cs
linker/Tests/TestCasesRunner/TestCaseMetadaProvider.cs
linker/Tests/TestCasesRunner/TestCaseSandbox.cs
linker/Tests/TestCasesRunner/TestRunner.cs

Add a response file test and add support to the test framework for defining response files

Add response file test

---

src/ILLink.Tasks/ILLink.Tasks.csproj
src/ILLink.Tasks/ILLink.Tasks.nuspec
src/ILLink.Tasks/Sdk/Sdk.props
src/linker/Linker/Driver.cs

Adding Sdk.props to be imported by the dotnet/sdk

Adding Sdk.props to be imported by the dotnet/sdk

---

test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
test/Mono.Linker.Tests.Cases/TestFramework/CanCompileTestCaseWithMcs.cs
test/Mono.Linker.Tests/TestCasesRunner/TestCaseCompiler.cs

Note that this also renames the files.

Fix typo: msc -> mcs

---

eng/azure-pipelines.yml

Fix another official build failure.

Publish asset manifests

---

test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj

Anytime I change this project with Rider it fixes this formatting.

csproj formatting change

---

src/ILLink.Tasks/ILLink.Tasks.csproj

The package should include Mono.Cecil.dll.
@marek-safar PTAL.

Fix packaging typo

---

test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
test/Mono.Linker.Tests.Cases/UnreachableBody/BodyWithManyVariables.cs
test/Mono.Linker.Tests.Cases/UnreachableBody/BodyWithManyVariablesWithSymbols.cs

Add some tests to ensure that a body with variables does not cause any issues, which it does not.

Add a couple more unreachable body tests

---

monobuild/Makefile
monolinker.sln
test/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj

Bump Cecil dependency

---

src/linker/Linker.Steps/OutputStep.cs
src/linker/Linker/Driver.cs
src/linker/Linker/LinkContext.cs

Add support for deterministic linking

---

src/linker/Mono.Linker.csproj
test/Mono.Linker.Tests.Cases.Expectations/Mono.Linker.Tests.Cases.Expectations.csproj

Now all of the projects will target net471

update to target net471

---

src/linker/Linker.Steps/MarkStep.cs
test/Mono.Linker.Tests.Cases/PreserveDependencies/Dependencies/PreserveDependencyInCopyAssembly.cs
test/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyFromCopiedAssembly.cs

Keep tracking PreserveDependencyAttribute when it cannot be removed.

---

src/linker/Linker.Steps/OutputStep.cs
src/linker/Linker.Steps/SweepStep.cs
src/linker/Linker/Driver.cs
src/linker/Linker/OutputException.cs

- for command line args
- for some comments
- for crashes during save

Update some descriptions

---

src/linker/Linker.Steps/SweepStep.cs
test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/ForwarderLibrary_3.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/ImplementationLibrary_3.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/ReferenceImplementationLibrary_3.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/UnusedForwarderWithAssemblyLinkedAndFacadeCopy.cs

to actually test what it says it does

Update UnusedForwarderWithAssemblyLinkedAndFacadeCopy test

---

src/linker/Linker.Steps/SweepStep.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/AttributeArgumentForwardedWithCopyAction.cs

only in case any of their dependencies was removed
Follow up fix for #737

Update CustomAttributes scope also for assemblies which are copied

---

src/linker/Linker.Steps/MarkStep.cs
src/linker/Linker.Steps/SweepStep.cs
test/Mono.Linker.Tests.Cases/Attributes/OnlyKeepUsed/NullableOnConstraints.cs
test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj

Add sweeping of attributes on type parameter constraints

---

src/tuner/Mono.Tuner/Dispatcher.cs

Trace substeps also for fields, methods, properties and events.
Refactor the code to store the `Tracer` in the dispatcher itself,
instead of each substep. Also avoid null checks and casts in
every dispatch method.
The example analyzer output before:
Dependency #1
TypeDef:Xamarin.Android.Net.AndroidClientHandler
| Other:Mono.Tuner.SubStepDispatcher
The example analyzer output after:
Dependency #1
TypeDef:Xamarin.Android.Net.AndroidClientHandler
| Other:MonoDroid.Tuner.PreserveHttpAndroidClientHandler [1 deps]
| Other:Mono.Tuner.SubStepDispatcher

Improve tracing in the substep dispatcher

---

src/linker/Linker.Steps/MarkStep.cs
src/linker/Linker/Driver.cs
src/linker/Linker/LinkContext.cs
test/Mono.Linker.Tests.Cases/PreserveDependencies/PreserveDependencyKeptOption.cs

This is useful for multi-stage link setup

Add command line option to keep dependency attribute

---

src/linker/Linker.Steps/MarkStep.cs
test/Mono.Linker.Tests.Cases/Reflection/RuntimeReflectionExtensionsCalls.cs

Add detection for single member lookup methods in RuntimeReflectionExtensions

---

src/linker/Linker.Steps/MarkStep.cs
src/linker/Linker/TypeReferenceExtensions.cs
test/Mono.Linker.Tests.Cases/ComponentModel/CustomTypeConvertor.cs
test/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflection.cs
test/Mono.Linker.Tests/TestCases/TestDatabase.cs
test/Mono.Linker.Tests/TestCases/TestSuites.cs

Add simple detection for custom TypeConvertors

---

src/linker/Linker.Steps/MarkStep.cs
test/Mono.Linker.Tests.Cases/ComponentModel/TypeConverterOnMembers.cs

Expand handling of TypeConverterAttribute on all elements

---

src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs

It takes care of removing associated sequential points.
Fixes #857

Replace instructions using ILProcessor in RemoveUnreachableBlocksStep

---

src/linker/Linker/BCL.cs

Check more corelib like assemblies for basic types.

---

src/linker/Linker.Steps/CodeRewriterStep.cs
src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs
src/linker/Linker/TypeDefinitionExtensions.cs
test/Mono.Linker.Tests.Cases/Substitutions/StubBody.cs
test/Mono.Linker.Tests.Cases/Substitutions/StubBody.xml
test/Mono.Linker.Tests.Cases/Substitutions/StubBodyUnsafe.cs
test/Mono.Linker.Tests.Cases/Substitutions/StubBodyUnsafe.xml
test/Mono.Linker.Tests.Cases/UnreachableBlock/ReplacedReturns.cs

This includes handling for both leave and ret instructions.
Fixes #867

Improve RemoveUnreachableBlocksStep handling of blocks with exits

---

src/linker/Linker.Steps/BodySubstituterStep.cs
src/linker/Linker.Steps/CodeRewriterStep.cs
test/Mono.Linker.Tests.Cases/Substitutions/StubBodyWithValue.cs
test/Mono.Linker.Tests.Cases/Substitutions/StubBodyWithValue.xml

Add uint values handling to substituter

---

src/linker/Linker.Steps/MarkStep.cs

Handle better the obscure case where linker is run to do nothing.

---

src/linker/Linker.Steps/ResolveFromAssemblyStep.cs

Do not ignore unresolved assemblies added with -r option

---

build.cmd
build.sh

Otherwise it tried to build both .sln files in the project root.

Build illink.sln with build.cmd/sh

---

src/linker/Linker/Driver.cs

Add handling for -out option which worked before by accident as any

---

src/linker/Linker.Steps/ClearInitLocals.cs
src/linker/Linker.Steps/MarkStep.cs
src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs
src/linker/Linker/Driver.cs
src/linker/Linker/LinkContext.cs
test/Mono.Linker.Tests.Cases/Statics/DisableBeforeFieldInit/UnusedStaticFieldInitializer.cs
test/Mono.Linker.Tests/Tests/CodeOptimizationsSettingsTests.cs

which allows setting the optimization for a specific assembly only

Extend enable-opt and disable-opt with additional option

---

src/linker/Linker/LinkContext.cs
test/Mono.Linker.Tests.Cases/UnreachableBlock/ComplexConditions.cs
test/Mono.Linker.Tests.Cases/UnreachableBlock/DeadVariables.cs
test/Mono.Linker.Tests.Cases/UnreachableBlock/MultiStageRemoval.cs
test/Mono.Linker.Tests.Cases/UnreachableBlock/ReplacedReturns.cs
test/Mono.Linker.Tests.Cases/UnreachableBlock/SimpleConditionalProperty.cs
test/Mono.Linker.Tests.Cases/UnreachableBlock/TryFinallyBlocks.cs

Make Interprocedural constant propagation opt non-default on frozed branch

---

Directory.Build.props

Fixes https://github.com/mono/linker/issues/973

Fix monolinker.sln

---

src/linker/Linker.Steps/MarkStep.cs

With https://github.com/mono/linker/commit/2d2b7e96ea48865c25df88b991ac054e9d24a450 we lost the ability to explicitly mark or explicitly not mark CustomAttribute usages.
These changes restore this ability for derived MarkSteps's

Restore ability to mark or not mark CustomAttributes

---

src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs
test/Mono.Linker.Tests.Cases/UnreachableBlock/Dependencies/LocalsWithoutStore.il
test/Mono.Linker.Tests.Cases/UnreachableBlock/UninitializedLocals.cs

When doing local variables analysis don't assume they are always assigned

---

src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs
test/Mono.Linker.Tests.Cases/UnreachableBlock/Dependencies/LocalsWithoutStore.il
test/Mono.Linker.Tests.Cases/UnreachableBlock/UninitializedLocals.cs

* When doing local variables analysis don't assume they are always assigned.
Fixes #927
* Add test

[mono-2020-02] When doing local variables analysis don't assume they are always… (#978)

---

test/Mono.Linker.Tests.Cases/UnreachableBlock/Dependencies/LocalsWithoutStore.il

Today I learned the metadata format has a representation for this.

Make a "static instance" method static

---

src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs
test/Mono.Linker.Tests.Cases/UnreachableBlock/SimpleConditionalProperty.cs

Add handling for generic value types returned from stack to RemoveUnreachableBlocksStep

---

src/linker/Linker.Steps/MarkStep.cs

On .NET Framework there is an overload of Activator.CreateInstance with takes just one parameter but it's not a Type. This should be reported as unrecognized pattern by the linker.
This change also switches in the internal infra to use exceptions instead of asserts as they play nicer with tests.
Fixes #995

Fix pattern matching for Activator.CreateInstance over unrecognized parameter

---

eng/azure-pipelines.yml

#1004 turned off the CI on all but select branches.

Enable CI in the feature/dataflow branch

---

NuGet.config
eng/Version.Details.xml
eng/Versions.props
eng/ilasm.ilproj
global.json
test/Mono.Linker.Tests/Mono.Linker.Tests.csproj

Feed cleanup and add darc dependency for Microsoft.NET.Sdk.IL

---

Directory.Build.props
src/linker/ref/Mono.Linker.csproj

This fixes an issue that the official build is hitting.

Fix issue with packaging logic expecting symbols

---

src/linker/Linker.Steps/MarkStep.cs
test/Mono.Linker.Tests.Cases/Reflection/ActivatorCreateInstance.cs

Adds more tests to validate the new behavior with data flow.

[feature/dataflow] Remove old implementation for pattern match of Activator.CreateInstance

---

src/linker/Linker.Steps/MarkStep.cs
test/Mono.Linker.Tests.Cases/DataFlow/MethodParametersDataFlow.cs
test/Mono.Linker.Tests.Cases/DataFlow/MethodReturnParameterDataFlow.cs

Describe the exact reason why the data flow analysis failed and what should be the proposed fix when possible.

[feature/dataflow] Much improved error messages when data flow fails

---

src/linker/Linker.Dataflow/MethodBodyScanner.cs
src/linker/Linker.Dataflow/ValueNode.cs
src/linker/Linker.Steps/MarkStep.cs
test/Mono.Linker.Tests.Cases/DataFlow/FieldDataFlow.cs

Open question: How to represent the field access in current reflection pattern recording (or how to change that)

Field access annotation propagation

---

test/Mono.Linker.Tests/TestCasesRunner/TestCaseMetadaProvider.cs

Bring https://github.com/mono/linker/pull/1027 to master from the feature/dataflow branch.
Also fix a bug with https://github.com/mono/linker/pull/1027.  cc @mateoatr @vitek-karas you'll probably want to PR/cherry-pick https://github.com/mono/linker/commit/1d7cf060de4c946fa8165dd9111ea77911eea5f4 to `feature/dataflow`

Master bring reflection pattern improvement to master

---

src/linker/Linker.Steps/MarkStep.cs
test/Mono.Linker.Tests.Cases/DataFlow/MemberKinds.cs

Adds extensive tests for all of the member access kinds.

[feature/dataflow] Implement propagation of all member access kinds to a type

---

src/linker/Linker.Dataflow/AttributeFlowAnnotationSource.cs
src/linker/Linker.Dataflow/FlowAnnotations.cs
src/linker/Linker.Dataflow/IFlowAnnotationSource.cs
src/linker/Linker.Steps/MarkStep.cs
test/Mono.Linker.Tests.Cases.Expectations/Support/DynamicallyAccessedMembersAttribute.cs
test/Mono.Linker.Tests.Cases/DataFlow/MethodThisDataFlow.cs

The functionality is limited to only System.Type (with some wiggle room for testing it). We will not support it on any other "this" parameter (the attribute is not recognized there).

[feature/dataflow] Implement data flow annotations on this parameter

---

src/linker/Linker.Dataflow/AggregateFlowAnnotationSource.cs
src/linker/Linker.Dataflow/JsonFlowAnnotationSource.cs
src/linker/Linker.Steps/MarkStep.cs
src/linker/Linker/Driver.cs
src/linker/Linker/LinkContext.cs
src/linker/Mono.Linker.csproj
test/Mono.Linker.Tests.Cases.Expectations/Metadata/SetupLinkerDataflowAnnotationsFile.cs
test/Mono.Linker.Tests.Cases/DataFlow/JsonAnnotations.cs
test/Mono.Linker.Tests.Cases/DataFlow/JsonAnnotations.json
test/Mono.Linker.Tests/TestCasesRunner/LinkerArgumentBuilder.cs
test/Mono.Linker.Tests/TestCasesRunner/TestCaseLinkerOptions.cs
test/Mono.Linker.Tests/TestCasesRunner/TestCaseMetadaProvider.cs
test/Mono.Linker.Tests/TestCasesRunner/TestCaseSandbox.cs

This is mostly for testing purposes - allows supplementing the attribute-based annotations with annotations read out of a JSON file.

[feature/dataflow] Add support for reading dataflow annotation from JSON

---

src/linker/Linker.Dataflow/AggregateFlowAnnotationSource.cs
src/linker/Linker.Dataflow/JsonFlowAnnotationSource.cs
test/Mono.Linker.Tests.Cases/DataFlow/JsonAnnotations.json

Also fixes a bad merge between the this annotation and the JSON annotation changes

JSON annotations allow comments

---

src/linker/Linker.Steps/MarkStep.cs
test/Mono.Linker.Tests.Cases/DataFlow/ApplyTypeAnnotations.cs
test/Mono.Linker.Tests.Cases/DataFlow/GetTypeDataFlow.cs
test/Mono.Linker.Tests.Cases/Reflection/ExpressionFieldString.cs
test/Mono.Linker.Tests.Cases/Reflection/ExpressionNewType.cs
test/Mono.Linker.Tests.Cases/Reflection/ExpressionPropertyString.cs
test/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflection.cs
test/Mono.Linker.Tests.Cases/Reflection/TypeUsedViaReflectionTypeDoesntExist.cs

Implements intrisics handling for Type.GetType.
Implements data flow of the return value.
Implements annotation propagation for string value and its handling as Type.GetType input.

Type.GetType data flow analysis and annotation propagation

---

src/linker/Linker/Driver.cs
test/Mono.Linker.Tests.Cases/BCLFeatures/ETW/BaseRemovedEventSource.cs
test/Mono.Linker.Tests.Cases/BCLFeatures/ETW/BaseRemovedEventSourceEmptyBody.cs
test/Mono.Linker.Tests.Cases/BCLFeatures/ETW/Excluded.cs
test/Mono.Linker.Tests.Cases/BCLFeatures/ETW/LocalsOfModifiedMethodAreRemoved.cs
test/Mono.Linker.Tests.Cases/BCLFeatures/ETW/StubbedMethodWithExceptionHandlers.cs
test/Mono.Linker.Tests.Cases/ComponentModel/TypeConverterOnMembers.cs
test/Mono.Linker.Tests.Cases/Interop/PInvoke/Individual/CanOutputPInvokes.cs
test/Mono.Linker.Tests.Cases/TestFramework/VerifyExpectModifiedAttributesWork.cs
test/Mono.Linker.Tests.Cases/Tracing/Individual/CanEnableReducedTracing.cs

As discussed in https://github.com/mono/linker/pull/1057#discussion_r404948069

Change illink default action to "link"

---

src/linker/Linker.Steps/BaseSubStep.cs
src/linker/Linker.Steps/ISubStep.cs
src/linker/Linker.Steps/SubStepTargets.cs
src/linker/Linker.Steps/SubStepsDispatcher.cs
src/linker/ref/Linker.Steps/BaseSubStep.cs
src/linker/ref/Linker.Steps/ISubStep.cs
src/linker/ref/Linker.Steps/SubStepTargets.cs
src/linker/ref/Linker.Steps/SubStepsDispatcher.cs
test/Mono.Linker.Tests.Cases/Extensibility/Dependencies/CustomSubStep.cs
test/Mono.Linker.Tests.Cases/Extensibility/Dependencies/MyDispatcher.cs
test/Mono.Linker.Tests.Cases/Extensibility/SubStepDispatcherUsage.cs
test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
test/Mono.Linker.Tests/TestCases/TestDatabase.cs
test/Mono.Linker.Tests/TestCases/TestSuites.cs

Migrate SubStepsDispatcher to linker and add basic test coverage for it

---

src/linker/Linker.Steps/MarkStep.cs
test/Mono.Linker.Tests.Cases/Reflection/ConstructorUsedViaReflection.cs
test/Mono.Linker.Tests.Cases/Reflection/EventUsedViaReflection.cs
test/Mono.Linker.Tests.Cases/Reflection/FieldUsedViaReflection.cs
test/Mono.Linker.Tests.Cases/Reflection/MethodUsedViaReflection.cs
test/Mono.Linker.Tests.Cases/Reflection/PropertyUsedViaReflection.cs

-Create new set of test for ConstructorUsedViaReflection and MethodUsedViaReflection
-Port functionality of System.Type.GetConstructor and System.Type.GetMethod from ReflectionPatternDetector.Process to new HandleCall method

[feature/dataflow] systemtype

---

src/linker/Linker.Steps/MarkStep.cs
test/Mono.Linker.Tests.Cases/Reflection/ExpressionCallString.cs
test/Mono.Linker.Tests.Cases/Reflection/ExpressionFieldString.cs
test/Mono.Linker.Tests.Cases/Reflection/ExpressionPropertyString.cs

Refactor Expression.* pattern matching and update its tests.

[feature/dataflow] Refactor Expression.*

---

src/linker/Linker.Steps/MarkStep.cs

This implements detection of intrinsic methods as well as annotated methods/fields so that full method body scanning can be done only when necessary.

[feature/dataflow] Implement detection of interesting reflection methods

---

src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
src/linker/Linker/MethodReferenceExtensions.cs

Verified that compiler now generates hashcode based switch (instead of series of equality compares). Also deduplicated lot of the code there into helper methods and made the whole thing a lot shorter.

[feature/dataflow] Improve the switch for intrinsic methods

---

src/linker/Linker.Steps/LoadReferencesStep.cs
src/linker/Linker/DirectoryAssemblyResolver.cs
src/linker/Linker/LinkContext.cs

Print better diagnostics when assembly references cannot be resolved

---

docs/error-codes.md
src/linker/Linker.Steps/BlacklistStep.cs
src/linker/Linker.Steps/OutputStep.cs
src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs
src/linker/Linker.Steps/ResolveFromAssemblyStep.cs
src/linker/Linker.Steps/ResolveFromXmlStep.cs
src/linker/Linker/AssemblyResolver.cs
src/linker/Linker/ConsoleLogger.cs
src/linker/Linker/ILogger.cs
src/linker/Linker/LinkContext.cs
test/Mono.Linker.Tests.Cases/CommandLine/Dependencies/CustomStepDummy.cs
test/Mono.Linker.Tests.Cases/CommandLine/Dependencies/CustomStepUser.cs
test/Mono.Linker.Tests/TestCasesRunner/LinkerTestLogger.cs

Remove old LogMessage overloads and MessageImportance

---

src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs

Use switch expression for shorter code, remove unused nullability and change switch.

Simplify code a little bit in handling of RuntimeReflectionExtensions intrinsic

---

src/ILLink.Tasks/LinkTask.cs
test/ILLink.Tasks.Tests/ILLink.Tasks.Tests.cs
test/ILLink.Tasks.Tests/Mock.cs
test/Mono.Linker.Tests/Tests/ParseResponseFileLinesTests.cs

Fixes part of https://github.com/mono/linker/issues/1134.

Expose CustomData on task

---

docs/illink-options.md
src/linker/Linker.Steps/BlacklistStep.cs
test/Mono.Linker.Tests.Cases/Resources/Dependencies/EmbeddedLinkXmlFileIsProcessedIfNameMatchesAnAssembly.xml
test/Mono.Linker.Tests.Cases/Resources/EmbeddedLinkXmlFileIsNotProcessedWithIgnoreDescriptors.cs
test/Mono.Linker.Tests.Cases/Resources/EmbeddedLinkXmlFileIsNotProcessedWithIgnoreDescriptorsAndRemoved.cs
test/Mono.Linker.Tests.Cases/Resources/EmbeddedLinkXmlFileIsProcessed.cs
test/Mono.Linker.Tests.Cases/Resources/EmbeddedLinkXmlFileIsProcessedIfNameMatchesAnAssembly.cs
test/Mono.Linker.Tests.Cases/Resources/NonLinkerEmbeddedResourceHasNoImpact.cs

Fixes https://github.com/mono/linker/issues/1257

Support ILLink.Descriptors.xml

---

test/Mono.Linker.Tests.Cases/DataFlow/DynamicDependencyDataflow.cs
test/Mono.Linker.Tests.Cases/DataFlow/SuppressWarningWithLinkAttributes.cs
test/Mono.Linker.Tests.Cases/DataFlow/SuppressWarningWithLinkAttributes.xml

Also fix a typo in related tests.
Closes https://github.com/mono/linker/issues/1140.

Test that DynamicDependency doesn't disable flow analysis

---

src/linker/Linker.Steps/SweepStep.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/AttributesScopeUpdated.cs

Update scope of any attribute which can exist on method.

---

docs/README.md
docs/custom-steps.md
docs/data-formats.md
docs/design/reflection-flow.md
docs/error-codes.md
docs/illink-options.md
docs/illink-tasks.md
src/ILLink.Tasks/README.md
src/linker/Linker/Constants.cs
src/linker/Linker/MessageContainer.cs
src/linker/Linker/WarningSuppressionWriter.cs
test/Mono.Linker.Tests.Cases/Logging/CommonLogs.cs
test/Mono.Linker.Tests/TestCases/Dependencies/WarningSuppressionExpectations1.cs
test/Mono.Linker.Tests/TestCases/Dependencies/WarningSuppressionExpectations2.cs
test/Mono.Linker.Tests/Tests/MessageContainerTests.cs

Related to https://github.com/mono/linker/issues/1158

Add terminology description to the illink task doc

---

docs/error-codes.md
src/linker/Linker/Driver.cs
test/Mono.Linker.Tests.Cases/CommandLine/InvalidArguments.cs

Show error on invalid command-line argument

---

docs/error-codes.md
src/linker/Linker.Steps/LinkAttributesStep.cs
test/Mono.Linker.Tests.Cases/DataFlow/LinkerAttributeRemoval.cs
test/Mono.Linker.Tests.Cases/DataFlow/LinkerAttributeRemoval.xml

-Fix warning problems when invalid scenarios happen which end up printing IL2029
-Create warnings for invalid scenarios.
-Create test

Improve warnings on internal attribute use

---

docs/illink-options.md
src/linker/Linker/Driver.cs
src/linker/Linker/LinkContext.cs
src/linker/Linker/MessageContainer.cs
src/linker/ref/Linker/MessageContainer.cs
test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
test/Mono.Linker.Tests.Cases/Warnings/CanDisableWarnAsError.cs
test/Mono.Linker.Tests.Cases/Warnings/CanDisableWarnAsErrorSubstitutions.xml
test/Mono.Linker.Tests.Cases/Warnings/CanDisableWarnings.cs
test/Mono.Linker.Tests.Cases/Warnings/CanDisableWarningsSubstitutions.xml
test/Mono.Linker.Tests.Cases/Warnings/CanWarnAsError.cs
test/Mono.Linker.Tests.Cases/Warnings/CanWarnAsErrorSubstitutions.xml
test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/CanGenerateWarningSuppressionFile.cs
test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/Dependencies/TriggerWarnings_Lib.cs
test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsInAssembly.cs
test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsInMembersAndTypes.cs
test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsInMembersAndTypesUsingTarget.cs
test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsInModule.cs
test/Mono.Linker.Tests/TestCases/Dependencies/WarningSuppressionExpectations1.cs
test/Mono.Linker.Tests/TestCases/Dependencies/WarningSuppressionExpectations2.cs
test/Mono.Linker.Tests/TestCases/IndividualTests.cs
test/Mono.Linker.Tests/TestCases/TestDatabase.cs
test/Mono.Linker.Tests/TestCases/TestSuites.cs

This PR implements the `warnaserror` option as discussed in #1356.
/cc @agocke

Add warnaserror option

---

src/linker/Linker.Steps/LinkAttributesStep.cs

We need to be able to create this type when setting up our pipeline

Make LinkAttributesStep public

---

test/Mono.Linker.Tests/Mono.Linker.Tests.csproj
test/Mono.Linker.Tests/TestCasesRunner/PeVerifier.cs
test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs

Update to recent nunit test adapter and clean up unused dependencies

---

src/linker/Linker.Steps/CodeRewriterStep.cs
test/Mono.Linker.Tests.Cases/Substitutions/InitFieldExistingCctor.cs
test/Mono.Linker.Tests.Cases/Substitutions/StubBody.cs
test/Mono.Linker.Tests.Cases/Substitutions/StubBodyWithValue.cs
test/Mono.Linker.Tests/TestCasesRunner/AssemblyChecker.cs

and update the test verification to validate written values.
Fixes #1465

Handle substitutions of custom long values

---

test/Mono.Linker.Tests.Cases/Warnings/CanSetWarningVersion0.cs
test/Mono.Linker.Tests.Cases/Warnings/CanSetWarningVersion5.cs
test/Mono.Linker.Tests.Cases/Warnings/CanSetWarningVersion9999.cs
test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/AddSuppressionsBeforeAttributeRemoval.cs
test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsInMembersAndTypes.cs

For compatibility to build correctly in our solution

Remove remaining unused using directives from test cases for compatibility with UnityLinker

---

src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs
test/Mono.Linker.Tests.Cases/UnreachableBlock/TryFilterBlocks.cs

Process also exception filters when marking unreachable blocks

---

src/linker/ref/Linker/Annotations.cs

Add `AnnotationStore.AddPreservedMethod (MethodDefinition key, MethodDefinition method)`
to public API.
Fixes #1456

Make AddPreservedMethod variant public

---

src/linker/Linker.Steps/RemoveUnreachableBlocksStep.cs
test/Mono.Linker.Tests.Cases/UnreachableBlock/Dependencies/LocalsWithoutStore.il
test/Mono.Linker.Tests.Cases/UnreachableBlock/UninitializedLocals.cs

Backport #1511 to release/5.0.

[5.0] Use TryGetValue when retrieving local variables from stack (#1511)

---

src/linker/Linker.Steps/MarkStep.cs

When we fail to resolve a type we try and recreate it and keep the IL valid rather than fail.  We have a test that ensures an unresolved attribute on an AssemblyDefinition can be recreated.  It started failing with the sync up.   LazyMarkCustomAttributes should not skip any attributes.  This would give inconsistent behavior with references that only have attributes marked.  It was also problematic because LazyMarkCustomAttributes would call HandleUnresolvedType on the type where as ProcessLazyAttributes will call HandleUnresolvedMethod. A call to HandleUnresolvedMethod is necessary for us to recreate valid IL.
I went ahead and added null checks to other places that were missing them such as the location @marek-safar mentioned in https://github.com/mono/linker/issues/1525
Fixes #1525

Unresolved attribute fixes

---

test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
test/Mono.Linker.Tests/TestCases/TestDatabase.cs
test/Mono.Linker.Tests/TestCases/TestSuites.cs

These tests have not been running since they were originally added https://github.com/Unity-Technologies/linker/commit/5648356e4eabb55a39461e4d5d9a9bfcf42b2497#diff-651a4b1255ae9fd3dc54a2bf07eab510

Fix Attributes.StructLayout tests not running

---

test/Mono.Linker.Tests.Cases/DataFlow/ComplexTypeHandling.cs

The test is currently failing due to https://github.com/mono/linker/issues/1559

Test handling of arrays in data flow

---

src/linker/Linker.Steps/MarkStep.cs
src/linker/Linker.Steps/SweepStep.cs

Add TypeInAssembly to list of reasons for marking a type

---

src/linker/Linker/MessageContainer.cs
src/linker/ref/Linker/MessageContainer.cs
test/Mono.Linker.Tests.Cases/Logging/CommonLogs.cs
test/Mono.Linker.Tests.Cases/Logging/Dependencies/LogStep.cs
test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
test/Mono.Linker.Tests.Cases/Warnings/Dependencies/CustomStep.cs
test/Mono.Linker.Tests.Cases/Warnings/Individual/CustomStepWithWarnings.cs
test/Mono.Linker.Tests/TestCases/IndividualTests.cs
test/Mono.Linker.Tests/Tests/MessageContainerTests.cs

Allow external warnings to use codes >= 6001

---

src/linker/Linker.Steps/MarkStep.cs
test/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerDisplayAttributeOnType.cs

Check if DebuggerDisplayAttribute value is null

---

src/linker/Linker.Steps/MarkStep.cs
test/Mono.Linker.Tests.Cases/BCLFeatures/SerializationCtors.cs

Don't aggressively mark serialization constructors for illink

---

src/linker/Linker/MethodReferenceExtensions.cs
test/Mono.Linker.Tests/AssemblyInfo.cs
test/Mono.Linker.Tests/TestCases/IndividualTests.cs
test/Mono.Linker.Tests/TestCasesRunner/LinkerTestLogger.cs
test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
test/Mono.Linker.Tests/Tests/DocumentationSignatureParserTests.cs
test/Mono.Linker.Tests/Tests/GetDisplayNameTests.cs
test/Mono.Linker.Tests/Tests/TestFrameworkRulesAndConventions.cs
test/Mono.Linker.Tests/Tests/TypeNameResolverTests.cs

Run all tests in parallel

---

src/linker/Linker.Steps/MarkStep.cs
src/linker/Linker/LinkContext.cs
test/Mono.Linker.Tests.Cases/BCLFeatures/SerializationCtors.cs

Don't aggressively mark serialization constructors for illink 6.0+

---

src/linker/Linker.Steps/OutputStep.cs
src/linker/Linker.Steps/OutputWarningSuppressions.cs
src/linker/Linker/Driver.cs
src/linker/Linker/LinkContext.cs
src/linker/Linker/WarningSuppressionWriter.cs
test/ILLink.Tasks.Tests/Mock.cs
test/Mono.Linker.Tests.Cases/FeatureSettings/FeatureSubstitutionsInvalid.cs
test/Mono.Linker.Tests.Cases/Warnings/CanDisableWarnAsError.cs
test/Mono.Linker.Tests.Cases/Warnings/CanWarnAsError.cs
test/Mono.Linker.Tests.Cases/Warnings/Individual/CanGenerateWarningSuppressionFileXml.cs
test/Mono.Linker.Tests.Cases/Warnings/NoWarnRegardlessOfWarnAsError.cs
test/Mono.Linker.Tests/TestCasesRunner/LinkerDriver.cs
test/Mono.Linker.Tests/Tests/AnnotationStoreTest.cs
test/Mono.Linker.Tests/Tests/MessageContainerTests.cs

also don't produce any output binaries when error occurs

Report error exit code when any error is reported

---

src/linker/Linker.Steps/OutputStep.cs

Remove static mutable state from the output step. It's not threading safe

---

src/linker/Linker.Steps/MarkStep.cs
test/Mono.Linker.Tests.Cases/Attributes/MarshalAsCustomMarshalerInterface.cs

Implement marking of custom marshaler required members

---

src/linker/Linker.Steps/SweepStep.cs
test/Mono.Linker.Tests.Cases/References/Dependencies/ReferenceWithEntryPoint_Lib.cs
test/Mono.Linker.Tests.Cases/References/ReferenceWithEntryPoint.cs

Sweep EntryPoint method reference

---

src/ILLink.RoslynAnalyzer/ILLink.RoslynAnalyzer.csproj
src/ILLink.RoslynAnalyzer/Microsoft.NET.ILLink.Analyzers.props

-Add props file so analyzer can see the MSBuild options
-Add pointer to props file in analyzer project

Add analyzer props file

---

.github/CONTRIBUTING.md
eng/azure-pipelines.yml

Ref. https://github.com/mono/linker/issues/1775

Build based on changes to main branch too

---

docs/illink-options.md
src/linker/Linker.Steps/BodySubstitutionParser.cs
src/linker/Linker.Steps/DescriptorMarker.cs
src/linker/Linker.Steps/LinkAttributesParser.cs
src/linker/Linker.Steps/MarkStep.cs
src/linker/Linker.Steps/RootAssemblyInputStep.cs
src/linker/Linker/Annotations.cs
src/linker/Linker/AssemblyRootMode.cs
src/linker/Linker/Driver.cs
src/linker/Linker/LinkContext.cs
src/linker/Linker/TypePreserveMembers.cs
test/Mono.Linker.Tests.Cases/Libraries/RootLibrary.cs

Extend root mode options with library mode

---

src/ILLink.Tasks/Sdk/Sdk.props

As discussed in https://github.com/dotnet/sdk/pull/15799

Remove UsingTasks that are in the Net.SDK

---

src/linker/Linker.Steps/RootAssemblyInputStep.cs
test/Mono.Linker.Tests.Cases/Libraries/RootLibraryInternalsWithIVT.cs

Fix wrong logic for internal members

---

src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
test/Mono.Linker.Tests.Cases/Reflection/ConstructorsUsedViaReflection.cs
test/Mono.Linker.Tests.Cases/Reflection/EventUsedViaReflection.cs
test/Mono.Linker.Tests.Cases/Reflection/EventsUsedViaReflection.cs
test/Mono.Linker.Tests.Cases/Reflection/FieldsUsedViaReflection.cs
test/Mono.Linker.Tests.Cases/Reflection/MemberUsedViaReflection.cs
test/Mono.Linker.Tests.Cases/Reflection/MembersUsedViaReflection.cs
test/Mono.Linker.Tests.Cases/Reflection/MethodsUsedViaReflection.cs
test/Mono.Linker.Tests.Cases/Reflection/NestedTypesUsedViaReflection.cs
test/Mono.Linker.Tests.Cases/Reflection/PropertiesUsedViaReflection.cs

Add new intrinsics for:
- GetConstructors
- GetEvents
- GetFields
- GetProperties
- GetMethods
- GetNestedTypes
- GetMember
- GetMembers
Add tests
This should fix the problem in #1724

New linker intrinsics

---

src/linker/Linker.Steps/SubStepsDispatcher.cs
test/Mono.Linker.Tests.Cases/Extensibility/Dependencies/CustomSubStepFields.cs
test/Mono.Linker.Tests.Cases/Extensibility/SubStepDispatcherFields.cs

Avoid NRE in SubStepsDispatcher

---

src/linker/Linker.Steps/SealerStep.cs
test/Mono.Linker.Tests.Cases/Sealer/TypesCanBeSealed.cs

Fixes sealer optimization handling of deep nested types.

---

src/linker/Linker.Steps/OutputStep.cs
src/linker/Linker/AssemblyResolver.cs
src/linker/Linker/DirectoryAssemblyResolver.cs
src/linker/Linker/LinkContext.cs
src/linker/ref/Linker/LinkContext.cs

Expose GetAssemblyLocation to custom steps

---

src/ILLink.RoslynAnalyzer/MSBuildPropertyOptionNames.cs
src/ILLink.RoslynAnalyzer/Microsoft.NET.ILLink.Analyzers.props
src/ILLink.RoslynAnalyzer/RequiresAssemblyFilesAnalyzer.cs
src/ILLink.RoslynAnalyzer/RequiresUnreferencedCodeAnalyzer.cs
src/ILLink.RoslynAnalyzer/SingleFileAnalyzer.cs
test/ILLink.RoslynAnalyzer.Tests/AvoidAssemblyLocationInSingleFileTests.cs
test/ILLink.RoslynAnalyzer.Tests/LinkerTestCases.cs
test/ILLink.RoslynAnalyzer.Tests/RequiresAssemblyFilesAnalyzerTests.cs
test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs

Change PublishSingleFile and PublishTrimmed for ~~AnalyzeSingleFile~~ EnableSingleFileAnalyzer and ~~AnalyzeTrimming~~ EnableTrimAnalyzer in the linker
Creating a draft for now, will merge ~~after~~ before merging https://github.com/dotnet/sdk/pull/16098

Change MSBuild properties for analyzer

---

src/linker/Linker/Annotations.cs
src/linker/ref/Linker/Annotations.cs

Expose SetMethodStubValue

---

src/ILLink.RoslynAnalyzer/RequiresUnreferencedCodeAnalyzer.cs
test/ILLink.RoslynAnalyzer.Tests/LinkerTestCases.cs
test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs
test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs

Add support in analyzer to detect RUC in overridden methods/properties
Add support in analyzer to detect RUC in static constructors
Add test for overridden property

Analyzer can warn on more RequiresUnreferencedCode cases

---

src/linker/Linker.Steps/MarkStep.cs
test/Mono.Linker.Tests.Cases/BCLFeatures/SerializationCtors.cs

This reverts commit 2a83b5234f8b4781bcab9e8c08e66a03c8bb83ef.
Fixes #1603

Revert "Disable serialization ctors removal to unblock libraries build"

---

src/linker/Linker.Dataflow/FlowAnnotations.cs
test/Mono.Linker.Tests.Cases/DataFlow/PropertyDataFlow.cs

Fix automatic propagation in property setters
Add test
Fixes #1902

Fix automatic propagation in property setters

---

docs/data-formats.md
src/linker/Linker.Steps/LinkAttributesParser.cs
src/linker/Linker.Steps/MarkStep.cs
src/linker/Linker/LinkerAttributesInformation.cs
src/linker/Linker/RemoveAttributeInstancesAttribute.cs
test/Mono.Linker.Tests.Cases/LinkAttributes/LinkerAttributeRemovalConditional.cs
test/Mono.Linker.Tests.Cases/LinkAttributes/LinkerAttributeRemovalConditional.xml

This is useful for key/value pair like custom attributes removal

Extend attributes removal to support values matching

---

eng/Versions.props
src/ILLink.CodeFix/ILLink.CodeFixProvider.csproj
src/ILLink.RoslynAnalyzer/ILLink.RoslynAnalyzer.csproj
src/ILLink.RoslynAnalyzer/OperationExtensions.cs
src/ILLink.RoslynAnalyzer/RequiresAssemblyFilesAnalyzer.cs
src/ILLink.RoslynAnalyzer/RequiresUnreferencedCodeAnalyzer.cs
test/ILLink.RoslynAnalyzer.Tests/ILLink.RoslynAnalyzer.Tests.csproj

Bundles both the analyzer and codefix together as analyzers.

Use CodeFixProvider project as analyzer package project

---

src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
src/linker/Linker.Steps/LinkAttributesParser.cs
src/linker/Linker.Steps/MarkStep.cs

Also resolved one of the TODOs.

Remove some TODO comments - instead file issues

---

src/linker/Linker.Steps/MarkStep.cs
test/Mono.Linker.Tests.Cases/Attributes.Debugger/DebuggerDisplayAttributeOnType.cs

[release/5.0] Check if DebuggerDisplayAttribute value is null

---

src/ILLink.RoslynAnalyzer/RequiresAssemblyFilesAnalyzer.cs

This can be merged once https://github.com/dotnet/docs/pull/23808 is merged.

Add helpLinkUri for IL3002

---

test/Mono.Linker.Tests.Cases/Reflection/ObjectGetType.cs

This is a test for https://github.com/mono/linker/issues/2027

Add a test for determining static type of enumeration

---

test/ILLink.RoslynAnalyzer.Tests/LinkerTestCases.cs
test/ILLink.RoslynAnalyzer.Tests/TestCaseUtils.cs

Found some non-determinism in finding the right file -- it should now look through all the files.

Try to re-enable RequiresCapability tests

---

src/linker/Linker.Steps/MarkStep.cs
test/Mono.Linker.Tests.Cases/Advanced/TypeCheckRemoval.cs

isinst code replacement
Fixes #2016

Update branch target instruction with replaced new instruction for

---

test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsInMembersAndTypes.cs
test/Mono.Linker.Tests/TestCasesRunner/TestCaseMetadaProvider.cs

Test for https://github.com/mono/linker/issues/2095

Add a test for case where we report double suppression incorrectly

---

src/linker/Linker.Steps/SweepStep.cs
test/Mono.Linker.Tests.Cases/Mono.Linker.Tests.Cases.csproj
test/Mono.Linker.Tests.Cases/TypeForwarding/AttributeArgumentForwarded.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/AttributeArgumentForwardedWithCopyAction.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/AttributesScopeUpdated.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/ForwarderLibraryWithUnusedReference.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/ReferenceImplementationUsedAndUnusedLibrary.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/Dependencies/UnusedImplementationLibrary.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/UsedAndUnusedForwarderWithAssemblyCopy.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/UsedForwarderInCopyAssemblyKeptByPreserveDependency.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/UsedForwarderInCopyAssemblyKeptByUsedCustomAttribute.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/UsedForwarderInCopyAssemblyKeptByUsedField.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/UsedForwarderInCopyAssemblyKeptByUsedInterface.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/UsedForwarderInCopyAssemblyKeptByUsedMethod.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/UsedForwarderInCopyAssemblyKeptByUsedNestedType.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/UsedForwarderInCopyAssemblyKeptByUsedProperty.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/UsedForwarderInCopyAssemblyKeptByUsedTypeAsGenericArg.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/UsedForwarderInGenericIsDynamicallyAccessedWithAssemblyCopyUsed.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/UsedForwarderIsDynamicallyAccessedWithAssemblyCopyUsed.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/UsedForwarderWithAssemblyCopy.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/UsedForwarderWithAssemblyCopyUsedAndFacadesKeptAndUnusedReference.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/UsedForwarderWithAssemblyCopyUsedAndForwarderLibraryKept.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/UsedTransitiveForwarderInCopyAssemblyIsDynamicallyAccessed.cs
test/Mono.Linker.Tests.Cases/TypeForwarding/UsedTransitiveForwarderInCopyUsedAssemblyIsDynamicallyAccessed.cs
test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs

Fixes https://github.com/mono/linker/issues/2138

Fix writing of updated copyused scopes

---

test/Mono.Linker.Tests.Cases/DataFlow/PropertyDataFlow.cs

Property which marks itself via annotated attribute - leads to endless recursion in the linker.

Adds a test for issue #2196

---

src/linker/Linker/LinkContext.cs

Runtime is trying to update to .NET 7 versioning, but this breaks linker since it hardcodes knowledge of all versions.
This change makes it forward compatible by recognizing "higher than what I know".
No test as there's not a really good way to test this without going through a lot of trouble. Tested locally with runtime targeting 7.0 versioning.
Fixes https://github.com/mono/linker/issues/2225

Make linker forward compatible with regards to framework versioning

---

eng/Versions.props

Set version to 7.0.100-alpha.1 in the main branch

---

src/ILLink.CodeFix/BaseAttributeCodeFixProvider.cs
src/ILLink.CodeFix/RequiresAssemblyFilesCodeFixProvider.cs
src/ILLink.CodeFix/RequiresUnreferencedCodeCodeFixProvider.cs
src/ILLink.CodeFix/UnconditionalSuppressMessageCodeFixProvider.cs
test/ILLink.RoslynAnalyzer.Tests/RequiresAssemblyFilesAnalyzerTests.cs
test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs

Update edited document before continuing code fixing

---

src/linker/Linker.Steps/MarkStep.cs
src/linker/Linker/Annotations.cs

Do a null check for TryResolve(type.BaseType) before trying to get the attributes
Fix #2274

Port Fix for TryResolve scenario

---

src/linker/Linker.Steps/SweepStep.cs
src/linker/Linker/TypeReferenceWalker.cs

Make the walker a true use-once class.

Minor simplification of the type ref walking code

---

eng/azure-pipelines.yml

Tracking issue: https://github.com/dotnet/core-eng/issues/14276

Switch to servicing pools on release/5.0

---

src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs
test/ILLink.RoslynAnalyzer.Tests/DynamicallyAccessedMembersAnalyzerTests.cs
test/Mono.Linker.Tests.Cases/DataFlow/MethodReturnParameterDataFlow.cs

Fixes #2308 by trying to get the symbol for an operation type only if it is generics

Fixes Issue 2308

---

src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs

This tracks a bit of extra information so that when we check annotations we can tell whether the source is a known type - no functional changes.
This isn't the final solution (https://github.com/dotnet/linker/pull/2360 is adding a better abstraction for this) but is meant to help unblock https://github.com/dotnet/linker/issues/2339 since @tlakollo ran into unrelated warnings when trying to enable binding logic for a known type flowing into an annotated location. The not-supported case for a known type would be the right place to call into the DAM binding logic.

[DAM analyzer] Separate known type case

---

test/Mono.Linker.Tests.Cases/LinkAttributes/Dependencies/LinkerAttributeRemovalAndPreserveAssembly_Lib.Descriptor.xml
test/Mono.Linker.Tests.Cases/LinkAttributes/Dependencies/LinkerAttributeRemovalAndPreserveAssembly_Lib.cs
test/Mono.Linker.Tests.Cases/LinkAttributes/LinkerAttributeRemovalAndPreserveAssembly.LinkAttributes.xml
test/Mono.Linker.Tests.Cases/LinkAttributes/LinkerAttributeRemovalAndPreserveAssembly.cs

Currently this causes a crash in the linker due to null location scope.

Add a test for https://github.com/dotnet/linker/issues/2358

---

src/ILLink.RoslynAnalyzer/DataFlow/DynamicallyAccessedMembersBinder.cs

Mostly 1:1 conversion of linker DAM to Analyzer, #2339

DynamicallyAccessedMembersBinder port to Analyzer

---

src/ILLink.CodeFix/RequiresDynamicCodeCodeFixProvider.cs
src/ILLink.CodeFix/Resources.resx
src/ILLink.CodeFix/UnconditionalSuppressMessageCodeFixProvider.cs
src/ILLink.RoslynAnalyzer/DiagnosticDescriptors.cs
src/ILLink.RoslynAnalyzer/MSBuildPropertyOptionNames.cs
src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
src/ILLink.RoslynAnalyzer/RequiresDynamicCodeAnalyzer.cs
src/ILLink.Shared/DiagnosticCategory.cs
src/ILLink.Shared/DiagnosticId.cs
src/ILLink.Shared/ILLink.Shared.projitems
src/ILLink.Shared/SharedStrings.resx
test/ILLink.RoslynAnalyzer.Tests/LinkerTestBase.cs
test/ILLink.RoslynAnalyzer.Tests/RequiresDynamicCodeAnalyzerTests.cs
test/ILLink.RoslynAnalyzer.Tests/TestCaseCompilation.cs
test/ILLink.RoslynAnalyzer.Tests/TestChecker.cs
test/ILLink.RoslynAnalyzer.Tests/UnconditionalSuppressMessageCodeFixTests.cs
test/Mono.Linker.Tests.Cases.Expectations/Metadata/RequiresDynamicCodeAttribute.cs
test/Mono.Linker.Tests.Cases/RequiresCapability/Dependencies/ReferenceInterfaces.cs
test/Mono.Linker.Tests.Cases/RequiresCapability/Dependencies/RequiresInCopyAssembly.cs
test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresCapability.cs
test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresInCompilerGeneratedCode.cs

Add analyzer and code fixer for the attribute
Add a placeholder for the attribute in metadata in linker and as an additional resource in the analyzer.
Add attributes in RequiresCapability for testing
Add tests for code fixer

Initial support for RequiresDynamicCodeAttribute analyzer

---

test/Mono.Linker.Tests.Cases/DataFlow/GenericParameterDataFlow.cs

Add test for wrong warning in MakeGenericType annotation mismatch

---

src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
src/linker/Linker/Annotations.cs
test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs
test/ILLink.RoslynAnalyzer.Tests/TestCaseCompilation.cs
test/ILLink.RoslynAnalyzer.Tests/TestCaseUtils.cs
test/ILLink.RoslynAnalyzer.Tests/TestChecker.cs
test/ILLink.RoslynAnalyzer.Tests/Verifiers/CSharpAnalyzerVerifier`1.cs

Fix NullReferenceException in Analyzer by checking the containing type is not null before using it
Fixes #2398

Fix NullReferenceException in Analyzer

---

test/Mono.Linker.Tests.Cases/Reflection/MethodUsedViaReflection.cs

See https://github.com/dotnet/linker/issues/2432 for details.

Adds a test for GetMethod with wrong binding flags

---

src/ILLink.Shared/DiagnosticId.cs
src/ILLink.Shared/DiagnosticString.cs
src/ILLink.Shared/MessageFormat.cs
src/linker/Linker/LinkerAttributesInformation.cs
test/ILLink.RoslynAnalyzer.Tests/TestCaseCompilation.cs

Add license header to ILLink.Shared files
Fixes some committed lint problems

Add license header to ILLink.Shared files

---

src/ILLink.RoslynAnalyzer/README.md

@vitek-karas give this a try and let me know if it works.

Add analyzer instructions

---

eng/Versions.props

Revert "Merge release/6.0.2xx to main"

---

test/Mono.Linker.Tests/TestCasesRunner/TestCaseCompilationMetadataProvider.cs

With latest VS we get a 6.0.2 runtime but only 6.0.1 ref pack. The tests so far expected to use the exact same version, but there's no hard rule that it will be the case.
Change the algorithm to search for highest available major.minor.* ref pack if the matching one doesn't exist.

Fix how test find the ref pack to compile test cases against

---

src/ILLink.RoslynAnalyzer/DataFlow/LocalDataFlowVisitor.cs
src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisVisitor.cs
src/ILLink.Shared/TrimAnalysis/RequireDynamicallyAccessedMembersAction.cs
test/Mono.Linker.Tests.Cases/DataFlow/AssemblyQualifiedNameDataflow.cs
test/Mono.Linker.Tests.Cases/DataFlow/FieldDataFlow.cs
test/Mono.Linker.Tests.Cases/DataFlow/MethodParametersDataFlow.cs
test/Mono.Linker.Tests.Cases/DataFlow/MethodReturnParameterDataFlow.cs
test/Mono.Linker.Tests.Cases/DataFlow/MethodThisDataFlow.cs
test/Mono.Linker.Tests.Cases/DataFlow/PropertyDataFlow.cs

And fix invocations of GetValueUsageInfo

[DAM analyzer] Produce unknown value for array access

---

test/Mono.Linker.Tests.Cases/DataFlow/LocalDataFlow.cs

This is a test for https://github.com/dotnet/linker/issues/2624

Adds a test for backward branch merging an unknown value to the result

---

test/Mono.Linker.Tests.Cases/DataFlow/AnnotatedMembersAccessedViaReflection.cs
test/Mono.Linker.Tests.Cases/Reflection/TypeHierarchyReflectionWarnings.cs

Test for https://github.com/dotnet/linker/issues/2628

Add test which accessed property backing field via reflection

---

docs/error-codes.md

Docs for this error code looked wrong, but I might be misunderstanding.

Update docs code for IL2078

---

test/ILLink.RoslynAnalyzer.Tests/ILLink.RoslynAnalyzer.Tests.csproj
test/ILLink.RoslynAnalyzer.Tests/generated/ILLink.RoslynAnalyzer.Tests.Generator/ILLink.RoslynAnalyzer.Tests.TestCaseGenerator/DataFlowTests.g.cs

And actually exclude them from the compilation.

Fix generated test sources

---

src/ILLink.RoslynAnalyzer/Microsoft.NET.ILLink.Analyzers.props

Add EnableAotAnalyzer as compiler visible property

Add EnableAotAnalyzer as compiler visible

---

test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs

Disposing of the assembly leads to code after it to throw if it triggers a deferred read of something in the assembly.  This wasn't causing any issues in the illinker test framework.  I'm making changes in Unity and I ran into this.
There is no need to dispose of the assembly at this point.  The resolver will be diposed and will handle disposing of the assembly.

Don't dispose of linked assembly in VerifyLinkingOfOtherAssemblies

---

test/Mono.Linker.Tests.Cases/DataFlow/TypeBaseTypeDataFlow.cs

Testcase for https://github.com/dotnet/linker/issues/2673

Add testcase for intrinsic with override

---

eng/Version.Details.xml
eng/Versions.props
eng/common/templates/job/execute-sdl.yml
eng/common/templates/jobs/codeql-build.yml
eng/common/templates/jobs/jobs.yml
eng/common/templates/steps/execute-sdl.yml
eng/common/templates/steps/source-build.yml
eng/common/templates/variables/sdl-variables.yml
global.json
src/linker/Linker.Steps/MarkStep.cs
test/Mono.Linker.Tests.Cases/ComponentModel/TypeDescriptionProviderAttributeOnType.cs

(cherry picked from commit b10e1bc3da22862b4ddedc2b50639dee9d8dacfd)
Co-authored-by: Jackson Schuster <36744439+jtschuster@users.noreply.github.com>

Merge 6.0.2xx into 6.0.x

---

src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisVisitor.cs
test/Mono.Linker.Tests.Cases/DataFlow/ArrayDataFlow.cs

Handle multiple values for an array node
Add test
Fixes https://github.com/dotnet/linker/issues/2736

Handle multiple values for an array node

---

test/Mono.Linker.Tests.Cases/DataFlow/ArrayDataFlow.cs

https://github.com/dotnet/linker/commit/fb5b3396eda1fb41765f04cad8b2cbd34d1fd53c broke the build because I forgot to update the array dataflow tests I added after @tlakollo's change https://github.com/dotnet/linker/pull/2744 went in.
This fixes the array tests with links to known issues.

Fix array dataflow tests

---

src/ILLink.RoslynAnalyzer/DataFlow/CapturedReferenceValue.cs
src/ILLink.RoslynAnalyzer/DataFlow/LocalDataFlowVisitor.cs
test/Mono.Linker.Tests.Cases/DataFlow/UnsafeDataFlow.cs

Fixes https://github.com/dotnet/linker/issues/2748

Don't throw on NoneOperation

---

src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresOnClass.cs

Change requires on type checking for mismatch

---

src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisVisitor.cs
test/Mono.Linker.Tests.Cases/DataFlow/ArrayDataFlow.cs

Added a test based on array analysis which uses integers as indices to the array.

Adds support for recognizing more integer types as consts

---

src/linker/Linker.Steps/UnreachableBlocksOptimizer.cs
test/Mono.Linker.Tests.Cases/FeatureSettings/FeatureSubstitutionsNested.cs
test/Mono.Linker.Tests.Cases/Substitutions/StubBodyWithStaticCtor.cs
test/Mono.Linker.Tests.Cases/Substitutions/StubBodyWithStaticCtor.xml

Consider side effects when evaluating manually substituted methods

---

src/linker/Linker/LinkerILProcessor.cs
test/Mono.Linker.Tests.Cases/UnreachableBlock/ReplacedJumpTarget.cs
test/Mono.Linker.Tests/TestCasesRunner/AssemblyChecker.cs

Add retargeting switch labels to ILProcessor

---

eng/Versions.props
src/ILLink.RoslynAnalyzer/ILLink.RoslynAnalyzer.csproj
src/ILLink.Shared/ClosedAttribute.cs
src/linker/Mono.Linker.csproj

Fixes https://github.com/dotnet/linker/issues/2902

Make StaticCs work in source build

---

src/linker/Linker/UnconditionalSuppressMessageAttributeState.cs
test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/SuppressWarningsInMembersAndTypes.cs

Suppressions can be now placed on properties.
\cc @vitek-karas

Added support for suppressions on properties

---

src/linker/Linker.Steps/CheckSuppressionsStep.cs
test/Mono.Linker.Tests.Cases/Warnings/WarningSuppression/DetectRedundantSuppressionsInMembersAndTypes.cs

Redundant suppressions detection for suppressions introduced in #2925.
\cc @vitek-karas, @tlakollo

Redundant suppressions on events and properties

---

src/ILLink.Shared/DataFlow/MaybeLattice.cs
src/ILLink.Shared/TrimAnalysis/HandleCallAction.cs
src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
test/ILLink.RoslynAnalyzer.Tests/generated/ILLink.RoslynAnalyzer.Tests.Generator/ILLink.RoslynAnalyzer.Tests.TestCaseGenerator/Inheritance.Interfaces.StaticInterfaceMethodsTests.g.cs
test/Mono.Linker.Tests.Cases/DataFlow/AttributeConstructorDataflow.cs
test/Mono.Linker.Tests.Cases/DataFlow/AttributeFieldDataflow.cs
test/Mono.Linker.Tests.Cases/DataFlow/AttributePropertyDataflow.cs
test/Mono.Linker.Tests.Cases/DataFlow/ByRefDataflow.cs
test/Mono.Linker.Tests.Cases/DataFlow/CompilerGeneratedCodeDataflow.cs
test/Mono.Linker.Tests.Cases/DataFlow/CompilerGeneratedTypes.cs
test/Mono.Linker.Tests.Cases/DataFlow/GetTypeDataFlow.cs

Sync tweaks necessary for the linker/AOT integration

Aot to linker sync

---

docs/error-codes.md

Added IL2121 to error-codes.md

---

test/ILLink.RoslynAnalyzer.Tests/generated/ILLink.RoslynAnalyzer.Tests.Generator/ILLink.RoslynAnalyzer.Tests.TestCaseGenerator/LinkXmlTests.g.cs

Adds the LinkXml test that is generate on each build.

Add generated test

---

src/linker/Linker.Steps/MarkStep.cs

Fixes https://github.com/dotnet/linker/issues/1374

Fix how keeping something due to DynamicDependency is traced

---

src/ILLink.Shared/TrimAnalysis/IntrinsicId.cs

Adds document for each IntrinsicId with links to the intrinsic methods they represent.

Add doc comments for IntrinsicIds

---

src/linker/Linker.Steps/MarkStep.cs
test/Mono.Linker.Tests.Cases/Inheritance.Interfaces/BaseProvidesInterfaceEdgeCase/BaseProvidesInterfaceMethodCircularReference.cs

Addresses PR comments from #3094

PR comments from PR #3094

---

external/Mono.Cecil.overrides

This breaks when running integration tests
/cc @sbomer

Revert "Update cecil"
